force-app/main/default/objects/PS_Project__c/PS_Project__c.object-meta.xml
<CustomObject>
    <description>SOX object - This object is used to track the Projects which are related to Professional Services SKU.</description>
    <label>PS Project</label>
    <nameField>
        <label>PS Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PS Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PS_SubTask__c/PS_SubTask__c.object-meta.xml
<CustomObject>
    <description>Object to capture Subtask related to PS Task under PS Project</description>
    <label>Legacy PS SubTask</label>
    <nameField>
        <displayFormat>SUBTASK-{0000000}</displayFormat>
        <label>PS SubTask ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PS Legacy PS SubTasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PS_Task__c/PS_Task__c.object-meta.xml
<CustomObject>
    <description>SOX object - This object is used to track the task performed as part of PS Project</description>
    <label>PS Task</label>
    <nameField>
        <displayFormat>PST-{0000000}</displayFormat>
        <label>PS Task ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PS Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PS_Time_Entry__c/PS_Time_Entry__c.object-meta.xml
<CustomObject>
    <description>SOX object - For tracking time entries for related PS Project</description>
    <label>PS Time Entry</label>
    <nameField>
        <label>PS Time Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PS Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PS_Time_Entry__c/fields/PS_Subtask__c.field-meta.xml
<CustomField>
    <fullName>PS_Subtask__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>(Deprecate) PS Subtask</label>
    <referenceTo>PS_SubTask__c</referenceTo>
    <relationshipLabel>PS Time Entries</relationshipLabel>
    <relationshipName>PS_Time_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PS_Time_Entry__c/fields/PS_Task__c.field-meta.xml
<CustomField>
    <fullName>PS_Task__c</fullName>
    <description>Task related to the time sheet</description>
    <inlineHelpText>Task related to the time sheet</inlineHelpText>
    <label>PS Task</label>
    <referenceTo>PS_Task__c</referenceTo>
    <relationshipLabel>PS Time Entries</relationshipLabel>
    <relationshipName>PS_Time_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TriggerControl__c/TriggerControl__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This setting is used to disable triggers dynamically without updating code</description>
    <label>TriggerControl</label>
</CustomObject>

force-app/main/default/classes/MigratePSDataBatch_test1.cls
@isTest
public class MigratePSDataBatch_test1 {
    @testSetup static  void createdata(){
        List<TriggerControl__c> TriggerControlSetting =          CustomTestDataFactory.TriggerControlSetting(true);
        list<Account> accId                           =          CustomTestDataFactory.testAccounts(1);
        list<Contact>  contactId                      =          CustomTestDataFactory.createcont(accId);
        list<opportunity> oppId                       =          CustomTestDataFactory.TESTOpp(accId);
        List<order> CreateOrder                       =          CustomTestDataFactory.testorders(accId,oppId);
        List<PS_Project__c> PsprojectId               =          CustomTestDataFactory.testPSProject_c(accId);
        
        List<PS_Task__c>  pstaskInstall               =          CustomTestDataFactory.createPstaskInstall(PsprojectId, false);
        List<PS_Task__c>  pstaskConsult               =          CustomTestDataFactory.createPstaskConsult(PsprojectId, false);
        List<PS_Task__c>  TaskAll = new List<PS_Task__c> ();
        TaskAll.addAll(pstaskInstall);
        TaskAll.addAll(pstaskConsult);
        insert TaskAll;
        
        
        List<PS_SubTask__c> PsSubInstall              =          CustomTestDataFactory.createPSSubtaskInstall(pstaskInstall, false);
        List<PS_SubTask__c> PsSubConsult              =          CustomTestDataFactory.createPSSubtaskConsult(pstaskConsult, false);
        
        List<PS_SubTask__c>  Admin                    =         CustomTestDataFactory.createPSSubtaskAdmin(pstaskInstall, false);
        
        List<PS_SubTask__c>  subTaskAll = new List<PS_SubTask__c> ();
        subTaskAll.addAll(PsSubInstall);
        subTaskAll.addAll(PsSubConsult);
        subTaskAll.addAll(Admin);
        insert subTaskAll;
        
        List<PS_Time_Entry__c> Adminentry             =         CustomTestDataFactory.createPSTimeEntryAdmin(TaskAll,subTaskAll);
    }
    
    public static testmethod void TestMigratePSData(){
        Test.startTest();
            MigratePSDataBatch mgps = new MigratePSDataBatch();
            Database.executeBatch(mgps,200);
        Test.stopTest();
    }
}