force-app/main/default/objects/PS_Project__c/PS_Project__c.object-meta.xml
<CustomObject>
    <description>SOX object - This object is used to track the Projects which are related to Professional Services SKU.</description>
    <label>PS Project</label>
    <nameField>
        <label>PS Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PS Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PS_Time_Card__c/PS_Time_Card__c.object-meta.xml
<CustomObject>
    <description>SOX object - This is the weekly hours submitted by the PS User on thier PS Task.This is submitted for approval at the end of the week. Can capture Billable and non billable task.</description>
    <label>PS Time Card</label>
    <nameField>
        <label>PS Time Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PS Time Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PS_Time_Card__c/fields/PS_Project__c.field-meta.xml
<CustomField>
    <fullName>PS_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PS Project</label>
    <referenceTo>PS_Project__c</referenceTo>
    <relationshipLabel>PS Time Cards</relationshipLabel>
    <relationshipName>PS_Time_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PS_Time_Card__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Approval_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/PSTimeCardTriggerHandler_test.cls
/**
* @Author      : Sai Kishore
*/
@IsTest
public class PSTimeCardTriggerHandler_test {
    
    @TestSetup
    public static void setupData(){
        List<Account> accLst = CustomTestDataFactory.testAccounts(1);
        List<Contact> conLst = CustomTestDataFactory.createcont(accLst);
        List<PS_Project__c> projectLst = CustomTestDataFactory.createPS_Project(conLst,accLst);        
        CustomTestDataFactory.CreatTimecard(projectLst);
    }
    
    @IsTest
    public static void testBefore(){
        PS_Time_Card__c timeCard = [SELECT Id FROM PS_Time_Card__c limit 1];
        timeCard.status__c = 'Approved';
        try {
            UPDATE timeCard;
            Assert.Fail();
        }
        catch(DMLException ex)
        {
            Assert.isTrue(ex.getMessage().contains('Operation not permitted. Please contact your manager for assistance.'));
        }
    }
}