force-app/main/default/objects/PS_Project__c/PS_Project__c.object-meta.xml
<CustomObject>
    <description>SOX object - This object is used to track the Projects which are related to Professional Services SKU.</description>
    <label>PS Project</label>
    <nameField>
        <label>PS Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PS Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PS_Project_Team_Member__c/PS_Project_Team_Member__c.object-meta.xml
<CustomObject>
    <description>SOX object - Represents Professional Services Users that worked on the Opportunity and will be working on the PS Project.</description>
    <label>PS Project Team Member</label>
    <nameField>
        <displayFormat>PSM-{0000000}</displayFormat>
        <label>PS Project Team Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PS Project Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PS_Project_Team_Member__c/fields/PS_Project__c.field-meta.xml
<CustomField>
    <fullName>PS_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PS Project</label>
    <referenceTo>PS_Project__c</referenceTo>
    <relationshipLabel>PS Project Team Members</relationshipLabel>
    <relationshipName>PS_Project_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PS_Project_Team_Member__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>PS_Project_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PS_SubTask__c/PS_SubTask__c.object-meta.xml
<CustomObject>
    <description>Object to capture Subtask related to PS Task under PS Project</description>
    <label>Legacy PS SubTask</label>
    <nameField>
        <displayFormat>SUBTASK-{0000000}</displayFormat>
        <label>PS SubTask ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PS Legacy PS SubTasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PS_SubTask__c/fields/PS_Assignee__c.field-meta.xml
<CustomField>
    <fullName>PS_Assignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The assignee for the PS Subtask</description>
    <inlineHelpText>The assignee for the PS Subtask</inlineHelpText>
    <label>PS Assignee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PS_Subtasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PS_SubTask__c/fields/Task__c.field-meta.xml
<CustomField>
    <fullName>Task__c</fullName>
    <description>PS Task related to this Subtask</description>
    <inlineHelpText>Select PS Task related to this Subtask</inlineHelpText>
    <label>Task</label>
    <referenceTo>PS_Task__c</referenceTo>
    <relationshipLabel>PS Subtasks</relationshipLabel>
    <relationshipName>PS_Subtasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PS_Task__c/PS_Task__c.object-meta.xml
<CustomObject>
    <description>SOX object - This object is used to track the task performed as part of PS Project</description>
    <label>PS Task</label>
    <nameField>
        <displayFormat>PST-{0000000}</displayFormat>
        <label>PS Task ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PS Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PS_Task__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>PS Project related to this Task</description>
    <inlineHelpText>PS Project related to this Task</inlineHelpText>
    <label>Project</label>
    <referenceTo>PS_Project__c</referenceTo>
    <relationshipLabel>PS Tasks</relationshipLabel>
    <relationshipName>PS_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProjectAccessBasedOnSubtaskBatch.cls
global class ProjectAccessBasedOnSubtaskBatch implements Database.Batchable<sObject>{
    
    global  Database.QueryLocator start(Database.BatchableContext BC) {
        string query = 'Select id from PS_Project__c'; 
        return Database.getQueryLocator(query);  
    }
    
    
    global  void execute(Database.BatchableContext bc,List<PS_Project__c> scope){
        
        // projects with Existing members
        map<id,set<id>> ProjectVsSetOfAssingnee = new map<id,set<id>>();
        for(PS_Project_Team_Member__c PSTeam :[Select id, PS_Project__c,Team_Member__c from PS_Project_Team_Member__c where PS_Project__c in:scope]){
            Set<id> assignIdset = new Set<id>();
            if(ProjectVsSetOfAssingnee.containsKey(PSTeam.PS_Project__c)){
                assignIdset = ProjectVsSetOfAssingnee.get(PSTeam.PS_Project__c);
                
            }
            assignIdset.add(PSTeam.Team_Member__c);
            ProjectVsSetOfAssingnee.put(PSTeam.PS_Project__c,assignIdset);
        }
        System.debug('ProjectVsSetOfAssingnee---------------'+ProjectVsSetOfAssingnee);
        
        //project with users who should have access..
        Map<id,set<id>> ProjectIdVsSetOfSubtask = new Map<id,set<id>>();
        for(PS_SubTask__c st : [Select id, PS_Assignee__c, Task__r.Project__c from PS_SubTask__c where Task__r.Project__c in :Scope AND PS_Assignee__c != null]){
            set<id> assignIdset = new Set<id>();
            if(ProjectIdVsSetOfSubtask.containsKey(st.Task__r.Project__c)){
                assignIdset = ProjectIdVsSetOfSubtask.get(st.Task__r.Project__c); 
            }
            assignIdset.add(st.PS_Assignee__c);
            ProjectIdVsSetOfSubtask.put(st.Task__r.Project__c,assignIdset);   
        }
        System.debug('ProjectIdVsSetOfSubtask---------------'+ProjectIdVsSetOfSubtask);
        
        list<PS_Project_Team_Member__c> PSProjectTeamMemberTobeInserted = new list<PS_Project_Team_Member__c>();
        //looping through map which has user who should be project members
        for(Id projId : ProjectIdVsSetOfSubtask.keyset()) {
            set<id> existingmemberId = new set<id> ();
            if(ProjectVsSetOfAssingnee.ContainsKey(projId))
                existingmemberId = ProjectVsSetOfAssingnee.get(projId);
            for(Id usrId : ProjectIdVsSetOfSubtask.get(projId)) {
                if(!existingmemberId.contains(usrId)){
                    PS_Project_Team_Member__c PsTeam = new PS_Project_Team_Member__c(
                        PS_Project__c  = projId,
                        Team_Member__c = usrId
                    );
                    PSProjectTeamMemberTobeInserted.add(PsTeam); 
                }
            }
        }    
        system.debug('PSProjectTeamMemberTobeInserted-------------'+PSProjectTeamMemberTobeInserted);
        insert PSProjectTeamMemberTobeInserted;
        
    }
    
    global  void finish(Database.BatchableContext bc){
        system.debug(' ___________ FINISH _______________________');
    }
    
}