force-app/main/default/objects/PS_Project__c/PS_Project__c.object-meta.xml
<CustomObject>
    <description>SOX object - This object is used to track the Projects which are related to Professional Services SKU.</description>
    <label>PS Project</label>
    <nameField>
        <label>PS Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PS Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PS_Project__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field refers to Account related to PS Project</description>
    <inlineHelpText>This field refers to Account related to PS Project</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PS Projects</relationshipLabel>
    <relationshipName>PS_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PS_Project__c/fields/Project_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Status__c</fullName>
    <description>PS Project&apos;s current status</description>
    <inlineHelpText>PS Project&apos;s current status</inlineHelpText>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PS_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PS_SubTask__c/PS_SubTask__c.object-meta.xml
<CustomObject>
    <description>Object to capture Subtask related to PS Task under PS Project</description>
    <label>Legacy PS SubTask</label>
    <nameField>
        <displayFormat>SUBTASK-{0000000}</displayFormat>
        <label>PS SubTask ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PS Legacy PS SubTasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PS_SubTask__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Task__r.Project__r.Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Account Name from related PS Project</inlineHelpText>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PS_SubTask__c/fields/PS_Assignee__c.field-meta.xml
<CustomField>
    <fullName>PS_Assignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The assignee for the PS Subtask</description>
    <inlineHelpText>The assignee for the PS Subtask</inlineHelpText>
    <label>PS Assignee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PS_Subtasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PS_SubTask__c/fields/Task__c.field-meta.xml
<CustomField>
    <fullName>Task__c</fullName>
    <description>PS Task related to this Subtask</description>
    <inlineHelpText>Select PS Task related to this Subtask</inlineHelpText>
    <label>Task</label>
    <referenceTo>PS_Task__c</referenceTo>
    <relationshipLabel>PS Subtasks</relationshipLabel>
    <relationshipName>PS_Subtasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PS_SubTask__c/fields/Task_Type__c.field-meta.xml
<CustomField>
    <fullName>Task_Type__c</fullName>
    <label>Task Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Install</fullName>
            </value>
            <value>
                <fullName>Consult</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PS_Task__c/PS_Task__c.object-meta.xml
<CustomObject>
    <description>SOX object - This object is used to track the task performed as part of PS Project</description>
    <label>PS Task</label>
    <nameField>
        <displayFormat>PST-{0000000}</displayFormat>
        <label>PS Task ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PS Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PS_Task__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PS Tasks</relationshipLabel>
    <relationshipName>PS_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PS_Task__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>PS Project related to this Task</description>
    <inlineHelpText>PS Project related to this Task</inlineHelpText>
    <label>Project</label>
    <referenceTo>PS_Project__c</referenceTo>
    <relationshipLabel>PS Tasks</relationshipLabel>
    <relationshipName>PS_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PS_Task__c/fields/Project_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Status__c</fullName>
    <description>DO NOT ADD TO PAGE LAYOUT</description>
    <formula>TEXT(Project__r.Project_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>DO NOT ADD TO PAGE LAYOUT</inlineHelpText>
    <label>Hidden Project Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PS_Task__c/fields/Task_Status__c.field-meta.xml
<CustomField>
    <fullName>Task_Status__c</fullName>
    <description>Status of the PS Task</description>
    <inlineHelpText>Status of the PS Task</inlineHelpText>
    <label>Task Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PS_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PS_Task__c/fields/Task_Type__c.field-meta.xml
<CustomField>
    <fullName>Task_Type__c</fullName>
    <description>Type of the PS Task</description>
    <inlineHelpText>Type of the PS Task</inlineHelpText>
    <label>Task Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Install</fullName>
            </value>
            <value>
                <fullName>Consult</fullName>
            </value>
            <value>
                <fullName>Consult-Onsite</fullName>
            </value>
            <value>
                <fullName>Consult-Remote</fullName>
            </value>
            <value>
                <fullName>Resident Engineer</fullName>
            </value>
            <value>
                <fullName>CSAT</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Migration</fullName>
            </value>
            <value>
                <fullName>T&amp;E</fullName>
            </value>
            <value>
                <fullName>Non-Billable (Product)</fullName>
            </value>
            <value>
                <fullName>Non-Billable (PS)</fullName>
            </value>
            <value>
                <fullName>Non-Billable (Sales)</fullName>
            </value>
            <value>
                <fullName>Non-Billable (Expired)</fullName>
            </value>
            <value>
                <fullName>Resident Engineer-PD</fullName>
            </value>
            <value>
                <fullName>Install-PD</fullName>
            </value>
            <value>
                <fullName>Consult-Remote-PD</fullName>
            </value>
            <value>
                <fullName>Consult-Onsite-PD</fullName>
            </value>
            <value>
                <fullName>RCDM-Install</fullName>
            </value>
            <value>
                <fullName>Accelerator</fullName>
            </value>
            <value>
                <fullName>Rubrik University</fullName>
            </value>
            <value>
                <fullName>Non-Billable Admin</fullName>
            </value>
            <value>
                <fullName>Non-Billable CSAT</fullName>
            </value>
            <value>
                <fullName>Non-Billable PreSales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PS_Time_Entry__c/PS_Time_Entry__c.object-meta.xml
<CustomObject>
    <description>SOX object - For tracking time entries for related PS Project</description>
    <label>PS Time Entry</label>
    <nameField>
        <label>PS Time Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PS Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PS_Time_Entry__c/fields/Hours_Spent__c.field-meta.xml
<CustomField>
    <fullName>Hours_Spent__c</fullName>
    <label>Hours Spent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PS_Time_Entry__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <formula>HYPERLINK(&quot;/&quot; +PS_Task__r.Project__c, PS_Task__r.Project__r.Name, &quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PS_Time_Entry__c/fields/PS_Subtask__c.field-meta.xml
<CustomField>
    <fullName>PS_Subtask__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>(Deprecate) PS Subtask</label>
    <referenceTo>PS_SubTask__c</referenceTo>
    <relationshipLabel>PS Time Entries</relationshipLabel>
    <relationshipName>PS_Time_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PS_Time_Entry__c/fields/PS_Task__c.field-meta.xml
<CustomField>
    <fullName>PS_Task__c</fullName>
    <description>Task related to the time sheet</description>
    <inlineHelpText>Task related to the time sheet</inlineHelpText>
    <label>PS Task</label>
    <referenceTo>PS_Task__c</referenceTo>
    <relationshipLabel>PS Time Entries</relationshipLabel>
    <relationshipName>PS_Time_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PS_Time_Entry__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Time Entry Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Approval_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PS_Time_Entry__c/fields/Task__c.field-meta.xml
<CustomField>
    <fullName>Task__c</fullName>
    <formula>TEXT(PS_Task__r.Task_Type__c) +&apos; &apos;+ TEXT(PS_Task__r.Task_Subtype__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Task</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PS_Time_Entry__c/fields/Task_Type__c.field-meta.xml
<CustomField>
    <fullName>Task_Type__c</fullName>
    <formula>TEXT(PS_Subtask__r.Task_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Task Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PS_Time_Entry__c/fields/Time_Entry_Date__c.field-meta.xml
<CustomField>
    <fullName>Time_Entry_Date__c</fullName>
    <label>Time Entry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TriggerControl__c/TriggerControl__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This setting is used to disable triggers dynamically without updating code</description>
    <label>TriggerControl</label>
</CustomObject>

force-app/main/default/classes/PSTimeEntryTriggerHandler_test.cls
@isTest
public class PSTimeEntryTriggerHandler_test {
    @testSetup static void setup() {
         List<TriggerControl__c> TriggerCon = CustomTestDataFactory.TriggerControlSetting(true); 
        List<PS_Task__c> taskList = new List<PS_Task__c>();
        List<PS_SubTask__c> subtaskList = new List<PS_SubTask__c>(); 
        List<PS_Time_Entry__c> psoList = new List<PS_Time_Entry__c>();
          List<PS_Time_Entry__c> psoList1 = new List<PS_Time_Entry__c>();
        Id devRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Partner/Distributor').getRecordTypeId();   
        Account acc = new Account(name='test1239',RecordTypeId= devRecordTypeId);
        insert acc;
        update acc;
        Date closeDt = System.Today()+30;
        opportunity oppr = new opportunity(Name='testing DIEtestsalesforce 4/6/2015' ,  AccountId= acc.Id,StageName = '1 Discovery',
                                           CloseDate = closeDt, Lead_Email_Hidden__c='', partner_lookup__c=acc.id, Alliance_Source_Type__c='Alliance Initiated Deal', Installation_Assigned_To__c ='FE Install');
        insert oppr;
        update oppr;
        Order od2 = new Order();
        od2.AccountId = acc.Id;
        od2.OpportunityId =oppr.Id;
        od2.EffectiveDate = Date.Today();
        //od2.Status = 'PO Received';
        od2.Order_Status__c = 'PO Received';
        od2.ShippingStreet ='Test Street';
        od2.ShippingCity ='Test City';
        od2.ShippingState ='California';
        od2.ShippingCountry ='United States';
        od2.ShippingPostalcode ='94820';
        //od2.ship_To_Name__c=acc.id;
        od2.Shipping_Address_Label__c = null;
        insert od2;
        od2.Order_Status__c = 'Returned';
        update od2;
        PS_Project__c proj = new PS_Project__c(Account__c=acc.Id,Project_Status__c='Open');
        insert proj;
        update proj;
        PS_Task__c task1 = new PS_Task__c(Project__c=proj.Id,Task_Type__c='Install',Task_Status__c='Open');
        taskList.add(task1);
        PS_Task__c task2 = new PS_Task__c(Project__c=proj.Id,Task_Type__c='Consult',Task_Status__c='Open');
        taskList.add(task2);
        insert taskList;
        update  taskList;   
        PS_SubTask__c subTask1 = new PS_SubTask__c(PS_Assignee__c = userinfo.getUserId(), Task__c=task1.id,Task_Type__c='Install');
        subtaskList.add(subTask1);
        PS_SubTask__c subTask2 = new PS_SubTask__c(PS_Assignee__c = userinfo.getUserId(), Task__c=task2.Id,Task_Type__c='Consult');
        subtaskList.add(subTask2);  
        insert subtaskList;
        update subtaskList;
        PS_Time_Entry__c psot1 = new PS_Time_Entry__c(status__c= 'Approved',PS_SubTask__c = subTask1.id, PS_Task__c = task1.id,Time_Entry_Date__c=system.today().addDays(-2),Comments__c='hello');
        psoList.add(psot1);
        PS_Time_Entry__c psot2 = new PS_Time_Entry__c(PS_SubTask__c = subTask1.id, PS_Task__c = task1.id,Time_Entry_Date__c=system.today(),Comments__c='hello');
        psoList.add(psot2);
        PS_Time_Entry__c psot3 = new PS_Time_Entry__c(PS_SubTask__c = subTask1.id, PS_Task__c = task1.id,Time_Entry_Date__c=system.today().addDays(1),Comments__c='hello');
        psoList.add(psot3); 
        PS_Time_Entry__c psot4 = new PS_Time_Entry__c(PS_SubTask__c = subTask2.id, PS_Task__c = task2.id,Time_Entry_Date__c=system.today().addDays(-2),Comments__c='hello');
        psoList.add(psot4);
        PS_Time_Entry__c psot5 = new PS_Time_Entry__c(PS_SubTask__c = subTask2.id, PS_Task__c = task2.id,Time_Entry_Date__c=system.today(),Comments__c='hello');
        psoList.add(psot5);
        PS_Time_Entry__c psot6 = new PS_Time_Entry__c(PS_SubTask__c = subTask2.id, PS_Task__c = task2.id, Time_Entry_Date__c=system.today().addDays(1),Comments__c='hello');
        psoList.add(psot6); 
        insert psoList;
        update psoList; 
    /*   PS_Time_Entry__c psot12 = new PS_Time_Entry__c(PS_SubTask__c = subTask1.id, PS_Task__c = task1.id, Hours_Spent__c=2,Time_Entry_Date__c=system.today().addDays(-2),Comments__c='hello');
        psoList1.add(psot12);
        PS_Time_Entry__c psot22 = new PS_Time_Entry__c(PS_SubTask__c = subTask1.id, PS_Task__c = task1.id, Hours_Spent__c=3,Time_Entry_Date__c=system.today(),Comments__c='hello');
        psoList1.add(psot22);
        PS_Time_Entry__c psot32 = new PS_Time_Entry__c(PS_SubTask__c = subTask1.id, PS_Task__c = task1.id, Hours_Spent__c=4,Time_Entry_Date__c=system.today().addDays(1),Comments__c='hello');
        psoList1.add(psot32); 
        PS_Time_Entry__c psot42 = new PS_Time_Entry__c(PS_SubTask__c = subTask2.id, PS_Task__c = task2.id, Hours_Spent__c=1,Time_Entry_Date__c=system.today().addDays(-2),Comments__c='hello');
        psoList1.add(psot42);
        PS_Time_Entry__c psot52 = new PS_Time_Entry__c(PS_SubTask__c = subTask2.id, PS_Task__c = task2.id, Hours_Spent__c=3,Time_Entry_Date__c=system.today(),Comments__c='hello');
        psoList1.add(psot52);
        PS_Time_Entry__c psot62 = new PS_Time_Entry__c(PS_SubTask__c = subTask2.id, PS_Task__c = task2.id, Time_Entry_Date__c=system.today().addDays(1),Comments__c='hello');
        psoList1.add(psot62); 
        delete psoList1; */
    }
    
    public static testMethod void PSTimeEntryTriggerHandler() {
        Test.startTest();
        PS_Project__c proj1 = [select Id from PS_Project__c limit 1];
        List<Order> orderList = [select Id from Order];
        List<PS_Task__c> taskList = [select Id,Project__c,Name,Task_Type__c from PS_Task__c];
        List<PS_SubTask__c> subtakList = [select Id,Name,Task__c,Task_Type__c from PS_SubTask__c];  
        Test.StopTest();
    }
   
    
    
    
    
}