force-app/main/default/objects/PS_Project__c/PS_Project__c.object-meta.xml
<CustomObject>
    <description>SOX object - This object is used to track the Projects which are related to Professional Services SKU.</description>
    <label>PS Project</label>
    <nameField>
        <label>PS Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PS Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PS_Project__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field refers to Account related to PS Project</description>
    <inlineHelpText>This field refers to Account related to PS Project</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PS Projects</relationshipLabel>
    <relationshipName>PS_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PS_Project__c/fields/Project_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Status__c</fullName>
    <description>PS Project&apos;s current status</description>
    <inlineHelpText>PS Project&apos;s current status</inlineHelpText>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PS_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PS_Project_Team_Member__c/PS_Project_Team_Member__c.object-meta.xml
<CustomObject>
    <description>SOX object - Represents Professional Services Users that worked on the Opportunity and will be working on the PS Project.</description>
    <label>PS Project Team Member</label>
    <nameField>
        <displayFormat>PSM-{0000000}</displayFormat>
        <label>PS Project Team Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PS Project Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PS_Project_Team_Member__c/fields/PS_Project__c.field-meta.xml
<CustomField>
    <fullName>PS_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PS Project</label>
    <referenceTo>PS_Project__c</referenceTo>
    <relationshipLabel>PS Project Team Members</relationshipLabel>
    <relationshipName>PS_Project_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PS_SubTask__c/PS_SubTask__c.object-meta.xml
<CustomObject>
    <description>Object to capture Subtask related to PS Task under PS Project</description>
    <label>Legacy PS SubTask</label>
    <nameField>
        <displayFormat>SUBTASK-{0000000}</displayFormat>
        <label>PS SubTask ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PS Legacy PS SubTasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PS_SubTask__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Task__r.Project__r.Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Account Name from related PS Project</inlineHelpText>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PS_SubTask__c/fields/Hours_logged__c.field-meta.xml
<CustomField>
    <fullName>Hours_logged__c</fullName>
    <inlineHelpText>Should be in the unit of hours. 1 day = 8 hours</inlineHelpText>
    <label># of hours logged(Deprecated)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PS_SubTask__c/fields/PS_Assignee__c.field-meta.xml
<CustomField>
    <fullName>PS_Assignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The assignee for the PS Subtask</description>
    <inlineHelpText>The assignee for the PS Subtask</inlineHelpText>
    <label>PS Assignee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PS_Subtasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PS_SubTask__c/fields/Subtask_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Subtask_End_Date__c</fullName>
    <description>End Date for Subtask</description>
    <label>Subtask End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PS_SubTask__c/fields/Subtask_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Subtask_Start_Date__c</fullName>
    <description>Start Date for Subtask</description>
    <label>Subtask Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PS_SubTask__c/fields/Subtask_Type__c.field-meta.xml
<CustomField>
    <fullName>Subtask_Type__c</fullName>
    <inlineHelpText>Select subtask Type:
For Install Task: 
Install

For Consult Task: 
Advanced Configuration
Automation
Deep-Dive Training
Onsite Resident
Documentation

For Admin Task: 
Travel
Training
PTO
CS</inlineHelpText>
    <label>Subtask Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Task_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Install</fullName>
            </value>
            <value>
                <fullName>Advanced Configuration</fullName>
            </value>
            <value>
                <fullName>Automation</fullName>
            </value>
            <value>
                <fullName>Deep-Dive Training</fullName>
            </value>
            <value>
                <fullName>Onsite Resident</fullName>
            </value>
            <value>
                <fullName>Documentation</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>PTO</fullName>
            </value>
            <value>
                <fullName>CSAT</fullName>
            </value>
            <value>
                <fullName>POC</fullName>
            </value>
            <value>
                <fullName>Shadow</fullName>
            </value>
            <value>
                <fullName>Break/fix</fullName>
            </value>
            <value>
                <fullName>Partner Enablement</fullName>
            </value>
            <value>
                <fullName>Consult (Non billable)</fullName>
            </value>
            <value>
                <fullName>Install (Non billable)</fullName>
            </value>
            <value>
                <fullName>Holiday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PS_SubTask__c/fields/Task__c.field-meta.xml
<CustomField>
    <fullName>Task__c</fullName>
    <description>PS Task related to this Subtask</description>
    <inlineHelpText>Select PS Task related to this Subtask</inlineHelpText>
    <label>Task</label>
    <referenceTo>PS_Task__c</referenceTo>
    <relationshipLabel>PS Subtasks</relationshipLabel>
    <relationshipName>PS_Subtasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PS_SubTask__c/fields/Task_Type__c.field-meta.xml
<CustomField>
    <fullName>Task_Type__c</fullName>
    <label>Task Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Install</fullName>
            </value>
            <value>
                <fullName>Consult</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PS_Task__c/PS_Task__c.object-meta.xml
<CustomObject>
    <description>SOX object - This object is used to track the task performed as part of PS Project</description>
    <label>PS Task</label>
    <nameField>
        <displayFormat>PST-{0000000}</displayFormat>
        <label>PS Task ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PS Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PS_Task__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PS Tasks</relationshipLabel>
    <relationshipName>PS_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PS_Task__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>PS Project related to this Task</description>
    <inlineHelpText>PS Project related to this Task</inlineHelpText>
    <label>Project</label>
    <referenceTo>PS_Project__c</referenceTo>
    <relationshipLabel>PS Tasks</relationshipLabel>
    <relationshipName>PS_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PS_Task__c/fields/Project_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Status__c</fullName>
    <description>DO NOT ADD TO PAGE LAYOUT</description>
    <formula>TEXT(Project__r.Project_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>DO NOT ADD TO PAGE LAYOUT</inlineHelpText>
    <label>Hidden Project Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PS_Task__c/fields/Task_Status__c.field-meta.xml
<CustomField>
    <fullName>Task_Status__c</fullName>
    <description>Status of the PS Task</description>
    <inlineHelpText>Status of the PS Task</inlineHelpText>
    <label>Task Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PS_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PS_Task__c/fields/Task_Type__c.field-meta.xml
<CustomField>
    <fullName>Task_Type__c</fullName>
    <description>Type of the PS Task</description>
    <inlineHelpText>Type of the PS Task</inlineHelpText>
    <label>Task Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Install</fullName>
            </value>
            <value>
                <fullName>Consult</fullName>
            </value>
            <value>
                <fullName>Consult-Onsite</fullName>
            </value>
            <value>
                <fullName>Consult-Remote</fullName>
            </value>
            <value>
                <fullName>Resident Engineer</fullName>
            </value>
            <value>
                <fullName>CSAT</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Migration</fullName>
            </value>
            <value>
                <fullName>T&amp;E</fullName>
            </value>
            <value>
                <fullName>Non-Billable (Product)</fullName>
            </value>
            <value>
                <fullName>Non-Billable (PS)</fullName>
            </value>
            <value>
                <fullName>Non-Billable (Sales)</fullName>
            </value>
            <value>
                <fullName>Non-Billable (Expired)</fullName>
            </value>
            <value>
                <fullName>Resident Engineer-PD</fullName>
            </value>
            <value>
                <fullName>Install-PD</fullName>
            </value>
            <value>
                <fullName>Consult-Remote-PD</fullName>
            </value>
            <value>
                <fullName>Consult-Onsite-PD</fullName>
            </value>
            <value>
                <fullName>RCDM-Install</fullName>
            </value>
            <value>
                <fullName>Accelerator</fullName>
            </value>
            <value>
                <fullName>Rubrik University</fullName>
            </value>
            <value>
                <fullName>Non-Billable Admin</fullName>
            </value>
            <value>
                <fullName>Non-Billable CSAT</fullName>
            </value>
            <value>
                <fullName>Non-Billable PreSales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PS_Time_Entry__c/PS_Time_Entry__c.object-meta.xml
<CustomObject>
    <description>SOX object - For tracking time entries for related PS Project</description>
    <label>PS Time Entry</label>
    <nameField>
        <label>PS Time Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PS Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PS_Time_Entry__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <formula>HYPERLINK(&quot;/&quot; +PS_Task__r.Project__c, PS_Task__r.Project__r.Name, &quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PS_Time_Entry__c/fields/PS_Subtask__c.field-meta.xml
<CustomField>
    <fullName>PS_Subtask__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>(Deprecate) PS Subtask</label>
    <referenceTo>PS_SubTask__c</referenceTo>
    <relationshipLabel>PS Time Entries</relationshipLabel>
    <relationshipName>PS_Time_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PS_Time_Entry__c/fields/PS_Task__c.field-meta.xml
<CustomField>
    <fullName>PS_Task__c</fullName>
    <description>Task related to the time sheet</description>
    <inlineHelpText>Task related to the time sheet</inlineHelpText>
    <label>PS Task</label>
    <referenceTo>PS_Task__c</referenceTo>
    <relationshipLabel>PS Time Entries</relationshipLabel>
    <relationshipName>PS_Time_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PS_Time_Entry__c/fields/Task__c.field-meta.xml
<CustomField>
    <fullName>Task__c</fullName>
    <formula>TEXT(PS_Task__r.Task_Type__c) +&apos; &apos;+ TEXT(PS_Task__r.Task_Subtype__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Task</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PS_Time_Entry__c/fields/Task_Type__c.field-meta.xml
<CustomField>
    <fullName>Task_Type__c</fullName>
    <formula>TEXT(PS_Subtask__r.Task_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Task Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PSProjectTeamMEmberTriggerTest.cls
@isTest
public class PSProjectTeamMEmberTriggerTest {
	@testSetup static  void createdata(){
        ShGl_TestFactoryHelper.insertCustomSettings();
		ShGl_TestFactoryHelper.WorkflowTriggerBypass();
        
        List<PS_Task__c> taskList = new List<PS_Task__c>();
        List<PS_SubTask__c> subtaskList = new List<PS_SubTask__c>(); 
        List<PS_Time_Entry__c> psoList = new List<PS_Time_Entry__c>();
         
        Account acc = new Account(name='test1239');
        insert acc;
        
        PS_Project__c proj = new PS_Project__c(Account__c=acc.Id,Project_Status__c='Open');
        insert proj;

        PS_Task__c task1 = new PS_Task__c(Project__c=proj.Id,Task_Type__c='Install',Task_Status__c='Open');
        taskList.add(task1);
        PS_Task__c task2 = new PS_Task__c(Project__c=proj.Id,Task_Type__c='Install',Task_Status__c='Open');
        taskList.add(task2);
        insert taskList;
         
        PS_SubTask__c subtask11 = new PS_SubTask__c(Subtask_End_Date__c=system.today(),Subtask_Start_Date__c=system.today(),Subtask_Type__c='Install',Hours_logged__c=10,PS_Assignee__c=userinfo.getuserid(),Task__c=taskList[0].Id,Task_Type__c='Install');
        subtaskList.add(subtask11); 
        PS_SubTask__c subtask21 = new PS_SubTask__c(Subtask_End_Date__c=system.today(),Subtask_Start_Date__c=system.today(),Subtask_Type__c='Install',Hours_logged__c=10,Task__c=taskList[1].Id,Task_Type__c='Install');
        subtaskList.add(subtask21); 
        PS_SubTask__c subtask12 = new PS_SubTask__c(Subtask_End_Date__c=system.today(),Subtask_Start_Date__c=system.today(),Subtask_Type__c='Install',Hours_logged__c=10,PS_Assignee__c=userinfo.getuserid(),Task__c=taskList[0].Id,Task_Type__c='Install');
        subtaskList.add(subtask12);  
        insert subtaskList;
        PS_Project_Team_Member__C mem = new PS_Project_Team_Member__C();
        mem.Team_Member__c = userinfo.getuserId();
        mem.PS_Project__c = proj.Id;
        insert mem;
    }
    public static testMethod void testupdateteammems() {
        User u = [select Id,name from User where isActive = true AND ContactId=null limit 1];
        PS_Project__c proj1 = [select Id from PS_Project__c limit 1];
        PS_Project_Team_Member__C mem = [select Id,Team_Member__c from PS_Project_Team_Member__C limit 1];
        mem.Team_Member__c = u.Id;
        update mem;
    }
}