force-app/main/default/objects/PS_Project__c/PS_Project__c.object-meta.xml
<CustomObject>
    <description>SOX object - This object is used to track the Projects which are related to Professional Services SKU.</description>
    <label>PS Project</label>
    <nameField>
        <label>PS Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PS Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PS_Project_Team_Member__c/PS_Project_Team_Member__c.object-meta.xml
<CustomObject>
    <description>SOX object - Represents Professional Services Users that worked on the Opportunity and will be working on the PS Project.</description>
    <label>PS Project Team Member</label>
    <nameField>
        <displayFormat>PSM-{0000000}</displayFormat>
        <label>PS Project Team Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PS Project Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PS_Project_Team_Member__c/fields/PS_Project__c.field-meta.xml
<CustomField>
    <fullName>PS_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PS Project</label>
    <referenceTo>PS_Project__c</referenceTo>
    <relationshipLabel>PS Project Team Members</relationshipLabel>
    <relationshipName>PS_Project_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PS_Project_Team_Member__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>PS_Project_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PS_Task__c/PS_Task__c.object-meta.xml
<CustomObject>
    <description>SOX object - This object is used to track the task performed as part of PS Project</description>
    <label>PS Task</label>
    <nameField>
        <displayFormat>PST-{0000000}</displayFormat>
        <label>PS Task ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PS Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PS_Task__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>PS Project related to this Task</description>
    <inlineHelpText>PS Project related to this Task</inlineHelpText>
    <label>Project</label>
    <referenceTo>PS_Project__c</referenceTo>
    <relationshipLabel>PS Tasks</relationshipLabel>
    <relationshipName>PS_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PS_Time_Entry__c/PS_Time_Entry__c.object-meta.xml
<CustomObject>
    <description>SOX object - For tracking time entries for related PS Project</description>
    <label>PS Time Entry</label>
    <nameField>
        <label>PS Time Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PS Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PS_Time_Entry__c/fields/Assignee__c.field-meta.xml
<CustomField>
    <fullName>Assignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The person who enters the time on his name.</description>
    <inlineHelpText>The person who enters the time on his name.</inlineHelpText>
    <label>Assignee</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>PS_Time_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PS_Time_Entry__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <formula>HYPERLINK(&quot;/&quot; +PS_Task__r.Project__c, PS_Task__r.Project__r.Name, &quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PS_Time_Entry__c/fields/PS_Task__c.field-meta.xml
<CustomField>
    <fullName>PS_Task__c</fullName>
    <description>Task related to the time sheet</description>
    <inlineHelpText>Task related to the time sheet</inlineHelpText>
    <label>PS Task</label>
    <referenceTo>PS_Task__c</referenceTo>
    <relationshipLabel>PS Time Entries</relationshipLabel>
    <relationshipName>PS_Time_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PS_Time_Entry__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Time Entry Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Approval_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/PSProjectTeamMEmberTriggerHelper.cls
public class PSProjectTeamMEmberTriggerHelper {
    
    public static void cleanTimeEntryRecord(Id projId, Id UserId) {
        //Check if there is any other memeber record on the same project
        List<PS_Project_Team_Member__c> existingTeamMember = [SELECT Id, PS_Project__c FROM PS_Project_Team_Member__c 
                                                              WHERE PS_Project__c =: projId AND Team_Member__c= :UserId];
        system.debug(existingTeamMember.size()+' ____existingTeamMember____ '+existingTeamMember);
        
        if(existingTeamMember.isEmpty()) {
            //fetch all TE on the project
            list<PS_Time_Entry__c> allTimeEntry = [SELECT Id, Assignee__c, PS_Task__c, PS_Task__r.Project__c, Status__c 
                                                   FROM PS_Time_Entry__c WHERE 
                                                   PS_Task__r.Project__c =: projId AND 
                                                   Assignee__c = :UserId AND 
                                                   Status__c != 'Approved'];
            system.debug(allTimeEntry.size()+' ____eallTimeEntry____ '+allTimeEntry);
            if(!allTimeEntry.isEmpty()) 
                delete allTimeEntry;
        }  
    }
    
}