force-app/main/default/objects/Custom_Error_Log__c/Custom_Error_Log__c.object-meta.xml
<CustomObject>
    <description>To Capture error info in a transaction</description>
    <label>Custom Error Log</label>
    <nameField>
        <label>Custom Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ErrorLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Error_Log__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Class name throwing the error</description>
    <label>Class</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Error_Log__c/fields/ErrorTrace__c.field-meta.xml
<CustomField>
    <fullName>ErrorTrace__c</fullName>
    <label>ErrorTrace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Custom_Error_Log__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <label>Exception Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Custom_Error_Log__c/fields/Functionality__c.field-meta.xml
<CustomField>
    <fullName>Functionality__c</fullName>
    <description>Category of the function that triggered this log.</description>
    <label>Functionality</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bookings</fullName>
            </value>
            <value>
                <fullName>CompanyMaster</fullName>
            </value>
            <value>
                <fullName>Edubrite User Update</fullName>
            </value>
            <value>
                <fullName>ETM</fullName>
            </value>
            <value>
                <fullName>Polaris</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ETMStage_Monitoring__c/ETMStage_Monitoring__c.object-meta.xml
<CustomObject>
    <label>ETM Stage Monitoring</label>
    <nameField>
        <label>ETM Stage Monitoring Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ETM Stage Monitorings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ETMStage_Monitoring__c/fields/Stage_History__c.field-meta.xml
<CustomField>
    <fullName>Stage_History__c</fullName>
    <label>Stage History</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ETMStage_Monitoring__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Init</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Territory_Management_Setup__mdt/Territory_Management_Setup__mdt.object-meta.xml
<CustomObject>
    <label>Territory Managemet Controller</label>
    <pluralLabel>Territory Management Controllers</pluralLabel>
</CustomObject>

force-app/main/default/classes/ETMArchieveTerritoryModel.cls
/**
 * @File Name          : ETMArchieveTerritoryModel.cls
 * @Description        : 
 * @Author             : Chaitra 
 * @Group              : 
 * @Last Modified By   : Bhushan Patil
 * @Last Modified On   : 3/4/2020, 12:23:44 pm
 * @Modification Log   : 
 * Ver       Date            Author                 Modification
 * 1.0    24/3/2020         Chaitra     Initial Version
**/
public class ETMArchieveTerritoryModel implements Queueable {
    public string terrModelName;
    public Set<Id> jobIds = new Set<Id>();  
    public ETMArchieveTerritoryModel(set<Id>JobIds,string terrModelName){
        this.terrModelName = terrModelName;
        this.JobIds = JobIds;
    }
    
    public void execute(QueueableContext context) {
        Boolean archivingModel = false;
        String strArchivingTerrName;
        Integer DELAY_MIN = 10; 
        Integer DEFAULT_DELAY_MIN = 1;
        Map<String,Territory2Model> mapModels = New Map<String,Territory2Model>();
        system.debug('Archieving Model'+terrModelName);
        try{
            for(Territory_Management_Setup__mdt setupData: [select Field_Value__c  from Territory_Management_Setup__mdt where DeveloperName ='TimeDelay_Archieve']) {
                if(setupData.Field_Value__c != null){
                    DELAY_MIN = Integer.valueof(setupData.Field_Value__c);
                }     
            }//End of mdt for
            List<Territory2Model> lstmodel = [
                Select 
                    Id,
                    State,
                    Name
                from
                    Territory2Model
                Where 
                    State ='Active'
                OR
                    Name =: terrModelName
            ];
            for(Territory2Model objModel : lstmodel){
                mapModels.put(objModel.Name,objModel);
            }    
            if(mapModels.containsKey(terrModelName)){
                for(Territory2Model objModel : lstmodel){
                    if(objModel.state == 'Active' 
                    && objModel.Name != terrModelName){
                        objModel.State = 'Archiving';
                        archivingModel = true;
                        strArchivingTerrName = objModel.Name;
                    }
                }
            }
            DateTime scheduleTime ;
            if(archivingModel){
                update lstmodel;
                //UpdateTerritoryLogs(jobIds,'Archiving Territory : ',strArchivingTerrName);
                scheduleTime = Datetime.now().addminutes(DELAY_MIN);
                //ETM-185: Prod Issue fix
                String hour = String.valueOf(scheduleTime.hour()); 
                string minute = String.valueOf(scheduleTime.minute());
                String second = String.valueOf(scheduleTime.second());  
                String nextFireTime = '0 ' + minute + ' ' + hour + ' ' + String.valueOf(scheduleTime.day()) + ' ' + String.valueOf(scheduleTime.month()) + ' ?' + ' ' + String.valueOf(scheduleTime.year());
                System.schedule('ETM_ActivateTerritoryModel_' + String.valueOf(Datetime.now()), nextFireTime, new ETM_ActivateTerritoryModel(jobIds,terrModelName,strArchivingTerrName));
            } 
            else
                //ETM-185: Prod Issue fix //SAL24-334/SF-37097
                //Database.ExecuteBatch(new ETM_ExecuteTerritoryAssignmentRuleBatch(jobIds,terrModelName,strArchivingTerrName,true,false),200);
                Database.ExecuteBatch(new ETM_ExecuteTerritoryAssignmentRuleBatch(jobIds,terrModelName,strArchivingTerrName,true,false),100);
        } 
        catch(Exception e){
           CreateErrUpdateTerrLog(e.getMessage(),e.getStackTraceString(),jobIds,'Exception occurred during Archiving terr : ',strArchivingTerrName + ' \n '); // Future call from batch isn't allowed
        }   
    }//End of  execute
         
    @future
    public static void CreateErrUpdateTerrLog(string execptionMsg , string trace ,set<Id> logIds,String strStatus,String modelName) {
        Custom_Error_Log__c CaptureError = new Custom_Error_Log__c();
        CaptureError.Class__c = 'ETM_ArchivingTerritoryModel';
        CaptureError.Functionality__c = 'ETM';
        if(execptionMsg != NULL){
            CaptureError.Exception_Message__c= execptionMsg;
            CaptureError.ErrorTrace__c= trace;
        }
        insert CaptureError;
         List<ETMStage_Monitoring__c> lstStageMoniter = [
            Select 
                Id,
                Stage_History__c,
                Status__c
            From    
                ETMStage_Monitoring__c
            Where 
                Id IN :logIds];
        for(ETMStage_Monitoring__c obj : lstStageMoniter){
            if(obj.Stage_History__c != null){
                obj.Stage_History__c += '\n'+ strStatus + modelName ;
            }else{
                obj.Stage_History__c = strStatus + modelName ;
            } 
            if(CaptureError!=null)
            obj.Stage_History__c += 'Excep errId: '+CaptureError.id;  
            obj.Status__c = 'Failed';  
        }
        Update lstStageMoniter;
    }//End of CreateErrUpdateTerrLog
    
   
}//End of class