force-app/main/default/objects/Custom_Error_Log__c/Custom_Error_Log__c.object-meta.xml
<CustomObject>
    <description>To Capture error info in a transaction</description>
    <label>Custom Error Log</label>
    <nameField>
        <label>Custom Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ErrorLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Error_Log__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Class name throwing the error</description>
    <label>Class</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Error_Log__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <label>Exception Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Custom_Error_Log__c/fields/FailedRecords__c.field-meta.xml
<CustomField>
    <fullName>FailedRecords__c</fullName>
    <description>To list the records failed in a transaction</description>
    <label>FailedRecords</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Error_Log__c/fields/Functionality__c.field-meta.xml
<CustomField>
    <fullName>Functionality__c</fullName>
    <description>Category of the function that triggered this log.</description>
    <label>Functionality</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bookings</fullName>
            </value>
            <value>
                <fullName>CompanyMaster</fullName>
            </value>
            <value>
                <fullName>Edubrite User Update</fullName>
            </value>
            <value>
                <fullName>ETM</fullName>
            </value>
            <value>
                <fullName>Polaris</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MIP_Account_Contribution__c/MIP_Account_Contribution__c.object-meta.xml
<CustomObject>
    <description>SOX object - Used to assign Partner Accounts to a Partner Mutual Investment Plan Contract and calculate PSNL and Total Bookings amounts.</description>
    <label>MIP Account Contribution</label>
    <nameField>
        <displayFormat>MIP AC- {0000000}</displayFormat>
        <label>MIP Account Contribution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MIP Account Contributions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MIP_Account_Contribution__c/fields/AccountContractKey__c.field-meta.xml
<CustomField>
    <fullName>AccountContractKey__c</fullName>
    <description>unique key for MIP calculation batch</description>
    <formula>CASESAFEID(Partner_Account__c) + &apos;-&apos; + CASESAFEID(MIP_Contract__c)</formula>
    <label>AccountContractKey</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MIP_Account_Contribution__c/fields/MIP_Contract__c.field-meta.xml
<CustomField>
    <fullName>MIP_Contract__c</fullName>
    <label>MIP Contract</label>
    <referenceTo>MIP_Contract__c</referenceTo>
    <relationshipLabel>MIP Account Contributions</relationshipLabel>
    <relationshipName>MIP_Account_Contributions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MIP_Account_Contribution__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <label>Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>MIP Account Contributions</relationshipLabel>
    <relationshipName>MIP_Account_Contributions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MIP_Account_Contribution__c/fields/PSNL_Bookings__c.field-meta.xml
<CustomField>
    <fullName>PSNL_Bookings__c</fullName>
    <defaultValue>0.0</defaultValue>
    <label>Partner Sourced Bookings</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MIP_Account_Contribution__c/fields/Total_Bookings__c.field-meta.xml
<CustomField>
    <fullName>Total_Bookings__c</fullName>
    <defaultValue>0.0</defaultValue>
    <label>Total Bookings</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MIP_Contract__c/MIP_Contract__c.object-meta.xml
<CustomObject>
    <description>SOX object - Used to create Partner Mutual Investment Plan Contracts and calculate expected and actual payouts based on the progress made against the selected incentive program.</description>
    <label>MIP Contract</label>
    <nameField>
        <displayFormat>CID-{0000000}</displayFormat>
        <label>MIP Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MIP Contracts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/MIP_Contract__c/fields/Actual_Enrollment_Payout__c.field-meta.xml
<CustomField>
    <fullName>Actual_Enrollment_Payout__c</fullName>
    <label>Actual Enrollment Payout</label>
    <summarizedField>MIP_Element__c.Actual_Enrollment_Payout__c</summarizedField>
    <summaryFilterItems>
        <field>MIP_Element__c.Element_Type__c</field>
        <operation>equals</operation>
        <value>Enrollment</value>
    </summaryFilterItems>
    <summaryForeignKey>MIP_Element__c.MIP_Contract__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/MIP_Contract__c/fields/Participating_Partner_Accounts__c.field-meta.xml
<CustomField>
    <fullName>Participating_Partner_Accounts__c</fullName>
    <description>Semi Colon Separated list of Partner Account Id&apos;s which are part of partner account hierarchy and are MIP contract participants</description>
    <label>Participating Partner Accounts</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MIP_Contract__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Partner Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Partner_Distributor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>MIP Contracts</relationshipLabel>
    <relationshipName>MIP_Contracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MIP_Element__c/MIP_Element__c.object-meta.xml
<CustomObject>
    <description>SOX object - Used to create Partner Mutual Investment Plan Contract; set booking goals, set milestones, and request a Rubrik Funded Head count.</description>
    <label>MIP Element</label>
    <nameField>
        <displayFormat>ELE-{00000}</displayFormat>
        <label>Element ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MIP Elements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MIP_Element__c/fields/Actual_Enrollment_Payout__c.field-meta.xml
<CustomField>
    <fullName>Actual_Enrollment_Payout__c</fullName>
    <label>Actual Enrollment Payout</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MIP_Element__c/fields/Bookings_Last_Sync_Date__c.field-meta.xml
<CustomField>
    <fullName>Bookings_Last_Sync_Date__c</fullName>
    <label>Bookings Last Sync Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MIP_Element__c/fields/Contract_Period_Bookings__c.field-meta.xml
<CustomField>
    <fullName>Contract_Period_Bookings__c</fullName>
    <defaultValue>0.0</defaultValue>
    <label>Contract Period Bookings</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MIP_Element__c/fields/Contract_Period_Bookings_ACV__c.field-meta.xml
<CustomField>
    <fullName>Contract_Period_Bookings_ACV__c</fullName>
    <description>TCV Value will be populated for MIPs created in FY25H1 &amp;&amp; ACV Value will be populated for MIPs created after FY25H2</description>
    <inlineHelpText>TCV Value will be populated for MIPs created in FY25H1 and ACV Value will be populated for MIPs created after FY25H2</inlineHelpText>
    <label>Contract Period Bookings (ACV)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MIP_Element__c/fields/Element_Type__c.field-meta.xml
<CustomField>
    <fullName>Element_Type__c</fullName>
    <description>MIP Element Type - Partner Sourced Bookings, Total Bookings, Rebate Milestone, Funded Head, Enrollment</description>
    <label>Element Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PSNL Bookings</fullName>
                <label>Partner Sourced Bookings</label>
            </value>
            <value>
                <fullName>Total Bookings</fullName>
            </value>
            <value>
                <fullName>Funded Head</fullName>
            </value>
            <value>
                <fullName>Rebate Milestone</fullName>
            </value>
            <value>
                <fullName>Enrollment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MIP_Element__c/fields/Enrollment_Payout_Rate__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Payout_Rate__c</fullName>
    <label>Enrollment Payout Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/MIP_Element__c/fields/MIP_Contract__c.field-meta.xml
<CustomField>
    <fullName>MIP_Contract__c</fullName>
    <label>MIP Contract</label>
    <referenceTo>MIP_Contract__c</referenceTo>
    <relationshipLabel>MIP Elements</relationshipLabel>
    <relationshipName>MIP_Elements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MIP_Element__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>MIP Elements</relationshipLabel>
    <relationshipName>MIP_Elements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MIP_Element__c/recordTypes/Enrollment.recordType-meta.xml
<RecordType>
    <fullName>Enrollment</fullName>
    <active>true</active>
    <description>Enrollment Element</description>
    <label>Enrollment</label>
</RecordType>

force-app/main/default/classes/MIPSyncBatch.cls
global class MIPSyncBatch implements Database.Batchable<sObject>{
    public Id recordId = null;
    global MIPSyncBatch(Id RecordId){
        this.recordId = RecordId;
    }
    global Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id, Partner_Account__c,(SELECT Id, MIP_Contract__c, Element_Type__c, Contract_Period_Bookings__c, Contract_Period_Bookings_ACV__c , Bookings_Last_Sync_Date__c, Actual_Enrollment_Payout__c, Enrollment_Payout_Rate__c  FROM MIP_Elements__r WHERE (Element_Type__c = \'Total Bookings\' OR Element_Type__c = \'PSNL Bookings\' OR Element_Type__c =\'Enrollment\') AND (RecordType.Name =\'Bookings Element\' OR RecordType.Name =\'Enrollment\')),';
        query += ' Participating_Partner_Accounts__c, End_Date__c, Start_Date__c, Status__c, Fiscal_Period__c FROM MIP_Contract__c WHERE Status__c =\'Approved\' AND IsActive__c = true';
        
        if(recordId != null){
            query += ' AND Id =: recordId';
        }
        //participating accounts , query on Contract - status, start date , end date, account ids
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, list<MIP_Contract__c> mipContractList){
        Map<Id, MIP_Contract__c> mipContractMap = new Map<Id, MIP_Contract__c>();
        List<MIP_Element__c> mipElementList = new List<MIP_Element__c>();
        Map<String, MIP_Account_Contribution__c> mipAccConMap = new Map<String ,MIP_Account_Contribution__c>();
        Map<String, List<MIP_Contract__c>> accContractMap = new Map<String, List<MIP_Contract__c>>();
        Map<Id, Decimal> conTotalBookings = new Map<Id, Decimal>();
        Map<Id, Decimal> conPSNLBookings = new Map<Id, Decimal>();
        Map<String, Decimal> accConTotalBookings = new Map<String, Decimal>();
        Map<String, Decimal> accConPSNLBookings = new Map<String, Decimal>();
        Map<Id, MIP_Account_Contribution__c> mipAccConMapToUpdate = new Map<Id, MIP_Account_Contribution__c>();
		Map<Id,List<MIP_Account_Contribution__c>> mipContractMIPAccConMap = new Map<Id,List<MIP_Account_Contribution__c>>();
        Decimal totalMIPAccContriPSNLBooking;
        
        for(MIP_Contract__c mipCon : mipContractList)
        {
            mipContractMap.put(mipCon.Id, mipCon);
            if(mipCon.MIP_Elements__r.size() > 0)
            mipElementList.addAll(mipCon.MIP_Elements__r);
        }
        
        for(MIP_Account_Contribution__c mipAccCon : [SELECT Id, AccountContractKey__c, MIP_Contract__c, Partner_Account__c, PSNL_Bookings__c, Total_Bookings__c FROM MIP_Account_Contribution__c WHERE MIP_Contract__c IN: mipContractMap.keySet()])
        {
            mipAccConMap.put(mipAccCon.AccountContractKey__c,mipAccCon);
            if(!accContractMap.containsKey(mipAccCon.Partner_Account__c)){
                accContractMap.put(mipAccCon.Partner_Account__c, new List<MIP_Contract__c>{mipContractMap.get(mipAccCon.MIP_Contract__c)});
            }else{
                List<MIP_Contract__c> mipConList = accContractMap.get(mipAccCon.Partner_Account__c);
                mipConList.add(mipContractMap.get(mipAccCon.MIP_Contract__c));
                accContractMap.put(mipAccCon.Partner_Account__c, mipConList);
            }
        }
        
        
        for(Opportunity opp : [SELECT Id, StageName, Partner_Lookup__c, ACV_Amount__c, Amount, Deal_Registration_Type__c, CloseDate from Opportunity WHERE Partner_Lookup__c IN:accContractMap.keySet() AND StageName ='7 Closed Won']){
             
            List<MIP_Contract__c> contrList = accContractMap.get(opp.Partner_Lookup__c);
            for(MIP_Contract__c contractRec : contrList)
            {
                String key = opp.Partner_Lookup__c+'-'+contractRec.Id;
                
                Decimal amountValue = 0;
                String tcvLabel = Label.MIP_Contract_TCV_Fiscal_Period;
                String acvLabel = Label.MIP_Contract_ACV_Fiscal_Period;
                
                if(contractRec.Fiscal_Period__c != null && contractRec.Fiscal_Period__c.contains(tcvLabel)){
                    amountValue = opp.Amount;
                }else{
                    amountValue = opp.ACV_Amount__c;
                }

                if(opp.CloseDate <= mipContractMap.get(contractRec.Id).End_Date__c && opp.CloseDate >= mipContractMap.get(contractRec.Id).Start_Date__c)
                {
                    //accConTotalBookings
                    if(!accConTotalBookings.containsKey(key)){
                        accConTotalBookings.put(key, amountValue);
                    }else{
                        accConTotalBookings.put(key, accConTotalBookings.get(key) + amountValue);
                    }
                    if(!conTotalBookings.containsKey(contractRec.Id)){
                        conTotalBookings.put(contractRec.Id, amountValue);
                    }else{
                        conTotalBookings.put(contractRec.Id, conTotalBookings.get(contractRec.Id) + amountValue);
                    }
                    //PSNL Bookings
                    if(opp.Deal_Registration_Type__c == 'Partner Sourced New Logo (PSNL)'){
                        if(!accConPSNLBookings.containsKey(key)){
                            accConPSNLBookings.put(key, amountValue);
                        }else{
                            accConPSNLBookings.put(key, accConPSNLBookings.get(key) + amountValue);
                        }
                        
                        if(!conPSNLBookings.containsKey(contractRec.Id)){
                            conPSNLBookings.put(contractRec.Id, amountValue);
                        }else{
                            conPSNLBookings.put(contractRec.Id, conPSNLBookings.get(contractRec.Id) + amountValue);
                        }
                    }
                }
            }
        }
        
        //update mip element PSNL/Total Bookings
        for(MIP_Element__c mipElement : mipElementList){
            if(conTotalBookings.containsKey(mipElement.MIP_Contract__c) && mipElement.Element_Type__c == 'Total Bookings')
            {
                mipElement.Contract_Period_Bookings_ACV__c = conTotalBookings.get(mipElement.MIP_Contract__c);
                mipElement.Bookings_Last_Sync_Date__c = date.today();
            }
            if(conPSNLBookings.containsKey(mipElement.MIP_Contract__c) && mipElement.Element_Type__c == 'PSNL Bookings')
            {
                mipElement.Contract_Period_Bookings_ACV__c = conPSNLBookings.get(mipElement.MIP_Contract__c);
                mipElement.Bookings_Last_Sync_Date__c = date.today();
            }
        }
        
        //update junction object
        for(MIP_Account_Contribution__c mipAccCon : mipAccConMap.values()){
            if(accConTotalBookings.containsKey(mipAccCon.AccountContractKey__c)){
                if(mipAccCon.Total_Bookings__c != accConTotalBookings.get(mipAccCon.AccountContractKey__c)){
                    mipAccCon.Total_Bookings__c = accConTotalBookings.get(mipAccCon.AccountContractKey__c);
                    mipAccConMapToUpdate.put(mipAccCon.Id, mipAccCon);
                }
            }
            if(accConPSNLBookings.containsKey(mipAccCon.AccountContractKey__c)){
                if(mipAccCon.PSNL_Bookings__c != accConPSNLBookings.get(mipAccCon.AccountContractKey__c)){
                    mipAccCon.PSNL_Bookings__c = accConPSNLBookings.get(mipAccCon.AccountContractKey__c);
                    mipAccConMapToUpdate.put(mipAccCon.Id, mipAccCon);
                }
            }
			
			if(!mipContractMIPAccConMap.containsKey(mipAccCon.MIP_Contract__c)){
				mipContractMIPAccConMap.put(mipAccCon.MIP_Contract__c, new List<MIP_Account_Contribution__c> {mipAccCon});
			}else{
				mipContractMIPAccConMap.get(mipAccCon.MIP_Contract__c).add(mipAccCon);
            }
        }
        
		
		//PRIT24-417
		//Populate MIP element Enrollment's Actual_Enrollment_Payout__c
		for(MIP_Element__c mipElement : mipElementList){
            if(mipElement.Element_Type__c == 'Enrollment' && mipContractMIPAccConMap.containsKey(mipElement.MIP_Contract__c)){
				totalMIPAccContriPSNLBooking = 0;
                system.debug('mipContractMIPAccConMap.get(mipElement.MIP_Contract__c)->'+mipContractMIPAccConMap.get(mipElement.MIP_Contract__c));
				for(MIP_Account_Contribution__c mipAccCont : mipContractMIPAccConMap.get(mipElement.MIP_Contract__c)){
                    system.debug('mipAccCont->'+mipAccCont.PSNL_Bookings__c);
					totalMIPAccContriPSNLBooking = totalMIPAccContriPSNLBooking + mipAccCont.PSNL_Bookings__c;
				}
				mipElement.Actual_Enrollment_Payout__c = totalMIPAccContriPSNLBooking * 0.01 * mipElement.Enrollment_Payout_Rate__c;
			}
		}
		
        
        List<Database.SaveResult> mipElementResult = Database.update(mipElementList, false);
        List<Database.SaveResult> mipAccConResult = Database.update(mipAccConMapToUpdate.values(), false);
        
        List<Custom_Error_Log__c> customErrorLogList = new List<Custom_Error_Log__c>();
        for(Integer i = 0 ; i < mipElementResult.size(); i++){
            Custom_Error_Log__c errorLogRec = new Custom_Error_Log__c();
            errorLogRec.Class__c = 'MIPSyncBatch';
            errorLogRec.Functionality__c = 'Recalculate MIP Contract';
            if(!mipElementResult.get(i).isSuccess() ){
                Database.Error dbError = mipElementResult.get(i).getErrors().get(0);
                errorLogRec.Exception_Message__c = dbError.getMessage();
                errorLogRec.FailedRecords__c  =mipElementList.get(i).Id;
                customErrorLogList.add(errorLogRec);
            }
        }
        for(Integer i=0; i < mipAccConResult.size(); i++){
            Custom_Error_Log__c errorLogRec = new Custom_Error_Log__c();
            errorLogRec.Class__c = 'MIPSyncBatch';
            errorLogRec.Functionality__c = 'Update Account Contract junction object';
            if(!mipAccConResult.get(i).isSuccess() ){
                Database.Error dbError = mipAccConResult.get(i).getErrors().get(0);
                errorLogRec.Exception_Message__c = dbError.getMessage();
                errorLogRec.FailedRecords__c  = mipAccConMapToUpdate.values().get(i).Id;
                customErrorLogList.add(errorLogRec);
            }
        }
        if(customErrorLogList.size()>0){
            insert customErrorLogList;
        }
        
    }
    
    global void finish(Database.BatchableContext BC){
        
    }
}