force-app/main/default/objects/Custom_Error_Log__c/Custom_Error_Log__c.object-meta.xml
<CustomObject>
    <description>To Capture error info in a transaction</description>
    <label>Custom Error Log</label>
    <nameField>
        <label>Custom Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ErrorLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Error_Log__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Class name throwing the error</description>
    <label>Class</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Error_Log__c/fields/ErrorTrace__c.field-meta.xml
<CustomField>
    <fullName>ErrorTrace__c</fullName>
    <label>ErrorTrace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Custom_Error_Log__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <label>Exception Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Custom_Error_Log__c/fields/Functionality__c.field-meta.xml
<CustomField>
    <fullName>Functionality__c</fullName>
    <description>Category of the function that triggered this log.</description>
    <label>Functionality</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bookings</fullName>
            </value>
            <value>
                <fullName>CompanyMaster</fullName>
            </value>
            <value>
                <fullName>Edubrite User Update</fullName>
            </value>
            <value>
                <fullName>ETM</fullName>
            </value>
            <value>
                <fullName>Polaris</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Territory_Owner_Assignment__c/Territory_Owner_Assignment__c.object-meta.xml
<CustomObject>
    <description>Stores the territoryId that needs  Account, Contact, Opportunity owner reassignment</description>
    <label>Territory Owner Assignment</label>
    <nameField>
        <label>Territory Owner Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Owner Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_Owner_Assignment__c/fields/Functionality__c.field-meta.xml
<CustomField>
    <fullName>Functionality__c</fullName>
    <description>Determines the ETM recalculation of TART or owner update based on functionality effected</description>
    <label>Functionality</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Owner Assignment</fullName>
                <default>true</default>
                <label>Owner Assignment</label>
            </value>
            <value>
                <fullName>Split Opportunity</fullName>
            </value>
            <value>
                <fullName>Sales Engineer Assignment</fullName>
            </value>
            <value>
                <fullName>Alliance Rep Assignment</fullName>
            </value>
            <value>
                <fullName>SDR Assignment</fullName>
            </value>
            <value>
                <fullName>Opp Co-Owner Assignment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UserTerritoryAssociation_History__c/UserTerritoryAssociation_History__c.object-meta.xml
<CustomObject>
    <label>UserTerritoryAssociation History</label>
    <nameField>
        <displayFormat>UTAH-{000000}</displayFormat>
        <label>UserTerritoryAssociation History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UserTerritoryAssociation History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UserTerritoryAssociation_History__c/fields/Adaptive_Territory_Id__c.field-meta.xml
<CustomField>
    <fullName>Adaptive_Territory_Id__c</fullName>
    <label>Adaptive Territory Id</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserTerritoryAssociation_History__c/fields/Territory_Id__c.field-meta.xml
<CustomField>
    <fullName>Territory_Id__c</fullName>
    <label>Territory Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserTerritoryAssociation_History__c/fields/Territory_Model__c.field-meta.xml
<CustomField>
    <fullName>Territory_Model__c</fullName>
    <label>Territory Model</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserTerritoryAssociation_History__c/fields/Territory_Model_State__c.field-meta.xml
<CustomField>
    <fullName>Territory_Model_State__c</fullName>
    <label>Territory Model State</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserTerritoryAssociation_History__c/fields/Territory_Type__c.field-meta.xml
<CustomField>
    <fullName>Territory_Type__c</fullName>
    <label>Territory Type</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserTerritoryAssociation_History__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserTerritoryAssociation_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UserTerritoryAssociation_History__c/fields/User_Territory_Role__c.field-meta.xml
<CustomField>
    <fullName>User_Territory_Role__c</fullName>
    <label>User Territory Role</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserTerritoryAssociation_History__c/fields/UserTerritoryAssociation_Id__c.field-meta.xml
<CustomField>
    <fullName>UserTerritoryAssociation_Id__c</fullName>
    <label>UserTerritoryAssociation Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UserTerritoryAssociationHistoryHelper.cls
/*********************************************************************************************************
Description : ETM-137: To create/update the UserTerritoryAssociation History when UTA is created or deleted
Developer : Natesh 
Date : 06/01/2020
**********************************************************************************************************/
public class UserTerritoryAssociationHistoryHelper implements Queueable{
    Set<Id> insertUTAIds;
    Set<Id> deleteUTAIds;
    String invokedFrom;
    //ETM-184: Start Date and End Date updates for commissions
    Map<Id, Date> insertUTAMap = new Map<Id, Date>();
    Map<Id, Date> updateUTAHistMap = new Map<Id, Date>();
    Set<Id> updateUTAIds = new Set<Id>();
    Set<Territory_Owner_Assignment__c> terrOwnerAssignSet = new Set<Territory_Owner_Assignment__c>(); //SAL25-57

    public UserTerritoryAssociationHistoryHelper(Set<Id> insertUTAIds, Set<Id> deleteUTAIds, String invokedFrom) {
        this.insertUTAIds = insertUTAIds;
        this.deleteUTAIds = deleteUTAIds;
        this.invokedFrom = invokedFrom;
    }

    //ETM-184: Start Date and End Date updates for commissions
    public UserTerritoryAssociationHistoryHelper(Map<Id, Date> insertUTAMap, Map<Id, Date> updateUTAHistMap, set<Id> updateUTAIds, String invokedFrom) {
        this.insertUTAMap = insertUTAMap;
        this.updateUTAHistMap = updateUTAHistMap;
        this.updateUTAIds = updateUTAIds;
        this.invokedFrom = invokedFrom;
    }

    //SAL25-57
    public UserTerritoryAssociationHistoryHelper(Set<Territory_Owner_Assignment__c> terrOwnerAssignSet, Map<Id, Date> insertUTAMap, Map<Id, Date> updateUTAHistMap, set<Id> updateUTAIds, String invokedFrom) {
        this.insertUTAMap = insertUTAMap;
        this.updateUTAHistMap = updateUTAHistMap;
        this.updateUTAIds = updateUTAIds;
        this.invokedFrom = invokedFrom;
        this.terrOwnerAssignSet = terrOwnerAssignSet;
    }
    
    //ETM-184: Start Date and End Date updates for commissions
    public void execute(QueueableContext context) {
        if(invokedFrom == 'BATCH'){
            createUTAHistory(insertUTAMap.keySet(), insertUTAMap);
            updateUTAHistory(updateUTAHistMap.keySet(), updateUTAHistMap, updateUTAIds);
            //SAL25-57
            if(terrOwnerAssignSet!= null && !terrOwnerAssignSet.isEmpty()){
                List<Territory_Owner_Assignment__c> terrOwnerAssignList = new List<Territory_Owner_Assignment__c>();
                terrOwnerAssignList.addall(terrOwnerAssignSet);
                List<Database.SaveResult> srList = Database.insert(terrOwnerAssignList, false);
                LogError.createDMLErrorLog((List<SObject>)terrOwnerAssignList, srList, 'UserTerritoryAssociationHistoryHelper','ETM - Insert TerritoryOwnerAssignment');
            }
        }
        else if(invokedFrom == 'TRIGGER-INSERT'){
            createUTAHistory(insertUTAIds, insertUTAMap); 
        }
        else if(invokedFrom == 'TRIGGER-DELETE'){
            updateUTAHistory(deleteUTAIds, updateUTAHistMap, updateUTAIds);
        }
        else{}
    }
    
    /**
        @Description : Create UTA History record when UTA record is created
    */
    //ETM-184: Start Date and End Date updates for commissions
    public static void createUTAHistory(Set<Id> newUTAIds, Map<Id, Date> insertUTAMap) {
        List<UserTerritoryAssociation_History__c> utaHistoryList = new List<UserTerritoryAssociation_History__c>();
        for(UserTerritory2Association uta :[select Id, Territory2Id, Territory2.Adaptive_Territory_Id__c, 
                                            Territory2.Territory2Model.DeveloperName, 
                                            Territory2.Territory2Model.State, 
                                            Territory2.Territory2Type.DeveloperName, 
                                            UserId, RoleInTerritory2 from UserTErritory2Association
                                            where Id IN :newUTAIds]) {
            UserTerritoryAssociation_History__c utaHist = new UserTerritoryAssociation_History__c();
            utaHist.Territory_Id__c = uta.Territory2Id;
            utaHist.Adaptive_Territory_Id__c = uta.Territory2.Adaptive_Territory_Id__c;
            utaHist.Territory_Model__c = uta.Territory2.Territory2Model.DeveloperName;
            utaHist.Territory_Model_State__c = uta.Territory2.Territory2Model.State;
            utaHist.Territory_Type__c = uta.Territory2.Territory2Type.DeveloperName;
            utaHist.User__c = uta.UserId;
            utaHist.User_Territory_Role__c = uta.RoleInTerritory2;
            //ETM-184: Start Date and End Date updates for commissions
            //utaHist.Start_Date__c = System.today();
            utaHist.Start_Date__c = !insertUTAMap.isEmpty() && insertUTAMap.containsKey(uta.Id) ? insertUTAMap.get(uta.Id) : System.today();
            utaHist.UserTerritoryAssociation_Id__c = uta.Id;

            utaHistoryList.add(utaHist);
        }
        if(!utaHistoryList.isEmpty()){
            try{
                Database.insert(utaHistoryList, false);
            }
            catch(Exception e){
                CreateErrLogs(e.getMessage(),e.getStackTraceString(), 'ETM-UTA-History-Insert', 'UserTerritory2AssociationTriggerHelper');
            }
        }
    }

    /**
        @Description : Create UTA History record when UTA record is deleted
    */
    //ETM-184: Start Date and End Date updates for commissions
    public static void updateUTAHistory(Set<Id> oldUTAIds, Map<Id, Date> updateUTAHistMap, set<Id> updateUTAIds) {
        Map<Id, UserTerritoryAssociation_History__c> utaHistoryMap = new Map<Id, UserTerritoryAssociation_History__c>();
        List<UserTerritoryAssociation_History__c> utaHistoryUpdateList = new List<UserTerritoryAssociation_History__c>();
        for(UserTerritoryAssociation_History__c utaHistItem :[select Id, UserTerritoryAssociation_Id__c, End_Date__c, Start_Date__c 
                                                          from UserTerritoryAssociation_History__c
                                                          where UserTerritoryAssociation_Id__c IN :oldUTAIds]){
            utaHistoryMap.put(utaHistItem.UserTerritoryAssociation_Id__c, utaHistItem);
            //ETM-184: Start Date and End Date updates for commissions
            //utaHistItem.End_Date__c = System.today();
            if(!updateUTAIds.isEmpty() && updateUTAIds.contains(utaHistItem.UserTerritoryAssociation_Id__c)) {
                if(utaHistItem.Start_Date__c != updateUTAHistMap.get(utaHistItem.UserTerritoryAssociation_Id__c)){
                    utaHistItem.Start_Date__c = updateUTAHistMap.get(utaHistItem.UserTerritoryAssociation_Id__c);
                    utaHistoryUpdateList.add(utaHistItem);
                }
            }
            else{
                utaHistItem.End_Date__c = !updateUTAHistMap.isEmpty() && updateUTAHistMap.containsKey(utaHistItem.UserTerritoryAssociation_Id__c) ? updateUTAHistMap.get(utaHistItem.UserTerritoryAssociation_Id__c) : System.today();
                utaHistoryUpdateList.add(utaHistItem);
            }
        }
        if(!utaHistoryUpdateList.isEmpty()){
            try{
                Database.update(utaHistoryUpdateList, false);
            }
            catch(Exception e){
                CreateErrLogs(e.getMessage(),e.getStackTraceString(), 'ETM-UTA-History-Update', 'UserTerritoryAssociationHistoryHelper');
            }
        }
    }

    public static void CreateErrLogs(string execptionMsg , string trace, String functionality, string className) {
        Custom_Error_Log__c CaptureError = new Custom_Error_Log__c();
        CaptureError.Class__c = className;
        CaptureError.Functionality__c = functionality;
        if(execptionMsg != NULL){
            CaptureError.Exception_Message__c= execptionMsg;
            CaptureError.ErrorTrace__c= trace;
        }
        insert CaptureError;
    }
}