force-app/main/default/objects/Custom_Error_Log__c/Custom_Error_Log__c.object-meta.xml
<CustomObject>
    <description>To Capture error info in a transaction</description>
    <label>Custom Error Log</label>
    <nameField>
        <label>Custom Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ErrorLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Error_Log__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Class name throwing the error</description>
    <label>Class</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Error_Log__c/fields/Functionality__c.field-meta.xml
<CustomField>
    <fullName>Functionality__c</fullName>
    <description>Category of the function that triggered this log.</description>
    <label>Functionality</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bookings</fullName>
            </value>
            <value>
                <fullName>CompanyMaster</fullName>
            </value>
            <value>
                <fullName>Edubrite User Update</fullName>
            </value>
            <value>
                <fullName>ETM</fullName>
            </value>
            <value>
                <fullName>Polaris</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Error_Log__c/fields/Http_Request__c.field-meta.xml
<CustomField>
    <fullName>Http_Request__c</fullName>
    <description>Capture the request of callout</description>
    <label>Http Request</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Custom_Error_Log__c/fields/Http_Response__c.field-meta.xml
<CustomField>
    <fullName>Http_Response__c</fullName>
    <label>Http Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Custom_Error_Log__c/fields/Server_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Server_Endpoint__c</fullName>
    <description>Endpoint url of external system</description>
    <label>Server Endpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Product_Feature__c/Product_Feature__c.object-meta.xml
<CustomObject>
    <description>SOX object - Holds feature data</description>
    <label>PDM Feature</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Feature Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PDM Feature</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Feature__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <label>Feature</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HYBRID RCDM</fullName>
            </value>
            <value>
                <fullName>CLOUD NATIVE PROTECTION</fullName>
            </value>
            <value>
                <fullName>KUBERNETES</fullName>
            </value>
            <value>
                <fullName>CLOUD CLUSTER ES</fullName>
            </value>
            <value>
                <fullName>CLOUD VAULT BACKUP</fullName>
            </value>
            <value>
                <fullName>SONAR</fullName>
            </value>
            <value>
                <fullName>APPFLOWS</fullName>
            </value>
            <value>
                <fullName>INCIDENT CONTAINMENT</fullName>
            </value>
            <value>
                <fullName>POLARIS RADAR</fullName>
            </value>
            <value>
                <fullName>HYBRID EDGE</fullName>
            </value>
            <value>
                <fullName>NAS DIRECT ARCHIVE</fullName>
            </value>
            <value>
                <fullName>IGNEOUS</fullName>
            </value>
            <value>
                <fullName>CLOUD VAULT ARCHIVE</fullName>
            </value>
            <value>
                <fullName>CLOUDON</fullName>
            </value>
            <value>
                <fullName>POLARIS GPS</fullName>
            </value>
            <value>
                <fullName>APP FLOWS</fullName>
            </value>
            <value>
                <fullName>PREMIUM SUPPORT</fullName>
            </value>
            <value>
                <fullName>CLOUDOUT</fullName>
            </value>
            <value>
                <fullName>CLOUD EDITION</fullName>
            </value>
            <value>
                <fullName>NAS CLOUD DIRECT</fullName>
            </value>
            <value>
                <fullName>CLOUD CLUSTER</fullName>
            </value>
            <value>
                <fullName>HYBRID SAP HANA</fullName>
            </value>
            <value>
                <fullName>UCL</fullName>
            </value>
            <value>
                <fullName>NOSQL</fullName>
            </value>
            <value>
                <fullName>PMC</fullName>
            </value>
            <value>
                <fullName>M365</fullName>
            </value>
            <value>
                <fullName>M365H</fullName>
            </value>
            <value>
                <fullName>THIRD PARTY RCDM</fullName>
            </value>
            <value>
                <fullName>RCDM</fullName>
            </value>
            <value>
                <fullName>HW SUPPORT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Feature__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>PDM Feature</relationshipLabel>
    <relationshipName>PDM_Feature</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RSCInstance__c/RSCInstance__c.object-meta.xml
<CustomObject>
    <description>The RSC Instance object is designed to model and manage Rubrik Service Cloud (RSC) accounts, supporting complex customer hierarchies, multiple account and URL relationships, and integrated with product provisioning. It is central to the multi-account project, enabling Rubrik to handle direct customers, MSPs, resellers, and various contract types</description>
    <label>RSC Instance</label>
    <nameField>
        <label>RSC Account Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSC Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RSCInstance__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It represents related Account</description>
    <label>Primary Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>RSC Instances</relationshipLabel>
    <relationshipName>RSCInstances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RSCInstance__c/fields/ContractType__c.field-meta.xml
<CustomField>
    <fullName>ContractType__c</fullName>
    <description>It represents the Contract/License Type</description>
    <label>License Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shared</fullName>
            </value>
            <value>
                <fullName>Dedicated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RSCInstance__c/fields/SDPEndUser__c.field-meta.xml
<CustomField>
    <fullName>SDPEndUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SDP End User</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>RSC Instances (SDP End User)</relationshipLabel>
    <relationshipName>SDP_RSCInstances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Setup_Integration_Log__mdt/Setup_Integration_Log__mdt.object-meta.xml
<CustomObject>
    <description>To control logging integration calls to third party systems</description>
    <label>Setup Integration Log</label>
    <pluralLabel>Setup Integration Logs.</pluralLabel>
</CustomObject>

force-app/main/default/objects/Setup_Integration_Log__mdt/fields/Enable_Custom_Logs__c.field-meta.xml
<CustomField>
    <fullName>Enable_Custom_Logs__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To store the Integartion logs</description>
    <label>Enable Custom Logs</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PolarisFeatureDetails_Webservice.cls
/*****************************************************************************************
Description : PRDOPS21-339
              Rest api used by polaris team 
Developer :   Chaitra  
Date :        12/2020
 * @last modified on  : 12-29-2025
 * Modifications Log
 * Ver   Date           Author        Modification
 * 1.0   12-2020        Chaitra       Initial Version - PRDOPS21-339
 * 2.0   12-29-2025     Prashik       RSC Instnace De-Provisioning - FY26WL-567
*****************************************************************************************/
/**
 * @author Chaitra
 * @description Rest api used by polaris team
 */
@RestResource(urlMapping='/polaris/getFeatureDetails')
global with sharing class PolarisFeatureDetails_Webservice {
  /**************************************************************
Input : accountId 
        featureType : Try N Buy ; POC ;  Revenue
        fieldset : list of extra fields to be set in response
           {
            accountid:001W000000vYD9ZIAW
            featuretype:Try N Buy
            fieldset:order.account.name,SBQQ__Asset__r.name
           }
Output : Latest order product details based on feature type  
*****************************************************************/
  /**
   * @author Prashant Kumar
   * @date 05-06-2025
   * @description fetchFeatureDetails method to provide json related to Entitlement and orderitems.
   */
  @HttpGet
  global static void fetchFeatureDetails() {
    RestRequest request = RestContext.request;
    Custom_Error_Log__c IntegrationLog = new Custom_Error_Log__c(
      Class__c = 'PolarisFeatureDeatils_Webservice',
      Functionality__c = 'Polaris',
      Server_Endpoint__c = '/polaris/getFeatureDetails'
    );
    System.debug(logginglevel.INFO, JSON.serializepretty(request));
    RestResponse res = RestContext.response;
    string resBody;
    string featureType;
    Map<string, object> featureDeatils = new Map<string, object>();
    Id accountId;
    String rscInstanceId; //Added for FY26WL-567
    String sdpEndUserId; //Added for FY26WL-567
    List<orderItem> OIList = new List<orderItem>();
    set<string> prodCode = new Set<string>();
    string fieldStr;
    list<Entitlement> ettList = new List<Entitlement>();
    list<string> fieldSet = new List<string>();
    Map<String, string> reqHeader = new Map<String, string>();
    List<Setup_Integration_Log__mdt> logCntrlr = new List<Setup_Integration_Log__mdt>();
    string whereClause;
    List<Map<string, object>> ordDetails = new List<Map<string, object>>();
    List<Account> currentAccount = new List<Account>();
    List<RSCInstance__c> currentRSCInstnaces = new List<RSCInstance__c>(); //Added for FY26WL-567
    Map<String, orderitem> compareLatestEnttAndOIMap = new Map<String, orderitem>();
    set<string> prodCodeEtt = new Set<string>();
    Map<String, Contractlineitem> productCodeToContractlineMap = new Map<String, Contractlineitem>();
    Boolean ManuallyReviewReqd = false;
    set<Id> pdmEnabledproductIds = new Set<Id>();
    Map<Id, List<String>> prodIdToBundleFeature = new Map<Id, List<String>>(); // to store bundle features corresponding to productId
    String regExp = '(^[\'"]|[\'"]$)|\\b(?i)null\\b';  //Added for FY26WL-567
    Boolean isSharedInstance = false; //Added for FY26WL-567

    try {
      logCntrlr = [SELECT id, Enable_Custom_Logs__c FROM Setup_Integration_Log__mdt WHERE DeveloperName = 'Polaris'];
      reqHeader = request.headers;
      IntegrationLog.Http_Request__c = JSON.serialize(reqHeader);
      featureType = reqHeader.get('featuretype');
      accountId = (Id) reqHeader.get('accountid');
      fieldStr = (string) reqHeader.get('fieldset');
      String rscRawValue = reqHeader.get('rscinstanceid');
      String sdpRawValue = reqHeader.get('sdpenduserid');
      rscInstanceId = (rscRawValue != null && String.isNotBlank(rscRawValue.replaceAll(regExp, '').trim())) ? (rscRawValue.replaceAll(regExp, '').trim()) : null;
      sdpEndUserId = (sdpRawValue != null && String.isNotBlank(sdpRawValue.replaceAll(regExp, '').trim())) ? (sdpRawValue.replaceAll(regExp, '').trim()) : null;
      if (rscInstanceId != null) {
        // Query RSC record
        currentRSCInstnaces = [
          SELECT Id, AccountId__c, SDPEndUser__c, ContractType__c
          FROM RSCInstance__c
          WHERE Id = :rscInstanceId
          WITH SECURITY_ENFORCED
          LIMIT 1
        ];
        system.debug(logginglevel.DEBUG, 'currentRSCInstnaces >>' + currentRSCInstnaces);
        if (!currentRSCInstnaces.isEmpty()) {
          accountId = currentRSCInstnaces[0].AccountId__c;
          sdpEndUserId = currentRSCInstnaces[0].SDPEndUser__c;
          isSharedInstance = (currentRSCInstnaces[0].ContractType__c == Constants.RSCINSTANCE_CONTRACT_TYPE_SHARED);
          
          featureDeatils.put('rscInstanceId', rscInstanceId);
          featureDeatils.put('sdpEndUserId', sdpEndUserId);
        } else {
          res.statusCode = 400;
          resBody = '{"status":"unsuccessful","message":"Invalid rscid provided"}';
          res.responseBody = Blob.valueof(resBody);
          return;
        }
      }
      if (accountId == null || string.isBlank(featureType)) {
        res.statusCode = 400;
        resBody = '{"status":"unsuccessful","Bad Request - Either accountid or featureType is missing"}';
        res.responseBody = Blob.valueof(resBody);
        return;
      }
      currentAccount = [SELECT Id, Owner.Email, Rubrik_Sales_Engineer__r.Email FROM Account WHERE Id = :accountId];
      if(!isSharedInstance){
        string ettquery = 'SELECT Id, Product__r.name, ContractLineItem.SBQQSC__Account__c,contractlineitem.enddate, contractlineitem.quantity,Order_Service_Item__r.Support_Start_Date__c, Order_Service_Item__r.product2.ProductCode,Order_Service_Item__r.product2Id, Order_Service_Item__r.Support_End_Date__c,Order_Service_Item__r.User_license_count__c, Order_Service_Item__r.createddate, Order_Service_Item__r.LastModifiedDate, Order_Service_Item__r.product2.Bundle_Features__c,Product__r.PDM_Feature_Enabled__c FROM Entitlement';
        string ettWhereClause = ' WHERE type!=\'Manufacturing Entitlement\' AND accountId= :accountId AND Order_Service_Item__c!=null AND Order_Service_Item__r.order.accountId !=: accountId';
        if (String.isNotBlank(sdpEndUserId)) {
          ettWhereClause += ' AND MSP_End_User_Lookup__c = :sdpEndUserId AND Order_Service_Item__r.order.Opportunity.MSP_End_User_Lookup__c !=: sdpEndUserId';
        }
        if ('revenue'.equalsIgnoreCase(featureType)) {
          ettWhereClause += ' AND Order_Service_Item__r.Order.Type =\'revenue\'';
        } else {
          ettWhereClause += ' AND Order_Service_Item__r.Order.Type=\'POC\' AND Order_Service_Item__r.Order.Order_Sub_Type__c =:featureType';
        }
        system.debug(LoggingLevel.DEBUG, 'ettWhereClause is ' + ettWhereClause);
        if (string.isNotBlank(ettWhereClause)) {
          ettquery += ettWhereClause;
        }
        ettquery += ' order by enddate desc';
        ettList = database.query(ettquery);

        for (Entitlement ett : ettList) {
          if (ett.Product__r.PDM_Feature_Enabled__c) {
            pdmEnabledproductIds.add(ett.Product__c);
          }
        }

        String query = 'SELECT product2.PDM_Feature_Enabled__c, product2.ProductCode, Support_End_Date__c, User_license_count__c, createddate, lastmodifieddate, Order.Account.Owner.Email, Order.Account.Rubrik_Sales_Engineer__r.Email, product2.Bundle_Features__c';
        List<String> existingFieldsList = query.replace('SELECT', '').deletewhitespace().toLowerCase().split(',');
        if (!String.isBlank(fieldStr)) {
          fieldSet = fieldStr.split(',');
          existingFieldsList.addAll(fieldStr.deletewhitespace().toLowerCase().split(','));
        }
        Set<String> existingFields = new Set<String>(existingFieldsList);
        existingFieldsList.clear();
        existingFieldsList.addAll(existingFields);
        query = 'SELECT ' + String.join(existingFieldsList, ', ') + ' from orderItem';
        whereClause = ' WHERE order.accountId =: accountId';
        if (sdpEndUserId != null) {
          whereClause += ' AND order.opportunity.MSP_End_User_Lookup__c = :sdpEndUserId';
        }
        if ('revenue'.equalsIgnoreCase(featureType)) {
          whereClause += ' AND Order.Type =\'revenue\'';
        } else {
          whereClause += ' AND Order.Type=\'POC\' AND Order.Order_Sub_Type__c =:featureType';
        }
        if (string.isNotBlank(whereClause)) {
          query += whereClause;
        }
        query += ' order by createddate desc';
        system.debug(logginglevel.INFO, query);
        OIList = database.query(query);
        for (orderItem OI : OIList) {
          if (OI.product2.PDM_Feature_Enabled__c) {
            pdmEnabledproductIds.add(OI.product2Id);
          }
        }

        prodIdToBundleFeature = getPDMFeaturesBasedIfEnabled(pdmEnabledproductIds);

        for (orderItem OI : OIList) {
          Map<string, object> OrdItems = new Map<string, object>();
          if (prodCode.contains(OI.product2.ProductCode)) {
            continue;
          }
          OrdItems.put('productName', OI.product2.ProductCode);
          OrdItems.put('supportEndDate', OI.Support_End_Date__c);
          OrdItems.put('userLicenseCount', OI.User_license_count__c);
          OrdItems.put('createdDate', OI.createddate);
          OrdItems.put('lastModifiedDate', OI.LastModifiedDate);
          prodCode.add(OI.product2.ProductCode);
          if (prodIdToBundleFeature.containskey(OI.product2Id)) {
            OrdItems.put('OIfeature', String.join(prodIdToBundleFeature.get(OI.product2Id), ';'));
          }

          for (string field : fieldSet) {
            List<string> fields = new List<string>(field.split('\\.'));
            Sobject obj = OI;
            try {
              for (integer i = 0; i < fields.size(); i++) {
                if (obj == null) {
                  OrdItems.put(field, 'Empty reference field');
                  break;
                } else if (i == fields.size() - 1) {
                  OrdItems.put(field, obj.get(fields[i]));
                } else {
                  obj = obj.getSobject(fields[i]);
                }
              }
            } catch (exception exp) {
              OrdItems.put(field, exp.getmessage());
            }
          }
          ordDetails.add(OrdItems);
        }

        for (Entitlement ett : ettList) {
          if (prodCodeEtt.contains(ett.Product__r.name))
            continue;
          prodCodeEtt.add(ett.Product__r.name);
          if (
            (compareLatestEnttAndOIMap.containskey(ett.Product__r.name) && ett.EndDate > compareLatestEnttAndOIMap.get(ett.Product__r.name).EndDate) ||
            !compareLatestEnttAndOIMap.containskey(ett.Product__r.name)
          ) {
            productCodeToContractlineMap.put(ett.Product__r.name, ett.ContractLineItem);
            compareLatestEnttAndOIMap.put(ett.Product__r.name, ett.Order_Service_Item__r);
            ManuallyReviewReqd = true;
          }
        }
        compareLatestEnttAndOIMap.remove(null);

        for (String str : compareLatestEnttAndOIMap.keyset()) {
          //Frame api Response => PDM Features , ContractDetails
          Map<string, object> OrdItems = new Map<string, object>();

          orderItem OI = compareLatestEnttAndOIMap.get(str);
          OrdItems.put('productName', OI.product2.ProductCode);
          OrdItems.put('supportEndDate', OI.Support_End_Date__c);
          OrdItems.put('userLicenseCount', OI.User_license_count__c);
          OrdItems.put('createdDate', OI.createddate);
          OrdItems.put('lastModifiedDate', OI.LastModifiedDate);
          if (productCodeToContractlineMap.containskey(OI.product2.ProductCode))
            OrdItems.put('contract', productCodeToContractlineMap.get(OI.product2.ProductCode));
          if (prodIdToBundleFeature.containskey(OI.product2Id)) {
            OrdItems.put('OIfeature', String.join(prodIdToBundleFeature.get(OI.product2Id), ';'));
          }
          OrdItems.put('product2.Bundle_Features__c', OI.product2.Bundle_Features__c);
          ordDetails.add(OrdItems);
          for (Entitlement ett : OI.entitlements__r) {
            if (ett.AccountId != OI.order.accountId) {
              ManuallyReviewReqd = true;
              break;
            }
          }
        }
      }

      if (!currentAccount.isEmpty()) {
        featureDeatils.put('accountExecutive', currentAccount[0].Owner.Email);
        featureDeatils.put('rubrikSalesEngineer', currentAccount[0].Rubrik_Sales_Engineer__r?.Email);
      }
      featureDeatils.put('accountId', accountId);
      featureDeatils.put('ManualReviewReqd', ManuallyReviewReqd);
      featureDeatils.put('featureType', featureType);
      featureDeatils.put('featureDetails', ordDetails);
      if (!OIList.isEmpty()) {
        featureDeatils.put('description', 'NA');
      } else {
        featureDeatils.put('description', 'No records found');
      }
      res.statusCode = 200;
      featureDeatils.put('status', 'successful');
    } catch (exception ex) {
      system.debug(logginglevel.DEBUG,ex.getMessage());
      system.debug(logginglevel.DEBUG,ex.getStackTraceString());
      res.statusCode = 500;
      featureDeatils.put('status', 'unsuccessful');
      featureDeatils.put('description', 'An unexpected exception occurred. Please try again later.');
      IntegrationLog.Http_Response__c = ex.getMessage();
    }
    if (!logCntrlr.isEmpty() && logCntrlr[0].Enable_Custom_Logs__c && res.statusCode != 200) {
      insert IntegrationLog;
    }
    res.responseBody = Blob.valueof(JSON.Serialize(featureDeatils));
  }
  /**
   * @author Prashant Kumar
   * @date 05-06-2025
   * @description populateFieldsOnInsert Method Called in Before Insert
   * @param pdmEnabledproductIds
   * @return Map<Id, List<String>>
   */
  public static Map<Id, List<String>> getPDMFeaturesBasedIfEnabled(set<Id> pdmEnabledproductIds) {
    Map<Id, List<String>> prodIdToBundleFeature = new Map<Id, List<String>>(); // to store bundle features corresponding to productId
    //List<Product_Feature__c> pdmFeature = [SELECT id, Feature__c, Product_Name__c FROM Product_Feature__c];
    for (Product_Feature__c pf : [
      SELECT id, Feature__c, Product_Name__c
      FROM Product_Feature__c
      WHERE Product_Name__c IN :pdmEnabledproductIds
    ]) {
      if (!prodIdToBundleFeature.containsKey(pf.Product_Name__c)) {
        prodIdToBundleFeature.put(pf.Product_Name__c, new List<String>());
      }

      prodIdToBundleFeature.get(pf.Product_Name__c).add(pf.Feature__c);
    }
    return prodIdToBundleFeature;
  }
}