force-app/main/default/objects/Risk_Profile__c/Risk_Profile__c.object-meta.xml
<CustomObject>
    <label>Risk Profile</label>
    <nameField>
        <displayFormat>RP-{00000}</displayFormat>
        <label>Risk Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risk Profiles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Risk_Profile__c/fields/ACV_At_Risk__c.field-meta.xml
<CustomField>
    <fullName>ACV_At_Risk__c</fullName>
    <label>ACV At Risk</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Risk_Profile__c/fields/Current_Status_Next_Steps__c.field-meta.xml
<CustomField>
    <fullName>Current_Status_Next_Steps__c</fullName>
    <label>Current Status &amp; Next Steps</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Risk_Profile__c/fields/Entitlement__c.field-meta.xml
<CustomField>
    <fullName>Entitlement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entitlement</label>
    <referenceTo>Entitlement</referenceTo>
    <relationshipLabel>Risk Profiles (Product Feature)</relationshipLabel>
    <relationshipName>Risk_Profiles1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Risk_Profile__c/fields/Entitlement_ACV__c.field-meta.xml
<CustomField>
    <fullName>Entitlement_ACV__c</fullName>
    <formula>Entitlement__r.AnnualContractValue__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entitlement ACV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Risk_Profile__c/fields/Entitlement_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Entitlement_Expiry_Date__c</fullName>
    <formula>Entitlement__r.EndDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entitlement Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Risk_Profile__c/fields/Governance_Owner__c.field-meta.xml
<CustomField>
    <fullName>Governance_Owner__c</fullName>
    <formula>IF(ISNULL(Owner:Queue.QueueName), Owner:User.FirstName + &quot; &quot; +Owner:User.LastName, Owner:Queue.QueueName)</formula>
    <label>Governance Owner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Risk_Profile__c/fields/Risk_Status__c.field-meta.xml
<CustomField>
    <fullName>Risk_Status__c</fullName>
    <label>Risk Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Mitigated</fullName>
            </value>
            <value>
                <fullName>Entitlement Expired</fullName>
            </value>
            <value>
                <fullName>Entitlement Churn</fullName>
            </value>
            <value>
                <fullName>Account Churn</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>At Risk</fullName>
            </value>
            <value>
                <fullName>Partially Mitigated</fullName>
            </value>
            <value>
                <fullName>Downsell</fullName>
            </value>
            <value>
                <fullName>CX health score improved</fullName>
            </value>
            <value>
                <fullName>No Risk</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Requires modification of CX Score Logic</fullName>
            </value>
            <value>
                <fullName>No mitigation possible</fullName>
            </value>
            <value>
                <fullName>Less time to mitigate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Risk_Profile__c/fields/Risk_Type__c.field-meta.xml
<CustomField>
    <fullName>Risk_Type__c</fullName>
    <label>Risk Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Risk</fullName>
            </value>
            <value>
                <fullName>Entitlement Risk</fullName>
            </value>
            <value>
                <fullName>Feature/Product Risk</fullName>
            </value>
            <value>
                <fullName>Discount and Extension</fullName>
            </value>
            <value>
                <fullName>Downsell</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Risk_Profile_Entitlement__c/Risk_Profile_Entitlement__c.object-meta.xml
<CustomObject>
    <label>Risk Profile Entitlement</label>
    <nameField>
        <label>Risk Profile Entitlement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Profile Entitlements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Risk_Profile_Entitlement__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Risk Profile Entitlements</relationshipLabel>
    <relationshipName>Risk_Profile_Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Risk_Profile_Entitlement__c/fields/Entitlement__c.field-meta.xml
<CustomField>
    <fullName>Entitlement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entitlement</label>
    <referenceTo>Entitlement</referenceTo>
    <relationshipLabel>Risk Profile Entitlements</relationshipLabel>
    <relationshipName>Risk_Profile_Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Risk_Profile_Entitlement__c/fields/Entitlement_ACV__c.field-meta.xml
<CustomField>
    <fullName>Entitlement_ACV__c</fullName>
    <formula>Entitlement__r.AnnualContractValue__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entitlement ACV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Risk_Profile_Entitlement__c/fields/Entitlement_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Entitlement_Expiry_Date__c</fullName>
    <formula>Entitlement__r.EndDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entitlement Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Risk_Profile_Entitlement__c/fields/Risk_Profile__c.field-meta.xml
<CustomField>
    <fullName>Risk_Profile__c</fullName>
    <label>Risk Profile</label>
    <referenceTo>Risk_Profile__c</referenceTo>
    <relationshipLabel>Risk Profile Entitlements</relationshipLabel>
    <relationshipName>Risk_Profile_Entitlements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Risk_Profile_PDM_Feature__c/Risk_Profile_PDM_Feature__c.object-meta.xml
<CustomObject>
    <label>Risk Profile PDM Feature</label>
    <nameField>
        <displayFormat>RP-PDM-{000000}</displayFormat>
        <label>Risk Profile PDM Feature Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risk Profile PDM Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Risk_Profile_PDM_Feature__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <formula>TEXT(PDM_Feature__r.Feature__c)</formula>
    <label>Feature</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Risk_Profile_PDM_Feature__c/fields/Risk_Profile__c.field-meta.xml
<CustomField>
    <fullName>Risk_Profile__c</fullName>
    <label>Risk Profile</label>
    <referenceTo>Risk_Profile__c</referenceTo>
    <relationshipLabel>Risk Profile PDM Features</relationshipLabel>
    <relationshipName>Risk_Profile_PDM_Features</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CS_CaseRetentionController.cls
/**
 * @author Sushant Arora
 * @date 2024-11-19
 * @description This controller fetches and processes Case data along with related Risk Profile PDM Features.
 * @TestClass - CaseRetentionControllerTest
 */

public class CS_CaseRetentionController {
    
    public String recordId { get; set; }
    
    /**
     * @description Default constructor to initialize the record ID from the current page parameters.
     */
    public CS_CaseRetentionController() {
        recordId = ApexPages.currentPage().getParameters().get('recordId');
    }
    
    /**
     * @description Fetches a Case record and its related Risk Profile PDM Features wrapped in a CasePDMWrapper object.
     * @param caseId The ID of the Case record to fetch.
     * @return CasePDMWrapper A wrapper containing the Case record and related Risk Profile PDM Features.
     */
    @AuraEnabled
    public static CasePDMWrapper getRetentionCaseRecord(Id caseId) {
        
        Case caseRecord = [ 
            SELECT Id, Owner.Name, CaseNumber, Account.Name, CreatedDate, Contact.Name, 
            Workaround_Provided__c, Status, Risk_Status__c,
            Risk_Profile__r.Risk_Status__c, Risk_Profile__r.Governance_Owner__c, Phase__c,
            Sub_Phase__c, Risk_Profile__r.Name, Risk_Profile__r.Risk_Type__c,
            Risk_Profile__r.Entitlement__c,Risk_Profile__r.Entitlement__r.Name, Risk_Profile__r.Entitlement_ACV__c,
            Risk_Profile__r.Entitlement_Expiry_Date__c,Risk_Profile__r.Owner.Name,OwnerId,
            ACV_At_Risk__c,ACV_mitigated__c, Risk_Opportunity__r.Name,
            Subject, Description,Resolution__c, Resolution_Details__c,Current_Status_Next_Steps__c,
            Mitigation_Case_Closed__c
            FROM Case 
            WHERE Id = :caseId 
            LIMIT 1 
        ];
        List<Risk_Profile_PDM_Feature__c> pdmFeatureRecord = new List<Risk_Profile_PDM_Feature__c>();
        List<Risk_Profile_Entitlement__c> riskProfileEntitlements = new List<Risk_Profile_Entitlement__c>();
        if(caseRecord?.Risk_Profile__c != null){
            pdmFeatureRecord = [ 
                SELECT Id, Name, Feature__c 
                FROM Risk_Profile_PDM_Feature__c
                WHERE Risk_Profile__c = :caseRecord.Risk_Profile__c
            ];
            riskProfileEntitlements = [
                SELECT Id,Entitlement__c, Entitlement__r.Name, Entitlement__r.AnnualContractValue__c , Entitlement__r.EndDate
                FROM Risk_Profile_Entitlement__c
                WHERE Case__c = :caseId
                AND Risk_Profile__c = :caseRecord.Risk_Profile__c
            ];
        }
        return new CasePDMWrapper(caseRecord, pdmFeatureRecord, riskProfileEntitlements);
    }
    /**
     * @description Wrapper class to hold a Case record and its related Risk Profile PDM Features.
     */
    public class CasePDMWrapper {
        /**
        * @description The Case record associated with this wrapper, exposed to LWC or Aura components.
        */
        @AuraEnabled public Case caseRecord { get; set; }
        /**
        * @description List of related Risk Profile PDM Feature records, exposed to LWC or Aura components.
        */
        @AuraEnabled public List<Risk_Profile_PDM_Feature__c> pdmFeatureRecord { get; set; }
        /**
        * @description List of related Risk Profile Entitlement records, exposed to LWC or Aura components.
        */
        @AuraEnabled public List<Risk_Profile_Entitlement__c> riskProfileEntitlements { get; set; }
        
        /**
         * @description Constructor to initialize the CasePDMWrapper with a Case record, 
         *              related PDM Features, and Risk Profile Entitlements.
         * @param caseRecord The Case record to wrap.
         * @param pdmFeatureRecord The list of related Risk Profile PDM Features.
         * @param riskProfileEntitlements The list of related Risk Profile Entitlement records.
         */
        public CasePDMWrapper(Case caseRecord, List<Risk_Profile_PDM_Feature__c> pdmFeatureRecord, List<Risk_Profile_Entitlement__c> riskProfileEntitlements) {
            this.caseRecord = caseRecord;
            this.pdmFeatureRecord = pdmFeatureRecord;
            this.riskProfileEntitlements = riskProfileEntitlements;
        }
    }
}