force-app/main/default/objects/MappingMatrix__mdt/MappingMatrix__mdt.object-meta.xml
<CustomObject>
    <description>generic mapping matrix to store values based on combinations.</description>
    <label>Mapping Matrix</label>
    <pluralLabel>Mapping Matrixs</pluralLabel>
</CustomObject>

force-app/main/default/objects/MappingMatrix__mdt/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <description>stores sobject name</description>
    <label>Object Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opportunity</fullName>
                <default>true</default>
                <label>Opportunity</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MappingMatrix__mdt/fields/OutputMapping__c.field-meta.xml
<CustomField>
    <fullName>OutputMapping__c</fullName>
    <description>stores output value of primary and secondary input combination.</description>
    <label>Output Mapping</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MappingMatrix__mdt/fields/PrimaryInput__c.field-meta.xml
<CustomField>
    <fullName>PrimaryInput__c</fullName>
    <description>stores data for primary mapping</description>
    <label>Primary Input</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MappingMatrix__mdt/fields/SecondaryInput__c.field-meta.xml
<CustomField>
    <fullName>SecondaryInput__c</fullName>
    <description>stores data for secondary input mapping.</description>
    <label>Secondary Input</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SalesOppChurnUtility.cls
/**
* @description handle opportunity churn related functionalities
*/
public with sharing class SalesOppChurnUtility {
    public static final String OPPORTUNITY = 'Opportunity';
    /**
* @description retrieves combination of Primary churn, secondary churn & HelpText.
* @return List<MappingMatrix__mdt>
*/
    public List<MappingMatrix__mdt> getChurnReasonInfo(){
        try{
            return getMappingMatrix(OPPORTUNITY); 
        }catch(Exception e) { ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));}   return null;     
        
    }
    
    /**
* @description retrieves mapping data for primary and secondary dependent fields
* @param objectName - API name of object.
* @return List<MappingMatrix__mdt> 
*/
    public static List<MappingMatrix__mdt> getMappingMatrix(String objectName){
        return [Select id,PrimaryInput__c,SecondaryInput__c,OutputMapping__c from MappingMatrix__mdt where ObjectName__c = :objectName WITH USER_MODE ];      
    }
    
}