force-app/main/default/objects/ETMStage_Monitoring__c/ETMStage_Monitoring__c.object-meta.xml
<CustomObject>
    <label>ETM Stage Monitoring</label>
    <nameField>
        <label>ETM Stage Monitoring Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ETM Stage Monitorings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ETMStage_Monitoring__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Init</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ShGl_DisableBusinessLogic__c/ShGl_DisableBusinessLogic__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Disable Business Logic in Salesforce - Includes Triggers, Workflows, Process Builders and Validation Rules</description>
    <label>DisableBusinessLogic</label>
</CustomObject>

force-app/main/default/objects/ShGl_DisableBusinessLogic__c/fields/Disable_ETMStageMonitoring_Triggers__c.field-meta.xml
<CustomField>
    <fullName>Disable_ETMStageMonitoring_Triggers__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disable_ETMStageMonitoring_Triggers</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ETMBatchJobsControllerTest.cls
@isTest
public class ETMBatchJobsControllerTest {
    /*public ETMStage_Monitoring__c ETMStageMonitor = new ETMStage_Monitoring__c();
    @testSetup 
    static void setup() {
        ETMStageMonitor = new ETMStage_Monitoring__c(Status__c='New',name='Test Stage');
        insert ETMStageMonitor;
    }*/

    static testmethod void runETMBatchTest1() {
        /*
        ShGl_DisableBusinessLogic__c disableBusinessLogicCS = ShGl_DisableBusinessLogic__c.getInstance();
        disableBusinessLogicCS.Disable_ETMStageMonitoring_Triggers__c = true;
        upsert disableBusinessLogicCS;
        */
        ETMStage_Monitoring__c ETMStageMonitor = new ETMStage_Monitoring__c(Status__c='New',name='Test Stage');
        insert ETMStageMonitor;
        ApexPages.StandardController sc = new ApexPages.StandardController(ETMStageMonitor);
        ETMBatchJobsController etmBJC = new ETMBatchJobsController(sc);

        PageReference pageRef = Page.ETMBatchJobsRun;
        pageRef.getParameters().put('id', String.valueOf(ETMStageMonitor.Id));
        Test.setCurrentPage(pageRef);
        Test.startTest();
        PageReference etmPR = etmBJC.runETMBatch();
        Test.stopTest();
    }

    static testmethod void runETMBatchTest2() {
        ETMStage_Monitoring__c ETMStageMonitor = new ETMStage_Monitoring__c(Status__c='Init',name='Test Stage');
        insert ETMStageMonitor;
        ApexPages.StandardController sc = new ApexPages.StandardController(ETMStageMonitor);
        ETMBatchJobsController etmBJC = new ETMBatchJobsController(sc);

        PageReference pageRef = Page.ETMBatchJobsRun;
        pageRef.getParameters().put('id', String.valueOf(ETMStageMonitor.Id));
        Test.setCurrentPage(pageRef);
        Test.startTest();
        PageReference etmPR1 = etmBJC.runETMBatch();
        PageReference etmPR2 = etmBJC.redirectToETMStageMonitorRecord();
        Test.stopTest();
    }

    static testmethod void runETMBatchTest3() {
        
        ShGl_DisableBusinessLogic__c disableBusinessLogicCS = ShGl_DisableBusinessLogic__c.getInstance();
        disableBusinessLogicCS.Disable_ETMStageMonitoring_Triggers__c = true;
        upsert disableBusinessLogicCS;
        
        ETMStage_Monitoring__c ETMStageMonitor = new ETMStage_Monitoring__c(Status__c='New',name='Test Stage');
        insert ETMStageMonitor;
        Test.startTest();
        ETMCreateTerritoryModelBatch etmBatch = new ETMCreateTerritoryModelBatch();
        etmBatch.etmStageMonitoringId = ETMStageMonitor.Id;
        Database.executeBatch(etmBatch,1);
        ApexPages.StandardController sc = new ApexPages.StandardController(ETMStageMonitor);
        ETMBatchJobsController etmBJC = new ETMBatchJobsController(sc);
        PageReference pageRef = Page.ETMBatchJobsRun;
        pageRef.getParameters().put('id', String.valueOf(ETMStageMonitor.Id));
        Test.setCurrentPage(pageRef);
        PageReference etmPR = etmBJC.runETMBatch();
        Test.stopTest();
    }
     static testmethod void runETMBatchTest4() {
        ETMStage_Monitoring__c ETMStageMonitor = new ETMStage_Monitoring__c(Status__c='New',name='Test Stage');
        insert ETMStageMonitor;
        Test.startTest(); 
        ETMBatchJobsLWCController.runETMBatch(ETMStageMonitor.Id);
        Test.stopTest();
    }

    static testmethod void runETMBatchTest5() {
        ETMStage_Monitoring__c ETMStageMonitor = new ETMStage_Monitoring__c(Status__c='Init',name='Test Stage');
        insert ETMStageMonitor;
        Test.startTest();
        ETMBatchJobsLWCController.runETMBatch(ETMStageMonitor.Id);
        Test.stopTest();
    }

    static testmethod void runETMBatchTest6() {
        
        ShGl_DisableBusinessLogic__c disableBusinessLogicCS = ShGl_DisableBusinessLogic__c.getInstance();
        disableBusinessLogicCS.Disable_ETMStageMonitoring_Triggers__c = true;
        upsert disableBusinessLogicCS;
        
        ETMStage_Monitoring__c ETMStageMonitor = new ETMStage_Monitoring__c(Status__c='New',name='Test Stage');
        insert ETMStageMonitor;
        Test.startTest();
        ETMCreateTerritoryModelBatch etmBatch = new ETMCreateTerritoryModelBatch();
        etmBatch.etmStageMonitoringId = ETMStageMonitor.Id;
        Database.executeBatch(etmBatch,1);
        ETMBatchJobsLWCController.runETMBatch(ETMStageMonitor.Id);
        Test.stopTest();
    }
}