force-app/main/default/objects/Country_With_State_RMARequest__mdt/Country_With_State_RMARequest__mdt.object-meta.xml
<CustomObject>
    <label>Country with State-RMA Request</label>
    <pluralLabel>Country with State-RMA Request</pluralLabel>
</CustomObject>

force-app/main/default/objects/Country_With_State_RMARequest__mdt/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Country_With_State_RMARequest__mdt/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Country_With_State_RMARequest__mdt/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TSP Inc.</fullName>
                <default>true</default>
                <label>TSP Inc.</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RMA_Order__c/RMA_Order__c.object-meta.xml
<CustomObject>
    <description>This Object is used to capture RMA requests</description>
    <label>RMA Request</label>
    <nameField>
        <displayFormat>RMA-{0000000}</displayFormat>
        <label>RMA Request #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMA Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMA_Order__c/fields/Additional_Interested_Parties_RMA__c.field-meta.xml
<CustomField>
    <fullName>Additional_Interested_Parties_RMA__c</fullName>
    <label>Additional Interested Parties</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RMA_Order__c/fields/Date_of_Smart_Hands_Arrival__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Smart_Hands_Arrival__c</fullName>
    <description>Use this date if the customer has any specific requirement on delivery time outside of the service level that’s listed below/above</description>
    <inlineHelpText>testttt</inlineHelpText>
    <label>Date of Smart Hands Arrival</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RMA_Order__c/fields/Entitled_for_Smart_Hands_Service__c.field-meta.xml
<CustomField>
    <fullName>Entitled_for_Smart_Hands_Service__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field capture if smart hands service is requested</description>
    <label>Entitled for Smart Hands Service</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RMA_Order__c/fields/Flash_Email_History__c.field-meta.xml
<CustomField>
    <fullName>Flash_Email_History__c</fullName>
    <label>Flash Email History</label>
    <length>131070</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RMA_Order__c/fields/Resend_Flash_Email__c.field-meta.xml
<CustomField>
    <fullName>Resend_Flash_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Resend Flash Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RMA_Order__c/fields/Send_Smart_Hands_Service__c.field-meta.xml
<CustomField>
    <fullName>Send_Smart_Hands_Service__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked If Smart Hand Service is requested by Customer</description>
    <inlineHelpText>Checked If Smart Hand Service is requested by Customer</inlineHelpText>
    <label>Send Smart Hands Service?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RMA_Order__c/fields/ShippingCountry__c.field-meta.xml
<CustomField>
    <fullName>ShippingCountry__c</fullName>
    <label>Shipping Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RMA_Order__c/fields/ShippingState__c.field-meta.xml
<CustomField>
    <fullName>ShippingState__c</fullName>
    <label>Shipping State/Province</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ShippingCountry__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>State_Province</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RMA_Order__c/fields/Smart_Hands_Change_Requested__c.field-meta.xml
<CustomField>
    <fullName>Smart_Hands_Change_Requested__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Smart Hands Change Requested</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RMA_Order__c/fields/Smart_Hands_Provider__c.field-meta.xml
<CustomField>
    <fullName>Smart_Hands_Provider__c</fullName>
    <label>Smart Hands Provider</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flash Global</fullName>
            </value>
            <value>
                <fullName>TSP Inc.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RMA_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field is to track status of RMA Request</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RMA_Order__c/fields/Time_of_Smart_Hands_Tech_Arrival__c.field-meta.xml
<CustomField>
    <fullName>Time_of_Smart_Hands_Tech_Arrival__c</fullName>
    <label>Time of Smart Hands Tech Arrival</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>08:00</fullName>
            </value>
            <value>
                <fullName>08:30</fullName>
            </value>
            <value>
                <fullName>09:00</fullName>
            </value>
            <value>
                <fullName>09:30</fullName>
            </value>
            <value>
                <fullName>10:00</fullName>
            </value>
            <value>
                <fullName>10:30</fullName>
            </value>
            <value>
                <fullName>11:00</fullName>
            </value>
            <value>
                <fullName>11:30</fullName>
            </value>
            <value>
                <fullName>12:00</fullName>
            </value>
            <value>
                <fullName>12:30</fullName>
            </value>
            <value>
                <fullName>13:00</fullName>
            </value>
            <value>
                <fullName>13:30</fullName>
            </value>
            <value>
                <fullName>14:00</fullName>
            </value>
            <value>
                <fullName>14:30</fullName>
            </value>
            <value>
                <fullName>15:00</fullName>
            </value>
            <value>
                <fullName>15:30</fullName>
            </value>
            <value>
                <fullName>16:00</fullName>
            </value>
            <value>
                <fullName>16:30</fullName>
            </value>
            <value>
                <fullName>17:00</fullName>
            </value>
            <value>
                <fullName>17:30</fullName>
            </value>
            <value>
                <fullName>18:00</fullName>
            </value>
            <value>
                <fullName>18:30</fullName>
            </value>
            <value>
                <fullName>19:00</fullName>
            </value>
            <value>
                <fullName>19:30</fullName>
            </value>
            <value>
                <fullName>20:00</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RMA_Order__c/fields/Valid_Support__c.field-meta.xml
<CustomField>
    <fullName>Valid_Support__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Valid Support</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/RMAOrderTriggerHelper.cls
public class RMAOrderTriggerHelper {
    public static final string DATETIME_CHANGE = 'DATETIME_CHANGE_REQUESTED'; 
    public static void checkRecordApprovedOnInsert(List<RMA_Order__c> newList){
        List<RMA_Order__c> RMAOrderList = new List<RMA_Order__c>();
        for(RMA_Order__c RMA : newList){
            if(RMA.Status__c=='Approved'){
                RMAOrderList.add(RMA);
            }
        }
        if(!RMAOrderList.isEmpty()) {
            RMAOrderService.createOrder(RMAOrderList);
        }
    }
    public static void checkEmailRegex(Map<Id,RMA_Order__c> oldMap,List<RMA_Order__c> newList){
        for(RMA_Order__c RMA : newList){
            if(RMA.Additional_Interested_Parties_RMA__c !=NULL){
                String emailRegex = '^[a-zA-Z][a-zA-Z0-9]*(?:[\\.|\\-|\\_][a-zA-Z0-9]+)*@[rR][uU][bB][rR][iI][kK].[cC][oO][mM](?:,[a-zA-Z][a-zA-Z0-9]*(?:[\\.|\\-|\\_][a-zA-Z0-9]+)*@[rR][uU][bB][rR][iI][kK].[cC][oO][mM])*$';
                Pattern EmailPattern = Pattern.compile(emailRegex);
                Matcher EmailMatcher = EmailPattern.matcher(RMA.Additional_Interested_Parties_RMA__c );
                if(!EmailMatcher.matches())
                {
                    RMA.addError('Please Enter comma seperated Rubrik email Address');
                    
                }
            }
            if(checkRecursive.runOnce() && RMA.Status__c=='Approved' && //&& RMA.Send_Smart_Hands_Service__c ==true && 
               ((RMA.Send_Smart_Hands_Service__c !=oldMap.get(RMA.Id).Send_Smart_Hands_Service__c) ||
                (RMA.Date_of_Smart_Hands_Arrival__c != null && oldMap.get(RMA.Id).Date_of_Smart_Hands_Arrival__c != RMA.Date_of_Smart_Hands_Arrival__c) ||
                (RMA.Time_of_Smart_Hands_Tech_Arrival__c != null && oldMap.get(RMA.Id).Time_of_Smart_Hands_Tech_Arrival__c != RMA.Time_of_Smart_Hands_Tech_Arrival__c))) {
                    RMA.Smart_Hands_Change_Requested__c =true;
                    RMA.Status__c ='Submitted';
            }
            //PRODOPS23-19
            if(oldMap.get(RMA.Id).Send_Smart_Hands_Service__c == true && 
               ((RMA.Date_of_Smart_Hands_Arrival__c != null && oldMap.get(RMA.Id).Date_of_Smart_Hands_Arrival__c !=null && oldMap.get(RMA.Id).Date_of_Smart_Hands_Arrival__c != RMA.Date_of_Smart_Hands_Arrival__c) ||
                (RMA.Time_of_Smart_Hands_Tech_Arrival__c != null && oldMap.get(RMA.Id).Time_of_Smart_Hands_Tech_Arrival__c != null &&oldMap.get(RMA.Id).Time_of_Smart_Hands_Tech_Arrival__c != RMA.Time_of_Smart_Hands_Tech_Arrival__c))){
                    RMA.Flash_Email_History__c = RMA.Flash_Email_History__c + '\n' + DATETIME_CHANGE;
                }
        }    
    }
    public static void checkRecordApprovedOnUpdate(Map<Id,RMA_Order__c> oldMap,List<RMA_Order__c> newList){
        List<RMA_Order__c> RMAOrderList = new List<RMA_Order__c>();
        Set<Id> RMAOrderListToResendFlashEmails = new Set<Id>();
        Set<Id> RMAIdsSmarthandremovedEmails = new Set<Id>();
        Set<Id> RMAIdsResendButton = new Set<Id>();
        Set<Id> RMAIdsUpsertTechOrder = new Set<Id>();
        for(RMA_Order__c RMA : newList){
            if(checkRecursive.runAfterOnce()){
                if((RMA.Status__c != oldMap.get(RMA.Id).Status__c) && RMA.Status__c=='Approved' && RMA.Smart_Hands_Change_Requested__c ==false){
                    RMAOrderList.add(RMA);
                }
                if (RMA.Status__c!= oldMap.get(RMA.Id).Status__c && RMA.Status__c=='Approved') {
                    if(RMA.Send_Smart_Hands_Service__c == true && RMA.Flash_Email_History__c != null && RMA.Flash_Email_History__c.contains(DATETIME_CHANGE)){
                        RMAOrderListToResendFlashEmails.add(RMA.Id);
                    }
                    else if(RMA.Send_Smart_Hands_Service__c == false && RMA.Smart_Hands_Change_Requested__c ==true )
                    {
                        RMAIdsSmarthandremovedEmails.add(RMA.Id);
                    }
                }
                else if (RMA.Valid_Support__c == True && RMA.Entitled_for_Smart_Hands_Service__c ==True && RMA.Status__c == 'Submitted') // Auto Approved
                {
                    if(RMA.Send_Smart_Hands_Service__c == true && RMA.Flash_Email_History__c != null && RMA.Flash_Email_History__c.contains(DATETIME_CHANGE)){
                        RMAOrderListToResendFlashEmails.add(RMA.Id);
                    }
                    else if(RMA.Send_Smart_Hands_Service__c == false && RMA.Smart_Hands_Change_Requested__c ==true)
                    {
                        RMAIdsSmarthandremovedEmails.add(RMA.Id);
                    }
                    
                }
                else if(RMA.Resend_Flash_Email__c == true){
                    RMAIdsResendButton.add(RMA.Id);
                }
                 /*
                @Author: Sukesh K
                @Description: for DGWD-17
                update techOrder
                */
                if ( RMA.Send_Smart_Hands_Service__c != oldMap.get(RMA.Id).get('Send_Smart_Hands_Service__c')) {
                    if (RMA.Send_Smart_Hands_Service__c) {
                        RMAIdsUpsertTechOrder.add(RMA.Id);
                    }
                }
            }
        }
        if(!RMAOrderList.isEmpty()) {
            RMAOrderService.createOrder(RMAOrderList);
        }
        if(!RMAOrderListToResendFlashEmails.isEmpty()) {
            RMAOrderService.updateRelatedOrders(RMAOrderListToResendFlashEmails);
        }
        if(!RMAIdsSmarthandremovedEmails.isEmpty()) {
            RMAOrderService.smartHandRemovedEmails(RMAIdsSmarthandremovedEmails);
        }
        if(!RMAIdsResendButton.isEmpty()) {
            RMAOrderService.mailOnResendButton(RMAIdsResendButton);
        }
        if (!RMAIdsUpsertTechOrder.isEmpty()) {
            RMAOrderService.upsertTechOrders(RMAIdsUpsertTechOrder);
        }
    }
	public static void populateSmartHandsProvider(List<RMA_Order__c> newList){
        Map<String, List<String>> countryStateMap = new Map<String, List<String>>();
        Map<String, Country_With_State_RMARequest__mdt> countryStateRMAMap = new Map<String, Country_With_State_RMARequest__mdt>();
        List<Country_With_State_RMARequest__mdt> countryRMARequestList = Country_With_State_RMARequest__mdt.getAll().values();
        for(Country_With_State_RMARequest__mdt countryStateMdt : countryRMARequestList){
            if(countryStateMdt.Country__c != null){
                countryStateRMAMap.put(countryStateMdt.Country__c, countryStateMdt);
                countryStateMap.put(countryStateMdt.Country__c, new List<String>{});
                if (countryStateMdt.State__c != null) {
                    String state = countryStateMdt.State__c;
                    List<String> stateList = state.split(',');
                    countryStateMap.get(countryStateMdt.Country__c).addall(stateList);
                }
            }
        }
        
        for(RMA_Order__c RMA : newList){
            if(countryStateMap.containsKey(RMA.ShippingCountry__c) && (countryStateMap.get(RMA.ShippingCountry__c).contains(RMA.ShippingState__c) || countryStateMap.get(RMA.ShippingCountry__c).isEmpty())){
            	RMA.Smart_Hands_Provider__c = countryStateRMAMap.get(RMA.ShippingCountry__c).Vendor__c;
            }
            else{
                RMA.Smart_Hands_Provider__c = 'Flash Global';
            }
        }
    }
}