force-app/main/default/objects/CountryWithCode__c/CountryWithCode__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Country With Code</label>
</CustomObject>

force-app/main/default/objects/CountryWithCode__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/Deal_Registration__c.object-meta.xml
<CustomObject>
    <description>SOX object - Object used for Deal Registrations by Partners</description>
    <label>Deal Registration</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Deal Registration #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Registration__c/fields/CDM__c.field-meta.xml
<CustomField>
    <fullName>CDM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CDM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Deal_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Deal_Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Deal_Registration_Status__c</fullName>
    <label>Deal Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Pending Conversion</fullName>
            </value>
            <value>
                <fullName>Pending Meeting</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity linked to Deal Reg</description>
    <label>Opportunity</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Please enter open opportunity name without an approved deal registration</errorMessage>
        <filterItems>
            <field>Opportunity.StageName</field>
            <operation>notEqual</operation>
            <value>7 Closed Won, 7 Closed Lost</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Registrations</relationshipLabel>
    <relationshipName>Deal_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/PatchManager__c.field-meta.xml
<CustomField>
    <fullName>PatchManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PatchManager</label>
    <referenceTo>PatchManager__c</referenceTo>
    <relationshipLabel>Deal Registrations</relationshipLabel>
    <relationshipName>Deal_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/SDR__c.field-meta.xml
<CustomField>
    <fullName>SDR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SDR for the Deal. Populated from Patch Manager</description>
    <label>SDR</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Deal_Registrations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PatchManager__c/PatchManager__c.object-meta.xml
<CustomObject>
    <label>PatchManager</label>
    <nameField>
        <displayFormat>PM-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PatchManagers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PatchManager__c/fields/AccountExecutive__c.field-meta.xml
<CustomField>
    <fullName>AccountExecutive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Executive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>FieldRep</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PatchManager__c/fields/CDM__c.field-meta.xml
<CustomField>
    <fullName>CDM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CDM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PatchManagers1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PatchManager__c/fields/CountryGlobal__c.field-meta.xml
<CustomField>
    <fullName>CountryGlobal__c</fullName>
    <label>CountryGlobal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PatchManager__c/fields/SDR__c.field-meta.xml
<CustomField>
    <fullName>SDR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SDR</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PatchManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PatchManager__c/fields/StateGlobal__c.field-meta.xml
<CustomField>
    <fullName>StateGlobal__c</fullName>
    <label>StateGlobal</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CountryGlobal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>State_Province</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PatchManager__c/fields/Zip_code__c.field-meta.xml
<CustomField>
    <fullName>Zip_code__c</fullName>
    <label>Zip code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PatchManager__c/recordTypes/Geographic.recordType-meta.xml
<RecordType>
    <fullName>Geographic</fullName>
    <active>true</active>
    <label>Geographic</label>
</RecordType>

force-app/main/default/objects/WorkflowTriggerBypass__c/WorkflowTriggerBypass__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>WorkflowTriggerBypass</label>
</CustomObject>

force-app/main/default/objects/WorkflowTriggerBypass__c/fields/ByPassTrigger__c.field-meta.xml
<CustomField>
    <fullName>ByPassTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPassTrigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PC_DealRegExtnReqControllerTest.cls
@isTest
public class PC_DealRegExtnReqControllerTest {
    @TestSetup
    static void makeData(){
    
        List<WorkflowTriggerBypass__c> wtList = new List<WorkflowTriggerBypass__c>();
        WorkflowTriggerBypass__c wt = new WorkflowTriggerBypass__c(name='leadReassignOnBusinessUnitChange',ByPassTrigger__c=false);
        wtList.add(wt);
        WorkflowTriggerBypass__c wt1 = new WorkflowTriggerBypass__c(name='cnsFirstAttemptUpdateLeadStatus',ByPassTrigger__c=false);
        wtList.add(wt1);
        WorkflowTriggerBypass__c wt2 = new WorkflowTriggerBypass__c(name='CreateSDRLedMeetingTask',ByPassTrigger__c=false);
        wtList.add(wt2);
        WorkflowTriggerBypass__c wt3 = new WorkflowTriggerBypass__c(name='updateLastOwnershipUpdateDate',ByPassTrigger__c=false);
        wtList.add(wt3);
        WorkflowTriggerBypass__c wt4 = new WorkflowTriggerBypass__c(name='updateOpportunitySource',ByPassTrigger__c=false);
        wtList.add(wt4);
        WorkflowTriggerBypass__c wt5 = new WorkflowTriggerBypass__c(name='salesOperationsAssignAccountSIC',ByPassTrigger__c=false);
        wtList.add(wt5);
        WorkflowTriggerBypass__c wt6 = new WorkflowTriggerBypass__c(name='salesOperationsSetEUResident',ByPassTrigger__c=false);
        wtList.add(wt6);
        insert wtList;
        
        Map<String, String> mapOfMapping = new Map<String, String>();
        Account acc=TestDataFactory.getAccount();
        insert acc;
        
        Contact con = TestDataFactory.getContact(acc);
        insert con;
        
        Opportunity opp = TestDataFactory.getOpportunity(acc,con);
        insert opp;
        
    }
    static testMethod void testMethod1(){
        
        User sysuser2  = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
            LastName = 'lastNameDRTest',
            Email = 'uniqueName1233' +'@rubrik.com',
            Username = 'uniqueName1233' +'@rubrik.com',
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'uniqueName'.substring(0,5),
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            Start_Date__c=System.Today().adddays(-30)
        );
        
        
        Opportunity opp = [Select Id from Opportunity LIMIT 1];
        
        Test.setMock(HttpCalloutMock.class, new PC_DealRegL2AMatchTest('SUCCESS'));
        System.runAs(sysuser2){
            Id georecId = Schema.SObjectType.PatchManager__c.getRecordTypeInfosByName().get('Geographic').getRecordTypeId();
            PatchManager__c pm = new PatchManager__c(recordtypeId=georecId,CDM__c=UserInfo.getUserId(),CountryGlobal__c='United States',City__c='City',State__c='AK',StateGlobal__c='AK',Zip_code__c='421302',SDR__c=UserInfo.getUserId(),AccountExecutive__c=UserInfo.getUserId());
            insert pm;
            
            CountryWithCode__c cc = new CountryWithCode__c(Code__c='US',Name='United States');
            insert cc;
            system.debug(cc);
            
            Deal_Registration__c deal=TestDataFactory.getDealRegistration();
            Id ResellerRecordTypeId = Schema.SObjectType.Deal_Registration__c.getRecordTypeInfosByName().get('Reseller').getRecordTypeId();
            deal.Deal_Registration_Status__c = 'Approved';
            deal.Opportunity__c = opp.Id;
            deal.RecordTypeId = ResellerRecordTypeId;
            system.debug('>>>>'+CountryWithCode__c.getAll());
            insert deal;
            
            Test.startTest();    
            PC_DealRegExtnReqController.getStatus(string.valueOf(deal.Id));    
            PC_DealRegExtnReqController.setExtension(string.valueOf(deal.Id));
            
            //already extension req processed
            PC_DealRegExtnReqController.setExtension(string.valueOf(deal.Id));
            Test.stopTest();    
        }
    }
    
    static testMethod void testMethod2(){
        
        User sysuser2  = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
            LastName = 'lastNameDRTest',
            Email = 'uniqueName1233' +'@rubrik.com',
            Username = 'uniqueName1233' +'@rubrik.com',
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'uniqueName'.substring(0,5),
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            Start_Date__c=System.Today().adddays(-30)
        );
        
                
        Test.setMock(HttpCalloutMock.class, new PC_DealRegL2AMatchTest('SUCCESS'));
        System.runAs(sysuser2){
            Id georecId = Schema.SObjectType.PatchManager__c.getRecordTypeInfosByName().get('Geographic').getRecordTypeId();
            PatchManager__c pm = new PatchManager__c(recordtypeId=georecId,CDM__c=UserInfo.getUserId(),CountryGlobal__c='United States',City__c='City',State__c='AK',StateGlobal__c='AK',Zip_code__c='421302',SDR__c=UserInfo.getUserId(),AccountExecutive__c=UserInfo.getUserId());
            insert pm;
            
            CountryWithCode__c cc = new CountryWithCode__c(Code__c='US',Name='United States');
            insert cc;
            system.debug(cc);
            
            Deal_Registration__c deal=TestDataFactory.getDealRegistration();
            Id ResellerRecordTypeId = Schema.SObjectType.Deal_Registration__c.getRecordTypeInfosByName().get('Reseller').getRecordTypeId();
            deal.Deal_Registration_Status__c = 'Approved';
            deal.RecordTypeId = ResellerRecordTypeId;
            insert deal;
            deal.Deal_Registration_Status__c = 'Expired';
            update deal;
            Test.startTest();    
            	PC_DealRegExtnReqController.setExtension(string.valueOf(deal.Id));            
            Test.stopTest();    
        }
    }
}