force-app/main/default/objects/CountryWithCode__c/CountryWithCode__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Country With Code</label>
</CustomObject>

force-app/main/default/objects/CountryWithCode__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/Partner_Registration_Request__c.object-meta.xml
<CustomObject>
    <description>This object is used to store Partner Portal Access Request from Partners</description>
    <label>Partner Portal Access Request</label>
    <nameField>
        <displayFormat>PR Request-{00000000}</displayFormat>
        <label>Partner Registration Request #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Portal Access Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Registration_Request__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>This is to enter Address</description>
    <label>Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/Auto_Approval__c.field-meta.xml
<CustomField>
    <fullName>Auto_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This boolean is checked once PR Request needs to be auto approved</description>
    <label>Auto Approval?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>This field is to capture City of the Address</description>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <description>This field is to capture Company name from the request</description>
    <label>Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>This field is to store the country of the address</description>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/Country_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Country_Picklist__c</fullName>
    <description>This is the country picklist version.</description>
    <inlineHelpText>This is the country picklist version.</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>This field is to capture email from request</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>This field is to capture First Name</description>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <description>This field is to store Job Title from the request</description>
    <label>Job Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>This field is to capture Last Name</description>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/Partner_Account_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>https://rubrik.atlassian.net/browse/PRIT24-714</description>
    <label>Partner Account Lookup</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.OwnerId</field>
            <operation>notEqual</operation>
            <value>0056f00000AzgeLAAR</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Partner/Distributor</value>
        </filterItems>
        <filterItems>
            <field>Account.OwnerId</field>
            <operation>notEqual</operation>
            <value>0058Y00000B5xtOQAR</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Portal Access Requests</relationshipLabel>
    <relationshipName>Partner_Portal_Access_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/Partner_Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Partner_Registration_Status__c</fullName>
    <label>Partner Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Login Issued</fullName>
            </value>
            <value>
                <fullName>Personal Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <description>This field to capture phone number</description>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <description>Postal code for the adddress</description>
    <label>Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/Related_Partner_Contact__c.field-meta.xml
<CustomField>
    <fullName>Related_Partner_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>https://rubrik.atlassian.net/browse/PRIT24-687</description>
    <label>Related Partner Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Partner Portal Access Requests</relationshipLabel>
    <relationshipName>Partner_Portal_Access_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>This field is to store State of the address</description>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StateCodeName__c/StateCodeName__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>StateCodeName</label>
</CustomObject>

force-app/main/default/objects/StateCodeName__c/fields/State_Name__c.field-meta.xml
<CustomField>
    <fullName>State_Name__c</fullName>
    <label>State_Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PC_PartnerRegistrationRequestTriggerTest.cls
@isTest
public class PC_PartnerRegistrationRequestTriggerTest {
	@testSetup static void setupmethod() {
        Profile p = [SELECT Id FROM Profile WHERE Name ='System Administrator'];
		Userrole usrRole = [SELECT Id FROM UserRole WHERE DeveloperName='Channel_Development_Manager'];
        String userName = 'PRUsr';
		User u = new User(Alias = 'std'+userName, Email=userName+'testuserdetails@testorg.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing'+userName, LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='testuserdetail@gmail.com'+userName, UserRoleId = usrRole.Id);
        System.runAs(u){
            Account accRec = ShGl_TestFactory.testMethod_PartnerAccount('Test Account');
            accRec.Name = 'TestCompany';
            update accRec;
                        
            List<Contact> contList = ShGl_TestFactory.testMethod_PartnerContact(2,accRec);
            contList[0].Email = 'abc2@gmailtest.sandbox.com';
            contList[1].Email = 'abc3@gmailtest.sandbox.com';
            update contList;
            
            CountryWithCode__c CountrySetting1 = new CountryWithCode__c();
            CountrySetting1.Name = 'United States';
            CountrySetting1.Code__c = 'US';
            insert CountrySetting1;
    
            StateCodeName__C stateSetting1 = new StateCodeName__C();
            stateSetting1.Name = 'US-AL';
            stateSetting1.State_Name__c = 'Alabama';
            insert stateSetting1;
            
            User portalUser = ShGl_TestFactoryHelper.createPortalUser(1,contList[1]); 
            portalUser.isActive = false;
            insert portalUser;
        }
	}
	
	@isTest
    public static void testPRWithoutContact(){
        Profile p = [SELECT Id FROM Profile WHERE Name ='System Administrator'];
        String userName = 'admin';
		User u = new User(Alias = 'std'+userName, Email=userName+'testuserdetails@testorg.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing'+userName, LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='admintestuser@gmail.com'+userName);
		System.runAs(u){
            Partner_Registration_Request__c prReq = createPR();
            prReq.First_Name__c = 'Test1';
            prReq.Partner_Registration_Status__c = 'Approved';
            prReq.Auto_Approval__c = true;
            insert prReq;
            
            List<Contact> clist = [SELECT Id FROM Contact WHERE FirstName = : prReq.First_Name__c];
			System.assertEquals(1,clist.size(),'Contact created Successfully');
    	}
    }
    
	@isTest
    public static void testPRWithoutUser(){
		Profile p = [SELECT Id FROM Profile WHERE Name ='System Administrator'];
        String userName = 'admin';
		User u = new User(Alias = 'std'+userName, Email=userName+'testuserdetails@testorg.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing'+userName, LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='admintestuser@gmail.com'+userName);
		System.runAs(u){
			Id contId = [SELECT Id FROM Contact WHERE Email ='abc2@gmailtest.sandbox.com' LIMIT 1].Id;
       
			Partner_Registration_Request__c prReq = createPR();
			prReq.First_Name__c = 'Test2';
			prReq.Partner_Registration_Status__c = 'Approved';
			prReq.Auto_Approval__c = true;
			prReq.Related_Partner_Contact__c = contId;
            insert prReq;
            
            List<Contact> cList = [SELECT Id FROM Contact WHERE Email = 'abc2@gmailtest.sandbox.com'];
			System.assertNotEquals(2,cList.size(),'No extra contacts created');
        }
    }
	
	@isTest
    public static void testPRWithInactiveUser(){
		Profile p = [SELECT Id FROM Profile WHERE Name ='System Administrator'];
        String userName = 'admin';
		User u = new User(Alias = 'std'+userName, Email=userName+'testuserdetails@testorg.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing'+userName, LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='admintestuser@gmail.com'+userName);
		System.runAs(u){
			Id contId = [SELECT Id FROM Contact WHERE Email = 'abc3@gmailtest.sandbox.com' LIMIT 1].Id;
            
			Partner_Registration_Request__c prReq = createPR();
			prReq.First_Name__c = 'Test3';
			prReq.Partner_Registration_Status__c = 'Approved';
			prReq.Auto_Approval__c = true;
			prReq.Related_Partner_Contact__c = contId;
            insert prReq;
            
            List<User> ulist = [SELECT Id FROM User WHERE Email = 'abc3@gmailtest.sandbox.com'];
			System.assertEquals(1,ulist.size(),'User activated Successfully');
        }
    }
    
    @isTest
    public static void testPRWithActiveUser(){
		Profile p = [SELECT Id FROM Profile WHERE Name ='System Administrator'];
        String userName = 'admin';
		User u = new User(Alias = 'std'+userName, Email=userName+'testuserdetails@testorg.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing'+userName, LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='admintestuser@gmail.com'+userName);
		System.runAs(u){
			Id contId = [SELECT Id FROM Contact WHERE Email = 'abc3@gmailtest.sandbox.com' LIMIT 1].Id;
            Id accId = [Select Id from Account Where Name = 'TestCompany' LIMIT 1].Id;
			List<User> ulist = [SELECT Id FROM User WHERE Email = 'abc3@gmailtest.sandbox.com'];
            
			Partner_Registration_Request__c prReq = createPR();
			prReq.First_Name__c = 'Test3';
            prReq.Email__c = 'abc3@gmailtest.sandbox.com';
			prReq.Partner_Registration_Status__c = 'Submitted';
            insert prReq;
            
            prReq.Partner_Registration_Status__c = 'Approved';
			prReq.Partner_Account_Lookup__c = accId;
            update prReq;
            
			System.assertEquals(1,ulist.size(),'User activated Successfully');
        }
    }
    
    @isTest
    public static void testPRWithManualApproval(){
		Profile p = [SELECT Id FROM Profile WHERE Name ='System Administrator'];
        String userName = 'admin';
		User u = new User(Alias = 'std'+userName, Email=userName+'testuserdetails@testorg.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing'+userName, LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='admintestuser@gmail.com'+userName);
		System.runAs(u){ 
			Partner_Registration_Request__c prReq = createPR();
			prReq.First_Name__c = 'Test4';
			prReq.Partner_Registration_Status__c = 'Submitted';
            insert prReq;
            
			prReq.Partner_Registration_Status__c = 'Approved';
			update prReq;
            
            List<Partner_Registration_Request__c> plist = [SELECT Id, Partner_Registration_Status__c FROM Partner_Registration_Request__c];
			System.assertEquals('Approved',plist[0].Partner_Registration_Status__c,'PR is approved');
		}
    }
    
    @isTest
    public static void testPRWithError(){
		Profile p = [SELECT Id FROM Profile WHERE Name ='System Administrator'];
        String userName = 'admin';
		User u = new User(Alias = 'std'+userName, Email=userName+'testuserdetails@testorg.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing'+userName, LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='admintestuser@gmail.com'+userName);
		System.runAs(u){
			Id devRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer/Prospect').getRecordTypeId();
			
			Account AccRecord = new Account();
			AccRecord.Name = 'test customer';
			AccRecord.BillingStreet = 'street';
			AccRecord.BillingCity = 'city';
			AccRecord.BillingCountry = 'India';
			AccRecord.BillingPostalCode = '55555';
			AccRecord.RecordTypeId= devRecordTypeId;
			AccRecord.Type = 'Reseller';
			insert AccRecord;
			
			Partner_Registration_Request__c prReq = createPR();
			prReq.First_Name__c = 'Test5';
			prReq.Partner_Registration_Status__c = 'Submitted';
            insert prReq;
			prReq.Partner_Account_Lookup__c = null;
			prReq.Partner_Registration_Status__c = 'Approved';
			try{
				update prReq;
			}catch(Exception e){
				system.debug(LoggingLevel.ERROR, e);
			}
			
			prReq.Partner_Account_Lookup__c = AccRecord.Id;
			prReq.Partner_Registration_Status__c = 'Approved';
			try{
				update prReq;
			}catch(Exception e){
				system.debug(LoggingLevel.ERROR, e);
			}
            
            List<Partner_Registration_Request__c> plist = [SELECT Id, Partner_Registration_Status__c FROM Partner_Registration_Request__c];
			System.assertEquals('Submitted',plist[0].Partner_Registration_Status__c,'PR is still in submitted status');
		}
    }
    
    private static Partner_Registration_Request__c createPR(){
        Id accId = [SELECT Id FROM Account LIMIT 1].Id;
        
        Partner_Registration_Request__c prReq = new Partner_Registration_Request__c();
        prReq.Last_Name__c = 'Test Lastname';
        prReq.Email__c = 'abc4@gmailtest.sandbox.com';
        prReq.Company_Name__c = 'TestCompany';
        prReq.Partner_Account_Lookup__c = accId;
        prReq.Country_Picklist__c = 'United States';
        prReq.Country__c = 'United States';
        prReq.State__c = 'AL';
        prReq.Job_Title__c = 'Test';
        prReq.Phone_Number__c = '21454487';
        prReq.Address__c = 'Alabama';
        prReq.City__c = 'Alabama';
        prReq.Postal_Code__c = '318645';
        return prReq;
    }
}