force-app/main/default/objects/CountryWithCode__c/CountryWithCode__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Country With Code</label>
</CustomObject>

force-app/main/default/objects/CountryWithCode__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/Partner_Registration_Request__c.object-meta.xml
<CustomObject>
    <description>This object is used to store Partner Portal Access Request from Partners</description>
    <label>Partner Portal Access Request</label>
    <nameField>
        <displayFormat>PR Request-{00000000}</displayFormat>
        <label>Partner Registration Request #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Portal Access Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Registration_Request__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>This is to enter Address</description>
    <label>Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/Admin_Access__c.field-meta.xml
<CustomField>
    <fullName>Admin_Access__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enabled to true when admin access is suppposed to be provided to the user</description>
    <label>Admin Access</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>This field is to capture City of the Address</description>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>This field is to store the country of the address</description>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>This field is to capture email from request</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>This field is to capture First Name</description>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <description>This field is to store Job Title from the request</description>
    <label>Job Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>This field is to capture Last Name</description>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/Partner_Account_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>https://rubrik.atlassian.net/browse/PRIT24-714</description>
    <label>Partner Account Lookup</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.OwnerId</field>
            <operation>notEqual</operation>
            <value>0056f00000AzgeLAAR</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Partner/Distributor</value>
        </filterItems>
        <filterItems>
            <field>Account.OwnerId</field>
            <operation>notEqual</operation>
            <value>0058Y00000B5xtOQAR</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Portal Access Requests</relationshipLabel>
    <relationshipName>Partner_Portal_Access_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <description>This field to capture phone number</description>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <description>Postal code for the adddress</description>
    <label>Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/Related_Partner_Contact__c.field-meta.xml
<CustomField>
    <fullName>Related_Partner_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>https://rubrik.atlassian.net/browse/PRIT24-687</description>
    <label>Related Partner Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Partner Portal Access Requests</relationshipLabel>
    <relationshipName>Partner_Portal_Access_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>This field is to store State of the address</description>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StateCodeName__c/StateCodeName__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>StateCodeName</label>
</CustomObject>

force-app/main/default/objects/StateCodeName__c/fields/State_Name__c.field-meta.xml
<CustomField>
    <fullName>State_Name__c</fullName>
    <label>State_Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PC_PartnerRegistrationRequestService.cls
/**
* @description : Service class to create/update portal user, create/update portal contact from Partner_Registration_Request__c record
*/
public inherited sharing class PC_PartnerRegistrationRequestService{

	/**
    * @description : Dertermine PR request to:
    * 				Create contact and Create user if no matching email contact found
    * 				Update contact and Create user if matchng contact found with no associated user
    * 				Update user to activate/change profile if both contact and associated user found
    * @return : void
    */
	public void processPR(List<Partner_Registration_Request__c> PartRegList){
		Set<Id> updateUserProfileIds = new Set<Id>();
		Set<Id> activateUserIds = new Set<Id>();
		Set<Id> existingContactIdWithoutUser = new Set<Id>();
		Set<Id> existingUserContactIds = new Set<Id>();
		List<Partner_Registration_Request__c> createContactPRList = new List<Partner_Registration_Request__c>();
		List<User> existingPartnerUsers = new List<User>();
		Map<String,Boolean> emailAdminAccessMap = new Map<String,Boolean>();
		Map<String,Partner_Registration_Request__c> emailPRMap = new Map<String,Partner_Registration_Request__c>();

		//below for loop can be moved to trigger helper
		for(Partner_Registration_Request__c pr : PartRegList){
			emailPRMap.put(pr.Email__c,pr);
			
			if(pr.Related_Partner_Contact__c != null){
				existingUserContactIds.add(pr.Related_Partner_Contact__c);
			}
			
		}
		
        if(!existingUserContactIds.isEmpty()){
            existingPartnerUsers = getUserDetails(existingUserContactIds);
            
            for(User existingUser : existingPartnerUsers){
                if(emailPRMap.containsKey(existingUser.Email) && emailPRMap.get(existingUser.Email).Admin_Access__c && existingUser.Profile.Name != 'Rubrik Partner Community Manager'){
                    updateUserProfileIds.add(existingUser.Id);
                }

                if(!existingUser.isActive && !updateUserProfileIds.contains(existingUser.Id)){
                    activateUserIds.add(existingUser.Id);
                }

                if(emailPRMap.containsKey(existingUser.Email)){
                    emailPRMap.remove(existingUser.Email);
                }
            }
        }

        for(Partner_Registration_Request__c pr : emailPRMap.values()){
			if(pr.Related_Partner_Contact__c != null){
				emailAdminAccessMap.put(pr.Email__c,pr.Admin_Access__c);
				existingContactIdWithoutUser.add(pr.Related_Partner_Contact__c);
			}else{
				createContactPRList.add(pr);
			}
		}

        //Activate existing Users OR Update existing Partner Users to Manager
        if(!activateUserIds.isEmpty() || !updateUserProfileIds.isEmpty()){
            Id jobId = System.enqueueJob(new PC_PartnerRegistrationRequestQueueable(activateUserIds,updateUserProfileIds));
		}

		//Update existing Contacts by marking Create_Portal_User__c as True to create new Users
		if(!emailAdminAccessMap.isEmpty()){
			modifyContacts(emailAdminAccessMap,existingContactIdWithoutUser);
		}

		//Create new Contacts by marking Create_Portal_User__c as True to create new Users
		if(!createContactPRList.isEmpty()){
			createContacts(createContactPRList);
		}
	}

    /**
    * @description : Get associated User details of Contacts
    * @return : List of users
    */
	public List<User> getUserDetails(Set<Id> contactIds){
		return [SELECT Id, isActive, Profile.Name, ContactId,UserType, Email FROM User WHERE ContactId IN : contactIds AND UserType ='PowerPartner'];
	}
	
    /**
    * @description : Mark the contact's primary role if Admin and mark Create_Portal_User__c as true to further 
    * 				create a user from contact Trigger
    * @return : void
    */
	public void modifyContacts(Map<String, Boolean> emailAdminAccessMap,Set<Id> existingContactIdWithoutUser){
		List<Contact> contactList = new List<Contact>();
		for(Contact conObj :  [SELECT Id,Email,Primary_Role__c,Create_Portal_User__c FROM Contact WHERE ID IN :existingContactIdWithoutUser]){
			if(emailAdminAccessMap.containsKey(conObj.Email)){
				if(emailAdminAccessMap.get(conObj.Email)){
					conObj.Primary_Role__c = 'Admin';
				}
				conObj.Create_Portal_User__c = true;
			}
			contactList.add(conObj);
		}
		update contactList;
	}

    /**
    * @description : Create contacts for the PR request
    * @return : void
    */
	public void createContacts(List<Partner_Registration_Request__c> PRList){
		List<Contact> contactList = new List<Contact>();
		Map<String, CountryWithCode__c> mapStatusCounrtyCodeCustomSetting = CountryWithCode__c.getAll();
		for(Partner_Registration_Request__c pr : PRList){
			Contact newContact = new Contact(
				LastName = pr.Last_Name__c,
				FirstName = pr.First_Name__c,
				AccountId = pr.Partner_Account_Lookup__c,
				Email = pr.Email__c,
				Title = pr.Job_Title__c,
				Phone = pr.Phone_Number__c,
				MailingStreet = pr.Address__c,
				MailingCity = pr.City__c,
				MailingCountry = pr.Country__c,
				MailingPostalCode = pr.Postal_Code__c,
				Communication_Opt_in__c = pr.Communication_Opt_in__c,
				create_Portal_User__c=true,
				LeadSource = 'Channel Marketing'
			);
			if(mapStatusCounrtyCodeCustomSetting.containsKey(pr.Country__c) && pr.State__c != null){
				String uniqueCode = mapStatusCounrtyCodeCustomSetting.get(pr.Country__c).code__c+'-'+pr.State__c;
				newContact.MailingState = StateCodeName__c.getInstance(uniqueCode).State_Name__c;
			}
			else{
				newContact.MailingState = null;
			}
			contactList.add(newContact);
		}
		insert contactList;
	}
}