force-app/main/default/objects/CountryWithCode__c/CountryWithCode__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Country With Code</label>
</CustomObject>

force-app/main/default/objects/CountryWithCode__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Page_Configuration__c/Partner_Page_Configuration__c.object-meta.xml
<CustomObject>
    <label>Partner Page Configuration</label>
    <nameField>
        <label>Community Page Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Page Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Page_Configuration__c/fields/Primary_role__c.field-meta.xml
<CustomField>
    <fullName>Primary_role__c</fullName>
    <label>Primary Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Contract Signatory</fullName>
            </value>
            <value>
                <fullName>Executive</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/Partner_Registration_Request__c.object-meta.xml
<CustomObject>
    <description>This object is used to store Partner Portal Access Request from Partners</description>
    <label>Partner Portal Access Request</label>
    <nameField>
        <displayFormat>PR Request-{00000000}</displayFormat>
        <label>Partner Registration Request #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Portal Access Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Registration_Request__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>This is to enter Address</description>
    <label>Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/Admin_Access__c.field-meta.xml
<CustomField>
    <fullName>Admin_Access__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enabled to true when admin access is suppposed to be provided to the user</description>
    <label>Admin Access</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>This field is to capture City of the Address</description>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <description>This field is to capture Company name from the request</description>
    <label>Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>This field is to store the country of the address</description>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/Country_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Country_Picklist__c</fullName>
    <description>This is the country picklist version.</description>
    <inlineHelpText>This is the country picklist version.</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>This field is to capture email from request</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>This field is to capture First Name</description>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/Is_Converted__c.field-meta.xml
<CustomField>
    <fullName>Is_Converted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This flag is to check whether PR_request is already converted to Contact or not</description>
    <label>Is_Converted?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>This field is to capture Last Name</description>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/Partner_Account_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>https://rubrik.atlassian.net/browse/PRIT24-714</description>
    <label>Partner Account Lookup</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.OwnerId</field>
            <operation>notEqual</operation>
            <value>0056f00000AzgeLAAR</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Partner/Distributor</value>
        </filterItems>
        <filterItems>
            <field>Account.OwnerId</field>
            <operation>notEqual</operation>
            <value>0058Y00000B5xtOQAR</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Portal Access Requests</relationshipLabel>
    <relationshipName>Partner_Portal_Access_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/Partner_Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Partner_Registration_Status__c</fullName>
    <label>Partner Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Login Issued</fullName>
            </value>
            <value>
                <fullName>Personal Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <description>This field to capture phone number</description>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <description>Postal code for the adddress</description>
    <label>Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>This field is to store State of the address</description>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Registration_Request__c/fields/State_Picklist__c.field-meta.xml
<CustomField>
    <fullName>State_Picklist__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country_Picklist__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>State_Province</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ShGl_DisableBusinessLogic__c/ShGl_DisableBusinessLogic__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Disable Business Logic in Salesforce - Includes Triggers, Workflows, Process Builders and Validation Rules</description>
    <label>DisableBusinessLogic</label>
</CustomObject>

force-app/main/default/objects/ShGl_DisableBusinessLogic__c/fields/Disable_PartnerRegRequest_Triggers__c.field-meta.xml
<CustomField>
    <fullName>Disable_PartnerRegRequest_Triggers__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable PartnerRegRequest Triggers</description>
    <inlineHelpText>Disable PartnerRegRequest Triggers</inlineHelpText>
    <label>Disable PartnerRegRequest Triggers</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ShGl_DisableFunctionalityLogic__c/ShGl_DisableFunctionalityLogic__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global custom setting to conditionally disable certain functionality in code. Differs from Disable Business Logic Custom setting. This custom settings only certain methods would be using - whole trigger / workflow / etc will not be bypassed</description>
    <label>DisableFunctionalityLogic</label>
</CustomObject>

force-app/main/default/objects/ShGl_DisableFunctionalityLogic__c/fields/Allow_account_Transfer__c.field-meta.xml
<CustomField>
    <fullName>Allow_account_Transfer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allow account Transfer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/StateCodeName__c/StateCodeName__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>StateCodeName</label>
</CustomObject>

force-app/main/default/objects/StateCodeName__c/fields/State_Name__c.field-meta.xml
<CustomField>
    <fullName>State_Name__c</fullName>
    <label>State_Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TriggerControl__c/TriggerControl__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This setting is used to disable triggers dynamically without updating code</description>
    <label>TriggerControl</label>
</CustomObject>

force-app/main/default/objects/TriggerControl__c/fields/DisableTrigger__c.field-meta.xml
<CustomField>
    <fullName>DisableTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox is used as an ON/OFF flag to disable the respective trigger</description>
    <label>Disable Trigger?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkflowTriggerBypass__c/WorkflowTriggerBypass__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>WorkflowTriggerBypass</label>
</CustomObject>

force-app/main/default/objects/WorkflowTriggerBypass__c/fields/ByPassTrigger__c.field-meta.xml
<CustomField>
    <fullName>ByPassTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPassTrigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PR_Request_Service_isTest.cls
@isTest
private class PR_Request_Service_isTest{
    @testSetup static void setupMethod() {
        List<Partner_Page_Configuration__c> pageList = new List<Partner_Page_Configuration__c>();
        List<Contact> contList = new List<Contact>();
        UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        Profile profile1 = [Select Id from Profile where name = 'System Administrator'];

        User portalAccountOwner1 = new User(
            UserRoleId = portalRole.Id,
            ProfileId = profile1.Id,
            Username = System.now().millisecond() + 'testpuser211@test.com',
            Alias = 'batman11',
            Email='bruce.wayne11@wayneenterprises.com',
            EmailEncodingKey='UTF-8',
            Firstname='Bruce',
            Lastname='Wayne',
            LanguageLocaleKey='en_US',
            LocaleSidKey='en_US',
            TimeZoneSidKey='America/Chicago'
        );
        Database.insert(portalAccountOwner1);
        System.runAs ( portalAccountOwner1 ) {
            insert new ShGl_DisableBusinessLogic__c(SetupOwnerId=UserInfo.getOrganizationId(), Disable_PartnerRegRequest_Triggers__c=true);
            Account portalAccount1 = new Account(
                Name = 'TestAccount11',
                OwnerId = portalAccountOwner1.Id,
                RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Partner/Distributor').getRecordTypeId()
                //Focused_Partner__c = true
            );
            Database.insert(portalAccount1);
            
            //Create contact
            Contact contact1 = new Contact(
                FirstName = 'Test11',
                Lastname = 'McTesty11',
                AccountId = portalAccount1.Id,
                Email = System.now().millisecond() + 'test@test.com',
                Primary_Role__c = 'Admin'
            );
            contList.add(contact1);
            insert contList;
            
            Profile portalProfile = [SELECT Id FROM Profile Where Name='Rubrik Partner community Manager' Limit 1];
            User user1 = new User(
                Username = System.now().millisecond() + 'tespuser133@test.com',
                ContactId = contact1.Id,
                ProfileId = portalProfile.Id,
                Alias = 'test3',
                Email = 'test1233345@test.com',
                EmailEncodingKey = 'UTF-8',
                LastName = 'McTestyyy',
                CommunityNickname = 'test1234533',
                TimeZoneSidKey = 'America/Los_Angeles',
                LocaleSidKey = 'en_US',
                LanguageLocaleKey = 'en_US'
            );
            Database.insert(user1);
        }
    }
	//Commented as only coverage required for PR_Request_Main Trigger
    /*static testMethod void createPRRequest(){
        CountryWithCode__c CountrySetting1 = new CountryWithCode__c();
        CountrySetting1.Name = 'United States';
        CountrySetting1.Code__c = 'US';
        insert CountrySetting1;
        CountryWithCode__c countrySetting2 = new CountryWithCode__c();
        countrySetting2.Name = 'Canada';
        countrySetting2.Code__c = 'CA';
        insert CountrySetting2;

        StateCodeName__C stateSetting1 = new StateCodeName__C();
        stateSetting1.Name = 'US-AL';
        stateSetting1.State_Name__c = 'Alabama';
        insert stateSetting1;
        StateCodeName__C stateSetting2 = new StateCodeName__C();
        stateSetting2.Name = 'US-CA';
        stateSetting2.State_Name__c = 'California';
        insert stateSetting2;
        PageReference pageRef = Page.PartnerRegistrationForm;
        Test.setCurrentPage(pageRef);
        Partner_Registration_Request__c PR_Rec = new Partner_Registration_Request__c(
            First_Name__c = 'Test', 
            Last_Name__c = 'Last Name is_Test_class', 
            Company_Name__c = 'Test Company', 
            Email__c = 'test@test123.com', 
            Phone_Number__c = '1234567890', 
            Address__c = 'test street', 
            City__c = 'test City', 
            Country__c = 'United States', 
            Country_Picklist__c = 'United States', 
            State__c = 'CA', 
            Postal_Code__c = '93506', 
            Partner_Registration_Status__c = 'Submitted', 
            is_Converted__c = false
        );
        ApexPages.StandardController sc = new ApexPages.standardController(PR_Rec);

        PartnerRegistrationRequestExtension PRExtn = new PartnerRegistrationRequestExtension(sc);
        PRExtn.isitRequired();
        PRExtn.zipLength();
        PRExtn.saveRequest();
    }*/

    static testMethod void convertPRRequestToContact(){
		User u = [SELECT Id FROM User WHERE Email = 'bruce.wayne11@wayneenterprises.com'];
		System.runAs(u){
			CountryWithCode__c CountrySetting1 = new CountryWithCode__c();
			CountrySetting1.Name = 'United States';
			CountrySetting1.Code__c = 'US';
			insert CountrySetting1;
			CountryWithCode__c countrySetting2 = new CountryWithCode__c();
			countrySetting2.Name = 'Canada';
			countrySetting2.Code__c = 'CA';
			insert CountrySetting2;

			StateCodeName__C stateSetting1 = new StateCodeName__C();
			stateSetting1.Name = 'US-AL';
			stateSetting1.State_Name__c = 'Alabama';
			insert stateSetting1;
			StateCodeName__C stateSetting2 = new StateCodeName__C();
			stateSetting2.Name = 'US-CA';
			stateSetting2.State_Name__c = 'California';
			insert stateSetting2;
			
			WorkflowTriggerBypass__c wfSetting = new WorkflowTriggerBypass__c();
			wfSetting.Name = 'PRRequestMainTrigger';
			wfSetting.ByPassTrigger__c = false;
			insert wfSetting;
			
			insert new ShGl_DisableFunctionalityLogic__c(SetupOwnerId=UserInfo.getOrganizationId(), Allow_account_Transfer__c=true);
			
			
			Account accRec = ShGl_TestFactory.testMethod_PartnerAccount('Test Account');
			accRec.Name = 'Test Company 2';
			accRec.Website = 'www.TestCompany2.com';
			accRec.BillingCountry = 'United States';
			accRec.type = 'Reseller';
			accRec.OwnerId = UserInfo.getUserId();
			update accRec;
	 
			List<Contact> conList = ShGl_TestFactory.testMethod_PartnerContact(1, accRec);
			List<String> conIdList = new List<String>();
			conIdList.add(conList[0].Id);
			
			Test.startTest();
			List<User> userList = ShGl_TestFactory.testMethod_PartnerUser(1, conList);
			Test.stopTest();
			
			PR_Request_Service.updateUser(conIdList);
			
			Partner_Registration_Request__c prTestRecord = new Partner_Registration_Request__c(
				First_Name__c = 'Test 2', 
				Last_Name__c = 'Last Name is_Test_class 2', 
				Company_Name__c = 'Test Company 2', 
				Email__c = 'test@testnewcontact.com', 
				Phone_Number__c = '1234567890', 
				Address__c = 'test street', 
				City__c = 'test City', 
				Country__c = 'United States', 
				Country_Picklist__c = 'United States', 
				State__c = 'CA', 
				Partner_Registration_Status__c = 'Submitted', 
				is_Converted__c = false, 
				Partner_Account_Lookup__c = accRec.Id
			);
			insert prTestRecord;
			Partner_Registration_Request__c queryRecord = [select id, Last_Name__c, First_Name__c, Partner_Registration_Status__c, is_Converted__c
														   from Partner_Registration_Request__c
														   where Last_Name__c = 'Last Name is_Test_class 2'
														   LIMIT 1];
			system.assertEquals(queryRecord.Last_Name__c, 'Last Name is_Test_class 2');
			system.assertEquals(queryRecord.Partner_Registration_Status__c, 'Submitted');
			system.assertEquals(queryRecord.is_Converted__c, false);
			queryRecord.Partner_Registration_Status__c = 'Approved';
			queryRecord.is_Converted__c = true;
			TriggerControl__c setting = new TriggerControl__c();
			setting.Name = 'Contact';
			setting.DisableTrigger__c = False;
			insert setting;
			update queryRecord;
			Partner_Registration_Request__c queryRecordAfterUpdate = [select id, Last_Name__c, First_Name__c, Partner_Registration_Status__c, is_Converted__c
																	  from Partner_Registration_Request__c
																	  where Last_Name__c = 'Last Name is_Test_class 2'
																	  LIMIT 1];
			system.assertEquals(queryRecordAfterUpdate.Partner_Registration_Status__c, 'Approved', 'Status is scuessefully Approved');
			//system.assertEquals(queryRecordAfterUpdate.is_Converted__c, true);
		}
    }

	//Commented as only coverage required for PR_Request_Main Trigger
    /*static testMethod void convertPRRequestToContactTest(){
        Test.startTest();
        Account accRec = ShGl_TestFactory.testMethod_PartnerAccount('Test Account');
        accRec.Name = 'PARTNER_MSP ';
        accRec.Website = 'www.test3.com';
        accRec.BillingCountry = 'United States';
        accRec.type = 'Reseller';
        update accRec;
        List<Contact> lstContact = ShGl_TestFactory.testMethod_PartnerContact(1, accRec);
        lstContact[0].MailingCountry = 'United States';
        update lstContact;
        Partner_Registration_Request__c pr = new Partner_Registration_Request__c();
        pr.First_Name__c = 'test partner0';
        pr.Last_Name__c = 'request0';
        pr.Address__c = 'test address';
        pr.State__c = 'testState';
        pr.Country__c = 'United States';
        pr.Company_Name__c = accRec.Name;
        pr.Email__c = lstContact[0].email;
        pr.State_Picklist__c = 'AZ';
        pr.Country_Picklist__c = 'United States';
        insert pr;

        List<Partner_Registration_Request__c> lstPR = new List<Partner_Registration_Request__c>();
        lstPR.add(pr);
        PR_Request_Service.convertPRtoContact(lstPR);
        Test.stopTest();
    }

    static testMethod void convertPRRequestToContactTest2(){
        Test.startTest();
        Account accRec = ShGl_TestFactory.testMethod_PartnerAccount('Test Account');
        accRec.Name = 'PARTNER_MSP';
        accRec.Website = 'www.test3.com';
        accRec.BillingCountry = 'United States';
        accRec.type = 'Reseller';
        update accRec;
        List<Contact> lstContact = ShGl_TestFactory.testMethod_PartnerContact(1, accRec);
        lstContact[0].MailingCountry = 'United States';
        update lstContact;
        Partner_Registration_Request__c pr = new Partner_Registration_Request__c();
        pr.First_Name__c = 'test partner1';
        pr.Last_Name__c = 'request1';
        pr.Address__c = 'test address';
        pr.State__c = 'testState';
        pr.Country__c = 'United State';
        pr.Company_Name__c = 'PARTNER_MSP';
        pr.Email__c = 'abc@a.com0';
        pr.State_Picklist__c = 'AZ';
        pr.Country_Picklist__c = 'United States';
        pr.Partner_Account_Lookup__c = accRec.Id;
        insert pr;
        List<Partner_Registration_Request__c> lstPR = new List<Partner_Registration_Request__c>();
        lstPR.add(pr);
        PR_Request_Service.convertPRtoContact(lstPR);
        Test.stopTest();
    }
    
    static testMethod void convertPRRequestToContactTest3(){
        Account accRec = [SELECT Id from Account WHERE Name='TestAccount11' LIMIT 1];
        User u = [SELECT Id,UserType from USer WHERE LastName = 'McTestyyy'];
        Partner_Registration_Request__c pr = new Partner_Registration_Request__c();
        pr.First_Name__c = 'test partner';
        pr.Last_Name__c = 'request';
        pr.Address__c = 'test address';
        pr.State__c = 'testState';
        pr.Country__c = 'United State';
        pr.Company_Name__c = 'PARTNER_MSP';
        pr.Email__c = 'test1233345@test.com';
        pr.State_Picklist__c = 'AZ';
        pr.Country_Picklist__c = 'United States';
        pr.Partner_Account_Lookup__c = accRec.Id;
        pr.Admin_Access__c = true;
        insert pr;
        test.startTest();
        PR_Request_Service.convertPRtoContact(new List<Partner_Registration_Request__c>{pr});
        test.stoptest();
        System.assert(true);
    }*/

}