force-app/main/default/objects/CountryWithCode__c/CountryWithCode__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Country With Code</label>
</CustomObject>

force-app/main/default/objects/CountryWithCode__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/Deal_Registration__c.object-meta.xml
<CustomObject>
    <description>SOX object - Object used for Deal Registrations by Partners</description>
    <label>Deal Registration</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Deal Registration #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Registration__c/fields/CDM__c.field-meta.xml
<CustomField>
    <fullName>CDM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CDM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Deal_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deal Registrations (Company Name)</relationshipLabel>
    <relationshipName>Deal_Registrations4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Deal_Reg_Exp_Date__c.field-meta.xml
<CustomField>
    <fullName>Deal_Reg_Exp_Date__c</fullName>
    <label>Deal Reg Exp Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Deal_Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Deal_Registration_Status__c</fullName>
    <label>Deal Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Pending Conversion</fullName>
            </value>
            <value>
                <fullName>Pending Meeting</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deal Registrations (Distributor)</relationshipLabel>
    <relationshipName>Deal_Registrations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Focused_Partner__c.field-meta.xml
<CustomField>
    <fullName>Focused_Partner__c</fullName>
    <formula>Partner_Lookup__r.Focused_Partner__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Focused Partner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/GSI_Deal_Registration__c.field-meta.xml
<CustomField>
    <fullName>GSI_Deal_Registration__c</fullName>
    <defaultValue>false</defaultValue>
    <description>https://rubrik.atlassian.net/browse/PRIT24-806</description>
    <label>GSI Deal Registration</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/GSI_NDA__c.field-meta.xml
<CustomField>
    <fullName>GSI_NDA__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Applicable for Internal Deal Registration</description>
    <label>GSI - NDA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Deal Registrations</relationshipLabel>
    <relationshipName>Deal_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Lead_Share_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Lead_Share_Campaign__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PRIT24-356</description>
    <label>Lead Share Campaign</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/OEM_SubType__c.field-meta.xml
<CustomField>
    <fullName>OEM_SubType__c</fullName>
    <formula>TEXT( Distributor__r.OEM_Subtype__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OEM SubType</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity linked to Deal Reg</description>
    <label>Opportunity</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Please enter open opportunity name without an approved deal registration</errorMessage>
        <filterItems>
            <field>Opportunity.StageName</field>
            <operation>notEqual</operation>
            <value>7 Closed Won, 7 Closed Lost</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Registrations</relationshipLabel>
    <relationshipName>Deal_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Partner_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Partner_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Lookup</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partner/Distributor</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deal Registrations</relationshipLabel>
    <relationshipName>Deal_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/PatchManager__c.field-meta.xml
<CustomField>
    <fullName>PatchManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PatchManager</label>
    <referenceTo>PatchManager__c</referenceTo>
    <relationshipLabel>Deal Registrations</relationshipLabel>
    <relationshipName>Deal_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Deal Registrations (Primary Contact)</relationshipLabel>
    <relationshipName>Deal_Registrations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Primary_Deal_Registration__c.field-meta.xml
<CustomField>
    <fullName>Primary_Deal_Registration__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To be checked when DR is the primary deal on the opportunity</description>
    <label>Primary Deal Registration</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/PS_Escalated__c.field-meta.xml
<CustomField>
    <fullName>PS_Escalated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the DR was Partner Source Escalated</description>
    <label>PS Escalated?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/rerun_PatchManager_Assignments__c.field-meta.xml
<CustomField>
    <fullName>rerun_PatchManager_Assignments__c</fullName>
    <defaultValue>false</defaultValue>
    <label>rerun PatchManager Assignments</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/SDR__c.field-meta.xml
<CustomField>
    <fullName>SDR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SDR for the Deal. Populated from Patch Manager</description>
    <label>SDR</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Deal_Registrations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/StateCode__c.field-meta.xml
<CustomField>
    <fullName>StateCode__c</fullName>
    <label>StateCode</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>State_Province</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/recordTypes/Alliance.recordType-meta.xml
<RecordType>
    <fullName>Alliance</fullName>
    <active>true</active>
    <label>Alliance</label>
</RecordType>

force-app/main/default/objects/Deal_Registration__c/recordTypes/Engagement.recordType-meta.xml
<RecordType>
    <fullName>Engagement</fullName>
    <active>true</active>
    <label>Engagement</label>
</RecordType>

force-app/main/default/objects/Deal_Registration__c/recordTypes/OEM.recordType-meta.xml
<RecordType>
    <fullName>OEM</fullName>
    <active>true</active>
    <label>OEM</label>
</RecordType>

force-app/main/default/objects/Deal_Registration__c/recordTypes/Service_Delivery_Partner.recordType-meta.xml
<RecordType>
    <fullName>Service_Delivery_Partner</fullName>
    <active>true</active>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/PatchManager__c/PatchManager__c.object-meta.xml
<CustomObject>
    <label>PatchManager</label>
    <nameField>
        <displayFormat>PM-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PatchManagers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PatchManager__c/fields/AccountExecutive__c.field-meta.xml
<CustomField>
    <fullName>AccountExecutive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Executive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>FieldRep</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PatchManager__c/fields/CDM__c.field-meta.xml
<CustomField>
    <fullName>CDM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CDM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PatchManagers1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PatchManager__c/fields/CountryGlobal__c.field-meta.xml
<CustomField>
    <fullName>CountryGlobal__c</fullName>
    <label>CountryGlobal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PatchManager__c/fields/SDR__c.field-meta.xml
<CustomField>
    <fullName>SDR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SDR</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PatchManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PatchManager__c/fields/StateGlobal__c.field-meta.xml
<CustomField>
    <fullName>StateGlobal__c</fullName>
    <label>StateGlobal</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CountryGlobal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>State_Province</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PatchManager__c/fields/TLevel1__c.field-meta.xml
<CustomField>
    <fullName>TLevel1__c</fullName>
    <label>T-Level 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>T_Level_1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PatchManager__c/fields/Zip_code__c.field-meta.xml
<CustomField>
    <fullName>Zip_code__c</fullName>
    <label>Zip code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PatchManager__c/recordTypes/Geographic.recordType-meta.xml
<RecordType>
    <fullName>Geographic</fullName>
    <active>true</active>
    <label>Geographic</label>
</RecordType>

force-app/main/default/objects/WorkflowTriggerBypass__c/WorkflowTriggerBypass__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>WorkflowTriggerBypass</label>
</CustomObject>

force-app/main/default/objects/WorkflowTriggerBypass__c/fields/ByPassTrigger__c.field-meta.xml
<CustomField>
    <fullName>ByPassTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPassTrigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DealRegistrationTriggerHelperTest.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 07-04-2025
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
public class DealRegistrationTriggerHelperTest {
	@TestSetup static void makeData(){
        List<WorkflowTriggerBypass__c> wtList = new List<WorkflowTriggerBypass__c>();
        WorkflowTriggerBypass__c wt = new WorkflowTriggerBypass__c(name='leadReassignOnBusinessUnitChange',ByPassTrigger__c=false);
        wtList.add(wt);
        WorkflowTriggerBypass__c wt1 = new WorkflowTriggerBypass__c(name='cnsFirstAttemptUpdateLeadStatus',ByPassTrigger__c=false);
        wtList.add(wt1);
        WorkflowTriggerBypass__c wt2 = new WorkflowTriggerBypass__c(name='CreateSDRLedMeetingTask',ByPassTrigger__c=false);
        wtList.add(wt2);
        WorkflowTriggerBypass__c wt3 = new WorkflowTriggerBypass__c(name='updateLastOwnershipUpdateDate',ByPassTrigger__c=false);
        wtList.add(wt3);
        WorkflowTriggerBypass__c wt4 = new WorkflowTriggerBypass__c(name='updateOpportunitySource',ByPassTrigger__c=false);
        wtList.add(wt4);
        WorkflowTriggerBypass__c wt5 = new WorkflowTriggerBypass__c(name='salesOperationsAssignAccountSIC',ByPassTrigger__c=false);
        wtList.add(wt5);
        WorkflowTriggerBypass__c wt6 = new WorkflowTriggerBypass__c(name='salesOperationsSetEUResident',ByPassTrigger__c=false);
        wtList.add(wt6);
        insert wtList;
        User sysuser2  = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
            LastName = 'lastNameDRTest',
            Email = 'uniqueName1233' +'@rubrik.com',
            Username = 'uniqueName1233' +'@rubrik.com',
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'uniqueName'.substring(0,5),
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            Start_Date__c=System.Today().adddays(-30)
        );
        insert sysuser2;
        System.runAs(sysuser2){
            CountryWithCode__c cc = new CountryWithCode__c(Code__c='US',Name='United States');
            insert cc;
            System.assert(true);
        }
    }
    @isTest static void testSellToPartner(){
        User sysuser1 = TestDataFactory.getUser();
        User sysuser2  = [Select id from user where LastName = 'lastNameDRTest'];

        Test.setMock(HttpCalloutMock.class, new PC_DealRegL2AMatchTest('SUCCESS'));
        system.runas(sysuser1){
            Account acc = TestDataFactory.getAccount();
            acc.name = 'Test New Account';
            acc.Type = 'Prospect';
            acc.OwnerId = sysuser2.id;
            acc.Focused_Partner__c = true;
            insert acc;

            //Create contact
            Contact contact1 = new Contact(
                FirstName = 'Test',
                Lastname = 'McTes11',
                AccountId = acc.Id,
                Email = System.now().millisecond() + 'test@test.com',
                Primary_Role__c = 'Admin'
            );
			insert contact1;
            Id georecId = Schema.SObjectType.PatchManager__c.getRecordTypeInfosByName().get('Geographic').getRecordTypeId();
            PatchManager__c pm = new PatchManager__c(recordtypeId=georecId,CDM__c=sysuser2.Id,CountryGlobal__c='United States',City__c='City',State__c='AK',StateGlobal__c='AK',Zip_code__c='421302',SDR__c=sysuser2.Id,AccountExecutive__c=sysuser2.Id);
            insert pm;
            CountryWithCode__c cc = new CountryWithCode__c(Code__c='US',Name='United States');
            insert cc;
            Opportunity opp = TestDataFactory.getOpportunity();
            insert opp;

            Id internal = Schema.SObjectType.Deal_Registration__c.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
            Deal_Registration__c deal=TestDataFactory.getDealRegistration();
            deal.Deal_Registration_Status__c = 'Submitted';
            deal.Company_Name__c = acc.id;
            deal.Partner_Lookup__c = acc.id;
            deal.RecordTypeId = internal;
            deal.GSI_Deal_Registration__c = true;
            deal.Primary_Contact__c = contact1.Id;
            try{
            	insert deal;
            }
            catch(exception e){
                System.debug(LoggingLevel.DEBUG, 'error');
            }
            System.assert(true);
        }
    }

    @isTest static void testsetOwnerTerritory(){
        Test.startTest();
        List<Territory2> territories = new List<Territory2>();
        List<Territory2Model> TModel = [Select id,Name from territory2model where State ='Active'];
        List<Territory2Type> terrType = [Select Id, DeveloperName from Territory2Type where DeveloperName = 'Territory'];

        for(Integer i=0;i<3;i++){
            Territory2 terr = new Territory2();
            terr.Name = 'CDM-' + i;
            terr.DeveloperName = 'CDM_' + i;
            terr.Adaptive_Territory_Id__c = '999999'+i;
            terr.Territory2ModelId = TModel[0].Id;
            terr.Territory2TypeId = terrType[0].Id;
            territories.add(terr);
        }
        insert territories;

        List<User> userList = new List<User>();
        List<PermissionSetAssignment> psAssignmentList = new List<PermissionSetAssignment>();
        
        Profile prCDM = [Select Id from profile where Name='Channel Development Manager'];
        Id psId = [SELECT Id from PermissionSet WHERE Name = 'RubrikChannelUsersNew'].Id;
        
        User uCDM1 = new User(firstname = 'James',
            lastName = 'Webb',
            email = 'JamWeb00098990@gmail.com',
            Username = 'JamWeb098877@gmail.com',
            EmailEncodingKey = 'ISO-8859-1',
            Alias = 'GAA',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            LanguageLocaleKey = 'en_US',
            ProfileId = prCDM.Id
        );
        userList.add(uCDM1);
        
        User uCDM2 = new User(firstname = 'James',
            lastName = 'Philips',
            email = 'JamPhilp889000@gmail.com',
            Username = 'JamPhilp234567@gmail.com',
            EmailEncodingKey = 'ISO-8859-1',
            Alias = 'GAA',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            LanguageLocaleKey = 'en_US',
            ProfileId = prCDM.Id
        );
        userList.add(uCDM2);

        User uCDM3 = new User(firstname = 'Joe',
            lastName = 'Rovers',
            email = 'JoeRov987895@gmail.com',
            Username = 'JoeRo6789@gmail.com',
            EmailEncodingKey = 'ISO-8859-1',
            Alias = 'GAA',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            LanguageLocaleKey = 'en_US',
            ProfileId = prCDM.Id
        );
        userList.add(uCDM3);
        
        insert userList;
        
        PermissionSetAssignment psa1 = new PermissionSetAssignment();
        psa1.AssigneeId = uCDM1.Id;
        psa1.PermissionSetId = psId;
        psAssignmentList.add(psa1);
        
        PermissionSetAssignment psa2 = new PermissionSetAssignment();
        psa2.AssigneeId = uCDM2.Id;
        psa2.PermissionSetId = psId;
        psAssignmentList.add(psa2);
        
        PermissionSetAssignment psa3 = new PermissionSetAssignment();
        psa3.AssigneeId = uCDM3.Id;
        psa3.PermissionSetId = psId;
        psAssignmentList.add(psa3);
        
        insert psAssignmentList;

        List<UserTerritory2Association> utaRecords = new List<UserTerritory2Association>();
        UserTerritory2Association uta = new UserTerritory2Association();
        uta.Territory2Id = territories[0].Id;
        uta.RoleInTerritory2 = 'Account Executive';
        uta.UserId = uCDM1.Id;
        utaRecords.add(uta);

        uta = new UserTerritory2Association();
        uta.Territory2Id = territories[0].Id;
        uta.RoleInTerritory2 = 'SDR';
        uta.UserId = uCDM2.Id;
        utaRecords.add(uta);

        uta = new UserTerritory2Association();
        uta.Territory2Id = territories[2].Id;
        uta.RoleInTerritory2 = 'Channel Manager';
        uta.UserId = uCDM3.Id;
        utaRecords.add(uta);

        Test.stopTest();
        String uniqueName = TestDataFactory.getUniqueName();
        User runAsUser = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Rubrik Field Sales User'].Id,
            LastName = 'last',
            Email = uniqueName +'@rubrik.com',
            Username = uniqueName +'@rubrik.com',
            CompanyName = 'TEST',
            Title = 'title',
            Alias = uniqueName.substring(0,5),
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            //UserRoleId = vUserRole.Id,
            Start_Date__c=System.Today().adddays(-30)
        );
        insert runAsUser;

        uta = new UserTerritory2Association();
        uta.Territory2Id = territories[0].Id;
        uta.RoleInTerritory2 = 'Account Executive';
        uta.UserId = runAsUser.Id;
        utaRecords.add(uta);

        insert utaRecords;
        System.assert(true);
    }

    @isTest static void testrunPatchManager() {
        Deal_Registration__c deal=TestDataFactory.getDealRegistration();
        Test.setMock(HttpCalloutMock.class, new PC_DealRegL2AMatchTest('SUCCESS'));
        deal.Deal_Registration_Status__c = 'Submitted';
        insert deal;
        Test.startTest();
            deal.rerun_PatchManager_Assignments__c = true;
            update deal;
        Test.stopTest();
    }

    static testMethod void testMethod4() {
        User sysuser1 = TestDataFactory.getUser();
        User sysuser2  = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
            LastName = 'last',
            Email = 'enrique1233' +'@rubrik.com',
            Username = 'enrique1233' +'@rubrik.com',
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'enrqueName'.substring(0,5),
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            Start_Date__c=System.Today().adddays(-30)
        );
        insert sysuser2;
        Test.setMock(HttpCalloutMock.class, new PC_DealRegL2AMatchTest('SUCCESS'));
        system.runas(sysuser1){
            Id georecId = Schema.SObjectType.PatchManager__c.getRecordTypeInfosByName().get('Geographic').getRecordTypeId();
            PatchManager__c pm = new PatchManager__c(recordtypeId=georecId,CDM__c=sysuser2.Id,CountryGlobal__c='United States',City__c='City',State__c='AK',StateGlobal__c='AK',Zip_code__c='421302',SDR__c=sysuser2.Id,AccountExecutive__c=sysuser2.Id);
            insert pm;
            Opportunity opp = TestDataFactory.getOpportunity();
            insert opp;
            Deal_Registration__c deal=TestDataFactory.getDealRegistration();
            deal.Deal_Registration_Status__c = 'Submitted';
            insert deal;
            deal.ownerid = sysuser2.Id;
            update deal;
            Deal_Registration__c deal1 = [select name from Deal_Registration__c where id =:deal.Id];
            opp.Deal_Registration_Number__c = deal1.name;
            update opp;
            deal1.Deal_Reg_Exp_Date__c  = system.today().addDays(-1);
            update deal1;
            Map<string,Date> dealRegOppMap = new Map<string,Date>();
            dealRegOppMap.put(deal1.name,system.today());

            PC_DealRegExpiryUpdateBatch b = new PC_DealRegExpiryUpdateBatch();
            Database.executeBatch(b,1);
            System.assert(true);
        }
    }

    static testMethod void testMethod5() {
        User sysuser1 = TestDataFactory.getUser();
        User sysuser2  = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
            LastName = 'last',
            Email = 'enrique1233' +'@rubrik.com',
            Username = 'enrique1233' +'@rubrik.com',
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'enrqueName'.substring(0,5),
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            Start_Date__c=System.Today().adddays(-30)
        );
        insert sysuser2;
        Test.setMock(HttpCalloutMock.class, new PC_DealRegL2AMatchTest('SUCCESS'));
        system.runas(sysuser1){
            Id georecId = Schema.SObjectType.PatchManager__c.getRecordTypeInfosByName().get('Geographic').getRecordTypeId();
            PatchManager__c pm = new PatchManager__c(recordtypeId=georecId,CDM__c=sysuser2.Id,CountryGlobal__c='United States',City__c='City',State__c='AK',StateGlobal__c='AK',Zip_code__c='421302',SDR__c=sysuser2.Id,AccountExecutive__c=sysuser2.Id);
            insert pm;
            Opportunity opp = TestDataFactory.getOpportunity();
            insert opp;
            Deal_Registration__c deal=TestDataFactory.getDealRegistration();
            deal.Deal_Registration_Status__c = 'Submitted';
            insert deal;
            deal.ownerid = sysuser2.Id;
            deal.Deal_Registration_Status__c = 'Escalated';
            deal.Opportunity__c = opp.Id;
            deal.PS_Escalated__c = true;
            update deal;
            Deal_Registration__c deal1 = [select name from Deal_Registration__c where id =:deal.Id];
            opp.Deal_Registration_Number__c = deal1.name;
            update opp;
            deal1.Deal_Reg_Exp_Date__c  = system.today().addDays(-1);
            update deal1;
            Map<string,Date> dealRegOppMap = new Map<string,Date>();
            dealRegOppMap.put(deal1.name,system.today());

            PC_DealRegExpiryUpdateBatch b = new PC_DealRegExpiryUpdateBatch();
            Database.executeBatch(b,1);
            System.assert(true);
        }
    }

    static testMethod void testMethod6() {
        string accountPartnerRecordType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Partner/Distributor').getRecordTypeId();
        User sysuser1 = TestDataFactory.getUser();
        User sysuser2  = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
            LastName = 'last',
            Email = 'enrique1233' +'@rubrik.com',
            Username = 'enrique1233' +'@rubrik.com',
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'enrqueName'.substring(0,5),
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            Start_Date__c=System.Today().adddays(-30)
        );
        insert sysuser2;
        Test.setMock(HttpCalloutMock.class, new PC_DealRegL2AMatchTest('SUCCESS'));
        system.runas(sysuser1){
            Account accp = TestDataFactory.getAccount();
            accp.name = 'Test New Account Partner Acc';
            accp.Type = 'Reseller';
            accp.OwnerId = sysuser2.Id;
            accp.RecordTypeId = accountPartnerRecordType;
            accp.MSP_Sub_Type__c = 'GSI';
            insert accp;

            Opportunity opp = TestDataFactory.getOpportunity();
            insert opp;
            Deal_Registration__c deal=TestDataFactory.getDealRegistration();
            deal.Deal_Registration_Status__c = 'Submitted';
            insert deal;
            deal.ownerid = sysuser2.Id;
            deal.Deal_Registration_Status__c = 'Approved';
            deal.Opportunity__c = opp.Id;
            deal.Partner_Lookup__c = accp.Id;
            //update deal;
            Deal_Registration__c deal1 = [select name from Deal_Registration__c where id =:deal.Id];
            opp.Deal_Registration_Number__c = deal1.name;
            opp.Deal_Reg_Approval_Status__c = 'Approved';
            update opp;
            deal1.Deal_Reg_Exp_Date__c  = system.today().addDays(-1);
            update deal1;
            Map<string,Date> dealRegOppMap = new Map<string,Date>();
            dealRegOppMap.put(deal1.name,system.today());

            PC_DealRegExpiryUpdateBatch b = new PC_DealRegExpiryUpdateBatch();
            Database.executeBatch(b,1);
            System.assert(true);
        }
    }
    
    static testMethod void testMethod7() {
        List<Territory2> territories = new List<Territory2>();
        List<Territory2Model> TModel = [Select id,Name from territory2model where State ='Active'];
        List<Territory2Type> terrType = [Select Id, DeveloperName from Territory2Type where DeveloperName = 'Territory'];

        for(Integer i=0;i<3;i++){
            Territory2 terr = new Territory2();
            terr.Name = 'CDM-' + i;
            terr.DeveloperName = 'CDM_' + i;
            terr.Adaptive_Territory_Id__c = '999999'+i;
            terr.Territory2ModelId = TModel[0].Id;
            terr.Territory2TypeId = terrType[0].Id;
            territories.add(terr);
        }
        insert territories;
        
        User sysuser1 = TestDataFactory.getUser();
        User sysuser2  = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
            LastName = 'last',
            Email = 'enrique1233' +'@rubrik.com',
            Username = 'enrique1233' +'@rubrik.com',
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'enrqueName'.substring(0,5),
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            Start_Date__c=System.Today().adddays(-30)
        );
        insert sysuser2;
        
        Test.setMock(HttpCalloutMock.class, new PC_DealRegL2AMatchTest('SUCCESS'));
        system.runas(sysuser1){
            
            //User Territory Association
            List<UserTerritory2Association> utaRecords = new List<UserTerritory2Association>();
            UserTerritory2Association uta = new UserTerritory2Association();
            uta.Territory2Id = territories[0].Id;
            uta.RoleInTerritory2 = 'Account Executive';
            uta.UserId = sysuser1.Id;
            utaRecords.add(uta);
            
            uta = new UserTerritory2Association();
            uta.Territory2Id = territories[0].Id;
            uta.RoleInTerritory2 = 'CDM';
            uta.UserId = sysuser2.Id;
            utaRecords.add(uta);
            
            insert utaRecords;
            Account portalAccount = new Account(Name = 'TestAccount', Type = 'MSP');
            insert portalAccount;

            Contact contact = new Contact(
                FirstName = 'Test',
                LastName = 'McTesty',
                AccountId = portalAccount.Id,
                Email = System.now().millisecond() + 'test@test.com',
                Primary_Role__c = 'Admin'
            );
            insert contact;
            
            Id georecId = Schema.SObjectType.PatchManager__c.getRecordTypeInfosByName().get('Geographic').getRecordTypeId();
            PatchManager__c pm = new PatchManager__c(recordtypeId=georecId,CDM__c=sysuser2.Id,CountryGlobal__c='United States',City__c='City',State__c='AK',StateGlobal__c='AK',Zip_code__c='421302',SDR__c=sysuser2.Id,AccountExecutive__c=sysuser2.Id,TLevel1__c='AMER');
            insert pm;
            Opportunity opp = TestDataFactory.getOpportunity();
            insert opp;
            Deal_Registration__c deal=TestDataFactory.getDealRegistration();
            deal.Deal_Registration_Status__c = 'Submitted';
            deal.Partner_Lookup__c = portalAccount.Id;
            deal.Company_Name__c = portalAccount.Id;
            deal.GSI_Deal_Registration__c = true;
            insert deal;
            deal.ownerid = sysuser2.Id;
            update deal;
            Deal_Registration__c deal1 = [select name from Deal_Registration__c where id =:deal.Id];
            opp.Deal_Registration_Number__c = deal1.name;
            update opp;
            deal1.Deal_Reg_Exp_Date__c  = system.today().addDays(-1);
            update deal1;
            Map<string,Date> dealRegOppMap = new Map<string,Date>();
            dealRegOppMap.put(deal1.name,system.today());

            PC_DealRegExpiryUpdateBatch b = new PC_DealRegExpiryUpdateBatch();
            Database.executeBatch(b,1);
            System.assert(true);
        }
    }
    
    @isTest static void testsetInternalDRStatus(){
        User sysuser1 = TestDataFactory.getUser();
        User sysuser2  = [Select id from user where LastName = 'lastNameDRTest'];

        Test.setMock(HttpCalloutMock.class, new PC_DealRegL2AMatchTest('SUCCESS'));
        system.runas(sysuser1){
            Account acc = TestDataFactory.getAccount();
            acc.name = 'Test New Account';
            acc.Type = 'Prospect';
            acc.OwnerId = sysuser2.id;
            acc.Focused_Partner__c = true;
            insert acc;
            //Create contact
            Contact contact1 = new Contact(
                FirstName = 'Test',
                Lastname = 'McTes11',
                AccountId = acc.Id,
                Email = System.now().millisecond() + 'test@test.com',
                Primary_Role__c = 'Admin'
            );
			insert contact1;
            CountryWithCode__c cc = new CountryWithCode__c(Code__c='US',Name='United States');
            insert cc;
            Opportunity opp = TestDataFactory.getOpportunity();
            insert opp;

            Deal_Registration__c deal = TestDataFactory.getDealRegistration();
            deal.Deal_Registration_Status__c = 'Submitted';
            deal.Company_Name__c = acc.id;
            deal.Partner_Lookup__c = acc.id;
            deal.RecordTypeId = Schema.SObjectType.Deal_Registration__c.getRecordTypeInfosByDeveloperName().get('Service_Delivery_Partner').getRecordTypeId();
            deal.GSI_Deal_Registration__c = true;
            deal.GSI_NDA__c = true;
            deal.Primary_Contact__c = contact1.Id;
            deal.StateCode__c = '';

            Test.startTest();
            insert deal;
            Test.stopTest();

            deal.Deal_Registration_Status__c = 'Approved';
            deal.Opportunity__c = opp.Id;
            update deal;
            System.assert(true);
        }
    }

    @isTest static void testUpdateAllianceOEMDR(){
        User sysuser1 = TestDataFactory.getUser();
        User sysuser2  = [Select id from user where LastName = 'lastNameDRTest'];

        Test.setMock(HttpCalloutMock.class, new PC_DealRegL2AMatchTest('SUCCESS'));
        system.runas(sysuser1){
            Account acc = TestDataFactory.getAccount();
            acc.name = 'Test New Account';
            acc.Type = 'Prospect';
            acc.OwnerId = sysuser2.id;
            acc.Focused_Partner__c = true;
            insert acc;

            Account acc1 = TestDataFactory.getAccount();
            acc1.name = 'Test New Account';
            acc1.Type = 'Partner';
            acc1.OwnerId = sysuser2.id;
            acc1.Focused_Partner__c = true;
            acc1.RecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('Partner/Distributor').getRecordTypeId();
            acc1.Type = 'OEM';
            acc1.OEM_SubType__c = 'Revshare';
            insert acc1;

            //Create contact
            Contact contact1 = new Contact(
                FirstName = 'Test',
                Lastname = 'McTes11',
                AccountId = acc.Id,
                Email = System.now().millisecond() + 'test@test.com',
                Primary_Role__c = 'Admin'
            );
			insert contact1;
            CountryWithCode__c cc = new CountryWithCode__c(Code__c='US',Name='United States');
            insert cc;
            Opportunity opp = TestDataFactory.getOpportunity();
            insert opp;

            Deal_Registration__c deal = TestDataFactory.getDealRegistration();
            deal.Deal_Registration_Status__c = 'Submitted';
            deal.Company_Name__c = acc.id;
            deal.Partner_Lookup__c = acc.id;
            deal.RecordTypeId = Schema.SObjectType.Deal_Registration__c.getRecordTypeInfosByDeveloperName().get('Alliance').getRecordTypeId();
            deal.Primary_Contact__c = contact1.Id;
            deal.StateCode__c = '';

            Test.startTest();
            insert deal;
            Test.stopTest();

            deal.Deal_Registration_Status__c = 'Approved';
            deal.Primary_Deal_Registration__c = true;
            deal.Opportunity__c = opp.Id;
            update deal;

            Id georecId = Schema.SObjectType.PatchManager__c.getRecordTypeInfosByName().get('Geographic').getRecordTypeId();
            PatchManager__c pmRec = new PatchManager__c(recordtypeId=georecId,CDM__c=sysuser2.Id,CountryGlobal__c='United States',City__c='City',State__c='',StateGlobal__c='',Zip_code__c='421302',SDR__c=sysuser2.Id,AccountExecutive__c=sysuser2.Id);
            insert pmRec;

            Deal_Registration__c deal1 = TestDataFactory.getDealRegistration();
            deal1.Deal_Registration_Status__c = 'Submitted';
            deal1.Company_Name__c = acc.id;
            deal1.Partner_Lookup__c = acc.id;
            deal1.RecordTypeId = Schema.SObjectType.Deal_Registration__c.getRecordTypeInfosByDeveloperName().get('OEM').getRecordTypeId();
            deal1.Primary_Contact__c = contact1.Id;
            deal1.StateCode__c = '';
            deal1.Distributor__c = acc1.Id;
            deal1.PatchManager__c = pmRec != null ? pmRec.Id : null;
            deal1.OwnerId = sysuser2.id;
            insert deal1;
            System.assert(true);
        }
    }

    @isTest static void testmanageConvertedLeads(){
        User sysuser1 = TestDataFactory.getUser();
        User sysuser2  = [Select id from user where LastName = 'lastNameDRTest'];

        Test.setMock(HttpCalloutMock.class, new PC_DealRegL2AMatchTest('SUCCESS'));
        system.runas(sysuser1){
            Account acc1 = TestDataFactory.getAccount();
            acc1.name = 'Test New Account';
            acc1.Type = 'Partner';
            acc1.OwnerId = sysuser2.id;
            acc1.Focused_Partner__c = true;
            acc1.RecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('Partner/Distributor').getRecordTypeId();
            insert acc1;

            CountryWithCode__c cc = new CountryWithCode__c(Code__c='US',Name='United States');
            insert cc;
            Opportunity opp = TestDataFactory.getOpportunity();
            insert opp;

            List<Lead> leadList = new List<Lead>();
            Lead led = (Lead) ShGl_TestFactory.createSObject(new Lead(), null);
            led.firstName = 'Test Lead FN';
            led.lastName = 'Test Lead LN';
            led.Status = 'Open';
            led.CountryCode = 'US';
            led.Routing_Rule_Applied__c ='test';
            leadList.add(led);

            Lead led1 = (Lead) ShGl_TestFactory.createSObject(new Lead(), null);
            led1.firstName = 'Test Lead FN12';
            led1.lastName = 'Test Lead LN23';
            led1.Status = 'Open';
            led1.CountryCode = 'US';
            led1.Routing_Rule_Applied__c ='test';
            leadList.add(led1);

            List<Deal_Registration__c> dealList = new List<Deal_Registration__c>();
            Deal_Registration__c deal = TestDataFactory.getDealRegistration();
            deal.Deal_Registration_Status__c = 'Submitted';
            deal.Partner_Lookup__c = acc1.id;
            deal.RecordTypeId = Schema.SObjectType.Deal_Registration__c.getRecordTypeInfosByName().get('Reseller').getRecordTypeId();
            deal.StateCode__c = '';
            deal.Lead_Share_Campaign__c = true;
            dealList.add(deal);

            Deal_Registration__c deal1 = TestDataFactory.getDealRegistration();
            deal1.Deal_Registration_Status__c = 'Submitted';
            deal1.Partner_Lookup__c = acc1.id;
            deal1.RecordTypeId = Schema.SObjectType.Deal_Registration__c.getRecordTypeInfosByName().get('Reseller').getRecordTypeId();
            deal1.StateCode__c = '';
            dealList.add(deal1);

            Test.startTest();
            insert dealList;
            insert leadList;
            Test.stopTest();

            dealList[0].Deal_Registration_Status__c = 'Pending Conversion';
            dealList[0].Lead__c = leadList[0].Id;
            update dealList[0];

            dealList[1].Deal_Registration_Status__c = 'Pending Conversion';
            dealList[1].Lead__c = leadList[1].Id;
            update dealList[1];
            System.assert(true);
        }
    }

    @isTest static void testaddCustomerContactAsOppRole(){
        User sysuser1 = TestDataFactory.getUser();
        User sysuser2  = [Select id from user where LastName = 'lastNameDRTest'];

        Test.setMock(HttpCalloutMock.class, new PC_DealRegL2AMatchTest('SUCCESS'));
        system.runas(sysuser1){
            Account acc1 = TestDataFactory.getAccount();
            acc1.name = 'Test New Account';
            acc1.Type = 'Partner';
            acc1.OwnerId = sysuser2.id;
            acc1.Focused_Partner__c = true;
            acc1.RecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('Partner/Distributor').getRecordTypeId();
            insert acc1;

            Account acc2 = TestDataFactory.getAccount();
            acc2.name = 'Test New Account';
            acc2.Type = 'MSP-Reseller';
            acc2.OwnerId = sysuser2.id;
            acc2.Focused_Partner__c = true;
            acc2.RecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('Partner/Distributor').getRecordTypeId();
            //acc2.Account_Status__c = 'Existing Customer';
            insert acc2;

            Account acc3 = TestDataFactory.getAccount();
            acc3.name = 'Test New Account';
            acc3.Type = 'MSP Customer';
            acc3.OwnerId = sysuser2.id;
            //acc3.Account_Status__c = 'Prospect';
            insert acc3;

            Contact contact1 = new Contact(
                FirstName = 'Tes33232t',
                Lastname = 'McTes11123',
                AccountId = acc1.Id,
                Email = 'test@test9876541.com',
                Primary_Role__c = 'Admin'
            );
            insert contact1;

            CountryWithCode__c cc = new CountryWithCode__c(Code__c='US',Name='United States');
            insert cc;
            Opportunity opp = TestDataFactory.getOpportunity();
            insert opp;

            Opportunity opp1 = TestDataFactory.getOpportunity();
            insert opp1;

            Opportunity opp2 = TestDataFactory.getOpportunity();
            opp2.AccountId = acc2.Id;
            insert opp2;

            Opportunity opp3 = TestDataFactory.getOpportunity();
            opp3.AccountId = acc3.Id;
            insert opp3;

            OpportunityContactRole ocr = new OpportunityContactRole();
            ocr.ContactId = contact1.Id;
            ocr.OpportunityId = opp.Id;
            insert ocr;

            List<Lead> leadList = new List<Lead>();
            Lead led = (Lead) ShGl_TestFactory.createSObject(new Lead(), null);
            led.firstName = 'Test Lead FN987';
            led.lastName = 'Test Lead LN987';
            led.Status = 'Open';
            led.email = 'test@test987654.com';
            led.status = 'RAW';
            led.CountryCode = 'US';
            led.Routing_Rule_Applied__c ='test';
            led.Deal_Registration__c = true;
            led.Deal_Reg_Approval_Status__c = 'Expired';
            leadList.add(led);

            List<Deal_Registration__c> dealList = new List<Deal_Registration__c>();
            Deal_Registration__c deal = TestDataFactory.getDealRegistration();
            deal.Deal_Registration_Status__c = 'Submitted';
            deal.Partner_Lookup__c = acc1.id;
            deal.RecordTypeId = Schema.SObjectType.Deal_Registration__c.getRecordTypeInfosByName().get('Reseller').getRecordTypeId();
            deal.Email__c = 'test@test987654.com';
            deal.StateCode__c = '';
            deal.company_name__c = acc1.id;
            deal.Lead_Share_Campaign__c = true;
            dealList.add(deal);

            Deal_Registration__c deal1 = TestDataFactory.getDealRegistration();
            deal1.Deal_Registration_Status__c = 'Submitted';
            deal1.Partner_Lookup__c = acc1.id;
            deal1.RecordTypeId = Schema.SObjectType.Deal_Registration__c.getRecordTypeInfosByDeveloperName().get('Service_Delivery_Partner').getRecordTypeId();
            deal1.StateCode__c = '';
            deal1.Email__c = 'test@test9876541.com';
            deal1.Primary_Contact__c = contact1.Id;
            dealList.add(deal1);

            Deal_Registration__c deal2 = TestDataFactory.getDealRegistration();
            deal2.Deal_Registration_Status__c = 'Submitted';
            deal2.Company_Name__c = acc2.id;
            deal2.Partner_Lookup__c = acc1.id;
            deal2.RecordTypeId = Schema.SObjectType.Deal_Registration__c.getRecordTypeInfosByName().get('Reseller').getRecordTypeId();
            deal2.StateCode__c = '';
            deal2.Email__c = 'test@test98765434.com';
            deal2.Primary_Contact__c = contact1.Id;
            dealList.add(deal2);

            Deal_Registration__c deal3 = TestDataFactory.getDealRegistration();
            deal3.Deal_Registration_Status__c = 'Submitted';
            deal3.Company_Name__c = acc3.id;
            deal3.Partner_Lookup__c = acc1.id;
            deal3.RecordTypeId = Schema.SObjectType.Deal_Registration__c.getRecordTypeInfosByName().get('Engagement').getRecordTypeId();
            deal3.StateCode__c = '';
            deal3.Email__c = 'test@test98765424.com';
            deal3.Primary_Contact__c = contact1.Id;
            dealList.add(deal3);

            Test.startTest();
            insert dealList;
            insert leadList;

            dealList[0].Deal_Registration_Status__c = 'Approved';
            dealList[0].Opportunity__c = opp.Id;

            dealList[1].Deal_Registration_Status__c = 'Approved';
            dealList[1].Opportunity__c = opp1.Id;
            
            dealList[2].Deal_Registration_Status__c = 'Approved';
            dealList[2].Opportunity__c = opp.Id;
            
            dealList[3].Deal_Registration_Status__c = 'Approved';
            dealList[3].Opportunity__c = opp1.Id;
            
            update dealList;
            List<Deal_Registration__c> errorList = new List<Deal_Registration__c>();
            try{
                deal.company_name__c = acc2.Id;
                deal1.Partner_Lookup__c = acc2.Id;
                deal2.Distributor__c = acc2.Id;
                deal3.Opportunity__c = opp.Id;
                errorList.add(deal);
                errorList.add(deal1);
                errorList.add(deal2);
                errorList.add(deal3);
                update errorList;
            }catch(exception e){
                System.debug(LoggingLevel.DEBUG, 'error');
            }
            
            Test.stopTest();
            System.assert(true);
        }
    }
    
    @isTest static void markDealRegApprovedTest(){
        User sysuser1 = TestDataFactory.getUser();
        User sysuser2  = [Select id from user where LastName = 'lastNameDRTest'];
        Test.setMock(HttpCalloutMock.class, new PC_DealRegL2AMatchTest('SUCCESS'));
        system.runas(sysuser1){
            Account acc1 = TestDataFactory.getAccount();
            acc1.name = 'Test New Account';
            acc1.Type = 'Partner';
            acc1.OwnerId = sysuser2.id;
            acc1.Focused_Partner__c = true;
            acc1.RecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('Partner/Distributor').getRecordTypeId();
            insert acc1;
            Contact contact1 = new Contact(
                FirstName = 'Tes33232t',
                Lastname = 'McTes11123',
                AccountId = acc1.Id,
                Email = 'test@test9876541.com',
                Primary_Role__c = 'Admin'
            );
            insert contact1;

            CountryWithCode__c cc = new CountryWithCode__c(Code__c='US',Name='United States');
            insert cc;
            Opportunity opp = TestDataFactory.getOpportunity();
            insert opp;
            
            List<Deal_Registration__c> dealList = new List<Deal_Registration__c>();
            Deal_Registration__c deal1 = TestDataFactory.getDealRegistration();
            deal1.Deal_Registration_Status__c = 'Submitted';
            deal1.Partner_Lookup__c = acc1.id;
            deal1.RecordTypeId = Schema.SObjectType.Deal_Registration__c.getRecordTypeInfosByDeveloperName().get('Service_Delivery_Partner').getRecordTypeId();
            deal1.StateCode__c = '';
            deal1.Email__c = 'test@test9876541.com';
            deal1.Primary_Contact__c = contact1.Id;
            deal1.Deal_Reg_Exp_Date__c = Date.today().addDays(1);
            dealList.add(deal1);
            
            Deal_Registration__c deal2 = TestDataFactory.getDealRegistration();
            deal2.Deal_Registration_Status__c = 'Pending Meeting';
            deal2.Company_Name__c = acc1.id;
            deal2.Partner_Lookup__c = acc1.id;
            deal2.RecordTypeId = Schema.SObjectType.Deal_Registration__c.getRecordTypeInfosByName().get('Reseller').getRecordTypeId();
            deal2.StateCode__c = '';
            deal2.Email__c = 'test@test98765434.com';
            deal2.Primary_Contact__c = contact1.Id;
            deal2.Deal_Reg_Exp_Date__c = Date.today().addDays(1);
            dealList.add(deal2);
            
            Deal_Registration__c deal3 = TestDataFactory.getDealRegistration();
            deal3.Deal_Registration_Status__c = 'Submitted';
            deal3.Partner_Lookup__c = acc1.id;
            deal3.RecordTypeId = Schema.SObjectType.Deal_Registration__c.getRecordTypeInfosByDeveloperName().get('Service_Delivery_Partner').getRecordTypeId();
            deal3.StateCode__c = '';
            deal3.Email__c = 'test@test9876541333.com';
            deal3.Primary_Contact__c = contact1.Id;
            deal3.Deal_Reg_Exp_Date__c = Date.today().addDays(1);
            dealList.add(deal3);
            
            insert dealList;
            
            deal1.Deal_Registration_Sub_Status__c = 'Extension Approved';
            deal1.Opportunity__c = opp.Id;
            
            deal2.Deal_Registration_Extension_Request__c = 'Pending Meeting Ext. Req. for next 10 Days';
            
            deal3.Deal_Registration_Status__c = 'Expired';
            Test.startTest();
        		update dealList;
            try{
                DealRegistrationTriggerHelper cls = new DealRegistrationTriggerHelper();
                Lead newLead = cls.copyDealRegToLead(deal1, null);
            }catch(exception e){
                System.debug(LoggingLevel.DEBUG, 'error');
            }
        	Test.stopTest();
            System.assert(true);
        }
    }
    
    @isTest static void populateGSIDealRegTest(){
        User sysuser1 = TestDataFactory.getUser();
        User sysuser2  = [Select id from user where LastName = 'lastNameDRTest'];
        Test.setMock(HttpCalloutMock.class, new PC_DealRegL2AMatchTest('SUCCESS'));
        system.runas(sysuser1){
            Account acc1 = TestDataFactory.getAccount();
            acc1.name = 'Test New Account';
            acc1.Type = 'Partner';
            acc1.OwnerId = sysuser2.id;
            acc1.Focused_Partner__c = true;
            acc1.MSP_Sub_Type__c = 'GSI';
            acc1.RecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('Partner/Distributor').getRecordTypeId();
            insert acc1;
            Contact contact1 = new Contact(
                FirstName = 'Tes33232t',
                Lastname = 'McTes11123',
                AccountId = acc1.Id,
                Email = 'test@test9876541.com',
                Primary_Role__c = 'Admin'
            );
            insert contact1;

            CountryWithCode__c cc = new CountryWithCode__c(Code__c='US',Name='United States');
            insert cc;
            Opportunity opp = TestDataFactory.getOpportunity();
            insert opp;
            List<Deal_Registration__c> dealList = new List<Deal_Registration__c>();
            Deal_Registration__c deal1 = TestDataFactory.getDealRegistration();
            deal1.Deal_Registration_Status__c = 'Submitted';
            deal1.Partner_Lookup__c = acc1.id;
            deal1.RecordTypeId = Schema.SObjectType.Deal_Registration__c.getRecordTypeInfosByDeveloperName().get('Service_Delivery_Partner').getRecordTypeId();
            deal1.StateCode__c = '';
            deal1.Email__c = 'test@test9876541.com';
            deal1.Primary_Contact__c = contact1.Id;
            deal1.Deal_Reg_Exp_Date__c = Date.today().addDays(1);
            dealList.add(deal1);
            
            Test.startTest();
        		insert dealList;
        	Test.stopTest();
            System.assert(true);
        }
    }
    
    @isTest static void checkDRInfoUpdateTest(){
        User sysuser1 = TestDataFactory.getUser();
        User sysuser2  = [Select id from user where LastName = 'lastNameDRTest'];
        Test.setMock(HttpCalloutMock.class, new PC_DealRegL2AMatchTest('SUCCESS'));
        system.runas(sysuser1){
            Account acc1 = TestDataFactory.getAccount();
            acc1.name = 'Test New Account';
            acc1.Type = 'Partner';
            acc1.OwnerId = sysuser2.id;
            acc1.Focused_Partner__c = true;
            acc1.MSP_Sub_Type__c = 'GSI';
            acc1.RecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('Partner/Distributor').getRecordTypeId();
            insert acc1;
            
            Contact contact1 = new Contact(
                FirstName = 'Tes33232t',
                Lastname = 'McTes11123',
                AccountId = acc1.Id,
                Email = 'test@test9876541.com',
                Primary_Role__c = 'Admin'
            );
            insert contact1;
            CountryWithCode__c cc = new CountryWithCode__c(Code__c='US',Name='United States');
            insert cc;
            Opportunity opp = TestDataFactory.getOpportunity();
            insert opp;
            
            Lead existingLead = new Lead(
                LastName = 'Old Lead',
                Company = 'Old Company',
                Country = 'United States'
            );
            insert existingLead;
            
            List<Deal_Registration__c> dealList = new List<Deal_Registration__c>();
            Deal_Registration__c deal1 = TestDataFactory.getDealRegistration();
            deal1.Deal_Registration_Status__c = 'Submitted';
            deal1.Partner_Lookup__c = acc1.id;
            deal1.RecordTypeId = Schema.SObjectType.Deal_Registration__c.getRecordTypeInfosByDeveloperName().get('Service_Delivery_Partner').getRecordTypeId();
            deal1.StateCode__c = '';
            deal1.Email__c = 'test@test9876541.com';
            deal1.Primary_Contact__c = contact1.Id;
            deal1.Deal_Reg_Exp_Date__c = Date.today().addDays(1);
            deal1.Lead__c = existingLead.Id;
            dealList.add(deal1);
            insert dealList;
            Deal_Registration__c dealQueried = [SELECT ID,Name FROM Deal_Registration__c WHERE ID =: deal1.Id];
            
            Test.startTest();
            	flowControll.LeadTriggerHandler = false;
            	existingLead.Deal_Reg_Number__c = dealQueried.Name;
            	update existingLead;
            	flowControll.LeadTriggerHandler = true;
            	deal1.Deal_Reg_Exp_Date__c = Date.today().addDays(3);
            	update deal1;
            Test.stopTest();
            System.assert(true);
        }
    }
    
    @isTest static void addCustomerContactAsOppRoleTest(){
        User sysuser1 = TestDataFactory.getUser();
        User sysuser2  = [Select id from user where LastName = 'lastNameDRTest'];
        Test.setMock(HttpCalloutMock.class, new PC_DealRegL2AMatchTest('SUCCESS'));
        system.runas(sysuser1){
            Account acc1 = TestDataFactory.getAccount();
            acc1.name = 'Test New Account';
            acc1.Type = 'Partner';
            acc1.OwnerId = sysuser2.id;
            acc1.Focused_Partner__c = true;
            acc1.MSP_Sub_Type__c = 'GSI';
            acc1.RecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('Partner/Distributor').getRecordTypeId();
            insert acc1;
            Account acc2 = TestDataFactory.getAccount();
            acc2.name = 'Test New Account 2';
            acc2.Type = 'Partner';
            acc2.OwnerId = sysuser2.id;
            acc2.Focused_Partner__c = true;
            acc2.MSP_Sub_Type__c = 'GSI';
            acc2.RecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('Partner/Distributor').getRecordTypeId();
            insert acc2;
            List<Contact> conList = new List<Contact>();
            Contact contact1 = new Contact(
                FirstName = 'Tes33232t',
                Lastname = 'McTes11123',
                AccountId = acc1.Id,
                Email = 'test@test987654122.com',
                Primary_Role__c = 'Admin'
            );
            conList.add(contact1);
            Contact contact2 = new Contact(
                FirstName = 'Tes33232t',
                Lastname = 'McTes11123',
                AccountId = acc2.Id,
                Email = 'test@test987654122.com',
                Primary_Role__c = 'Admin'
            );
            conList.add(contact2);
            insert conList;
            CountryWithCode__c cc = new CountryWithCode__c(Code__c='US',Name='United States');
            insert cc;
            Opportunity opp = TestDataFactory.getOpportunity();
            insert opp;
            
            List<Deal_Registration__c> dealList = new List<Deal_Registration__c>();
            Deal_Registration__c deal1 = TestDataFactory.getDealRegistration();
            deal1.Deal_Registration_Status__c = 'Submitted';
            deal1.Partner_Lookup__c = acc1.id;
            deal1.Company_Name__c = acc1.Id;
            deal1.RecordTypeId = Schema.SObjectType.Deal_Registration__c.getRecordTypeInfosByName().get('Reseller').getRecordTypeId();
            deal1.StateCode__c = '';
            deal1.Email__c = 'test@test987654122.com';
            deal1.Primary_Contact__c = contact1.Id;
            deal1.Deal_Reg_Exp_Date__c = Date.today().addDays(1);
            deal1.Opportunity__c = opp.Id;
            dealList.add(deal1);
            insert dealList;
            Map<Id, Opportunity> oppMap = new Map<Id, Opportunity>();
            oppMap.put(opp.Id,opp);
            Test.startTest();
            try{
            DealRegistrationTriggerHelper.addCustomerContactAsOppRole(dealList, oppMap);
            }catch(exception e){
                System.debug(LoggingLevel.DEBUG, 'error');
            }
            Test.stopTest();
            System.assert(true);
        }
    }

    @isTest static void createCampaignMembersTest(){
        User sysuser1 = TestDataFactory.getUser();
        User sysuser2  = [Select id from user where LastName = 'lastNameDRTest'];
        Test.setMock(HttpCalloutMock.class, new PC_DealRegL2AMatchTest('SUCCESS'));
        system.runas(sysuser1){
            Account acc1 = TestDataFactory.getAccount();
            acc1.name = 'Test New Account';
            acc1.Type = 'Partner';
            acc1.OwnerId = sysuser2.id;
            acc1.Focused_Partner__c = true;
            acc1.MSP_Sub_Type__c = 'GSI';
            acc1.RecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('Partner/Distributor').getRecordTypeId();
            insert acc1;
            List<Contact> conList = new List<Contact>();
            Contact contact1 = new Contact(
                FirstName = 'Tes33232t',
                Lastname = 'McTes11123',
                AccountId = acc1.Id,
                Email = 'test@test987654122.com',
                Primary_Role__c = 'Admin'
            );
            conList.add(contact1);
            Contact contact2 = new Contact(
                FirstName = 'Tes33232t',
                Lastname = 'McTes11123',
                AccountId = acc1.Id,
                Email = 'test@test987654122.com',
                Primary_Role__c = 'Admin'
            );
            conList.add(contact2);
            insert conList;
            CountryWithCode__c cc = new CountryWithCode__c(Code__c='US',Name='United States');
            insert cc;
            Opportunity opp = TestDataFactory.getOpportunity();
            insert opp;
            
            Lead existingLead = new Lead(
                LastName = 'Old Lead',
                Company = 'Old Company',
                Country = 'United States'
            );
            insert existingLead;
            Lead existingLead1 = new Lead(
                LastName = 'Old Lead',
                Company = 'Old Company',
                Country = 'United States'
            );
            insert existingLead1;
            
            List<Deal_Registration__c> dealList = new List<Deal_Registration__c>();
            Deal_Registration__c deal1 = TestDataFactory.getDealRegistration();
            deal1.Deal_Registration_Status__c = 'Submitted';
            deal1.Partner_Lookup__c = acc1.id;
            deal1.Company_Name__c = acc1.Id;
            deal1.RecordTypeId = Schema.SObjectType.Deal_Registration__c.getRecordTypeInfosByName().get('Reseller').getRecordTypeId();
            deal1.StateCode__c = '';
            deal1.Email__c = 'test@test987654122.com';
            deal1.Primary_Contact__c = contact1.Id;
            deal1.Deal_Reg_Exp_Date__c = Date.today().addDays(1);
            deal1.Opportunity__c = opp.Id;
            deal1.Rubrik_Complete_Edition_Reg__c = true;
            dealList.add(deal1);

            Deal_Registration__c deal2 = TestDataFactory.getDealRegistration();
            deal2.Deal_Registration_Status__c = 'Submitted';
            deal2.Partner_Lookup__c = acc1.id;
            deal2.Company_Name__c = acc1.Id;
            deal2.RecordTypeId = Schema.SObjectType.Deal_Registration__c.getRecordTypeInfosByName().get('Reseller').getRecordTypeId();
            deal2.StateCode__c = '';
            deal2.Email__c = 'test@test987654122.com';
            deal2.Primary_Contact__c = contact1.Id;
            deal2.Deal_Reg_Exp_Date__c = Date.today().addDays(1);
            deal2.Opportunity__c = opp.Id;
            dealList.add(deal2);
            insert dealList;

            Map<Integer, Lead> successIndexToLeads = new Map<Integer, Lead>();
            successIndexToLeads.put(0,existingLead);
            successIndexToLeads.put(1,existingLead1);

             // Create a Campaign record - Rubrik Complete Campaign
            List<Campaign> campList = new List<Campaign>();
            Campaign testCampaign = new Campaign(
                Name = 'Partner Portal Deal Registration',
                Status = 'Planned',
                Type = 'Email',
                IsActive = true,
                StartDate = Date.today(),
                EndDate = Date.today().addDays(10),
                Campaign_Sales_Area__c ='AMER',
                Executed_By__c = 'Partner Marketing',
                Alliance_Partner__c = 'Amazon Web Services',
                Campaign_Sales_Region__c = 'AMER',
                Campaign_Theme__c = 'General',
                Campaign_Sales_Theatre__c = 'AMER',
                GTM_Play__c = 'General',
                Involvement_by_Customer_Marketing__c = 'No'
            );
            campList.add(testCampaign);
            Campaign testCampaign1 = new Campaign(
                Name = 'Rubrik Complete Campaign',
                Status = 'Planned',
                Type = 'Email',
                IsActive = true,
                StartDate = Date.today(),
                EndDate = Date.today().addDays(10),
                Campaign_Sales_Area__c ='AMER',
                Executed_By__c = 'Partner Marketing',
                Alliance_Partner__c = 'Amazon Web Services',
                Campaign_Sales_Region__c = 'AMER',
                Campaign_Theme__c = 'General',
                Campaign_Sales_Theatre__c = 'AMER',
                GTM_Play__c = 'General',
                Involvement_by_Customer_Marketing__c = 'No'
            );
            campList.add(testCampaign1);
            flowControll.CampaignTrigger = false;
            insert campList;
            flowControll.CampaignTrigger = true;
            ShGl_DisableBusinessLogic__c setting = new ShGl_DisableBusinessLogic__c(  // required for org-wide default
                Disable_Campaign_Member_Triggers__c = true
            );
            insert setting;

            List<CampaignMember> cMList = new List<CampaignMember>();
            CampaignMember member = new CampaignMember(
                CampaignId = testCampaign.Id,
                LeadId = existingLead.Id,
                Status = 'Planned'  // Optional, depends on org settings
            );
            cMList.add(member);
            CampaignMember member1 = new CampaignMember(
                CampaignId = testCampaign1.Id,
                LeadId = existingLead.Id,
                Status = 'Planned'  // Optional, depends on org settings
            );
            cMList.add(member1);
            insert cMList;
			//Start PRIT26-544
            /*Test.startTest();
            DealRegistrationTriggerHelper helper = new DealRegistrationTriggerHelper();
                helper.createCampaignMembers(successIndexToLeads,dealList);
            Test.stopTest();*/
            //End PRIT26-544
			System.assert(true);
        }
    }
    
    @isTest static void handleDuplicatesTest(){
        User sysuser1 = TestDataFactory.getUser();
        User sysuser2  = [Select id from user where LastName = 'lastNameDRTest'];
        Test.setMock(HttpCalloutMock.class, new PC_DealRegL2AMatchTest('SUCCESS'));
        system.runas(sysuser1){
            
            flowControll.DealRegistrationTrigger = false;
            flowControll.LeadTriggerHandler = false;
            flowControll.CampaignTrigger = false;
            
            Account acc1 = TestDataFactory.getAccount();
            acc1.name = 'Test New Account';
            acc1.Type = 'Partner';
            acc1.OwnerId = sysuser2.id;
            acc1.Focused_Partner__c = true;
            acc1.MSP_Sub_Type__c = 'GSI';
            acc1.RecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('Partner/Distributor').getRecordTypeId();
            insert acc1;
            Account acc2 = TestDataFactory.getAccount();
            acc2.name = 'Test New Account 2';
            acc2.Type = 'Partner';
            acc2.OwnerId = sysuser2.id;
            acc2.Focused_Partner__c = true;
            acc2.MSP_Sub_Type__c = 'GSI';
            acc2.RecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('Partner/Distributor').getRecordTypeId();
            insert acc2;
            List<Contact> conList = new List<Contact>();
            Contact contact1 = new Contact(
                FirstName = 'Tes33232t',
                Lastname = 'McTes11123',
                AccountId = acc1.Id,
                Email = 'test@test987654122.com',
                Primary_Role__c = 'Admin'
            );
            conList.add(contact1);
            Contact contact2 = new Contact(
                FirstName = 'Tes33232t',
                Lastname = 'McTes11123',
                AccountId = acc2.Id,
                Email = 'test@test987654122.com',
                Primary_Role__c = 'Admin'
            );
            conList.add(contact2);
            insert conList;
            CountryWithCode__c cc = new CountryWithCode__c(Code__c='US',Name='United States');
            insert cc;
            Opportunity opp = TestDataFactory.getOpportunity();
            insert opp;
            
            Lead existingLead = new Lead(
                LastName = 'Old Lead',
                Company = 'Old Company',
                Country = 'United States'
            );
            insert existingLead;
            
            List<Deal_Registration__c> dealList = new List<Deal_Registration__c>();
            Deal_Registration__c deal1 = TestDataFactory.getDealRegistration();
            deal1.Deal_Registration_Status__c = 'Submitted';
            deal1.Partner_Lookup__c = acc1.id;
            deal1.Company_Name__c = acc1.Id;
            deal1.RecordTypeId = Schema.SObjectType.Deal_Registration__c.getRecordTypeInfosByName().get('Reseller').getRecordTypeId();
            deal1.StateCode__c = '';
            deal1.Email__c = 'test@test987654122.com';
            deal1.Primary_Contact__c = contact1.Id;
            deal1.Deal_Reg_Exp_Date__c = Date.today().addDays(1);
            deal1.Opportunity__c = opp.Id;
            deal1.Lead__c = existingLead.Id;
            
            dealList.add(deal1);
            
            Deal_Registration__c deal2 = TestDataFactory.getDealRegistration();
            deal2.Deal_Registration_Status__c = 'Submitted';
            deal2.Partner_Lookup__c = acc1.id;
            deal2.Company_Name__c = acc1.Id;
            deal2.RecordTypeId = Schema.SObjectType.Deal_Registration__c.getRecordTypeInfosByName().get('Reseller').getRecordTypeId();
            deal2.StateCode__c = '';
            deal2.Email__c = 'test@test987654122.com';
            deal2.Primary_Contact__c = contact1.Id;
            deal2.Deal_Reg_Exp_Date__c = Date.today().addDays(1);
            deal2.Opportunity__c = opp.Id;
            dealList.add(deal2);
            
            insert dealList;
            Map<Integer, Set<Id>> mapLead = new Map<Integer, Set<Id>>();
            mapLead.put(1,new Set<Id>{existingLead.Id});
            Test.startTest();
            DealRegistrationTriggerHelper cls = new DealRegistrationTriggerHelper();
            cls.handleDuplicates(mapLead,new List<Lead>{existingLead}, dealList, new Map<Integer, Lead>());
            Test.stopTest();
            System.assert(true);
        }
    }
    
}