force-app/main/default/objects/Deal_Registration__c/Deal_Registration__c.object-meta.xml
<CustomObject>
    <description>SOX object - Object used for Deal Registrations by Partners</description>
    <label>Deal Registration</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Deal Registration #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Registration__c/fields/Days_Before_Expiration__c.field-meta.xml
<CustomField>
    <fullName>Days_Before_Expiration__c</fullName>
    <description>Provides number of days remained for deal expiry</description>
    <formula>Deal_Registration_Expiration__c -  TODAY()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Before Expiration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Deal_Registration_Extension_Request__c.field-meta.xml
<CustomField>
    <fullName>Deal_Registration_Extension_Request__c</fullName>
    <label>Deal Registration Extension Request</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Deal_Registration_Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Meeting Ext. Req. for next 10 Days</fullName>
            </value>
            <value>
                <fullName>1st Deal Reg Ext. Req. for next 10 Days</fullName>
                <isActive>false</isActive>
                <label>1st Deal Reg Ext. Req. for next 10 Days</label>
            </value>
            <value>
                <fullName>1st Deal Reg Ext. Req. for next 45 Days</fullName>
                <isActive>false</isActive>
                <label>1st Deal Reg Ext. Req. for next 45 Days</label>
            </value>
            <value>
                <fullName>1st Meeting Ext. Req. for next 10 Days</fullName>
                <isActive>false</isActive>
                <label>1st Meeting Ext. Req. for next 10 Days</label>
            </value>
            <value>
                <fullName>2nd Deal Reg Ext. Req. for next 10 Days</fullName>
                <isActive>false</isActive>
                <label>2nd Deal Reg Ext. Req. for next 10 Days</label>
            </value>
            <value>
                <fullName>2nd Deal Reg Ext. Req. for next 45 Days</fullName>
                <isActive>false</isActive>
                <label>2nd Deal Reg Ext. Req. for next 45 Days</label>
            </value>
            <value>
                <fullName>2nd Meeting Ext. Req. for next 10 Days</fullName>
                <isActive>false</isActive>
                <label>2nd Meeting Ext. Req. for next 10 Days</label>
            </value>
            <value>
                <fullName>3rd Deal Reg Ext. Req. for next 45 Days</fullName>
                <isActive>false</isActive>
                <label>3rd Deal Reg Ext. Req. for next 45 Days</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Deal_Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Deal_Registration_Status__c</fullName>
    <label>Deal Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Pending Conversion</fullName>
            </value>
            <value>
                <fullName>Pending Meeting</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Deal_Registration_Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Deal_Registration_Sub_Status__c</fullName>
    <label>Deal Registration Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Extension Requested</fullName>
            </value>
            <value>
                <fullName>Extension Approved</fullName>
            </value>
            <value>
                <fullName>Extension Rejected</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Closed Admin</fullName>
            </value>
            <value>
                <fullName>Pending Artifact Upload</fullName>
            </value>
            <value>
                <fullName>Pending RSM Approval</fullName>
            </value>
            <value>
                <fullName>Pending L1 Approval</fullName>
            </value>
            <value>
                <fullName>Pending TVP Approval</fullName>
            </value>
            <value>
                <fullName>RSM Approved</fullName>
            </value>
            <value>
                <fullName>RSM Rejected</fullName>
            </value>
            <value>
                <fullName>Pending RVP Approval</fullName>
            </value>
            <value>
                <fullName>RVP Approved</fullName>
            </value>
            <value>
                <fullName>RVP Rejected</fullName>
            </value>
            <value>
                <fullName>GSI-NDA Pending Approval</fullName>
            </value>
            <value>
                <fullName>Auto - Expired</fullName>
                <isActive>false</isActive>
                <label>Auto - Expired</label>
            </value>
            <value>
                <fullName>SLA Violation</fullName>
                <isActive>false</isActive>
                <label>SLA Violation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity linked to Deal Reg</description>
    <label>Opportunity</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Please enter open opportunity name without an approved deal registration</errorMessage>
        <filterItems>
            <field>Opportunity.StageName</field>
            <operation>notEqual</operation>
            <value>7 Closed Won, 7 Closed Lost</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Registrations</relationshipLabel>
    <relationshipName>Deal_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Requested_for_Extension__c.field-meta.xml
<CustomField>
    <fullName>Requested_for_Extension__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requested for Extension</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PC_DealRegExtnReqController.cls
public without sharing class PC_DealRegExtnReqController {

    @AuraEnabled
    public static Deal_Registration__c getStatus(string dealRegId){
        string status = '';
        Deal_Registration__c dealreg = new Deal_Registration__c();
        
        //PRIT25-484
        if(!string.isBlank(dealRegId)){
        	dealreg = [select Id,Deal_Registration_Status__c,Days_Before_Expiration__c from Deal_Registration__c where Id =: dealRegId LIMIT 1];
        }
        return dealreg;
    }
    
     @AuraEnabled
    public static string setExtension(string dealRegId){
        string message = '';
        List<Deal_Registration__c> dealregList = new List<Deal_Registration__c>();
        if(!string.isBlank(dealRegId)){
        	dealregList = [select Id,Deal_Registration_Status__c,Requested_for_Extension__c,Deal_Registration_Extension_Request__c,Opportunity__c from Deal_Registration__c where Id =: dealRegId];
            if(!dealregList.isEmpty() && dealregList[0].Requested_for_Extension__c == true){
             	message = 'Deal Registration is already Requested for Extension';  
            }
            if(!dealregList.isEmpty() && dealregList[0].Requested_for_Extension__c == false && (/*dealregList[0].Deal_Registration_Extension_Request__c != '3rd Deal Reg Ext. Req. for next 45 Days' &&*/ dealregList[0].Deal_Registration_Extension_Request__c != 'Pending Meeting Ext. Req. for next 10 Days' && ((String.isNotBlank(dealregList[0].Opportunity__c) && (dealregList[0].Deal_Registration_Status__c == 'Expired' || dealregList[0].Deal_Registration_Status__c == 'Approved')) || (dealregList[0].Deal_Registration_Status__c == 'Pending Meeting')))){
                
                dealregList[0].Requested_for_Extension__c = true;
                dealregList[0].Deal_Registration_Sub_Status__c = 'Extension Requested';
                try{
                    update dealregList;
                    message = 'Deal Registration is successfully Requested for Extension';  
                }catch(Exception e){
                    message = e.getMessage();
                }
            }else if(!dealregList.isEmpty() && dealregList[0].Requested_for_Extension__c == false && (/*dealregList[0].Deal_Registration_Extension_Request__c == '3rd Deal Reg Ext. Req. for next 45 Days' ||*/ dealregList[0].Deal_Registration_Extension_Request__c == 'Pending Meeting Ext. Req. for next 10 Days' || (dealregList[0].Deal_Registration_Status__c == 'Expired' && String.isBlank(dealregList[0].Opportunity__c)))){
                    message = 'This Deal Registration cannot be further Extended';  
            }
        }
        return message;
    }

}