force-app/main/default/objects/Deal_Registration__c/Deal_Registration__c.object-meta.xml
<CustomObject>
    <description>SOX object - Object used for Deal Registrations by Partners</description>
    <label>Deal Registration</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Deal Registration #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Registration__c/fields/Alliance_Type__c.field-meta.xml
<CustomField>
    <fullName>Alliance_Type__c</fullName>
    <label>Alliance Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cloud</fullName>
            </value>
            <value>
                <fullName>Security</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Approval_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Approval_Timestamp__c</fullName>
    <label>Status Change Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/CDM__c.field-meta.xml
<CustomField>
    <fullName>CDM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CDM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Deal_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deal Registrations (Company Name)</relationshipLabel>
    <relationshipName>Deal_Registrations4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Deal_Reg_Exp_Date__c.field-meta.xml
<CustomField>
    <fullName>Deal_Reg_Exp_Date__c</fullName>
    <label>Deal Reg Exp Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Deal_Reg_Submitted_Date__c.field-meta.xml
<CustomField>
    <fullName>Deal_Reg_Submitted_Date__c</fullName>
    <label>Deal Reg Submitted Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Deal_Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Deal_Registration_Status__c</fullName>
    <label>Deal Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Pending Conversion</fullName>
            </value>
            <value>
                <fullName>Pending Meeting</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Deal_Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Registration_Type__c</fullName>
    <label>Deal Initiated Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Partner Sourced New Logo (PSNL)</fullName>
            </value>
            <value>
                <fullName>Partner Sourced Expand</fullName>
            </value>
            <value>
                <fullName>Rubrik Sourced</fullName>
            </value>
            <value>
                <fullName>Joint Initiated Deal</fullName>
                <isActive>false</isActive>
                <label>Joint Initiated Deal</label>
            </value>
            <value>
                <fullName>Partner Initiated Deal</fullName>
                <isActive>false</isActive>
                <label>Partner Initiated Deal</label>
            </value>
            <value>
                <fullName>Rubrik Initiated Deal</fullName>
                <isActive>false</isActive>
                <label>Rubrik Initiated Deal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Dedicated_Managed_Service__c.field-meta.xml
<CustomField>
    <fullName>Dedicated_Managed_Service__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dedicated Managed Service</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deal Registrations (Distributor)</relationshipLabel>
    <relationshipName>Deal_Registrations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/GSI_NDA__c.field-meta.xml
<CustomField>
    <fullName>GSI_NDA__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Applicable for Internal Deal Registration</description>
    <label>GSI - NDA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Deal Registrations</relationshipLabel>
    <relationshipName>Deal_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Lead_Share_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Lead_Share_Campaign__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PRIT24-356</description>
    <label>Lead Share Campaign</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/OEM_SubType__c.field-meta.xml
<CustomField>
    <fullName>OEM_SubType__c</fullName>
    <formula>TEXT( Distributor__r.OEM_Subtype__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OEM SubType</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity linked to Deal Reg</description>
    <label>Opportunity</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Please enter open opportunity name without an approved deal registration</errorMessage>
        <filterItems>
            <field>Opportunity.StageName</field>
            <operation>notEqual</operation>
            <value>7 Closed Won, 7 Closed Lost</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Registrations</relationshipLabel>
    <relationshipName>Deal_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Partner_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Partner_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Lookup</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partner/Distributor</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deal Registrations</relationshipLabel>
    <relationshipName>Deal_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Partner_Rep__c.field-meta.xml
<CustomField>
    <fullName>Partner_Rep__c</fullName>
    <label>Partner Sales Rep Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Partner_Rep_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Partner_Rep_Email_Address__c</fullName>
    <label>Partner Rep Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Partner_Rep_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Partner_Rep_Phone_Number__c</fullName>
    <label>Partner Rep Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/PatchManager__c.field-meta.xml
<CustomField>
    <fullName>PatchManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PatchManager</label>
    <referenceTo>PatchManager__c</referenceTo>
    <relationshipLabel>Deal Registrations</relationshipLabel>
    <relationshipName>Deal_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Deal Registrations (Primary Contact)</relationshipLabel>
    <relationshipName>Deal_Registrations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Primary_Deal_Registration__c.field-meta.xml
<CustomField>
    <fullName>Primary_Deal_Registration__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To be checked when DR is the primary deal on the opportunity</description>
    <label>Primary Deal Registration</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Purchase_Timeframe__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Timeframe__c</fullName>
    <label>(DEPRECATED) Timeframe</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0-3 Months</fullName>
            </value>
            <value>
                <fullName>3-6 Months</fullName>
            </value>
            <value>
                <fullName>6-12 Months</fullName>
            </value>
            <value>
                <fullName>&gt;12 Months</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Requested_for_Extension__c.field-meta.xml
<CustomField>
    <fullName>Requested_for_Extension__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requested for Extension</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/rerun_PatchManager_Assignments__c.field-meta.xml
<CustomField>
    <fullName>rerun_PatchManager_Assignments__c</fullName>
    <defaultValue>false</defaultValue>
    <label>rerun PatchManager Assignments</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Rubrik_Complete_Edition_Reg__c.field-meta.xml
<CustomField>
    <fullName>Rubrik_Complete_Edition_Reg__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DEP Rubrik Complete Edition Registration</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Secondary_Email_for_Deal_Reg__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Email_for_Deal_Reg__c</fullName>
    <label>Secondary Email for Deal Reg</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/skipValidation__c.field-meta.xml
<CustomField>
    <fullName>skipValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>skipValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/StateCode__c.field-meta.xml
<CustomField>
    <fullName>StateCode__c</fullName>
    <label>StateCode</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>State_Province</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/recordTypes/Alliance.recordType-meta.xml
<RecordType>
    <fullName>Alliance</fullName>
    <active>true</active>
    <label>Alliance</label>
</RecordType>

force-app/main/default/objects/Deal_Registration__c/recordTypes/Engagement.recordType-meta.xml
<RecordType>
    <fullName>Engagement</fullName>
    <active>true</active>
    <label>Engagement</label>
</RecordType>

force-app/main/default/objects/Deal_Registration__c/recordTypes/OEM.recordType-meta.xml
<RecordType>
    <fullName>OEM</fullName>
    <active>true</active>
    <label>OEM</label>
</RecordType>

force-app/main/default/objects/PatchManager__c/PatchManager__c.object-meta.xml
<CustomObject>
    <label>PatchManager</label>
    <nameField>
        <displayFormat>PM-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PatchManagers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PatchManager__c/fields/CDM__c.field-meta.xml
<CustomField>
    <fullName>CDM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CDM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PatchManagers1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PatchManager__c/recordTypes/Geographic.recordType-meta.xml
<RecordType>
    <fullName>Geographic</fullName>
    <active>true</active>
    <label>Geographic</label>
</RecordType>

force-app/main/default/classes/DealRegistrationTriggerTest.cls
/**
 * @description       : Test Class of DealRegistrationTrigger
 * @author            : Harshit Garg
 * @group             : 
 * @last modified on  : 02-17-2026
 * @last modified by  : Harshit Garg
**/
@isTest(SeeAllData=false) 
public with sharing class DealRegistrationTriggerTest {

	/**
     * @description setup method to create data
     */
    @TestSetup
    static void setupTestData(){

		List<User> users = PartnerTestDataUtility.createUsers(2, 'System Administrator', null);
		insert users;

		List<Territory2Model> territoryModels = [SELECT Id, Name FROM Territory2Model WHERE State = 'Active' LIMIT 1];
        List<Territory2Type> territoryTypes = [SELECT Id, DeveloperName FROM Territory2Type WHERE DeveloperName = 'Territory' LIMIT 1];

		if (!territoryModels.isEmpty() && !territoryTypes.isEmpty()) {
			
			List<Territory2> territories = PartnerTestDataUtility.createTerritories(1, territoryModels[0].Id, territoryTypes[0].Id, null);
			insert territories;
			
			List<UserTerritory2Association> associations = PartnerTestDataUtility.createUserTerritoryAssociations(1, Label.AccountExecRoleName, territories[0].Id, users[1].Id, null);
			associations.addAll(PartnerTestDataUtility.createUserTerritoryAssociations(1, 'SDR', territories[0].Id, users[0].Id, null));
			insert associations;
        }
		
		System.runAs(users[0]) {

			List<WorkflowTriggerBypass__c> wtList = new List<WorkflowTriggerBypass__c>();
			wtList.addAll(PartnerTestDataUtility.createWorkflowTriggerBypass(1, 'leadReassignOnBusinessUnitChange', false, null));
			wtList.addAll(PartnerTestDataUtility.createWorkflowTriggerBypass(1, 'cnsFirstAttemptUpdateLeadStatus', false, null));
			wtList.addAll(PartnerTestDataUtility.createWorkflowTriggerBypass(1, 'CreateSDRLedMeetingTask', false, null));
			wtList.addAll(PartnerTestDataUtility.createWorkflowTriggerBypass(1, 'updateLastOwnershipUpdateDate', false, null));
			wtList.addAll(PartnerTestDataUtility.createWorkflowTriggerBypass(1, 'updateOpportunitySource', false, null));
			wtList.addAll(PartnerTestDataUtility.createWorkflowTriggerBypass(1, 'salesOperationsAssignAccountSIC', false, null));
			wtList.addAll(PartnerTestDataUtility.createWorkflowTriggerBypass(1, 'salesOperationsSetEUResident', false, null));
			insert wtList;

			List<CountryWithCode__c> countryCodes = PartnerTestDataUtility.createCountryWithCode(1,'US','United States',null);
			insert countryCodes;

			List<CodeWithCountry__c> codeCountries = new List<CodeWithCountry__c>();
			codeCountries.addAll(PartnerTestDataUtility.createCodeWithCountry(1,'US','United States',null));
			codeCountries.addAll(PartnerTestDataUtility.createCodeWithCountry(1,'GB','United Kingdom',null));
			insert codeCountries;

			List<DealregLeadMapping__c> drmapping = new List<DealregLeadMapping__c>();
			drmapping.addAll(PartnerTestDataUtility.createDealRegLeadMapping(1,'Country__c','Country',null));
			drmapping.addAll(PartnerTestDataUtility.createDealRegLeadMapping(1,'LastName__c','LastName',null));
			drmapping.addAll(PartnerTestDataUtility.createDealRegLeadMapping(1,'Company__c','Company',null));
			drmapping.addAll(PartnerTestDataUtility.createDealRegLeadMapping(1,'Email__c','Email',null));
			insert drmapping;
			
			List<PatchManager__c> patchMgrs = PartnerTestDataUtility.createPatchManagers(1, 'Geographic', users[0].Id, null);
			insert patchMgrs;
			
			List<Account> accounts = new List<Account>();
			Map<String, Object> accountFields = new Map<String, Object>();
			accountFields.put('Name', 'Customer Account');
			accounts.addAll(PartnerTestDataUtility.createAccounts(1, null, 'Customer/Prospect', accountFields));
			accountFields.put('Name', 'Distributor Account');
			accountFields.put('Type','OEM');
			accountFields.put('OEM_Subtype__c','Revshare');
			accounts.addAll(PartnerTestDataUtility.createAccounts(1, null, 'Partner/Distributor', accountFields));
			insert accounts;

			List<Contact> contacts = new List<Contact>();
			Map<String, Object> contactFields = new Map<String, Object>();
			contactFields.put('Email', 'Test_alliance@redsky.com.sandbox');
			contactFields.put('LeadSource', 'Email');
			contacts.addAll(PartnerTestDataUtility.createContacts(1, accounts[0].Id, contactFields));
			
			contactFields.put('Email', 'Test_sd@redsky.com.sandbox');
			contacts.addAll(PartnerTestDataUtility.createContacts(1, accounts[0].Id, contactFields));

			contactFields.put('Email', 'Test_oem@redsky.com.sandbox');
			contacts.addAll(PartnerTestDataUtility.createContacts(1, accounts[0].Id, contactFields));

			contactFields.put('Email', 'Test_eng@redsky.com.sandbox');
			contacts.addAll(PartnerTestDataUtility.createContacts(1, accounts[0].Id, contactFields));
			insert contacts;
			
			Map<String, Object> oppFields = new Map<String, Object>{
												  'Amount' => 3000,
												  'Type' => 'New Customer',
												  'Lead_Email_Hidden__c' => contacts[0].Email,
												  'Initial_Contacts_Name__c' => contacts[0].Id,
												  'Deal_Registration_Type__c' => 'Rubrik Sourced'
												};
			List<Opportunity> opps = PartnerTestDataUtility.createOpportunities(1, null, accounts[0].Id, oppFields);
			insert opps;

			List<Deal_Registration__c> dealRegReqs = new List<Deal_Registration__c>();
			Map<String, Object> dealRegFields = new Map<String, Object>();
			dealRegFields.put('Email__c', 'Test_alliance@redsky.com.sandbox');
			dealRegFields.put('Primary__c', true);
			dealRegFields.put('Deal_Reg_Submitted_Date__c', System.now());
			dealRegFields.put('Rubrik_Complete_Edition_Reg__c', true);
			dealRegFields.put('OwnerId', users[1].Id);
			dealRegFields.put('CDM__c', users[1].Id);
			dealRegFields.put('Lead_Share_Campaign__c', false);
			dealRegFields.put('Partner_Lookup__c', accounts[0].Id);
			dealRegReqs.addAll(PartnerTestDataUtility.createDealRegistrations(1,'Alliance','Submitted',dealRegFields));
		
			dealRegFields.put('Email__c', 'Test_dist@redsky.com.sandbox');
			dealRegFields.put('Primary__c', false);
			dealRegFields.put('Rubrik_Complete_Edition_Reg__c', false);
			dealRegFields.put('OwnerId', users[0].Id);
			dealRegFields.put('CDM__c', null);
			dealRegFields.put('Lead_Share_Campaign__c', true);
			dealRegFields.put('Partner_Lookup__c', accounts[1].Id);
			dealRegFields.put('Dedicated_Managed_Service__c', true);
			dealRegReqs.addAll(PartnerTestDataUtility.createDealRegistrations(1,'Reseller','Submitted',dealRegFields));

			dealRegFields.put('Email__c', 'Test_dist_1@redsky.com.sandbox');
			dealRegReqs.addAll(PartnerTestDataUtility.createDealRegistrations(1,'Reseller','Submitted',dealRegFields));

			dealRegFields.put('Email__c', 'Test_sd@redsky.com.sandbox');
			dealRegFields.put('Primary__c', true);
			dealRegFields.put('Rubrik_Complete_Edition_Reg__c', true);
			dealRegFields.put('OwnerId', users[1].Id);
			dealRegFields.put('CDM__c', users[1].Id);
			dealRegFields.put('Lead_Share_Campaign__c', false);
			dealRegFields.put('Partner_Lookup__c', accounts[0].Id);
			dealRegFields.put('GSI_NDA__c', true);
			dealRegReqs.addAll(PartnerTestDataUtility.createDealRegistrations(1,'Internal','Submitted',dealRegFields));

			dealRegFields.put('Email__c', 'Test_oem@redsky.com.sandbox');
			dealRegFields.put('OwnerId', users[0].Id);
			dealRegFields.put('Distributor__c', accounts[1].Id);
			dealRegReqs.addAll(PartnerTestDataUtility.createDealRegistrations(1,'OEM','Submitted',dealRegFields));

			dealRegFields.put('Email__c', 'Test_eng@redsky.com.sandbox');
			dealRegReqs.addAll(PartnerTestDataUtility.createDealRegistrations(1,'Engagement','Submitted',dealRegFields));

			dealRegFields.put('Email__c', 'Test_oem_2@redsky.com.sandbox');
			dealRegReqs.addAll(PartnerTestDataUtility.createDealRegistrations(1,'OEM','Submitted',dealRegFields));

			dealRegFields.put('Email__c', 'Test_oem_3@redsky.com.sandbox');
			dealRegReqs.addAll(PartnerTestDataUtility.createDealRegistrations(1,'OEM','Submitted',dealRegFields));

			dealRegFields.put('Email__c', 'Test_alliance_3@redsky.com.sandbox');
			dealRegFields.put('Alliance_Type__c','Cloud');
			dealRegReqs.addAll(PartnerTestDataUtility.createDealRegistrations(1,'Alliance','Submitted',dealRegFields));

			dealRegFields = new Map<String, Object>();
			dealRegFields.put('Email__c', 'Test_alliance_2@redsky.com.sandbox');
			dealRegFields.put('Primary_Contact__c', contacts[0].Id);
			dealRegFields.put('Company_Name__c', accounts[0].Id);
			dealRegFields.put('Partner_Lookup__c', accounts[0].Id);
			dealRegFields.put('StateCode__c', null);
			dealRegFields.put('Alliance_Type__c','Cloud');
			dealRegReqs.addAll(PartnerTestDataUtility.createDealRegistrations(1,'Alliance','Submitted',dealRegFields));

			insert dealRegReqs;

			List<Lead> leads = new List<Lead>();
			Map<String, Object> leadFields = new Map<String, Object>{
												  'FirstName' => 'Dist',
												  'LastName' => 'Test',
												  'Company' => 'Dist Company',
												  'Email' => 'Test_dist@redsky.com.sandbox',
												  'Purchase_Timeframe__c' => 'N/A',
												  'Street' => 'Street',
												  'StateCode' => 'AK',
												  'PostalCode' => '421302',
												  'City' => 'City',
												  'CountryCode' => 'US',
												  'SDR_Led__c' => true,
												  'Partner__c' => 'Rubrik',
												  'Partner_Rep__c' => 'Rep Name',
												  'Partner_Rep_Phone_Number__c' => '1234567890',
												  'Partner_Rep_Email_Address__c' => 'partner@redsky.com.sandbox',
												  'Secondary_Email_for_Deal_Reg__c' => 'partner@redsky.com.sandbox'
												};
			leads.addAll(PartnerTestDataUtility.createLeads(1, null, leadFields));

			leadFields = new Map<String, Object>{
												  'FirstName' => 'OEM',
												  'LastName' => 'Test',
												  'Company' => 'OEM Company',
												  'Email' => 'Test_oem_2@redsky.com.sandbox',
												  'Purchase_Timeframe__c' => 'N/A',
												  'Street' => 'Street',
												  'StateCode' => 'AK',
												  'PostalCode' => '421302',
												  'City' => 'City',
												  'CountryCode' => 'US'
												};
			leads.addAll(PartnerTestDataUtility.createLeads(1, null, leadFields));
			insert leads;
		}
	}
	
	@isTest static void testMethod1() {
		
		User testUser = [SELECT Id FROM User WHERE Email = 'testuser0@example.com.sandbox' LIMIT 1];
		
		System.runAs(testUser) {
			
			Test.startTest();
			
			Deal_Registration__c dealReg = [SELECT Id, Name FROM Deal_Registration__c WHERE Email__c = 'Test_dist@redsky.com.sandbox' LIMIT 1];
			dealReg.OwnerId = testUser.id;
            update dealReg;
			
			TriggerManager.resetTriggerCounter('Deal_Registration__c');
			
			Lead l1 = [SELECT Id FROM Lead LIMIT 1];
			
			dealReg.Lead__c = l1.Id;
            dealReg.Deal_Registration_Status__c = 'Pending Meeting';
            update dealReg;
			
			l1.Deal_Registration__c = true;
            l1.Deal_Reg_Number__c = dealReg.Name;
            l1.Deal_Reg_Approval_Status__c = 'Pending Meeting';
            update l1;
			
			Database.LeadConvert lc = new database.LeadConvert();  
            lc.setLeadId( l1.Id );  
            lc.setDoNotCreateOpportunity( true );  
            lc.setConvertedStatus( 'Closed - Converted' );  
            Database.LeadConvertResult lcr = Database.convertLead(lc, false);
			
			dealReg.Deal_Registration_Status__c = 'Approved';
            dealReg.OwnerId = testUser.Id;
            dealReg.Approval_Timestamp__c = System.now();
            dealReg.Deal_Reg_Exp_Date__c  = System.today().addDays(29);
            dealReg.Primary__c = true;
            dealReg.Lead__c = null;
            update dealReg;

            Test.stopTest();

            System.assertEquals('Approved', dealReg.Deal_Registration_Status__c,
                'Deal Registration Status should be Approved');
        }
    }
	
	
	@isTest static void testMethod2() {
        User testUser = [SELECT Id FROM User WHERE Email = 'testuser0@example.com.sandbox' LIMIT 1];
		
		System.runAs(testUser) {
            Test.startTest();

			User recCDM = [SELECT Id FROM User WHERE Email = 'testuser1@example.com.sandbox' LIMIT 1];
			Lead objLead = [SELECT Id FROM Lead LIMIT 1];
			Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
            Deal_Registration__c dealReg = [SELECT Id, Name FROM Deal_Registration__c WHERE Email__c = 'Test_dist@redsky.com.sandbox' LIMIT 1];
			
			objLead.Deal_Registration__c = true;
            objLead.Deal_Reg_Number__c = dealReg.Name;
            objLead.Deal_Reg_Approval_Status__c = 'Pending Meeting';
            update objLead;
			
            dealReg.Primary__c = false;
            dealReg.Deal_Reg_Submitted_Date__c = System.now();
            dealReg.Deal_Registration_Status__c = 'Approved';
            dealReg.OwnerId = recCDM.Id;
            dealReg.CDM__c = recCDM.Id;
            dealReg.Requested_for_Extension__c = true;
            dealReg.Deal_Reg_Exp_Date__c  = System.today().addDays(29);
            dealReg.Lead__c = objLead.Id;
            dealReg.Opportunity__c = opp.Id;
            dealReg.Primary_Deal_Registration__c = true;
            update dealReg;
			

            dealReg.rerun_PatchManager_Assignments__c=true;
            dealReg.OwnerId = testUser.Id;
            dealReg.skipValidation__c = false;
            dealReg.Approval_Timestamp__c = System.now();
            dealReg.Requested_for_Extension__c = true;
            dealReg.Rubrik_Complete_Edition_Reg__c = false;
			dealReg.Deal_Registration_Sub_Status__c = 'Extension Approved';
            dealReg.isConverted__c = true;
			update dealReg;
			
			dealReg.Deal_Registration_Status__c = 'Pending Meeting';
			update dealReg;
			
			dealReg.Deal_Registration_Extension_Request__c = 'Pending Meeting Ext. Req. for next 10 Days';
			update dealReg;
			
			Test.stopTest();
			
			System.assertEquals('Pending Meeting', dealReg.Deal_Registration_Status__c,
                'Deal Registration Status should be Pending Meeting');
        }
    }
	
	@isTest static void testMethod3() {
        User testUser = [SELECT Id FROM User WHERE Email = 'testuser0@example.com.sandbox' LIMIT 1];
		
		System.runAs(testUser) {
            Test.startTest();
			
			Deal_Registration__c dealReg = [SELECT Id, Name FROM Deal_Registration__c WHERE Email__c = 'Test_dist_1@redsky.com.sandbox' LIMIT 1];
			
			dealReg.Deal_Registration_Status__c = 'Pending Conversion';
			update dealReg;
		
			Test.stopTest();
			
			System.assertEquals('Pending Conversion', dealReg.Deal_Registration_Status__c,
                'Deal Registration Status should be Pending Conversion');
        }
    }
	
	@isTest static void testMethod4() {
        User testUser = [SELECT Id FROM User WHERE Email = 'testuser0@example.com.sandbox' LIMIT 1];
		
		System.runAs(testUser) {
            Test.startTest();
			
			Deal_Registration__c dealReg = [SELECT Id, Name FROM Deal_Registration__c WHERE Email__c = 'Test_dist@redsky.com.sandbox' LIMIT 1];
			
			Lead objLead = [SELECT Id FROM Lead LIMIT 1];
			
			dealReg.Deal_Registration_Status__c = 'Pending Conversion';
			dealReg.Lead__c = objLead.Id;
			dealReg.Lead_Share_Campaign__c = true;
			dealReg.Deal_Reg_Exp_Date__c  = System.today().addDays(29);
			update dealReg;
			
			Test.stopTest();
			
			System.assertEquals('Pending Conversion', dealReg.Deal_Registration_Status__c,
                'Deal Registration Status should be Pending Conversion');
        }
    }
	
	@isTest static void testAllianceReqApproved() {
        User testUser = [SELECT Id FROM User WHERE Email = 'testuser0@example.com.sandbox' LIMIT 1];
		
		System.runAs(testUser) {
            Test.startTest();
			
			Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
			Deal_Registration__c dealReg = [SELECT Id, Name FROM Deal_Registration__c WHERE Email__c = 'Test_alliance@redsky.com.sandbox' LIMIT 1];
			
			Contact con = [SELECT Id FROM Contact WHERE Email = 'Test_alliance@redsky.com.sandbox' LIMIT 1];
			
			dealReg.Deal_Registration_Status__c = 'Approved';
			dealReg.Opportunity__c = opp.Id;
			dealReg.Primary_Contact__c = con.Id;
			update dealReg;
			
			Test.stopTest();
			
			System.assertEquals('Approved', dealReg.Deal_Registration_Status__c,
                'Deal Registration Status should be Approved');
        }
    }
	
	@isTest static void testSDReqApproved() {
        User testUser = [SELECT Id FROM User WHERE Email = 'testuser0@example.com.sandbox' LIMIT 1];
		
		System.runAs(testUser) {
            Test.startTest();
			
			Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
			Deal_Registration__c dealReg = [SELECT Id, Name FROM Deal_Registration__c WHERE Email__c = 'Test_sd@redsky.com.sandbox' LIMIT 1];
			
			Contact con = [SELECT Id FROM Contact WHERE Email = 'Test_sd@redsky.com.sandbox' LIMIT 1];
			
			dealReg.Deal_Registration_Status__c = 'Approved';
			dealReg.Opportunity__c = opp.Id;
			dealReg.Primary_Contact__c = con.Id;
			update dealReg;
			
			Test.stopTest();
			
			System.assertEquals('Approved', dealReg.Deal_Registration_Status__c,
                'Deal Registration Status should be Approved');
        }
    }
	
	@isTest static void testOEMReqApproved() {
        User testUser = [SELECT Id FROM User WHERE Email = 'testuser0@example.com.sandbox' LIMIT 1];
		
		System.runAs(testUser) {
            Test.startTest();
			
			Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
			Deal_Registration__c dealReg = [SELECT Id, Name FROM Deal_Registration__c WHERE Email__c = 'Test_oem@redsky.com.sandbox' LIMIT 1];
			
			Contact con = [SELECT Id, AccountId FROM Contact WHERE Email = 'Test_oem@redsky.com.sandbox' LIMIT 1];
			
            dealReg.Company_Name__c = con.AccountId;
			update dealReg;
			
            dealReg.Deal_Registration_Status__c = 'Approved';
			dealReg.Opportunity__c = opp.Id;
			dealReg.Primary_Contact__c = con.Id;
			dealReg.Company_Name__c = con.AccountId;
			update dealReg;
			
			Test.stopTest();
			
			System.assertEquals('Approved', dealReg.Deal_Registration_Status__c,
                'Deal Registration Status should be Approved');
        }
    }

    @isTest static void testOEMWithLeadReqApproved() {
        User testUser = [SELECT Id FROM User WHERE Email = 'testuser0@example.com.sandbox' LIMIT 1];
		
		System.runAs(testUser) {
            Test.startTest();
			
			Opportunity opp = [SELECT Id, AccountId FROM Opportunity LIMIT 1];
			Deal_Registration__c dealReg = [SELECT Id, Name FROM Deal_Registration__c WHERE Email__c = 'Test_oem_2@redsky.com.sandbox' LIMIT 1];
			
			Lead leadObj = [SELECT Id FROM Lead WHERE Email = 'Test_oem_2@redsky.com.sandbox' LIMIT 1];
			leadObj.Status = 'Open';
			update leadObj;
			
			dealReg.Company_Name__c = opp.AccountId;
			update dealReg;
            
			dealReg.Deal_Registration_Status__c = 'Approved';
			dealReg.Opportunity__c = opp.Id;
			dealReg.Company_Name__c = opp.AccountId;
			update dealReg;
			
			Test.stopTest();
			
			System.assertEquals('Approved', dealReg.Deal_Registration_Status__c,
                'Deal Registration Status should be Approved');
        }
    }

	@isTest static void testOEMWithNewConReqApproved() {
        User testUser = [SELECT Id FROM User WHERE Email = 'testuser0@example.com.sandbox' LIMIT 1];
		
		System.runAs(testUser) {
            Test.startTest();
			
			Opportunity opp = [SELECT Id, AccountId FROM Opportunity LIMIT 1];
			Deal_Registration__c dealReg = [SELECT Id, Name FROM Deal_Registration__c WHERE Email__c = 'Test_oem_3@redsky.com.sandbox' LIMIT 1];
			
			dealReg.Company_Name__c = opp.AccountId;
			update dealReg;
            
			dealReg.Deal_Registration_Status__c = 'Approved';
			dealReg.Opportunity__c = opp.Id;
			dealReg.Company_Name__c = opp.AccountId;
			update dealReg;
			
			Test.stopTest();
			
			System.assertEquals('Approved', dealReg.Deal_Registration_Status__c,
                'Deal Registration Status should be Approved');
        }
    }
	
	@isTest static void testEngReqApproved() {
        User testUser = [SELECT Id FROM User WHERE Email = 'testuser0@example.com.sandbox' LIMIT 1];
		
		System.runAs(testUser) {
            Test.startTest();
			
			Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
			Deal_Registration__c dealReg = [SELECT Id, Name FROM Deal_Registration__c WHERE Email__c = 'Test_eng@redsky.com.sandbox' LIMIT 1];
			
			Contact con = [SELECT Id FROM Contact WHERE Email = 'Test_eng@redsky.com.sandbox' LIMIT 1];
			
			dealReg.Deal_Registration_Status__c = 'Approved';
			dealReg.Opportunity__c = opp.Id;
			dealReg.Primary_Contact__c = con.Id;
			update dealReg;
			
			Test.stopTest();
			
			System.assertEquals('Approved', dealReg.Deal_Registration_Status__c,
                'Deal Registration Status should be Approved');
        }
    }
	
	@isTest static void testCloudReqApproved() {
        User testUser = [SELECT Id FROM User WHERE Email = 'testuser0@example.com.sandbox' LIMIT 1];
		
		System.runAs(testUser) {
            Test.startTest();
			
			Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
			Deal_Registration__c dealReg = [SELECT Id, Name FROM Deal_Registration__c WHERE Email__c = 'Test_alliance_3@redsky.com.sandbox' LIMIT 1];
			
			Contact con = [SELECT Id FROM Contact WHERE Email = 'Test_eng@redsky.com.sandbox' LIMIT 1];
			
			dealReg.Deal_Registration_Status__c = 'Approved';
			dealReg.Opportunity__c = opp.Id;
			dealReg.Primary_Deal_Registration__c = false;
			dealReg.Deal_Registration_Type__c = 'Partner Sourced New Logo (PSNL)';
			update dealReg;
			
			Test.stopTest();
			
			System.assertEquals('Approved', dealReg.Deal_Registration_Status__c,
                'Deal Registration Status should be Approved');
        }
    }

	@isTest static void testCoverage() {
        User testUser = [SELECT Id FROM User WHERE Email = 'testuser0@example.com.sandbox' LIMIT 1];
		
		System.runAs(testUser) {
            Test.startTest();
			
			Deal_Registration__c dealReg = [SELECT Id, Name, Country__c,LastName__c,Company__c,Email__c, Partner_Lookup__c, Lead_Share_Campaign__c FROM Deal_Registration__c WHERE Email__c = 'Test_eng@redsky.com.sandbox' LIMIT 1];
			
			DealRegistrationTriggerHelper helper = new DealRegistrationTriggerHelper();
			helper.copyDealRegToLead(dealReg, null);
			DealRegistrationTriggerHelper.addCustomerContactAsOppRole(null,null);
			DealRegistrationTriggerHelper.updateOpportunities(null);
			Test.stopTest();
			
			System.assert(true,'success');
        }
    }
}