force-app/main/default/objects/Customer_Registration_Request__c/Customer_Registration_Request__c.object-meta.xml
<CustomObject>
    <label>Customer Registration Request</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Customer Registration Request Number#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Registration Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Registration_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending for Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Unknown email domain</fullName>
            </value>
            <value>
                <fullName>Waiting for internal Rubrik</fullName>
            </value>
            <value>
                <fullName>Waiting for registration user</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Assign_CRR_ControllerTest.cls
@isTest
public class Assign_CRR_ControllerTest {
    @testSetup static void setup() {
        List<Account> actList = new List<Account>();
        testDataFactoryClass.createCustomSettings();
        actList.add(new Account(Name = 'TestAcct1',Website='www.test3.com',OwnerId = UserInfo.getUserId(),type='Customer'));
        insert actList; 
        List<Contact> conList = testDataFactoryClass.createContact(actList);
        List<Customer_Registration_Request__c> csrList = testDataFactoryClass.createCustomerRegRequest(1,actList);
    }
    
    
    @isTest static void testMethod1() {
        Customer_Registration_Request__c crr = [select id,ownerId,Status__c from Customer_Registration_Request__c limit 1];
        
        ApexPages.StandardController st = new ApexPages.StandardController(crr);
        Assign_CRR_Controller arr = new Assign_CRR_Controller(st);
        arr.updateApprover();
    }
}