force-app/main/default/objects/How_To__kav/How_To__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <page>ArticleNewView</page>
            <template>Page</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <page>ArticleNewView</page>
            <template>Page</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <page>ArticleNewView</page>
            <template>Page</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge Centered Support (KCS)</label>
    <pluralLabel>Knowledge Base</pluralLabel>
</CustomObject>

force-app/main/default/objects/How_To__kav/fields/Cause__c.field-meta.xml
<CustomField>
    <fullName>Cause__c</fullName>
    <label>Cause</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/How_To__kav/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <label>Environment</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/How_To__kav/fields/Resolution__c.field-meta.xml
<CustomField>
    <fullName>Resolution__c</fullName>
    <label>Resolution</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/How_To__kav/fields/Summary__c.field-meta.xml
<CustomField>
    <fullName>Summary__c</fullName>
    <label>Summary</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/How_To__kav/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <label>Version</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/KnowledgeDetailController.cls
/*
 * Class Name :- KnowledgeDetailController
 * Visualforce Component :- KnowledgeDetailComponent
 * Author :- Shiva Sharma
 * Created Date :- 24-06-2019
 * Description : This Controller is being used in KnowledgeDetailComponent for displaying article info.
 * 
 // ********************Change Logs *****************************************************************************
 * 
 * Modified By          Date        Description 
 * 
 * 
 * 
 // ********************Change Logs Ends*************************************************************************
*/
global class KnowledgeDetailController {

    global String kbRecordId{get;set;}
    
    global List<how_to__kav> knowRecord{get;set;}
    public List<how_to__kav> getknowRecords(){
        knowRecord = new List<how_to__kav>();
        
        knowRecord = [select id,ArticleNumber,Summary,Summary__c,Version__c,Environment__c,Cause__c,Resolution__c from how_to__kav where (KnowledgeArticleid =:kbRecordId OR ID =: kbRecordId)];
        String baseUrl = System.label.KbBaseURL;
        if(!knowRecord.isEmpty()){
            if(knowRecord[0].Summary__c != null && knowRecord[0].Summary__c.contains('src="')){            knowRecord[0].Summary__c = knowRecord[0].Summary__c.replaceAll('src="','src="'+baseUrl);            } 
            if(knowRecord[0].Version__c != null && knowRecord[0].Version__c.contains('src="')){knowRecord[0].Version__c = knowRecord[0].Version__c.replaceAll('src="','src="'+baseUrl); } 
            if(knowRecord[0].Environment__c != null && knowRecord[0].Environment__c.contains('src="')){knowRecord[0].Environment__c = knowRecord[0].Environment__c.replaceAll('src="','src="'+baseUrl);} 
            if(knowRecord[0].Cause__c != null && knowRecord[0].Cause__c.contains('src="')){knowRecord[0].Cause__c = knowRecord[0].Cause__c.replaceAll('src="','src="'+baseUrl);} 
            if(knowRecord[0].Resolution__c != null && knowRecord[0].Resolution__c.contains('src="')){knowRecord[0].Resolution__c = knowRecord[0].Resolution__c.replaceAll('src="','src="'+baseUrl);} 
        }
        
        return knowRecord;
    }
    
}