force-app/main/default/objects/Cross_Object_Fields_Sync_Mapping__mdt/Cross_Object_Fields_Sync_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Establish a sync between the 2 objects fields</description>
    <label>Cross-Object Fields Sync Mapping</label>
    <pluralLabel>Cross-Object Fields Sync Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Cross_Object_Fields_Sync_Mapping__mdt/fields/Destination_FieldAPIName__c.field-meta.xml
<CustomField>
    <fullName>Destination_FieldAPIName__c</fullName>
    <description>FieldAPIName of the destination field</description>
    <label>Destination FieldAPIName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cross_Object_Fields_Sync_Mapping__mdt/fields/Destination_Object__c.field-meta.xml
<CustomField>
    <fullName>Destination_Object__c</fullName>
    <description>Destination Object where values will be synced</description>
    <label>Destination Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cross_Object_Fields_Sync_Mapping__mdt/fields/Destination_Object_Id_Field__c.field-meta.xml
<CustomField>
    <fullName>Destination_Object_Id_Field__c</fullName>
    <description>Field name in which destination record Id is present</description>
    <label>Destination Object Id Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cross_Object_Fields_Sync_Mapping__mdt/fields/Source_FieldAPIName__c.field-meta.xml
<CustomField>
    <fullName>Source_FieldAPIName__c</fullName>
    <description>FieldAPIName of the source field</description>
    <label>Source FieldAPIName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cross_Object_Fields_Sync_Mapping__mdt/fields/Source_Object__c.field-meta.xml
<CustomField>
    <fullName>Source_Object__c</fullName>
    <description>Object from where sync will start</description>
    <label>Source Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cross_Object_Fields_Sync_Mapping__mdt/fields/Sync_Name__c.field-meta.xml
<CustomField>
    <fullName>Sync_Name__c</fullName>
    <description>Name of the Sync</description>
    <inlineHelpText>Name of the Sync with which you will retrieve the fields to sync</inlineHelpText>
    <label>Sync Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Risk_Profile__c/Risk_Profile__c.object-meta.xml
<CustomObject>
    <label>Risk Profile</label>
    <nameField>
        <displayFormat>RP-{00000}</displayFormat>
        <label>Risk Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risk Profiles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Risk_Profile__c/fields/Primary_Risk_Reason__c.field-meta.xml
<CustomField>
    <fullName>Primary_Risk_Reason__c</fullName>
    <label>Primary Risk Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adoption</fullName>
            </value>
            <value>
                <fullName>Account Relationship</fullName>
            </value>
            <value>
                <fullName>Competition</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Customer Related</fullName>
            </value>
            <value>
                <fullName>Customer Fit / Maturity</fullName>
            </value>
            <value>
                <fullName>Support issues</fullName>
            </value>
            <value>
                <fullName>Rubrik-related</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Risk_Profile__c/fields/Risk_Status__c.field-meta.xml
<CustomField>
    <fullName>Risk_Status__c</fullName>
    <label>Risk Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Mitigated</fullName>
            </value>
            <value>
                <fullName>Entitlement Expired</fullName>
            </value>
            <value>
                <fullName>Entitlement Churn</fullName>
            </value>
            <value>
                <fullName>Account Churn</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>At Risk</fullName>
            </value>
            <value>
                <fullName>Partially Mitigated</fullName>
            </value>
            <value>
                <fullName>Downsell</fullName>
            </value>
            <value>
                <fullName>CX health score improved</fullName>
            </value>
            <value>
                <fullName>No Risk</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Requires modification of CX Score Logic</fullName>
            </value>
            <value>
                <fullName>No mitigation possible</fullName>
            </value>
            <value>
                <fullName>Less time to mitigate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Risk_Profile__c/fields/Risk_Type__c.field-meta.xml
<CustomField>
    <fullName>Risk_Type__c</fullName>
    <label>Risk Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Risk</fullName>
            </value>
            <value>
                <fullName>Entitlement Risk</fullName>
            </value>
            <value>
                <fullName>Feature/Product Risk</fullName>
            </value>
            <value>
                <fullName>Discount and Extension</fullName>
            </value>
            <value>
                <fullName>Downsell</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Risk_Profile__c/fields/Risk_Validation_Status__c.field-meta.xml
<CustomField>
    <fullName>Risk_Validation_Status__c</fullName>
    <label>Risk Validation Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Valid</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Snoozed / DNT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Risk_Profile__c/fields/Secondary_Risk_Reason__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Risk_Reason__c</fullName>
    <label>Secondary Risk Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Primary_Risk_Reason__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activation</fullName>
            </value>
            <value>
                <fullName>Lack of Adoption</fullName>
            </value>
            <value>
                <fullName>Value Realization</fullName>
            </value>
            <value>
                <fullName>Disengaged</fullName>
            </value>
            <value>
                <fullName>Key Sponsor Turnover</fullName>
            </value>
            <value>
                <fullName>Lack of Engagement</fullName>
            </value>
            <value>
                <fullName>Pricing</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Use Case / Feature Mismatch</fullName>
            </value>
            <value>
                <fullName>In-stability and Downtime</fullName>
            </value>
            <value>
                <fullName>Product Defect</fullName>
            </value>
            <value>
                <fullName>Lack of functionality</fullName>
            </value>
            <value>
                <fullName>Business Requirements not met</fullName>
            </value>
            <value>
                <fullName>Product roadmap deviations</fullName>
            </value>
            <value>
                <fullName>Contact not Responding</fullName>
            </value>
            <value>
                <fullName>Dissolved / Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Mergers &amp; Acquisitions</fullName>
            </value>
            <value>
                <fullName>Project on Hold / Project De-Prioritization</fullName>
            </value>
            <value>
                <fullName>Cloud Readiness</fullName>
            </value>
            <value>
                <fullName>Right Sizing</fullName>
            </value>
            <value>
                <fullName>Support Issues</fullName>
            </value>
            <value>
                <fullName>Budget Constraint</fullName>
            </value>
            <value>
                <fullName>Cloud Migration</fullName>
            </value>
            <value>
                <fullName>Sales Play not valid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Risk_Profile_Assignment__c/Risk_Profile_Assignment__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This setting is used to assigned sequence of the Risk Profile record</description>
    <label>Risk Profile Assignment</label>
</CustomObject>

force-app/main/default/objects/Risk_Profile_Assignment__c/fields/Last_Assigned_Index__c.field-meta.xml
<CustomField>
    <fullName>Last_Assigned_Index__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Last Assigned Index</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CS_CrossObjectFieldSyncMappingTest.cls
@isTest
public class CS_CrossObjectFieldSyncMappingTest {
    
    static void executeSyncProcess() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        testCase.Risk_Status__c = 'New';
        update testCase;
        
        Cross_Object_Fields_Sync_Mapping__mdt mapping = new Cross_Object_Fields_Sync_Mapping__mdt(
            Sync_Name__c = 'Test Sync Name',
            Source_Object__c = 'Case',
            Destination_Object__c = 'Risk_Profile__c',
            Source_FieldAPIName__c = 'Risk_Status__c',
            Destination_FieldAPIName__c = 'Risk_Status__c',
            Destination_Object_Id_Field__c = 'Risk_Profile__c'
        );
        
        CS_CrossObjectFieldSyncMapping syncInstance = new CS_CrossObjectFieldSyncMapping('Test Sync');
        CS_CrossObjectFieldSyncMapping.testMockFieldMappings = new List<Cross_Object_Fields_Sync_Mapping__mdt>{ mapping };
        syncInstance.setSourceRecordIds(new Set<Id>{testCase.Id});
        
        CS_CrossObjectFieldSyncMapping.execute(syncInstance, new Map<String, String>{'Id' => testCase.Id});
    }

    private static void verifySyncResults() {
        Case testCase = [SELECT Id, Risk_Profile__r.Risk_Status__c, Risk_Status__c FROM Case LIMIT 1];
        System.assertEquals(testCase.Risk_Status__c, testCase.Risk_Profile__r.Risk_Status__c, 
                            'The Risk Status field on the Risk Profile should match the Risk Status field on the Case.');
    }
	
    @future
    static void insertRiskGrovernanceMember(){
         Group riskGovernanceGroup = [SELECT Id FROM Group WHERE DeveloperName = 'Risk_Governance_Team' LIMIT 1];
        
        GroupMember groupMember = new GroupMember(
            GroupId = riskGovernanceGroup.Id,
            UserOrGroupId = UserInfo.getUserId()
        );
        insert groupMember;
    }
    @testSetup
    static void setupTestData() {       
        insertRiskGrovernanceMember();
        Risk_Profile_Assignment__c customSetting = new Risk_Profile_Assignment__c(
            Last_Assigned_Index__c = 0
        );
        insert customSetting;       
               
        Account testAccount = new Account(Name = 'Test Account New');
        insert testAccount;

        Risk_Profile__c testRiskProfile = new Risk_Profile__c(
            Risk_Type__c = 'Account Risk',
            Primary_Risk_Reason__c = 'Support issues',
            Secondary_Risk_Reason__c = 'Support issues',
            Risk_Validation_Status__c = 'Invalid'
        );
        insert testRiskProfile;
        
        testRiskProfile.Risk_Validation_Status__c = 'Valid';
        update testRiskProfile;        
    }

    @isTest
    static void testSyncExecution() {
        Test.startTest();
        	executeSyncProcess();  
        Test.stopTest();
        verifySyncResults();
    }

    @isTest
    static void testAsyncExecution() {
        Test.startTest();
        	runAsyncProcess();
        Test.stopTest();
        
        verifySyncResults();
    }

    @future
    static void runAsyncProcess() {
        executeSyncProcess();
    }
}