force-app/main/default/objects/PS_SubTask__c/PS_SubTask__c.object-meta.xml
<CustomObject>
    <description>Object to capture Subtask related to PS Task under PS Project</description>
    <label>Legacy PS SubTask</label>
    <nameField>
        <displayFormat>SUBTASK-{0000000}</displayFormat>
        <label>PS SubTask ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PS Legacy PS SubTasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PS_SubTask__c/fields/Billable__c.field-meta.xml
<CustomField>
    <fullName>Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Toggling this will make the subtask non-billable. If the task is created as billable, all of these automatically created subtasks should inherit from the parent task</description>
    <inlineHelpText>Toggling this will make the subtask non-billable. If the task is created as billable, all of these automatically created subtasks should inherit from the parent task</inlineHelpText>
    <label>Billable (to be deprecated)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PS_SubTask__c/fields/Is_Billable__c.field-meta.xml
<CustomField>
    <fullName>Is_Billable__c</fullName>
    <formula>If(Task__r.Project__r.CSAT__c == false 
&amp;&amp; 
!CONTAINS(TEXT(Subtask_Type__c),&apos;Non billable&apos;),true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Billable?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PS_SubTaskTriggerHandler.cls
public class PS_SubTaskTriggerHandler {
	public static Boolean noRecurssion = false;
    public static void updateBillable(List<PS_SubTask__c> newPsTasks){
        List<PS_SubTask__c> updateSubTaskList = new List<PS_SubTask__c>();
        for(PS_SubTask__c sub : [select Id,Billable__c,Is_Billable__c from PS_SubTask__c where Id IN: newPsTasks]){
            sub.Billable__c = sub.Is_Billable__c;
            updateSubTaskList.add(sub);
        }
        if(!updateSubTaskList.isEmpty()){
            PS_SubTaskTriggerHandler.noRecurssion = true;
            update updateSubTaskList;
        }
    }
}