force-app/main/default/objects/PS_SubTask__c/PS_SubTask__c.object-meta.xml
<CustomObject>
    <description>Object to capture Subtask related to PS Task under PS Project</description>
    <label>Legacy PS SubTask</label>
    <nameField>
        <displayFormat>SUBTASK-{0000000}</displayFormat>
        <label>PS SubTask ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PS Legacy PS SubTasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PS_SubTask__c/fields/Billable__c.field-meta.xml
<CustomField>
    <fullName>Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Toggling this will make the subtask non-billable. If the task is created as billable, all of these automatically created subtasks should inherit from the parent task</description>
    <inlineHelpText>Toggling this will make the subtask non-billable. If the task is created as billable, all of these automatically created subtasks should inherit from the parent task</inlineHelpText>
    <label>Billable (to be deprecated)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PS_SubTask__c/fields/Hours_logged__c.field-meta.xml
<CustomField>
    <fullName>Hours_logged__c</fullName>
    <inlineHelpText>Should be in the unit of hours. 1 day = 8 hours</inlineHelpText>
    <label># of hours logged(Deprecated)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PS_SubTask__c/fields/Is_Billable__c.field-meta.xml
<CustomField>
    <fullName>Is_Billable__c</fullName>
    <formula>If(Task__r.Project__r.CSAT__c == false 
&amp;&amp; 
!CONTAINS(TEXT(Subtask_Type__c),&apos;Non billable&apos;),true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Billable?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PS_SubTask__c/fields/Project_ID__c.field-meta.xml
<CustomField>
    <fullName>Project_ID__c</fullName>
    <formula>CASESAFEID(Task__r.Project__r.Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PS_SubTask__c/fields/PS_Assignee__c.field-meta.xml
<CustomField>
    <fullName>PS_Assignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The assignee for the PS Subtask</description>
    <inlineHelpText>The assignee for the PS Subtask</inlineHelpText>
    <label>PS Assignee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PS_Subtasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PS_SubTask__c/fields/Subtask_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Subtask_End_Date__c</fullName>
    <description>End Date for Subtask</description>
    <label>Subtask End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PS_SubTask__c/fields/Subtask_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Subtask_Start_Date__c</fullName>
    <description>Start Date for Subtask</description>
    <label>Subtask Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PS_SubTask__c/fields/Subtask_Type__c.field-meta.xml
<CustomField>
    <fullName>Subtask_Type__c</fullName>
    <inlineHelpText>Select subtask Type:
For Install Task: 
Install

For Consult Task: 
Advanced Configuration
Automation
Deep-Dive Training
Onsite Resident
Documentation

For Admin Task: 
Travel
Training
PTO
CS</inlineHelpText>
    <label>Subtask Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Task_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Install</fullName>
            </value>
            <value>
                <fullName>Advanced Configuration</fullName>
            </value>
            <value>
                <fullName>Automation</fullName>
            </value>
            <value>
                <fullName>Deep-Dive Training</fullName>
            </value>
            <value>
                <fullName>Onsite Resident</fullName>
            </value>
            <value>
                <fullName>Documentation</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>PTO</fullName>
            </value>
            <value>
                <fullName>CSAT</fullName>
            </value>
            <value>
                <fullName>POC</fullName>
            </value>
            <value>
                <fullName>Shadow</fullName>
            </value>
            <value>
                <fullName>Break/fix</fullName>
            </value>
            <value>
                <fullName>Partner Enablement</fullName>
            </value>
            <value>
                <fullName>Consult (Non billable)</fullName>
            </value>
            <value>
                <fullName>Install (Non billable)</fullName>
            </value>
            <value>
                <fullName>Holiday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PS_SubTask__c/fields/Task__c.field-meta.xml
<CustomField>
    <fullName>Task__c</fullName>
    <description>PS Task related to this Subtask</description>
    <inlineHelpText>Select PS Task related to this Subtask</inlineHelpText>
    <label>Task</label>
    <referenceTo>PS_Task__c</referenceTo>
    <relationshipLabel>PS Subtasks</relationshipLabel>
    <relationshipName>PS_Subtasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PS_SubTask__c/fields/Task_Type__c.field-meta.xml
<CustomField>
    <fullName>Task_Type__c</fullName>
    <label>Task Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Install</fullName>
            </value>
            <value>
                <fullName>Consult</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PS_Task__c/PS_Task__c.object-meta.xml
<CustomObject>
    <description>SOX object - This object is used to track the task performed as part of PS Project</description>
    <label>PS Task</label>
    <nameField>
        <displayFormat>PST-{0000000}</displayFormat>
        <label>PS Task ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PS Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PS_Task__c/fields/Order_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Item</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>PS Tasks</relationshipLabel>
    <relationshipName>PS_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PS_Task__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>PS Project related to this Task</description>
    <inlineHelpText>PS Project related to this Task</inlineHelpText>
    <label>Project</label>
    <referenceTo>PS_Project__c</referenceTo>
    <relationshipLabel>PS Tasks</relationshipLabel>
    <relationshipName>PS_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PS_Task__c/fields/Task_Type__c.field-meta.xml
<CustomField>
    <fullName>Task_Type__c</fullName>
    <description>Type of the PS Task</description>
    <inlineHelpText>Type of the PS Task</inlineHelpText>
    <label>Task Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Install</fullName>
            </value>
            <value>
                <fullName>Consult</fullName>
            </value>
            <value>
                <fullName>Consult-Onsite</fullName>
            </value>
            <value>
                <fullName>Consult-Remote</fullName>
            </value>
            <value>
                <fullName>Resident Engineer</fullName>
            </value>
            <value>
                <fullName>CSAT</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Migration</fullName>
            </value>
            <value>
                <fullName>T&amp;E</fullName>
            </value>
            <value>
                <fullName>Non-Billable (Product)</fullName>
            </value>
            <value>
                <fullName>Non-Billable (PS)</fullName>
            </value>
            <value>
                <fullName>Non-Billable (Sales)</fullName>
            </value>
            <value>
                <fullName>Non-Billable (Expired)</fullName>
            </value>
            <value>
                <fullName>Resident Engineer-PD</fullName>
            </value>
            <value>
                <fullName>Install-PD</fullName>
            </value>
            <value>
                <fullName>Consult-Remote-PD</fullName>
            </value>
            <value>
                <fullName>Consult-Onsite-PD</fullName>
            </value>
            <value>
                <fullName>RCDM-Install</fullName>
            </value>
            <value>
                <fullName>Accelerator</fullName>
            </value>
            <value>
                <fullName>Rubrik University</fullName>
            </value>
            <value>
                <fullName>Non-Billable Admin</fullName>
            </value>
            <value>
                <fullName>Non-Billable CSAT</fullName>
            </value>
            <value>
                <fullName>Non-Billable PreSales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssignTasksCmpController.cls
public class AssignTasksCmpController{
    @AuraEnabled
    public static List<PSTaskWrapper> getPsTask(String Projid){
        String taskNamePostFix = '';
        List<PSTaskWrapper> PsTaskWrapperList = new List<PSTaskWrapper>();
        for(PS_Task__c tsk :[SELECT Id,Name,Order_Item__r.order.ShippingCity,Order_Item__r.order.ShippingCountryCode,Order_Item__r.order.ShippingStateCode,
                             Task_Type__c,Order_Item__r.Order.OrderNumber
                             FROM PS_Task__c
                             WHERE Project__c =: id.valueof(Projid)]){
                                 taskNamePostFix = '';
                                 if(tsk.Order_Item__r.order.ShippingCity != null ) {
                                     taskNamePostFix += '(' +tsk.Order_Item__r.order.ShippingCity;
                                     system.debug('taskname000--'+taskNamePostFix);
                                 }
                                 if(tsk.Order_Item__r.order.ShippingCountryCode != null && (tsk.Order_Item__r.order.ShippingCountryCode != 'US' && tsk.Order_Item__r.order.ShippingCountryCode != 'CA')){
                                     if(taskNamePostFix == '') {
                                         taskNamePostFix += '('+tsk.Order_Item__r.order.ShippingCountryCode;
                                     }
                                     else {
                                         taskNamePostFix +=  '-'+tsk.Order_Item__r.order.ShippingCountryCode;
                                     }
                                     system.debug('taskname111--'+taskNamePostFix);
                                 }
                                 else {
                                     system.debug('taskname222--'+taskNamePostFix);
                                     if(taskNamePostFix == '') {
                                         taskNamePostFix += '('+tsk.Order_Item__r.order.ShippingStateCode;
                                     }
                                     else {
                                         taskNamePostFix +=  +'-'+tsk.Order_Item__r.order.ShippingStateCode;
                                     }
                                 }
                                 if(taskNamePostFix.contains('(')) {
                                     taskNamePostFix = taskNamePostFix + ')';
                                 }
                                 
                                 String taskName = tsk.Name+'-'+string.valueOf(tsk.Task_Type__c);
                                 if(!string.isBlank(tsk.Order_Item__r.Order.OrderNumber)){
                                     taskName = taskName+'-'+tsk.Order_Item__r.Order.OrderNumber;
                                 }
                                 if(!string.isBlank(taskNamePostFix)){
                                     taskName = taskName+'-'+taskNamePostFix;
                                 }
                                 PSTaskWrapper wrap = new PSTaskWrapper();
                                 wrap.TaskName = taskName;
                                 wrap.Id = tsk.Id;
                                 wrap.selectAll = false;
                                 PsTaskWrapperList.add(wrap);
                                 
                             }
        return PsTaskWrapperList;
    }
    @AuraEnabled
    public static List<PS_SubTask__c> getAllPsSubTask(String Projid){
        List<PS_SubTask__c> PSSTList = new List<PS_SubTask__c>();
        Set<String> uniqueSubtasksSet = new Set<string>();
        string str ='';
        for(PS_SubTask__c ps : [SELECT Id,Name,Task__c,Subtask_Type__c FROM PS_SubTask__c WHERE Project_ID__c =: id.valueof(Projid)]){
            str = ps.Task__c+'-'+ps.Subtask_Type__c;
            if(uniqueSubtasksSet.isEmpty() || !uniqueSubtasksSet.contains(str)){
                uniqueSubtasksSet.add(Str);
                PSSTList.add(ps);
            }
        }  
        system.debug('@@ getAllPsSubTask '+PSSTList);
        return PSSTList;
    }
    @AuraEnabled
    public static List<PSSubTaskWrapper> getPsSubTask(String TaskId, List<string> subTaskIds){
        List<PSSubTaskWrapper> PsWrapperList = new List<PSSubTaskWrapper>();
        PS_SubTask__c PsSub ;
        if(!subTaskIds.isEmpty()){
            for(PS_SubTask__c PSST :[SELECT id,Name,Task__c,Task__r.Name,Subtask_Type__c,
                                     Task_Type__c,Is_Billable__c
                                     FROM PS_SubTask__c
                                     WHERE Task__c =: id.valueof(TaskId) AND Id IN: subTaskIds]){
                                         PsSub = new PS_SubTask__c();
                                         PSSubTaskWrapper PSSTW = new PSSubTaskWrapper();
                                         PSSTW.SubtaskType = PSST.Subtask_Type__c;
                                         PSSTW.TaskType = PSST.Task_Type__c;
                                         PSSTW.TaskName = PSST.Task__r.Name;
                                         PSSTW.Id = PSST.id;
                                         PSSTW.Selected = false;
                                         
                                         PsWrapperList.add(PSSTW);
                                     }
        }
        system.debug('@@ getPsSubTask '+PsWrapperList);
        return PsWrapperList;
    }
    
    @AuraEnabled
    public static String assignSubtasks(String userid, String selectedsubtaskid){      
        List<Id> subtaskids =(List<Id>)System.JSON.deserialize(selectedsubtaskid, List<Id>.class);
        List<PS_SubTask__c> toInsertNewPSSubTaskList = new List<PS_SubTask__c>();
        List<PS_SubTask__c> PSSubTaskList = [SELECT Id, PS_Assignee__c,Task__c,Task_Type__c,
                                             Subtask_End_Date__c,Subtask_Start_Date__c,Subtask_Type__c,
                                             Hours_logged__c,Project_ID__c 
                                             FROM PS_SubTask__c WHERE Id IN : subtaskids ];
        if(PSSubTaskList != null){
            for(Id UsrId : (List<Id>)System.JSON.deserialize(userid, List<id>.class)){
                system.debug('UsrId = '+UsrId);
                for(PS_SubTask__c originalSubtask: PSSubTaskList){
                    PS_SubTask__c sub = new PS_SubTask__c();
                    sub.Task__c = originalSubtask.Task__c;
                    sub.PS_Assignee__c = Id.valueOf(UsrId);
                    sub.Subtask_End_Date__c = originalSubtask.Subtask_End_Date__c;
                    sub.Subtask_Start_Date__c = originalSubtask.Subtask_Start_Date__c;
                    sub.Task_Type__c = originalSubtask.Task_Type__c;
                    sub.Subtask_Type__c = originalSubtask.Subtask_Type__c;
                    sub.Hours_logged__c = originalSubtask.Hours_logged__c;
                    //sub.Billable__c = originalSubtask.Billable__c;
                    //sub.Include_in_Utilization__c = originalSubtask.Billable__c;
                    toInsertNewPSSubTaskList.add(sub);
                }
            }
        }
        if(!toInsertNewPSSubTaskList.isEmpty()){
            insert toInsertNewPSSubTaskList;
        }
        return 'success';
    }
    
    @testVisible
    class PSTaskWrapper{
        public @AuraEnabled string TaskName;
        public @AuraEnabled string Id;
        public @AuraEnabled boolean selectAll;
    }
    
    @testVisible
    class PSSubTaskWrapper{
        public @AuraEnabled String PsSubTask;
        public @AuraEnabled boolean Selected;
        public @AuraEnabled string Id;
        public @AuraEnabled string TaskName;
        public @AuraEnabled string TaskType;
        public @AuraEnabled string SubtaskType;
    }
}