force-app/main/default/objects/PS_Task__c/PS_Task__c.object-meta.xml
<CustomObject>
    <description>SOX object - This object is used to track the task performed as part of PS Project</description>
    <label>PS Task</label>
    <nameField>
        <displayFormat>PST-{0000000}</displayFormat>
        <label>PS Task ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PS Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PS_Task__c/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <formula>Order_Item__r.PricebookEntry.Product2.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Product</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PS_Task__c/fields/Revenue_Type__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Type__c</fullName>
    <label>Revenue Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid Upon Delivery</fullName>
            </value>
            <value>
                <fullName>Prepaid</fullName>
                <default>true</default>
                <label>Prepaid</label>
            </value>
            <value>
                <fullName>RES</fullName>
            </value>
            <value>
                <fullName>No Revenue</fullName>
            </value>
            <value>
                <fullName>T&amp;E</fullName>
            </value>
            <value>
                <fullName>Migration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PS_Task_Meta__mdt/PS_Task_Meta__mdt.object-meta.xml
<CustomObject>
    <label>PS Task Meta</label>
    <pluralLabel>PS Tasks Meta</pluralLabel>
</CustomObject>

force-app/main/default/objects/PS_Task_Meta__mdt/fields/Revenue_Type__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Type__c</fullName>
    <label>Revenue Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid Upon Delivery</fullName>
            </value>
            <value>
                <fullName>Prepaid</fullName>
                <default>true</default>
                <label>Prepaid</label>
            </value>
            <value>
                <fullName>RES</fullName>
            </value>
            <value>
                <fullName>No Revenue</fullName>
            </value>
            <value>
                <fullName>T&amp;E</fullName>
            </value>
            <value>
                <fullName>Migration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Batch_OTM_UpdatePSTaskRevenue.cls
public class Batch_OTM_UpdatePSTaskRevenue implements Database.Batchable<sObject>, Database.Stateful {
	
    public Map<String, String> mapProductToRevenueType ;
    
    public Database.QueryLocator start(Database.BatchableContext BC) {
        this.mapProductToRevenueType = new Map<String, String>();
        for( PS_Task_Meta__mdt taskmdt : [Select Id, MasterLabel , Revenue_Type__c from PS_Task_Meta__mdt] ) {
            mapProductToRevenueType.put( taskmdt.MasterLabel, taskmdt.Revenue_Type__c );
        }
        return Database.getQueryLocator('Select Id, Order_Product__c,Revenue_Type__c From PS_Task__c Where Revenue_Type__c=null');
    }
    
    public void execute(Database.BatchableContext bc, List<PS_Task__c> lstScope) {
        List<PS_Task__c> lstTaskToUpdate = new List<PS_Task__c>();
        for( PS_Task__c objTask : lstScope ) {
            if( mapProductToRevenueType.containsKey( objTask.Order_Product__c ) ) {
                objTask.Revenue_Type__c = mapProductToRevenueType.get( objTask.Order_Product__c );
                lstTaskToUpdate.add( objTask );
            }
        }
        if( !lstTaskToUpdate.isEmpty() ) {
            update lstTaskToUpdate;
        }
    }
    
    public void finish(Database.BatchableContext BC){
        
    }
    
    public static void dummyMethod() {
        Integer i=0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    }
    
}