force-app/main/default/objects/Status_Tracking__c/Status_Tracking__c.object-meta.xml
<CustomObject>
    <label>Status Tracking</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Status Tracking Number#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Status Tracker</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Status_Tracking__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Status Tracker</relationshipLabel>
    <relationshipName>Status_Tracker</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Status_Tracking__c/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <label>Days</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Status_Tracking__c/fields/Hours__c.field-meta.xml
<CustomField>
    <fullName>Hours__c</fullName>
    <label>Hours</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Status_Tracking__c/fields/Miliseconds__c.field-meta.xml
<CustomField>
    <fullName>Miliseconds__c</fullName>
    <label>Miliseconds</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Status_Tracking__c/fields/Minutes__c.field-meta.xml
<CustomField>
    <fullName>Minutes__c</fullName>
    <label>Minutes</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Status_Tracking__c/fields/Number_of_times_in_status__c.field-meta.xml
<CustomField>
    <fullName>Number_of_times_in_status__c</fullName>
    <label>Number of times in status</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Status_Tracking__c/fields/Total_Time__c.field-meta.xml
<CustomField>
    <fullName>Total_Time__c</fullName>
    <formula>TEXT(FLOOR( Miliseconds__c / 86400)) +&apos; Days, &apos;+ TEXT( FLOOR( MOD(Miliseconds__c ,86400) / 3600)) +&apos; Hours, &apos;+ TEXT(FLOOR(MOD( MOD(Miliseconds__c ,86400),3600) / 60))+&apos; Minutes&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Time</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Status_Tracking__c/fields/Tracking__c.field-meta.xml
<CustomField>
    <fullName>Tracking__c</fullName>
    <label>Tracking</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RelatedListStatusTrackerController.cls
public class RelatedListStatusTrackerController {
    public Id caseId;
    public List<Status_Tracking__c> caseTrackerList{get;set;}
    public RelatedListStatusTrackerController(ApexPages.StandardController controller){
        caseId = (id) controller.getId();
        caseTrackerList = new List<Status_Tracking__c>();
        caseTrackerListAction();
    }
    
    public void caseTrackerListAction(){
        caseTrackerList = [SELECT id,Tracking__c, Miliseconds__c, Days__c, Hours__c, Minutes__c, Total_Time__c, Number_of_times_in_status__c FROM Status_Tracking__c where Case__c =: caseId];
    }    
}