force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>SOX object - Captures booking, booking adjustments and distibutor &amp; partner referal fee</description>
    <label>Booking</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Autonumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Field_Update_Status__c.field-meta.xml
<CustomField>
    <fullName>Field_Update_Status__c</fullName>
    <label>Field Update Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Core Attributes - Frozen</fullName>
            </value>
            <value>
                <fullName>Freeze Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Original Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UpdateHistoricalBookingBatch.cls
global class UpdateHistoricalBookingBatch implements Database.batchable<sObject>, Database.Stateful{
    
    global Database.QueryLocator start(Database.BatchableContext bc){
       string query = ' select id,Opportunity__r.closeDate from Booking__c where Opportunity__r.closeDate <= 2020-01-31' ;
        system.debug('query'+query);
        return Database.getQueryLocator(query);
        
    }
    
    global void execute(Database.BatchableContext bc, List<Booking__c> scope)
    {
         List<Booking__c> Updatebkg = new List<Booking__c>();
         for (Booking__c Bkg : scope){
             Updatebkg.add(new Booking__c(Field_Update_Status__c ='Freeze Completed',id=Bkg.id));
         }
         if(!Updatebkg.isEmpty())
             update Updatebkg ;
                  
    }
    
    global void finish(Database.BatchableContext BC)
    {          
                 
       
    }
}