force-app/main/default/objects/Case_Special_Handling__c/Case_Special_Handling__c.object-meta.xml
<CustomObject>
    <description>This Object modernizes the way we manage and display the information in the ”Case Special Handling” field.(CS21-1971)</description>
    <label>Case Special Handling</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Case Special Handling Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Special Handling</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Special_Handling__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the account that this message will be displayed for.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Case Special Handling</relationshipLabel>
    <relationshipName>Case_Special_Handling</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Special_Handling__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Category of the message to be shown.</description>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Custom configuration</fullName>
            </value>
            <value>
                <fullName>Darksite information</fullName>
            </value>
            <value>
                <fullName>Misc. Information</fullName>
            </value>
            <value>
                <fullName>POC information</fullName>
            </value>
            <value>
                <fullName>Ransomware Events</fullName>
            </value>
            <value>
                <fullName>RMA instructions</fullName>
            </value>
            <value>
                <fullName>SLA Retention Lock</fullName>
            </value>
            <value>
                <fullName>Support contract exceptions</fullName>
            </value>
            <value>
                <fullName>Support guidelines</fullName>
            </value>
            <value>
                <fullName>Migrated Case Special Handling</fullName>
                <isActive>false</isActive>
                <label>Migrated Case Special Handling</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Special_Handling__c/fields/Icon__c.field-meta.xml
<CustomField>
    <fullName>Icon__c</fullName>
    <description>It will determine the icon shown</description>
    <label>Icon</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dark Site</fullName>
            </value>
            <value>
                <fullName>Prefers Email</fullName>
                <label>Prefers E-mail</label>
            </value>
            <value>
                <fullName>Prefers Phone</fullName>
            </value>
            <value>
                <fullName>Retention Lock SLA</fullName>
            </value>
            <value>
                <fullName>RKSupport Approved</fullName>
            </value>
            <value>
                <fullName>Strict Change Control</fullName>
            </value>
            <value>
                <fullName>Remote - Skype</fullName>
            </value>
            <value>
                <fullName>Remote - Teams</fullName>
            </value>
            <value>
                <fullName>Remote - Webex</fullName>
            </value>
            <value>
                <fullName>Remote - Zoom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Special_Handling__c/fields/Is_Archived__c.field-meta.xml
<CustomField>
    <fullName>Is_Archived__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It controls if a message is shown or not in the case display</description>
    <label>Is Archived?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case_Special_Handling__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>the specific message that will be displayed</description>
    <label>Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Case_Special_Handling__c/fields/Show_Banner__c.field-meta.xml
<CustomField>
    <fullName>Show_Banner__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It controls if a message needs to be shown as a banner</description>
    <label>Show Banner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CS_CaseSpecialHandlingControllerTest.cls
@isTest
public class CS_CaseSpecialHandlingControllerTest {

    static Account testAccount;

    @TestSetup
    static void testSetup() {
        UserRole vUserRole = new UserRole(DeveloperName = 'RubrikDeveloper1', Name = 'My Role');
        insert vUserRole;
        
        User u = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
            LastName = 'last',
            Email = 'testuser@testuser1.com',
            Username = 'testrbkstlnw' +'@rubrik.com.sandbox',
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'stlnw',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            UserRoleId = vUserRole.Id,
            Start_Date__c=System.Today().adddays(-30)
            
        );
        
        insert u;
        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'Case_Special_Handling_Edit_Access'];
        PermissionSetAssignment psa = new PermissionSetAssignment();
        psa.AssigneeId = u.Id;
        psa.PermissionSetId = ps.Id;
        insert psa;   
        System.runAs(u) {
        // Create a dummy Account record
        testAccount = new Account(Name = 'Test Account');
        insert testAccount;
        }
    }

    /* test method for getRecords method*/
    @isTest
    static void testGetRecords() {
        User u = [SELECT id, name from user where email ='testuser@testuser1.com'];
        System.runAs(u){
        Id accId = [SELECT Id FROM Account LIMIT 1].id;
        // Create a Case record associated with the Account
        Case testCase = new Case(AccountId = accId, Priority = 'P4', RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Support_Case').getRecordTypeId());
        insert testCase;
            
        Case testCase1 = new Case(AccountId = accId, Priority = 'P4', RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Customer_Success').getRecordTypeId());
        insert testCase1;

        Case_Special_Handling__c testSpecialHandling = new Case_Special_Handling__c(
            Account_Id__c = accId,
            Icon__c = 'Dark Site',
            Category__c = 'Support contract exceptions',
            Message__c = 'SomeMessage',
            Is_Archived__c = false
        );
        insert testSpecialHandling;
        Case_Special_Handling__c testSpecialHandling1 = new Case_Special_Handling__c(
            Account_Id__c = accId,
            Icon__c = 'Dark Site',
            Category__c = 'Support contract exceptions',
            Message__c = 'SomeMessage',
            Is_Archived__c = false,
            Show_Banner__c = true
        );
        insert testSpecialHandling1;
            
		String querLimit = '5';
        String filter = 'Show_Banner__c = true';
        // Test the getRecords method with valid Case Id
        Test.startTest();
        List <Case_Special_Handling__c> result = CS_CaseSpecialHandlingController.getRecords(testCase.Id,querLimit,filter);
        List <Case_Special_Handling__c> result1 = CS_CaseSpecialHandlingController.getRecords(testCase1.Id,querLimit,filter);
        
        // Assertions for the valid Case Id scenario
        System.assertEquals(1, result.size());
        System.assertEquals('Dark Site', result[0].Icon__c);
        System.assertEquals('Support contract exceptions', result[0].Category__c);
        System.assertEquals('SomeMessage', result[0].Message__c);

        // Test the getRecords method with invalid Case Id
        try {
            result = CS_CaseSpecialHandlingController.getRecords(null,null,null);
            // Ensure that no result is returned if an exception is thrown
            System.assertEquals(0, result.size(), 'No records should be returned if an exception is thrown.');
        } catch (CS_CaseSpecialHandlingController.CS_CaseSpecialHandlingControllerException e) {
            // Verify that the custom exception is thrown with the expected message
            System.assertEquals('Script-thrown exception', e.getMessage(), 'Correct exception message should be thrown.');
        }
        Test.stopTest();
        }
    }

    @isTest
    static void testUpdateDateField() {
        User u = [SELECT id, name from user where email ='testuser@testuser1.com'];
        System.runAs(u){
        // Create a Case_Special_Handling record associated with the Account
        Case_Special_Handling__c testSpecialHandling = new Case_Special_Handling__c(
            Account_Id__c = [SELECT Id FROM Account LIMIT 1].id,
            Icon__c = 'Dark Site',
            Category__c = 'Support contract exceptions',
            Message__c = 'SomeMessage',
            Is_Archived__c = false
        );
        insert testSpecialHandling;

        // Test the updateDateField method with valid record Id
        Test.startTest();
        String result = CS_CaseSpecialHandlingController.updateDateField(testSpecialHandling.Id);

        // Assertions for the valid record Id scenario
        System.assertEquals('Success: Manual Review Requested Successfully.', result);

        // Test the updateDateField method with invalid record Id
        result = CS_CaseSpecialHandlingController.updateDateField('invalidId');

        // Assertions for the invalid record Id scenario
        System.assertEquals('Error: Invalid id: invalidId', result);
        Test.stopTest();
        }
    }
     @IsTest
    static void testCheckObjectAccess() {
        User u = [SELECT id, name from user where email ='testuser@testuser1.com'];
        System.runAs(u){
        Test.startTest();
        Boolean hasAccessToAccount = CS_CaseSpecialHandlingController.checkObjectAccess('Case_Special_Handling__c');
        Test.stopTest();
        System.assertEquals(true, hasAccessToAccount, 'Expected to have access to Account object');
        }
    }
    
    @IsTest
    static void testCheckObjectAccessWithNull() {
        User u = [SELECT id, name from user where email ='testuser@testuser1.com'];
        System.runAs(u){
        // Test with null value
        Test.startTest();
        Boolean hasAccessToNull = CS_CaseSpecialHandlingController.checkObjectAccess(null);
        Test.stopTest();
        System.assertEquals(false, hasAccessToNull, 'Expected to not have access when objectName is null');
        }
    }
}