force-app/main/default/objects/ShGl_DisableBusinessLogic__c/ShGl_DisableBusinessLogic__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Disable Business Logic in Salesforce - Includes Triggers, Workflows, Process Builders and Validation Rules</description>
    <label>DisableBusinessLogic</label>
</CustomObject>

force-app/main/default/objects/ShGl_DisableBusinessLogic__c/fields/Disable_Account_Triggers__c.field-meta.xml
<CustomField>
    <fullName>Disable_Account_Triggers__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable Account Triggers</description>
    <inlineHelpText>Disable Account Triggers</inlineHelpText>
    <label>Disable Account Triggers</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ShGl_DisableBusinessLogic__c/fields/Disable_Opportunity_Triggers__c.field-meta.xml
<CustomField>
    <fullName>Disable_Opportunity_Triggers__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable Opportunity Trigger</description>
    <inlineHelpText>Disable Opportunity Trigger</inlineHelpText>
    <label>Disable Opportunity Triggers</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ShGl_DisableBusinessLogic__c/fields/Disable_Opportunity_Validation_Rules__c.field-meta.xml
<CustomField>
    <fullName>Disable_Opportunity_Validation_Rules__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable Opportunity Validation Rules</description>
    <inlineHelpText>Disable Opportunity Validation Rules</inlineHelpText>
    <label>Disable Opportunity Validation Rules</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ShGl_DisableBusinessLogic__c/fields/Disable_Order_Old_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Disable_Order_Old_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable Order Old Trigger
Switch on and off between old and new triggers</description>
    <label>Disable Order Old Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ShGl_DisableBusinessLogic__c/fields/Disable_OrderItem_Old_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Disable_OrderItem_Old_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disable OrderItem Old Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ShGl_DisableBusinessLogic__c/fields/Disable_SBQQ_Quote_Triggers__c.field-meta.xml
<CustomField>
    <fullName>Disable_SBQQ_Quote_Triggers__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable SBQQ Quote Triggers</description>
    <label>Disable SBQQ Quote Triggers</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerControl__c/TriggerControl__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This setting is used to disable triggers dynamically without updating code</description>
    <label>TriggerControl</label>
</CustomObject>

force-app/main/default/objects/TriggerControl__c/fields/DisableTrigger__c.field-meta.xml
<CustomField>
    <fullName>DisableTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox is used as an ON/OFF flag to disable the respective trigger</description>
    <label>Disable Trigger?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/RenewalCaseHelperTest.cls
/**
 * @description class RenewalCaseHelper {
 */
@isTest
public class RenewalCaseHelperTest {
    
    static TriggerControl__c getTriggerControl(){
        ShGl_DisableBusinessLogic__c disableLogic= new ShGl_DisableBusinessLogic__c(Disable_SBQQ_Quote_Triggers__c = true, Disable_Order_Old_Trigger__c = true, Disable_OrderItem_Old_Trigger__c = true, Disable_Account_Triggers__c = true);
        disableLogic.Name = 'System Administrator';   
        disableLogic.Disable_Opportunity_Validation_Rules__c = TRUE; 
        disableLogic.Disable_Opportunity_Triggers__c = true;
        insert disableLogic;
        TriggerControl__c tc= new TriggerControl__c();
        tc.Name='Opportunity';
        tc.DisableTrigger__c = true;
        return tc;
    }
    static TriggerControl__c getTriggerControlCase(){
        TriggerControl__c tc=new TriggerControl__c();
        tc.Name='Renewal Case';
        tc.DisableTrigger__c = false ;
        return tc;
    }
   
    static testMethod void csCreationTest(){
        
        TriggerControl__c triggerCntlr= getTriggerControl();
        insert triggerCntlr;
        insert getTriggerControlCase();
        
        Account ACCT = new Account(Name='Test Account', Phone='123-456-7890', AccountNumber='Test',
                                   BillingStreet = '123 street', BillingCity = 'Santa Clara', BillingState = 'California', BillingPostalCode = '95050', BillingCountry = 'United States');
        insert ACCT;
        QuoteTriggerHandler.disableQuoteTrigger = true;
        Opportunity tempOpp= new Opportunity(name='Temp Opp', OwnerID=UserInfo.getUserId(),accountId=ACCT.id,stagename='Approved',Amount=1000,Lead_Email_Hidden__c='test@email.com',closeDate=Date.today());
        insert tempOpp;
        
        ServiceContract testContract = new ServiceContract();
        testContract.AccountId = ACCT.id;
        testContract.SBQQSC__RenewalOpportunityRecordTypeId__c = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Renewal Opportunity').getRecordTypeId();
        testContract.Name = 'Case Instrument Contract Test- Contract';
        testContract.StartDate = System.today()+10;
        testContract.Term = 24;
        testContract.SBQQSC__RenewalTerm__c = 24;
        testContract.EndDate = System.today()+365;
        User u = [SELECT id FROM User WHERE id =: UserInfo.getUserId()];
        System.RunAs(u){
            insert testContract;
            testContract.SBQQSC__RenewalQuoted__c = true;
            testContract.SBQQSC__Opportunity__c = tempopp.Id;
            update testContract;
        }
        System.assertNotEquals(testContract.SBQQSC__Opportunity__c,testContract.SBQQSC__RenewalOpportunity__c,'Not Matching');
    }
    
    static testMethod void csCreationTest2(){
        
        TriggerControl__c triggerCntlr= getTriggerControl();
        insert triggerCntlr;
        insert getTriggerControlCase();
        
        Account ACCT = new Account(Name='Test Account', Phone='123-456-7890', AccountNumber='Test',
                                   BillingStreet = '123 street', BillingCity = 'Santa Clara', BillingState = 'California', BillingPostalCode = '95050', BillingCountry = 'United States');
        insert ACCT;
        QuoteTriggerHandler.disableQuoteTrigger = true;
        Opportunity tempOpp= new Opportunity(name='Temp Opp', OwnerID=UserInfo.getUserId(),accountId=ACCT.id,stagename='Approved',Amount=1000,Lead_Email_Hidden__c='test@email.com',closeDate=Date.today());
        insert tempOpp;
        
        ServiceContract testContract = new ServiceContract();
        testContract.AccountId = ACCT.id;
        testContract.SBQQSC__RenewalOpportunityRecordTypeId__c = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Renewal Opportunity').getRecordTypeId();
        testContract.Name = 'Case Instrument Contract Test- Contract';
        testContract.StartDate = System.today()+10;
        testContract.Term = 24;
        testContract.SBQQSC__RenewalTerm__c = 24;
        testContract.EndDate = System.today()+365;
        testContract.SBQQSC__RenewalOpportunity__c = tempopp.Id;
        testContract.SBQQSC__Opportunity__c = tempopp.Id;
        User u = [SELECT id FROM User WHERE id =: UserInfo.getUserId()];
        System.RunAs(u){
            insert testContract;
            testContract.SBQQSC__RenewalQuoted__c = true;
            update testContract;
        }
       
        System.assertEquals(testContract.SBQQSC__Opportunity__c,testContract.SBQQSC__RenewalOpportunity__c);

    }
}