force-app/main/default/objects/AspenConfig__mdt/AspenConfig__mdt.object-meta.xml
<CustomObject>
    <label>Aspen Config</label>
    <pluralLabel>Aspen Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/AspenConfig__mdt/fields/EmailId__c.field-meta.xml
<CustomField>
    <fullName>EmailId__c</fullName>
    <inlineHelpText>Incase of multiple email address enter comma-separated values</inlineHelpText>
    <label>CM Notification</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Email_Preferences__mdt/Email_Preferences__mdt.object-meta.xml
<CustomObject>
    <description>Used in MissingEntitlementsEmailAlert class which is designed to send emails everyday for Order items that are shipped but no entitlements were generated.</description>
    <label>Email Preferences</label>
    <pluralLabel>Email Preferences</pluralLabel>
</CustomObject>

force-app/main/default/objects/Email_Preferences__mdt/fields/cc__c.field-meta.xml
<CustomField>
    <fullName>cc__c</fullName>
    <label>cc</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Email_Preferences__mdt/fields/Receipient__c.field-meta.xml
<CustomField>
    <fullName>Receipient__c</fullName>
    <label>Receipient</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Sfdc_Disti_Mapping__mdt/Sfdc_Disti_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Sfdc Disti Mapping</label>
    <pluralLabel>Sfdc Disti Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Sfdc_Disti_Mapping__mdt/fields/Distributor_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Email_Address__c</fullName>
    <label>Distributor Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/SandboxRefreshConfigEmailMaskScheduler.cls
public with sharing class SandboxRefreshConfigEmailMaskScheduler implements Schedulable{
    public void execute(SchedulableContext sc) {
        //'Disable Triggers & Validation Rules
        Organization orgInfo = [Select InstanceName, Name, NamespacePrefix, OrganizationType, IsSandbox, PrimaryContact  From Organization];
        if(orgInfo.IsSandbox || Test.isRunningTest()){
            //SandboxRefreshUtil.changeCustomSettingTriggerControl(true);
            SandboxRefreshUtil.disableFunctionalityLogicCustomSetting();
            SandboxRefreshUtil.disableBusinessLogicCustomSetting();
            SandboxRefreshUtil.updateSandboxRefreshConfig('Disable Triggers & Validation Rules', 'Completed', '');
            Database.executebatch(new SandboxRefreshConfigEmailMaskBatch(), 1);
            Database.executebatch(new SandboxRefreshCustomMetadataBatch('Email_Preferences__mdt', new List<String>{'cc__c', 'Receipient__c'},'Email Masking in Email Preference Custom Metadata'), 1);
            SandboxRefreshUtil.updateSandboxRefreshConfig('Email Masking in Email Preference Custom Metadata', 'Processing', '');
            Database.executebatch(new SandboxRefreshCustomMetadataBatch('AspenConfig__mdt', new List<String>{'EmailId__c'},'Email Masking in Aspen Config Custom Metadata'), 1);
            SandboxRefreshUtil.updateSandboxRefreshConfig('Email Masking in Aspen Config Custom Metadata', 'Processing', '');
            Database.executebatch(new SandboxRefreshCustomMetadataBatch('Sfdc_Disti_Mapping__mdt', new List<String>{'Distributor_Email_Address__c'},'Email Masking in Distributor Config Custom Metadata'), 1);
            SandboxRefreshUtil.updateSandboxRefreshConfig('Email Masking in Distributor Config Custom Metadata', 'Processing', '');
            if(!Test.isRunningTest()){
                //Delete Scheduled Reports
                Database.executebatch(new SandboxRefreshReportAbortBatch(), 100);
            }
            SandboxRefreshUtil.updateSandboxRefreshConfig('Delete Scheduled Reports', 'Completed', '');
            
            //Update URL in Admin Tab
            //SandboxRefreshUtil.updateUrlInAdminTab();
            SandboxRefreshUtil.updateSandboxRefreshConfig('Update URL in Admin Tab', 'Completed', '');
        }
    }
}