force-app/main/default/objects/Error_Logs__c/Error_Logs__c.object-meta.xml
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IGL-{00000000}</displayFormat>
        <label>Integration Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Logs__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Message</label>
    <length>130768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Logs__c/fields/Error_Type__c.field-meta.xml
<CustomField>
    <fullName>Error_Type__c</fullName>
    <label>Error Type</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Error_Logs__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&quot;Integration&quot;</defaultValue>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Integration</fullName>
                <default>true</default>
                <label>Integration</label>
            </value>
            <value>
                <fullName>SFDC</fullName>
            </value>
            <value>
                <fullName>Add DealReg on Oppty</fullName>
            </value>
            <value>
                <fullName>RSC Integration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item_Extension__c/Order_Item_Extension__c.object-meta.xml
<CustomObject>
    <description>FY25SR-319 To capture credit calculation data</description>
    <label>OrderItem Extension</label>
    <nameField>
        <label>OrderItem Extension Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderItem Extension</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item_Extension__c/fields/Credit_Calculation_Status__c.field-meta.xml
<CustomField>
    <fullName>Credit_Calculation_Status__c</fullName>
    <description>This field stores the current stage of the credit calculation process for the order item. Values for this field are sourced directly from NetSuite. Any change to this field&apos;s value will automatically trigger the credit calculation process for the associated order item. JIRA Story: FY25SR-319 and FY25SR-1144</description>
    <inlineHelpText>Indicates the current status of the credit calculation. Values are populated from NetSuite. A change in this status triggers the credit calculation.</inlineHelpText>
    <label>Credit Calculation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To process</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item_Extension__c/fields/Failure_Reason__c.field-meta.xml
<CustomField>
    <fullName>Failure_Reason__c</fullName>
    <description>This field stores the specific reason for a failure in the credit calculation process. It&apos;s used to capture and log any errors encountered during the calculation. (Implemented as part of FY25SR-335.)</description>
    <inlineHelpText>The reason why the credit calculation process failed.</inlineHelpText>
    <label>Failure Reason</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order_Item_Extension__c/fields/Order_Line_ID__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>FY25SR-319 Related Order Line</description>
    <label>Order Line ID</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>OrderItem Extension</relationshipLabel>
    <relationshipName>Order_Item_Extensions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item_Extension__c/fields/Paid_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Paid_Quantity__c</fullName>
    <description>This field shows how much of the total quantity of a license a customer has paid for by the end of their paid term.</description>
    <inlineHelpText>How much of the license quantity is paid for by the end of the paid term.</inlineHelpText>
    <label>Paid Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item_Extension__c/fields/Per_DayQuantity_Amount__c.field-meta.xml
<CustomField>
    <fullName>Per_DayQuantity_Amount__c</fullName>
    <description>This field holds the amount of quantity calculated for each day.</description>
    <inlineHelpText>The amount per quantity per day.</inlineHelpText>
    <label>Per DayQuantity Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Item_Extension__c/fields/Quantity_Type__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Type__c</fullName>
    <description>This field tells you if the recorded amount is for a quantity (like number of items) or capacity (like storage space or bandwidth).</description>
    <inlineHelpText>Is this a quantity or a capacity?</inlineHelpText>
    <label>Quantity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quantity</fullName>
            </value>
            <value>
                <fullName>Capacity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item_Extension__c/fields/Remaining_Amount__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Amount__c</fullName>
    <description>This field shows the remaining balance calculated as the Sale Price minus the Sales Order (SO) Line Paid Amount. (Implemented as part of FY25SR-319.)</description>
    <inlineHelpText>The remaining amount after subtracting the paid amount from the sale price.</inlineHelpText>
    <label>Remaining Amount Per Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/OrderItemExtensionHelper.cls
/************************************************************
 * @description       : Order Item Extension Update Helper Class
 * @author            : Ravi
 * @last modified on  : 24-04-2025
 * @last modified by  : Siva Kumar
 * Test class         : OrderItemExtensionTriggerTest
 * Modifications Log
 * Ver   Date          Author        Modification
 * 1.0   24-05-2024   Ravi        Initial Version
 **************************************************************/

public class OrderItemExtensionHelper {
  private static orderItemExtensionHelper OrderItemExtensionHelperInstance = null;
  public Set<Id> orderItemIds = new Set<Id>();
  public list<Order_Item_Extension__c> ordItemExtensionsToProcess = new List<Order_Item_Extension__c>();
  public List<Error_Logs__c> errorLogs = new List<Error_Logs__c>();
  /**
   * @description		Initiate orderItemExtensionHelper it instance is null else retuns the orderItemExtensionHelper instance.
   * @author 			Ravi
   * @last modified on 24-04-2025
   * @return 			orderItemExtensionHelper Instance
   */
  public static orderItemExtensionHelper getInstance() {
    if (OrderItemExtensionHelperInstance == null) {
      OrderItemExtensionHelperInstance = new OrderItemExtensionHelper();
    }
    return OrderItemExtensionHelperInstance;
  }

  /**
   * @description		Intializes OrderItem Extension records with Parent field values.
   * @author 			Ravi
   * @last modified on 24-04-2025
   */
  public void init() {
    if (orderItemIds.isEmpty()) {
      for (Order_Item_Extension__c ordItemExtension : (List<Order_Item_Extension__c>) Trigger.new) {
        if (ordItemExtension.Order_Line_ID__c != null && ordItemExtension.Credit_Calculation_Status__c == 'To process') {
          orderItemIds.add(ordItemExtension.Order_Line_ID__c);
        }
      }
    }
    ordItemExtensionsToProcess = [
      SELECT
        Id,
        Per_DayQuantity_amount__c,
        Paid_Quantity__c,
        Remaining_Amount__c,
        Order_Line_ID__c,
        Order_Line_ID__r.TotalPrice,
        Order_Line_ID__r.SerialNumber__c,
        Order_Line_ID__r.Quantity,
        Order_Line_ID__r.Support_Start_Date__c,
        Order_Line_ID__r.Support_End_Date__c,
        Order_Line_ID__r.UnitPrice,
        Order_Line_ID__r.Product2.Usable_Capacity__c,
        Order_Line_ID__r.Product2.Product_Level__c,
        Order_Line_ID__r.Product2.Bundle_Features__c,
        Order_Line_ID__r.Product2.Product_Type__c,
        Order_Line_ID__r.Product2.Family,
        Order_Line_ID__r.Is_third_party_hardware_line__c
      FROM Order_Item_Extension__c
      WHERE Order_Line_ID__c IN :orderItemIds AND Credit_Calculation_Status__c = 'To Process'
    ];
  }

  /**
   * @description		Calculates Amount fields and Update Status on Order Item Extension when new Order Item Extension record is created.
   * @author 			Ravi
   * @last modified on 24-04-2025
   */
  public void calculateOIECreditAmounts() {
    List<Order_Item_Extension__c> ordItemExtensionsToUpdate = new List<Order_Item_Extension__c>();
    for (Order_Item_Extension__c ordItemExtension : ordItemExtensionsToProcess) {
      try {
        getPerDayQuantityAmountOnItemExtension(ordItemExtension);
        ordItemExtension.Remaining_Amount__c = getRemainingAmount(ordItemExtension);
        ordItemExtension.Credit_Calculation_Status__c = 'Completed';
        ordItemExtensionsToUpdate.add(ordItemExtension);
      } catch (Exception error) {
        ordItemExtensionsToUpdate.add(handleException(ordItemExtension, error));
      }
    }
    if (!ordItemExtensionsToUpdate.isEmpty()) {
      Database.SaveResult[] updateResults = Database.update(ordItemExtensionsToUpdate, false);
      for (Integer i = 0; i < updateResults.size(); i++) {
        if (!updateResults[i].isSuccess()) {
          errorlogs.add(new Error_Logs__c(Error_Type__c = 'Order Item Extension Error', Error_Message__c = updateResults[i].getErrors()[0].getMessage(), Type__c = 'SFDC'));
        }
      }
      if (!errorlogs.isEmpty()) {
        insert errorlogs;
      }
    }
  }

  /**
   * @description							Calculates Per Day Quantity Amount of Order Item extension for V1 SKU TPH & V2 SKU's.
   * Calculate Remaining amount on Order Item extension
   * @author 								Siva Kumar
   * @date 								24-04-2025
   * @param oItemExtension 				OrderItem Extension record on which amount fields needs to be calculate
   */
  private void getPerDayQuantityAmountOnItemExtension(Order_Item_Extension__c oItemExtension) {
    Decimal perDayQuantityAmount = 0;
    Integer totalNoDays = oItemExtension?.Order_Line_ID__r?.Support_Start_Date__c.daysBetween(oItemExtension?.Order_Line_ID__r?.Support_End_Date__c) + 1;
    Decimal totalPrice = (oItemExtension?.Order_Line_ID__r?.TotalPrice != null) ? oItemExtension?.Order_Line_ID__r?.TotalPrice : 0;
    Decimal oItemQuantity = oItemExtension?.Order_Line_ID__r?.Quantity;
    oItemExtension.Quantity_Type__c = 'Quantity';
    oItemExtension.Per_DayQuantity_Amount__c = (totalPrice) / (totalNoDays * oItemQuantity);
  }
  /**
   * @description      This method is used to calculate Remaining Amount on Order Item Extension
   * @param ordItemExtension Order Item Extension record
   * @return Decimal It holds calculated remaining amount value
   */
  private Decimal getRemainingAmount(Order_Item_Extension__c ordItemExtension) {
    Decimal paidQuantity = (ordItemExtension?.Paid_Quantity__c != null) ? ordItemExtension?.Paid_Quantity__c : 0;
    Decimal totalPrice = (ordItemExtension?.Order_Line_ID__r?.TotalPrice != null) ? ordItemExtension?.Order_Line_ID__r?.TotalPrice : 0;
    Decimal unitPrice = (ordItemExtension?.Order_Line_ID__r?.UnitPrice != null) ? ordItemExtension?.Order_Line_ID__r?.UnitPrice : 0;
    Decimal quantity = (ordItemExtension?.Order_Line_ID__r?.Quantity != null) ? ordItemExtension?.Order_Line_ID__r?.Quantity : 0;

    return (totalPrice - (paidQuantity * unitPrice)) / quantity;
  }
  /**
   * @description				Maps failure reason when Order Item extension is failed to calculate Amount values
   * @author 					Siva Kumar
   * @date 					24-04-2025
   * @param failedOIE			OrderItem Externsion which has errors while calculating Amount field values
   * @param error 				Errors during Amount field calculations
   * @return					OrderItem Extension with failure reason
   */
  private Order_Item_Extension__c handleException(Order_Item_Extension__c failedOIE, Exception error) {
    failedOIE.Credit_Calculation_Status__c = 'Failed';
    failedOIE.Failure_Reason__c = error.getMessage();
    return failedOIE;
  }
}