force-app/main/default/objects/Cluster__c/Cluster__c.object-meta.xml
<CustomObject>
    <label>Cluster</label>
    <nameField>
        <label>Cluster UUID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cluster__c/fields/account__c.field-meta.xml
<CustomField>
    <fullName>account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clusters</relationshipLabel>
    <relationshipName>Clusters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cluster__c/fields/Capacity_Days_Until_100__c.field-meta.xml
<CustomField>
    <fullName>Capacity_Days_Until_100__c</fullName>
    <description>Number of days left until the cluster capacity reaches 100%</description>
    <formula>IF(
NOT(ISNULL(Tentative_Date_for_100_Capacity__c)),
IF(
Tentative_Date_for_100_Capacity__c &gt;= TODAY(),
Tentative_Date_for_100_Capacity__c - TODAY(),
0
),
null
)</formula>
    <inlineHelpText>Number of days left until the cluster capacity reaches 100%</inlineHelpText>
    <label>Capacity Days Until 100%</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cluster__c/fields/software_version__c.field-meta.xml
<CustomField>
    <fullName>software_version__c</fullName>
    <label>Software Version</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cluster_Issue__c/Cluster_Issue__c.object-meta.xml
<CustomObject>
    <description>This object (previously known as Cluster Issue) stores the data for issues related to the clusters when the capacity is about to reach 100% or there are some failing jobs</description>
    <label>Customer Proactive Response</label>
    <nameField>
        <displayFormat>CPR-{0000000000}</displayFormat>
        <label>Issue Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Proactive Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cluster_Issue__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Cluster_Issues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cluster_Issue__c/fields/Capacity_Days_Until_100__c.field-meta.xml
<CustomField>
    <fullName>Capacity_Days_Until_100__c</fullName>
    <formula>Cluster__r.Capacity_Days_Until_100__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Capacity Days Until 100%</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cluster_Issue__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Cluster_Issues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cluster_Issue__c/fields/Close_Reason__c.field-meta.xml
<CustomField>
    <fullName>Close_Reason__c</fullName>
    <label>Close Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Case created</fullName>
            </value>
            <value>
                <fullName>Opportunity created</fullName>
            </value>
            <value>
                <fullName>Existing Opportunity</fullName>
            </value>
            <value>
                <fullName>Customer Resolved</fullName>
            </value>
            <value>
                <fullName>Incorrect Forecast data</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cluster_Issue__c/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <label>Cluster</label>
    <referenceTo>Cluster__c</referenceTo>
    <relationshipName>Cluster_Issues</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cluster_Issue__c/fields/Mute_notifications__c.field-meta.xml
<CustomField>
    <fullName>Mute_notifications__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Notifications will not be sent again to Account SE/Owner if checked, until issue priority changes to next higher value</description>
    <inlineHelpText>Notifications will not be sent again to Account SE/Owner if checked, until issue priority changes to next higher value</inlineHelpText>
    <label>Mute notifications?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Cluster_Issue__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Cluster_Issues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cluster_Issue__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>P1</fullName>
                <label>P1 - High</label>
            </value>
            <value>
                <fullName>P2</fullName>
                <label>P2 - Medium</label>
            </value>
            <value>
                <fullName>P3</fullName>
                <label>P3 - Low</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cluster_Issue__c/recordTypes/Read_Only.recordType-meta.xml
<RecordType>
    <fullName>Read_Only</fullName>
    <active>true</active>
    <description>Issue converted to a Case or an Opportunity i.e. Status changed to Closed</description>
    <label>Read Only</label>
</RecordType>

force-app/main/default/objects/Cluster_Issue_Conversion_Mapping__mdt/Cluster_Issue_Conversion_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>This custom metadata type consists of field mapping from for Case/Opportunity creation from Cluster issue conversion</description>
    <label>Cluster Issue Conversion Mapping</label>
    <pluralLabel>Cluster Issue Conversion Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Cluster_Issue_Conversion_Mapping__mdt/fields/Dynamic__c.field-meta.xml
<CustomField>
    <fullName>Dynamic__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dynamic?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Cluster_Issue_Conversion_Mapping__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Case</fullName>
                <default>true</default>
                <label>Case</label>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cluster_Issue_Conversion_Mapping__mdt/fields/Object_Field__c.field-meta.xml
<CustomField>
    <fullName>Object_Field__c</fullName>
    <label>Object Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cluster_Issue_Conversion_Mapping__mdt/fields/Object_Field_Datatype__c.field-meta.xml
<CustomField>
    <fullName>Object_Field_Datatype__c</fullName>
    <label>Object Field Datatype</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cluster_Issue_Conversion_Mapping__mdt/fields/Object_Field_Value__c.field-meta.xml
<CustomField>
    <fullName>Object_Field_Value__c</fullName>
    <label>Object Field Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CreateCaseOrOpportunityController.cls
public with sharing class CreateCaseOrOpportunityController {
    private String clusterIssueId = '';
    private String objectName = '';
    public String recordId {get; set;}
    public String tabId {get; set;}

    public CreateCaseOrOpportunityController(ApexPages.StandardController clusterIssueObject) {
        clusterIssueId = ApexPages.currentPage().getParameters().get('id');
        objectName =  ApexPages.currentPage().getParameters().get('object');
        tabId = ApexPages.currentPage().getParameters().get('tabId');
        recordId = '';
    }

    public PageReference createCaseOrOpportunity() {
        SObject recordToBeInserted;

        List<Cluster_Issue_Conversion_Mapping__mdt> fieldMappingList = [SELECT Id, Object_Field_Value__c, Object_Field__c, Object_Field_Datatype__c, Dynamic__c, Object__c
                                                                        FROM Cluster_Issue_Conversion_Mapping__mdt
                                                                        WHERE Object__c =: objectName];

        Cluster_Issue__c clusterIssueRecord = [SELECT Id, Name, Account__c, Account__r.Name, Account__r.OwnerId,
                                                Cluster__r.Capacity_Days_Until_100__c, Priority__c, Cluster__r.software_version__c,
                                                Case__c, Opportunity__c, Status__c, Close_Reason__c, RecordTypeId
                                                FROM Cluster_Issue__c
                                                WHERE Id =: clusterIssueId];

        //RecordType readOnlyRecordType = [SELECT Id FROM RecordType WHERE DeveloperName = 'Read_Only' AND SobjectType = 'Cluster_Issue__c'];

        if(objectName == 'Case') {
            recordToBeInserted = (SObject)prepareCase(clusterIssueRecord, fieldMappingList);
        }
        else if(objectName == 'Opportunity') {
            recordToBeInserted = (SObject)prepareOpportunity(clusterIssueRecord, fieldMappingList);
        }

        try {
            insert recordToBeInserted;
            recordId = recordToBeInserted.Id;

            if(objectName == 'Case') {
                clusterIssueRecord.Case__c = recordToBeInserted.Id;
            }
            else if(objectName == 'Opportunity') {
                clusterIssueRecord.Opportunity__c = recordToBeInserted.Id;
            }

            clusterIssueRecord.Close_Reason__c = objectName + ' created';
            //clusterIssueRecord.RecordTypeId = readOnlyRecordType.Id;
            clusterIssueRecord.Mute_Notifications__c = true;
            clusterIssueRecord.Status__c = 'Closed';

            update clusterIssueRecord;
        } catch(DmlException e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.error, e.getDmlMessage(0)));
            return null;
        } catch(Exception ex) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.error, ex.getMessage()));
            return null;
        }
        return null;
    }

    public PageReference redirectToCreatedRecord() {
        return new PageReference('/' + recordId);
    }

    private Case prepareCase(Cluster_Issue__c clusterIssueRecord, List<Cluster_Issue_Conversion_Mapping__mdt> fieldMappingList) {
        Case caseObject = new Case();
        caseObject.Subject = clusterIssueRecord.Name;

        if(clusterIssueRecord.Cluster__r.Capacity_Days_Until_100__c != null) {
            caseObject.Subject += ' - ' + (System.Label.Cluster_Utilisation_Message).replace('<days>', String.valueOf(clusterIssueRecord.Cluster__r.Capacity_Days_Until_100__c));
            caseObject.Description = (System.Label.Cluster_Utilisation_Message).replace('<days>', String.valueOf(clusterIssueRecord.Cluster__r.Capacity_Days_Until_100__c));
        }

        caseObject.Software_Version__c = clusterIssueRecord.Cluster__r.software_version__c;

        //Map fields directly from the data stored in Campaign to Opportunity Field mapping custom metadata
        for(Cluster_Issue_Conversion_Mapping__mdt eachField : fieldMappingList) {
            if(eachField.Dynamic__c) {
                caseObject.put(eachField.Object_Field__c, clusterIssueRecord.get(eachField.Object_Field_Value__c));
            }
            else {
                if(eachField.Object_Field_Datatype__c.equalsIgnoreCase('Text')) {
                    caseObject.put(eachField.Object_Field__c, eachField.Object_Field_Value__c);
                }
                /*else if(eachField.Object_Field_Datatype__c.equalsIgnoreCase('Number')) {
                    caseObject.put(eachField.Object_Field__c, Integer.valueOf(eachField.Object_Field_Value__c));
                }
                else if(eachField.Object_Field_Datatype__c.equalsIgnoreCase('Date')) {
                    caseObject.put(eachField.Object_Field__c, System.today() + Integer.valueOf(eachField.Object_Field_Value__c));
                }*/
            }
        }
        return caseObject;
    }

    private Opportunity prepareOpportunity(Cluster_Issue__c clusterIssueRecord, List<Cluster_Issue_Conversion_Mapping__mdt> fieldMappingList) {
        Opportunity opportunityObject = new Opportunity();

        opportunityObject.Name = clusterIssueRecord.Account__r.Name + ' - ' + clusterIssueRecord.Name;

        //Relate the opportunity to the Account of the member who responded to the campaign
        //opportunityObject.AccountId = clusterIssueRecord.Cluster__r.Account__c;

        //Map the owner of the Account of the member who responded to the Opportunity owner
        opportunityObject.OwnerId = clusterIssueRecord.Account__r.OwnerId;

        //Map fields directly from the data stored in Campaign to Opportunity Field mapping custom metadata
        for(Cluster_Issue_Conversion_Mapping__mdt eachField : fieldMappingList) {
            if(eachField.Dynamic__c) {
                opportunityObject.put(eachField.Object_Field__c, clusterIssueRecord.get(eachField.Object_Field_Value__c));
            }
            else {
                if(eachField.Object_Field_Datatype__c.equalsIgnoreCase('Text')) {
                    opportunityObject.put(eachField.Object_Field__c, eachField.Object_Field_Value__c);
                }
                else if(eachField.Object_Field_Datatype__c.equalsIgnoreCase('Number')) {
                    opportunityObject.put(eachField.Object_Field__c, Integer.valueOf(eachField.Object_Field_Value__c));
                }
                else if(eachField.Object_Field_Datatype__c.equalsIgnoreCase('Date')) {
                    opportunityObject.put(eachField.Object_Field__c, System.today() + Integer.valueOf(eachField.Object_Field_Value__c));
                }
            }
        }
        return opportunityObject;
    }
}