force-app/main/default/objects/Cluster__c/Cluster__c.object-meta.xml
<CustomObject>
    <label>Cluster</label>
    <nameField>
        <label>Cluster UUID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cluster__c/fields/software_version__c.field-meta.xml
<CustomField>
    <fullName>software_version__c</fullName>
    <label>Software Version</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cluster__c/fields/tag__c.field-meta.xml
<CustomField>
    <fullName>tag__c</fullName>
    <label>Tag</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cluster__c/fields/uuid__c.field-meta.xml
<CustomField>
    <fullName>uuid__c</fullName>
    <label>UUID</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RMA_Order__c/RMA_Order__c.object-meta.xml
<CustomObject>
    <description>This Object is used to capture RMA requests</description>
    <label>RMA Request</label>
    <nameField>
        <displayFormat>RMA-{0000000}</displayFormat>
        <label>RMA Request #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMA Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMA_Order__c/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <label>Cluster</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RMA_Order__c/fields/Parent_Case__c.field-meta.xml
<CustomField>
    <fullName>Parent_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to capture related case</description>
    <label>Parent Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>RMA_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OrderCaseInfoControllerTest.cls
@isTest
public class OrderCaseInfoControllerTest {
    public static  testmethod void caseInfo(){
        Account ac = new Account(Name='Test account');
        insert ac;
        Contact con = new Contact(LastName = 'test contact', Phone = '9805321262',Email = 'test@gmail.com');
        insert con;
        Cluster__c cl = New Cluster__c(Name = 'test',tag__c = 'test',UUID__c = 'test');
        insert cl;
        Case cs = new Case(Subject='Test case',AccountId = ac.Id, ContactId = con.Id,Cluster__c = cl.Id,Priority = 'Low',Software_Version__c = '5.1.0-EA2-7015',Origin = 'Email',Contact_method__c = 'Email',Problem_Type__c = 'Activity',Current_Status__c = 'testing',Description='test');
        insert cs;
        RMA_Order__C rmaOrder = new RMA_Order__C(Parent_Case__c = cs.Id);
        insert rmaOrder;
        Order ord = new Order(Name = 'Test order',AccountId = ac.Id,EffectiveDate = date.today(),RMA_Request__c = rmaOrder.Id);
        insert ord;
        OrderCaseInfoController oc = new OrderCaseInfoController();
        oc.orderId = ord.Id;
        oc.getCaseInfo();
    }
}