force-app/main/default/objects/Cluster__c/Cluster__c.object-meta.xml
<CustomObject>
    <label>Cluster</label>
    <nameField>
        <label>Cluster UUID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cluster__c/fields/account__c.field-meta.xml
<CustomField>
    <fullName>account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clusters</relationshipLabel>
    <relationshipName>Clusters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cluster__c/fields/Tentative_Date_for_100_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Tentative_Date_for_100_Capacity__c</fullName>
    <label>Tentative Date for 100% Capacity</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cluster__c/fields/uuid__c.field-meta.xml
<CustomField>
    <fullName>uuid__c</fullName>
    <label>UUID</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Cluster_Issue__c/Cluster_Issue__c.object-meta.xml
<CustomObject>
    <description>This object (previously known as Cluster Issue) stores the data for issues related to the clusters when the capacity is about to reach 100% or there are some failing jobs</description>
    <label>Customer Proactive Response</label>
    <nameField>
        <displayFormat>CPR-{0000000000}</displayFormat>
        <label>Issue Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Proactive Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cluster_Issue__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Cluster_Issues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cluster_Issue__c/fields/Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cluster_Issues1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cluster_Issue__c/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <label>Cluster</label>
    <referenceTo>Cluster__c</referenceTo>
    <relationshipName>Cluster_Issues</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cluster_Issue__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cluster_Issues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cluster_Issue__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>P1</fullName>
                <label>P1 - High</label>
            </value>
            <value>
                <fullName>P2</fullName>
                <label>P2 - Medium</label>
            </value>
            <value>
                <fullName>P3</fullName>
                <label>P3 - Low</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MuteNotifOnClusterIssueTest.cls
@isTest(seeAllData=false)
public class MuteNotifOnClusterIssueTest {
    public static testMethod void testMuteNotifOnClusterIssueTest() {
        Account acc = new Account(name='testAcc', OwnerId = UserInfo.getUserId());
        insert acc;

        Cluster__c clusterRecord = new Cluster__c();
        clusterRecord.Name = 'Test Cluster1';
        clusterRecord.uuid__c = 'Test Cluster1';
        clusterRecord.account__c = acc.Id;
        clusterRecord.Tentative_Date_for_100_Capacity__c = System.today() + 20;
        insert clusterRecord;

        Cluster_Issue__c clusterIssueRecord = new Cluster_Issue__c();
        clusterIssueRecord.Cluster__c = clusterRecord.Id;
        clusterIssueRecord.Account__c = acc.Id;
        clusterIssueRecord.Account_Owner__c = acc.OwnerId;
        clusterIssueRecord.Priority__c = 'P2';
        clusterIssueRecord.Status__c = 'Open';
        clusterIssueRecord.Owner__c = acc.OwnerId;
        insert clusterIssueRecord;

        Test.startTest();

        ApexPages.StandardController sc = new ApexPages.StandardController(clusterIssueRecord);
        MuteNotifOnClusterIssueController controllerObject = new MuteNotifOnClusterIssueController(sc);

        PageReference pageRef = Page.MuteNotificationsOnClusterIssue;
        Test.setCurrentPage(pageRef);

        PageReference recordRef = controllerObject.muteNotifications();
        System.assert(recordRef != null);

        clusterIssueRecord.Status__c = 'Opened';

        ApexPages.StandardController sc2 = new ApexPages.StandardController(clusterIssueRecord);
        MuteNotifOnClusterIssueController controllerObject2 = new MuteNotifOnClusterIssueController(sc2);

        PageReference pageRef2 = Page.MuteNotificationsOnClusterIssue;
        Test.setCurrentPage(pageRef2);

        PageReference recordRef2 = controllerObject2.muteNotifications();
        System.assert(recordRef2 == null);

        Test.stopTest();
    }
}