force-app/main/default/objects/Cluster__c/Cluster__c.object-meta.xml
<CustomObject>
    <label>Cluster</label>
    <nameField>
        <label>Cluster UUID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cluster__c/fields/account__c.field-meta.xml
<CustomField>
    <fullName>account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clusters</relationshipLabel>
    <relationshipName>Clusters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cluster__c/fields/archived__c.field-meta.xml
<CustomField>
    <fullName>archived__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Denotes if a cluster has been decommissioned (e.g., end of POC) or an &apos;sdreset&apos; was performed that changed the cluster ID. This allows us to track historical data.</description>
    <inlineHelpText>Denotes if a cluster has been decommissioned (e.g., end of POC) or an &apos;sdreset&apos; was performed that changed the cluster ID. This allows us to track historical data.</inlineHelpText>
    <label>Archived</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Cluster__c/fields/Entitlement__c.field-meta.xml
<CustomField>
    <fullName>Entitlement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entitlement</label>
    <referenceTo>Entitlement</referenceTo>
    <relationshipLabel>Clusters</relationshipLabel>
    <relationshipName>Clusters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entitlement_Use__c/Entitlement_Use__c.object-meta.xml
<CustomObject>
    <description>&quot;SOX object - The end consumer of an entitlement. The end user could be a contact or a cluster or both.
Primarirly used by manaufacturing team.&quot;</description>
    <label>Entitlement Use</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entitlement Uses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Entitlement_Use__c/fields/account__c.field-meta.xml
<CustomField>
    <fullName>account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Entitlement Uses</relationshipLabel>
    <relationshipName>Entitlement_Uses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entitlement_Use__c/fields/activation_date__c.field-meta.xml
<CustomField>
    <fullName>activation_date__c</fullName>
    <description>Activation Date</description>
    <label>Activation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Entitlement_Use__c/fields/actual_usage__c.field-meta.xml
<CustomField>
    <fullName>actual_usage__c</fullName>
    <description>Actual Usage</description>
    <label>Actual Usage</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entitlement_Use__c/fields/archived__c.field-meta.xml
<CustomField>
    <fullName>archived__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is archived</description>
    <label>Archived</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Entitlement_Use__c/fields/cluster__c.field-meta.xml
<CustomField>
    <fullName>cluster__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cluster on which this entitlement is activated / consumed / used / bound.</description>
    <label>Cluster</label>
    <referenceTo>Cluster__c</referenceTo>
    <relationshipLabel>Entitlement Uses</relationshipLabel>
    <relationshipName>Entitlement_Uses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entitlement_Use__c/fields/contact__c.field-meta.xml
<CustomField>
    <fullName>contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>contact id</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Entitlement Uses</relationshipLabel>
    <relationshipName>Entitlement_Uses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entitlement_Use__c/fields/entitlement__c.field-meta.xml
<CustomField>
    <fullName>entitlement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Entitlement ID</description>
    <label>Entitlement</label>
    <referenceTo>Entitlement</referenceTo>
    <relationshipLabel>Entitlement Uses</relationshipLabel>
    <relationshipName>Entitlement_Uses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entitlement_Use__c/fields/node__c.field-meta.xml
<CustomField>
    <fullName>node__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Node</label>
    <referenceTo>Node__c</referenceTo>
    <relationshipLabel>Entitlement Uses</relationshipLabel>
    <relationshipName>Entitlement_Uses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entitlement_Use__c/fields/notes__c.field-meta.xml
<CustomField>
    <fullName>notes__c</fullName>
    <description>General Notes</description>
    <label>Notes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entitlement_Use__c/fields/serial_number__c.field-meta.xml
<CustomField>
    <fullName>serial_number__c</fullName>
    <label>Serial Number</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Entitlement_Use__c/fields/usage_limit__c.field-meta.xml
<CustomField>
    <fullName>usage_limit__c</fullName>
    <description>Usage Limit (e.g. 50TB, 1000VM) -- Usually inferred  as the parent entitlement.</description>
    <label>Usage Limit</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Node__c/Node__c.object-meta.xml
<CustomObject>
    <label>Node</label>
    <nameField>
        <label>Node Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Node__c/fields/cluster__c.field-meta.xml
<CustomField>
    <fullName>cluster__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cluster</label>
    <referenceTo>Cluster__c</referenceTo>
    <relationshipLabel>Nodes</relationshipLabel>
    <relationshipName>Nodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Node__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/EntitlementUsageTest.cls
//Gaurav Jain: Test Data to be created later.
@isTest(SeeAllData=true)
public class EntitlementUsageTest {
	public static testMethod void test_EntitlementUsage () {
        Entitlement_Use__c entitlementUse = [select Id, Name, Account__c, activation_date__c, actual_usage__c, archived__c, cluster__c, contact__c, entitlement__c, notes__c, serial_number__c, usage_limit__c, node__c from Entitlement_Use__c LIMIT 1];
        
		Entitlement_Use__c entitlementUseClone = entitlementUse.clone(false, true, false, false);
        
        entitlementUseClone.serial_number__c += '-1';
        entitlementUseClone.Name += '-1';
        
        insert entitlementUseClone;
        
        delete entitlementUseClone;
        
        undelete entitlementUseClone;
        
        update entitlementUseClone;
    }
}