force-app/main/default/objects/Cluster__c/Cluster__c.object-meta.xml
<CustomObject>
    <label>Cluster</label>
    <nameField>
        <label>Cluster UUID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cluster__c/fields/account__c.field-meta.xml
<CustomField>
    <fullName>account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clusters</relationshipLabel>
    <relationshipName>Clusters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cluster__c/fields/is_callhome_on__c.field-meta.xml
<CustomField>
    <fullName>is_callhome_on__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The Field to track receiving either Stats or live logs from cluster. Will be turned off by PhoneHome when not receiving stats after certain period(7 days)</description>
    <inlineHelpText>To track if we are receiving stats/logs or not, managed by heartbeat</inlineHelpText>
    <label>Receiving CallHome</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Cluster__c/fields/replication_target__c.field-meta.xml
<CustomField>
    <fullName>replication_target__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Replication Target</label>
    <referenceTo>Cluster__c</referenceTo>
    <relationshipLabel>Clusters</relationshipLabel>
    <relationshipName>Clusters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CustomerReportController.cls
public without sharing class CustomerReportController {
    public Map<ID, Account> AccountClusterMap{get;set;}
    public List<Account> fetchAcc{get;set;}
    
    public CustomerReportController(){
        fetchAcc = new List<Account>();
        List<Opportunity> ClosedOpp = New List<Opportunity>();
        Set<Id> AccOppId = new  Set<Id>();
        ClosedOpp=[select id,AccountId,name from Opportunity where StageName ='7 Closed Won'];
    
        for(Opportunity opp :ClosedOpp)
        {
            AccOppId.add(opp.AccountId);
        }
        
        
        fetchAcc = [select id,name,(select id ,name,account__r.Id,is_callhome_on__c from Clusters__r ),(select id,name,AccountID,CloseDate from Opportunities where StageName ='7 Closed Won' )from  Account where id IN : AccOppId];
        
        
        AccountClusterMap = new Map<ID, Account>();
     
       if (fetchAcc.size() > 0)
        {
                for (Account acc :fetchAcc)
                {
                    if(acc.Clusters__r.size() < 1)
                    {
                        AccountClusterMap.put(acc.Id,acc);
                    }
                    
                    for(cluster__C clust :Acc.Clusters__r)
                      {
                            if(clust.is_callhome_on__c == false)
                            {
                                AccountClusterMap.put(acc.Id,acc);
                            }
                        }
                  
                 }
                
            }
 
    }
    
    }