force-app/main/default/objects/Cluster__c/Cluster__c.object-meta.xml
<CustomObject>
    <label>Cluster</label>
    <nameField>
        <label>Cluster UUID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cluster__c/fields/account__c.field-meta.xml
<CustomField>
    <fullName>account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clusters</relationshipLabel>
    <relationshipName>Clusters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cluster__c/fields/Tentative_Date_for_100_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Tentative_Date_for_100_Capacity__c</fullName>
    <label>Tentative Date for 100% Capacity</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cluster__c/fields/uuid__c.field-meta.xml
<CustomField>
    <fullName>uuid__c</fullName>
    <label>UUID</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Cluster_Issue__c/Cluster_Issue__c.object-meta.xml
<CustomObject>
    <description>This object (previously known as Cluster Issue) stores the data for issues related to the clusters when the capacity is about to reach 100% or there are some failing jobs</description>
    <label>Customer Proactive Response</label>
    <nameField>
        <displayFormat>CPR-{0000000000}</displayFormat>
        <label>Issue Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Proactive Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cluster_Issue__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Cluster_Issues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cluster_Issue__c/fields/Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cluster_Issues1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cluster_Issue__c/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <label>Cluster</label>
    <referenceTo>Cluster__c</referenceTo>
    <relationshipName>Cluster_Issues</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cluster_Issue__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cluster_Issues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cluster_Issue__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>P1</fullName>
                <label>P1 - High</label>
            </value>
            <value>
                <fullName>P2</fullName>
                <label>P2 - Medium</label>
            </value>
            <value>
                <fullName>P3</fullName>
                <label>P3 - Low</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateClusterIssueBatchTest.cls
@isTest(seeAllData=false)
public class UpdateClusterIssueBatchTest {
    public static testMethod void testUpdateClusterIssueBatch() {
        List<User> userList = new List<User>();

        Id profileId = [SELECT Id, Name from Profile WHERE Name = 'Sales Operations'].Id;
        User userRecord = new User(
            ProfileId = profileId,
            LastName = 'last',
            Email = 'testuser@test.com',
            Username = System.now().millisecond() + 'testuser@test.com',
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            Employee_Time_Off__c = true);
        insert userRecord;

        Account acc = new Account(name='testAcc', OwnerId = userRecord.Id);
        insert acc;

        List<Cluster__c> clusterList = new List<Cluster__c>();
        Cluster__c clusterRecord = new Cluster__c();
        clusterRecord.Name = 'Test Cluster1';
        clusterRecord.uuid__c = 'Test Cluster1';
        clusterRecord.account__c = acc.Id;
        clusterRecord.Tentative_Date_for_100_Capacity__c = System.today() + 20;
        clusterList.add(clusterRecord);

        clusterRecord = new Cluster__c();
        clusterRecord.Name = 'Test Cluster2';
        clusterRecord.uuid__c = 'Test Cluster2';
        clusterRecord.account__c = acc.Id;
        clusterRecord.Tentative_Date_for_100_Capacity__c = System.today() + 100;
        clusterList.add(clusterRecord);

        insert clusterList;

        List<Cluster_Issue__c> clusterIssueList = new List<Cluster_Issue__c>();
        Cluster_Issue__c clusterIssueRecord = new Cluster_Issue__c();
        clusterIssueRecord.Cluster__c = clusterList[0].Id;
        clusterIssueRecord.Account__c = acc.Id;
        clusterIssueRecord.Account_Owner__c = acc.OwnerId;
        clusterIssueRecord.Priority__c = 'P2';
        clusterIssueRecord.Status__c = 'Open';
        clusterIssueRecord.Owner__c = acc.OwnerId;
        clusterIssueList.add(clusterIssueRecord);

        clusterIssueRecord = new Cluster_Issue__c();
        clusterIssueRecord.Cluster__c = clusterList[1].Id;
        clusterIssueRecord.Account__c = acc.Id;
        clusterIssueRecord.Account_Owner__c = acc.OwnerId;
        clusterIssueRecord.Priority__c = 'P3';
        clusterIssueRecord.Status__c = 'Open';
        clusterIssueRecord.Owner__c = acc.OwnerId;
        clusterIssueList.add(clusterIssueRecord);

        insert clusterIssueList;

        User currentUser = [SELECT Id FROM User WHERE Id =: UserInfo.getUserId()];

        System.runAs(userRecord) {
            acc.OwnerId = currentUser.Id;
            acc.Rubrik_Sales_Engineer__c = currentUser.Id;
            update acc;
        }

        clusterList[0].Tentative_Date_for_100_Capacity__c = System.today() + 10;
        clusterList[1].Tentative_Date_for_100_Capacity__c = System.today() + 80;
        update clusterList;

        Test.startTest();

        Database.executeBatch(new UpdateClusterIssueOnCapacityChangeBatch(), 200);

        Test.stopTest();

        Cluster_Issue__c clusterIssue = [SELECT Id, Owner__c FROM Cluster_Issue__c LIMIT 1];
        System.assert(clusterIssue.Owner__c == currentUser.Id);
    }
}