force-app/main/default/objects/Cluster__c/Cluster__c.object-meta.xml
<CustomObject>
    <label>Cluster</label>
    <nameField>
        <label>Cluster UUID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cluster__c/fields/account__c.field-meta.xml
<CustomField>
    <fullName>account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clusters</relationshipLabel>
    <relationshipName>Clusters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cluster__c/fields/archived__c.field-meta.xml
<CustomField>
    <fullName>archived__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Denotes if a cluster has been decommissioned (e.g., end of POC) or an &apos;sdreset&apos; was performed that changed the cluster ID. This allows us to track historical data.</description>
    <inlineHelpText>Denotes if a cluster has been decommissioned (e.g., end of POC) or an &apos;sdreset&apos; was performed that changed the cluster ID. This allows us to track historical data.</inlineHelpText>
    <label>Archived</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Node__c/Node__c.object-meta.xml
<CustomObject>
    <label>Node</label>
    <nameField>
        <label>Node Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Node__c/fields/asset__c.field-meta.xml
<CustomField>
    <fullName>asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Nodes</relationshipLabel>
    <relationshipName>Nodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Node__c/fields/cluster__c.field-meta.xml
<CustomField>
    <fullName>cluster__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cluster</label>
    <referenceTo>Cluster__c</referenceTo>
    <relationshipLabel>Nodes</relationshipLabel>
    <relationshipName>Nodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ClusterAccountUpdate.cls
public with sharing class ClusterAccountUpdate implements Database.Batchable<SObject>, Schedulable{
    public void execute(SchedulableContext sc){
        ClusterAccountUpdate ob = new ClusterAccountUpdate();
        Database.executeBatch(ob, 100);
    }

    public Database.Querylocator start(Database.BatchableContext BC){
        return Database.getQueryLocator('Select Id, Account__c, (Select Id, Asset__c, Asset__r.AccountId from Nodes__r where Asset__c != null) from Cluster__c where archived__c = false');
    }

    public void execute(Database.BatchableContext BC,List<Cluster__c> scope){
        List<Cluster__c> clustersToUpdate = new List<Cluster__c>();
        for(Cluster__c cluster: scope){
            if(cluster.Nodes__r.size()==0){
                continue;
            }
            
            Id accountId = null;
            for(Node__c node: cluster.Nodes__r){
                if(accountId == null){
                    accountId = node.Asset__r.AccountId;
                }
                else if(accountId != node.Asset__r.AccountId){
                    accountId = null;
                    break;
                }
            }

            if(accountId == null){
                continue;
            }

            if(cluster.Account__c != accountId){
                clustersToUpdate.add(new Cluster__c(Id = cluster.Id, Account__c = accountId));
            }
        }

        if(clustersToUpdate.size()>0){
            update clustersToUpdate;
        }
    }

    public void finish(Database.BatchableContext BC){
    }


}