force-app/main/default/objects/Booking_Line_Item__c/Booking_Line_Item__c.object-meta.xml
<CustomObject>
    <description>SOX object - To capture booking line item associated with booking and debooking</description>
    <label>Booking Line Item</label>
    <nameField>
        <displayFormat>BLI-{0000000}</displayFormat>
        <label>Booking Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TriggerControl__c/TriggerControl__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This setting is used to disable triggers dynamically without updating code</description>
    <label>TriggerControl</label>
</CustomObject>

force-app/main/default/objects/TriggerControl__c/fields/DisableTrigger__c.field-meta.xml
<CustomField>
    <fullName>DisableTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox is used as an ON/OFF flag to disable the respective trigger</description>
    <label>Disable Trigger?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BookingLineItemHandler.cls
/***************************************************************************** 
* @description       : This is a handler class for Booking Line Item trigger
* @author            : Prashik
* @last modified on  : 10-06-2025
* @last modified by  : Prashik
* Modifications Log
* Ver   Date          Author               Modification
* 1.0   10-06-2025    Prashik              Initial Version/PRDOPS26-982
******************************************************************************/
public with sharing class BookingLineItemHandler extends TriggerHandler {
  /**
  * @description This method handler before insert context
  */
  public override void beforeUpdate() {
    if(TriggerControl__c.getInstance('Booking') != null && TriggerControl__c.getInstance('Booking').DisableTrigger__c) {
        return;
    }
    BookingLineItemHelper.validateBookingUpdatePermissions((Map<Id,Booking_Line_Item__c>) Trigger.newMap,(Map<Id,Booking_Line_Item__c>) Trigger.oldMap);
  }


}