force-app/main/default/objects/Replacement_Field_Mapping__mdt/Replacement_Field_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Replacement Field Mapping</label>
    <pluralLabel>Replacement Field Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Replacement_Field_Mapping__mdt/fields/Product_Type_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type_Sub_Type__c</fullName>
    <description>This field holds value for SKU Replacement Screen for holding attributes</description>
    <label>Product Type/Sub Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Replacement_Field_Mapping__mdt/fields/SKU_Attribute_Fields__c.field-meta.xml
<CustomField>
    <fullName>SKU_Attribute_Fields__c</fullName>
    <label>SKU Attribute Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ReplacementFieldMetadata.cls
/***********************************************************************************************************
      * Class Name          : ReplacementFieldMetadata
      * Date Created/Modified: 24/05/2024
      * Author               : Rahul
      * @description         : This method fetches the mock custom metadata details
/**********************************************************************************************************/
public virtual class ReplacementFieldMetadata {
  static ReplacementFieldMetadata service = new ReplacementFieldMetadata();
  /***********************************************************************************************************
    * Method Name          : setMock
    * Date Created/Modified: 24/05/2024
    * Author               : Rahul
    * @description         : This method fetches the mock custom metadata details
    * @param mock
  /**********************************************************************************************************/
  @TestVisible
  static void setMock(ReplacementFieldMetadata mock) {
      service = mock;
  }
  /***********************************************************************************************************
    * Method Name          : getAll
    * Date Created/Modified: 24/05/2024
    * Author               : Rahul
    * @description         : This method fetches the quote details
    * @return              : getAllInternal
  /**********************************************************************************************************/
  public static List<Replacement_Field_Mapping__mdt> getAll() {
      return service.getAllInternal();
  }
  /***********************************************************************************************************
    * Method Name          : getQuoteDetails
    * Date Created/Modified: 24/05/2024
    * Author               : Shivani
    * @description         : This method fetches the quote details
    * @return              : List of custom metadata records
  /**********************************************************************************************************/
  @TestVisible
  protected virtual List<Replacement_Field_Mapping__mdt> getAllInternal() {
      return [SELECT Id, Product_Type_Sub_Type__c, SKU_Attribute_Fields__c FROM Replacement_Field_Mapping__mdt];
  }
}