force-app/main/default/objects/CCR__c/CCR__c.object-meta.xml
<CustomObject>
    <description>SOX object - Actively used object to submit Compensation adjustment requests by the Sales team like additional commissions to Sales Reps, split ratio of commissions between Sales Reps etc</description>
    <label>CCR</label>
    <nameField>
        <displayFormat>CCR-{0000000}</displayFormat>
        <label>CCR #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCRs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CCR__c/fields/Incentive__c.field-meta.xml
<CustomField>
    <fullName>Incentive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Incentive</label>
    <referenceTo>Incentives__c</referenceTo>
    <relationshipLabel>CCRs</relationshipLabel>
    <relationshipName>CCRs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCR__c/fields/Partner_REP_Amount__c.field-meta.xml
<CustomField>
    <fullName>Partner_REP_Amount__c</fullName>
    <label>Partner Payee Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CCR__c/fields/Partner_Rep_Email__c.field-meta.xml
<CustomField>
    <fullName>Partner_Rep_Email__c</fullName>
    <label>Partner Payee Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/CCR__c/fields/Partner_SE_Amount__c.field-meta.xml
<CustomField>
    <fullName>Partner_SE_Amount__c</fullName>
    <label>Partner SE Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/PC_TilesInformation.cls
public without sharing class PC_TilesInformation {
    @AuraEnabled
    public static decimal claimDetails(){
        string LoggedinEmail;
        decimal totalAmount=0;
        User u=[select id ,email from user where id=:UserInfo.getUserID()];
        if(!string.isblank(u.email)){
            LoggedinEmail=u.email;
            system.debug('@@ LoggedinEmail '+LoggedinEmail); 
            for(CCR__c cr:[select id,Incentive__c,Partner_Rep_Email__c,Partner_REP_Amount__c,Partner_SE_Amount__c,Partner_SE_Email__c from CCR__c]){
                if(LoggedinEmail==cr.Partner_Rep_Email__c && cr.Partner_REP_Amount__c!=null ){
                    totalAmount+=cr.Partner_REP_Amount__c;
                }
                if( LoggedinEmail==cr.Partner_SE_Email__c && cr.Partner_SE_Amount__c!=null){
                    totalAmount+=cr.Partner_SE_Amount__c;
                }
            }
			system.debug('@@ totalAmount '+totalAmount);           
        }
        return totalAmount;
    }
}