force-app/main/default/objects/CCR__c/CCR__c.object-meta.xml
<CustomObject>
    <description>SOX object - Actively used object to submit Compensation adjustment requests by the Sales team like additional commissions to Sales Reps, split ratio of commissions between Sales Reps etc</description>
    <label>CCR</label>
    <nameField>
        <displayFormat>CCR-{0000000}</displayFormat>
        <label>CCR #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCRs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CCR__c/fields/CCR_Type__c.field-meta.xml
<CustomField>
    <fullName>CCR_Type__c</fullName>
    <label>CCR Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Partner Rebate</fullName>
            </value>
            <value>
                <fullName>Territory Split</fullName>
            </value>
            <value>
                <fullName>Virgin / Non-Virgin Territory &amp; Quota</fullName>
            </value>
            <value>
                <fullName>Draw(s) AE/SE</fullName>
            </value>
            <value>
                <fullName>Manager Burden Change</fullName>
            </value>
            <value>
                <fullName>Official Change from Payer Coach to Manager</fullName>
            </value>
            <value>
                <fullName>PROMO</fullName>
            </value>
            <value>
                <fullName>Marketing SPIFF</fullName>
            </value>
            <value>
                <fullName>Channel SPIFF</fullName>
            </value>
            <value>
                <fullName>Sales SPIFF</fullName>
            </value>
            <value>
                <fullName>Partner Referral Fee</fullName>
            </value>
            <value>
                <fullName>Concession Request - Returns</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Change in Booking Policy / De-Risk Decision</fullName>
            </value>
            <value>
                <fullName>Customer Returns / Refunds</fullName>
            </value>
            <value>
                <fullName>Non-Payment</fullName>
            </value>
            <value>
                <fullName>Unpaid Replacement Debooking</fullName>
            </value>
            <value>
                <fullName>Compensation Exception</fullName>
            </value>
            <value>
                <fullName>Manual Compensation Transaction</fullName>
            </value>
            <value>
                <fullName>Incorrect Order/Mis-quote</fullName>
            </value>
            <value>
                <fullName>Bonus</fullName>
                <isActive>false</isActive>
                <label>Bonus</label>
            </value>
            <value>
                <fullName>Change ICP</fullName>
                <isActive>false</isActive>
                <label>Change ICP</label>
            </value>
            <value>
                <fullName>Commission Relief</fullName>
                <isActive>false</isActive>
                <label>Commission Relief</label>
            </value>
            <value>
                <fullName>Draw</fullName>
                <isActive>false</isActive>
                <label>Draw</label>
            </value>
            <value>
                <fullName>Free Unit</fullName>
                <isActive>false</isActive>
                <label>Free Unit</label>
            </value>
            <value>
                <fullName>Holdovers</fullName>
                <isActive>false</isActive>
                <label>Holdovers</label>
            </value>
            <value>
                <fullName>ICP Change</fullName>
                <isActive>false</isActive>
                <label>ICP Change</label>
            </value>
            <value>
                <fullName>Late / Non Payment</fullName>
                <isActive>false</isActive>
                <label>Late / Non Payment</label>
            </value>
            <value>
                <fullName>Manager Change</fullName>
                <isActive>false</isActive>
                <label>Manager Change</label>
            </value>
            <value>
                <fullName>OTI Change</fullName>
                <isActive>false</isActive>
                <label>OTI Change</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCR__c/fields/Partner_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Partner_Company_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Company Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CCRs (Partner Company Name)</relationshipLabel>
    <relationshipName>CCRs1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCR__c/fields/Partner_SE_Name__c.field-meta.xml
<CustomField>
    <fullName>Partner_SE_Name__c</fullName>
    <label>Partner SE Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCR__c/fields/Partner_SE_Phone__c.field-meta.xml
<CustomField>
    <fullName>Partner_SE_Phone__c</fullName>
    <label>Partner SE Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Incentives__c/Incentives__c.object-meta.xml
<CustomObject>
    <description>SOX object - Used to capture Transform Accelerator Claims for the Partner &apos;Transform Program&apos; Point System. Also used to capture Channel SPIFF Claims.</description>
    <label>Incentive</label>
    <nameField>
        <label>Incentives Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incentives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Incentives__c/fields/CCR_Type__c.field-meta.xml
<CustomField>
    <fullName>CCR_Type__c</fullName>
    <label>Incentive Form</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Brik_Dollar_Incentive_Claim_Req</fullName>
                <label>Meeting Form</label>
            </value>
            <value>
                <fullName>North_America_and_ANZ</fullName>
                <label>Deal Registration Form</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Incentives__c/fields/Primary_role__c.field-meta.xml
<CustomField>
    <fullName>Primary_role__c</fullName>
    <label>Primary role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Executive</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Incentives__c/recordTypes/Incentive.recordType-meta.xml
<RecordType>
    <fullName>Incentive</fullName>
    <active>true</active>
    <label>Incentive</label>
</RecordType>

force-app/main/default/classes/PC_IncentiveController.cls
public class PC_IncentiveController {
    /** For Getting User Details **/
    @AuraEnabled
    public Static User getUserDetails(){
        User partner = [select Id, Name, Email, Phone,AccountID,Contact.Account.Distributor__c, Contact.Account.Distributor__r.Name, 
                        Contact.Account.Name,SmallPhotoUrl,FullPhotoUrl,country,CompanyName,Contact.Account.Type,Contact.AccountId, IsActive,Contact.Primary_Role__c 
                        from User 
                        where id=:UserInfo.getUserId()];
        return partner;
    }
    /**
    * @description This method is used for getting Incentive record.
    * @param incentiveId Get the incentive record based on Id.
    * @return Incentives__c record based on Id.
    */
    @AuraEnabled
    public Static Incentives__c getIncentiveForm(Id incentiveId){
        Incentives__c incentive = [select Id, Name, CCR_Type__c from Incentives__c where id =:incentiveId];
        return incentive;
    }
    
    /** Saving CCR record **/
    @AuraEnabled
    public static string saveCcrRecord(CCR__c record,string ccrtype){
        string result;
        record.CCR_Type__c = ccrtype;
        
        /** based on new form Change  **/
        //User loggedInUser = [Select id,contactId,Contact.AccountId from User where id=:UserInfo.getUserId()];
       // string partnerco = loggedInUser.Contact.AccountId;
       // record.Partner_Company_Name__c=partnerco;
        //record.CCR_Type__c = ccrtype;
        /*List<AccountTeamMember>  accTeamMember = [SELECT AccountId,Id,TeamMemberRole,UserId,User.Email,User.Name,User.Phone FROM AccountTeamMember WHERE
                                                  AccountId =:partnerco AND TeamMemberRole = 'Sales Engineer' LIMIT 1];
        if(accTeamMember.size()>0)   {
            record.Partner_SE_Name__c = accTeamMember[0].User.name;
            if(!string.isBlank(accTeamMember[0].User.email))
                record.Partner_SE_Email__c = accTeamMember[0].User.email;
            if(!string.isBlank(accTeamMember[0].User.Phone))
                record.Partner_SE_Phone__c = accTeamMember[0].User.Phone;
        }  */
        Database.DMLOptions dml = new Database.DMLOptions();
        dml.DuplicateRuleHeader.allowSave = true;
        dml.DuplicateRuleHeader.runAsCurrentUser = true; 
        Database.SaveResult sr = Database.insert(record, dml);
        
        //PRIT26-20 : Changed logic to show error
        if (sr.isSuccess()) {
            result = sr.getId();
        }else {
            for(Database.Error err : sr.getErrors()) {
                result = result != null? result + err.getMessage() + '\n' : err.getMessage() + '\n';
            }
        }
        
        return result;
    }
}