force-app/main/default/objects/CCR__c/CCR__c.object-meta.xml
<CustomObject>
    <description>SOX object - Actively used object to submit Compensation adjustment requests by the Sales team like additional commissions to Sales Reps, split ratio of commissions between Sales Reps etc</description>
    <label>CCR</label>
    <nameField>
        <displayFormat>CCR-{0000000}</displayFormat>
        <label>CCR #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCRs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CCR__c/fields/Justifications__c.field-meta.xml
<CustomField>
    <fullName>Justifications__c</fullName>
    <description>Justifications based on selected CCR Type , Only for Internal CCRs</description>
    <label>Justifications</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CCR_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OTE Change</fullName>
            </value>
            <value>
                <fullName>AE/SE/SDR mapping change</fullName>
            </value>
            <value>
                <fullName>Bookings Quota</fullName>
            </value>
            <value>
                <fullName>Logo Quota Change</fullName>
            </value>
            <value>
                <fullName>Request Draw</fullName>
            </value>
            <value>
                <fullName>Competitive Pricing</fullName>
            </value>
            <value>
                <fullName>Cohesity Specific Situation</fullName>
            </value>
            <value>
                <fullName>Legacy Pricing</fullName>
            </value>
            <value>
                <fullName>Legacy List Price / Price Floors</fullName>
            </value>
            <value>
                <fullName>Sales Engineer Credit Exception</fullName>
            </value>
            <value>
                <fullName>Bonus</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Promotion</fullName>
            </value>
            <value>
                <fullName>Commissionable credit exception</fullName>
            </value>
            <value>
                <fullName>SPIFF eligibility exception</fullName>
            </value>
            <value>
                <fullName>Global Account Crediting</fullName>
            </value>
            <value>
                <fullName>Global Commissionable Credit Exception</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCR__c/fields/Number_of_Attchments__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Attchments__c</fullName>
    <label># of Attchments</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LCC_Submit_for_Approval_CCR_Controller.cls
public class LCC_Submit_for_Approval_CCR_Controller {
    @AuraEnabled
    public static string ccrApproval(String recId){  
        String validate  = SubmitCCRValidation.ApprovalValidation(recId);
        CCR__c ccrRec = [Select Id,Justifications__c,Number_of_Attchments__c  from CCR__c where Id =:recId];
        if(validate=='No error'){
            if(ccrRec.Justifications__c == 'Cohesity Specific Situation' && ccrRec.Number_of_Attchments__c < 2)
            {
                return 'CCR must be have 2 attachments before submitting for approval when Justification is Cohesity Specific Situation';
            }
            else{
                Approval.ProcessSubmitRequest reqApproval = new Approval.ProcessSubmitRequest();
                reqApproval.setComments('Submitting request for approval.');
                reqApproval.setObjectId(ccrRec.id);
                try{
                    Approval.ProcessResult result = Approval.process(reqApproval);
                }catch(Exception e)
                {
                    return e.getMessage();
                }
                
                return 'Approved';        
            }
        }else{
            return validate;
        }
    }
}