force-app/main/default/objects/Marketing_GetFeedback_Survey__c/Marketing_GetFeedback_Survey__c.object-meta.xml
<CustomObject>
    <label>Marketing GetFeedback Survey</label>
    <nameField>
        <label>Marketing GetFeedback Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing GetFeedback Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_GetFeedback_Survey__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Marketing GetFeedback Surveys</relationshipLabel>
    <relationshipName>Marketing_GetFeedback_Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketing_GetFeedback_Survey__c/fields/Area_of_interest_next__c.field-meta.xml
<CustomField>
    <fullName>Area_of_interest_next__c</fullName>
    <label>Area of interest next</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Security</fullName>
            </value>
            <value>
                <fullName>Backup</fullName>
            </value>
            <value>
                <fullName>Cloud</fullName>
            </value>
            <value>
                <fullName>Disaster Recovery</fullName>
            </value>
            <value>
                <fullName>Data Governance</fullName>
            </value>
            <value>
                <fullName>Ransomware</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_GetFeedback_Survey__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Marketing GetFeedback Surveys</relationshipLabel>
    <relationshipName>Marketing_GetFeedback_Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MarketingFeedbackTriggerHandlerTest.cls
@isTest public with sharing class MarketingFeedbackTriggerHandlerTest {
    @isTest static void setMarketingFeedbackSurveyLastReceivedDate(){
        
        Account act = (Account) ShGl_TestFactory.createSObject(new Account(), null);
        insert act;
        List<Contact> conList = (List<Contact>)ShGl_TestFactory.createSObjectList(new Contact(), 3, null);
        conList[0].AccountId = act.Id;
        conList[0].Primary_Customer_Mailing_Contact__c = TRUE;
        conList[1].AccountId = act.Id;
        conList[1].Primary_Customer_Mailing_Contact__c = TRUE;
        conList[2].AccountId = act.Id;
        insert conList;
        
        test.starttest();
        try{
            Marketing_GetFeedback_Survey__c objSurvey = new Marketing_GetFeedback_Survey__c();
            objSurvey.Account__c = act.Id;
            objSurvey.Contact__c = conList[0].Id;
            objSurvey.Name = 'Test Survey - 001';
            objSurvey.Area_of_interest_next__c = 'Security';
            insert objSurvey;
        }catch(Exception e){
            
        }

        test.stoptest();
        system.assert( [Select Last_Marketing_GetFeedBack_Date__c From Contact Where Id=:conList[0].Id LIMIT 1].Last_Marketing_GetFeedBack_Date__c == Date.today() );
    }
}