force-app/main/default/objects/Deal_Desk_Case__c/Deal_Desk_Case__c.object-meta.xml
<CustomObject>
    <description>SOX object - Custom Object</description>
    <label>Deal Desk Case</label>
    <nameField>
        <displayFormat>DDC-{000000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Desk Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Desk_Case__c/fields/Amount_Conditional__c.field-meta.xml
<CustomField>
    <fullName>Amount_Conditional__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Desk_Case__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>In Queue</fullName>
                <isActive>false</isActive>
                <label>In Queue</label>
            </value>
            <value>
                <fullName>Requested</fullName>
                <isActive>false</isActive>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Revoked</fullName>
                <isActive>false</isActive>
                <label>Revoked</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Desk_Case__c/fields/Business_Justification__c.field-meta.xml
<CustomField>
    <fullName>Business_Justification__c</fullName>
    <label>What Do You Need Help With?</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Deal_Desk_Case__c/fields/Deal_Desk_Team__c.field-meta.xml
<CustomField>
    <fullName>Deal_Desk_Team__c</fullName>
    <inlineHelpText>Select Deal Structuring if you need help with discounting, quote approvals, structuring or pricing.

Select Deal Operations for help with system errors, quoting bugs or enablement.</inlineHelpText>
    <label>Deal Desk Team</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deal Structuring</fullName>
            </value>
            <value>
                <fullName>Deal Operations</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Desk_Case__c/fields/ETM_Area__c.field-meta.xml
<CustomField>
    <fullName>ETM_Area__c</fullName>
    <label>ETM (Area)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Desk_Case__c/fields/ETM_Theatre__c.field-meta.xml
<CustomField>
    <fullName>ETM_Theatre__c</fullName>
    <label>ETM (Theatre)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Desk_Case__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Desk Cases</relationshipLabel>
    <relationshipName>Deal_Desk_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Desk_Case__c/fields/Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Request_Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Closed - Completed</fullName>
            </value>
            <value>
                <fullName>Closed - Incomplete</fullName>
            </value>
            <value>
                <fullName>Conditionally Approved</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Modification Requested</fullName>
                <isActive>false</isActive>
                <label>Modification Requested</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Desk_Case__c/fields/Request_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Sub_Type__c</fullName>
    <label>Request Sub-Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1 Year: FED/SLED</fullName>
            </value>
            <value>
                <fullName>Add-On Node</fullName>
            </value>
            <value>
                <fullName>Approval Issues</fullName>
            </value>
            <value>
                <fullName>ASPEN</fullName>
            </value>
            <value>
                <fullName>Below Minimum Amount (Deal or Product)</fullName>
            </value>
            <value>
                <fullName>Below Minimum Term</fullName>
            </value>
            <value>
                <fullName>Best Practices Enablement</fullName>
            </value>
            <value>
                <fullName>Cohesity Take Out</fullName>
            </value>
            <value>
                <fullName>Complete Quoting</fullName>
            </value>
            <value>
                <fullName>CPQ Bug</fullName>
            </value>
            <value>
                <fullName>CSAT</fullName>
            </value>
            <value>
                <fullName>Custom Deal Structure</fullName>
            </value>
            <value>
                <fullName>Custom Legal Verbiage</fullName>
            </value>
            <value>
                <fullName>Deal Ops Exception</fullName>
            </value>
            <value>
                <fullName>Delayed Start Date</fullName>
            </value>
            <value>
                <fullName>Discount Beyond Hard Floor</fullName>
            </value>
            <value>
                <fullName>Downgrade Request</fullName>
            </value>
            <value>
                <fullName>E1000</fullName>
            </value>
            <value>
                <fullName>E1000’s Request</fullName>
            </value>
            <value>
                <fullName>Entitlement Transfer</fullName>
            </value>
            <value>
                <fullName>Error Message</fullName>
            </value>
            <value>
                <fullName>Expiration Date Change</fullName>
            </value>
            <value>
                <fullName>Expiration Date Update</fullName>
            </value>
            <value>
                <fullName>Extended Payment Terms</fullName>
            </value>
            <value>
                <fullName>Financial Stability Letter</fullName>
            </value>
            <value>
                <fullName>Flip quote</fullName>
            </value>
            <value>
                <fullName>HW Only Quoting</fullName>
            </value>
            <value>
                <fullName>License Transfer</fullName>
            </value>
            <value>
                <fullName>Limited Availability</fullName>
            </value>
            <value>
                <fullName>M365 Beachhead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Desk_Case__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Deal_Desk_Team__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deal Ops Exception</fullName>
            </value>
            <value>
                <fullName>General Inquiry</fullName>
            </value>
            <value>
                <fullName>Legal Language</fullName>
            </value>
            <value>
                <fullName>Minimum or Maximum Discount, Floor, or Term Exceptions</fullName>
            </value>
            <value>
                <fullName>Non-Standard Payments</fullName>
            </value>
            <value>
                <fullName>Non-Standard Programs / Deal Structures</fullName>
            </value>
            <value>
                <fullName>Quoting Bug</fullName>
            </value>
            <value>
                <fullName>Renewal Quote</fullName>
            </value>
            <value>
                <fullName>Exception Quoting</fullName>
                <isActive>false</isActive>
                <label>Exception Quoting</label>
            </value>
            <value>
                <fullName>GTM Program Exceptions</fullName>
                <isActive>false</isActive>
                <label>GTM Program Exceptions</label>
            </value>
            <value>
                <fullName>Product Usage Exceptions</fullName>
                <isActive>false</isActive>
                <label>Product Usage Exceptions</label>
            </value>
            <value>
                <fullName>Term, Floor, Deal Size Threshold</fullName>
                <isActive>false</isActive>
                <label>Term, Floor, Deal Size Threshold</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DdcLwcControllerTest.cls
@isTest
public class DdcLwcControllerTest {
    @TestSetup
    static void setupMethod(){
        
        List<Profile> listProfile = new List<Profile>();
        listProfile = [Select Id
                       From Profile
                       Where Name = 'Rubrik Inside Sales'
                       OR Name = 'System Administrator'
                       Order By Name
                      ];
        
        List<User> listUser = TestDataFactory.getUsers('testClassUser', new Set<Id>{listProfile[0].Id}, 3);
        
        listUser.addAll(TestDataFactory.getUsers('testClassUserAdmin', new Set<Id>{listProfile[1].Id}, 1));
        
        insert listUser;
        
        
        
        List<Group> listGroup = TestDataFactory.getGroups('Test Group', 2);
        
        System.runAs (listUser[3]) {
            insert listGroup;
            
            List<GroupMember> listGroupMember =
                TestDataFactory.getGroupMembers(listGroup[0].Id, new Set<Id>{listUser[1].Id, listUser[2].Id});
            listGroupMember.addAll(TestDataFactory.getGroupMembers(listGroup[1].Id, new Set<Id>{listUser[2].Id}));
            insert listGroupMember;
        }
        
        Opportunity objOpportunity = TestDataFactory.getOpportunity();
        insert objOpportunity;
        
        List<SBQQ__Quote__c> listQuote = TestDataFactory.getQuotes(new Set<Id>{objOpportunity.Id}, 1);
        insert listQuote;
        
        List<sbaa__Approver__c> listApprover =
            TestDataFactory.getApprovers(
                new Set<Id> {
                    listUser[0].Id,
                        listUser[1].Id,
                        listUser[2].Id,
                        listUser[3].Id
                        },
                new Set<Id> {
                    listGroup[0].Id,
                        listGroup[1].Id
                        }
            );
        insert listApprover;
        
        Deal_Desk_Case__c ddCase = new Deal_Desk_Case__c();
        ddCase.Deal_Desk_Team__c = 'Deal Structuring';
        ddCase.Amount_Conditional__c = 100;
        ddCase.Request_Type__c = 'General Inquiry';
        ddCase.Request_Sub_Type__c = 'Below Minimum Term';
        //ddCase.Request_Status__c = 'Draft';
        ddCase.Business_Justification__c = 'minimum characters';
        ddCase.ETM_Theatre__c = 'EMEA';
        ddCase.Opportunity__c = objOpportunity.Id;
        ddCase.ETM_Area__c = 'MAJORS';
        ddCase.ApprovalStatus__c = 'Pending';
        insert ddCase;
        
        TestDataFactory.setTriggerSwitch('Approval', false);        
        
        List<sbaa__Approval__c> listddApproval =
            new List<sbaa__Approval__c> {
                new sbaa__Approval__c(
                    Deal_Desk_Case__c = ddCase.Id,
                    sbaa__Opportunity__c = objOpportunity.Id,
                    sbaa__Status__c = 'Requested',
                    sbaa__Approver__c = listApprover[listApprover.size()-1].Id,
                    //sbaa__AssignedTo__c = listUser[0].Id,
                    sbaa__RecordField__c = 'Deal_Desk_Case__c',
                    sbaa__ApprovalStep__c = 1,
                    //sbaa__DelegatedApprover__c = listApprover[2].Id,
                    Previous_status__c = 'TestStatus'
                ), // Approval with Approver User and Delegated Approver User
                    new sbaa__Approval__c(
                        Deal_Desk_Case__c = ddCase.Id,
                        sbaa__Opportunity__c = objOpportunity.Id,
                        sbaa__Status__c = 'Requested',
                        sbaa__AssignedGroupId__c = listApprover[4].Id,
                        sbaa__RecordField__c = 'Deal_Desk_Case__c',
                        sbaa__ApprovalStep__c = 1,
                        Previous_status__c = 'TestStatus'
                    ), // Approval with Approver Group
                    new sbaa__Approval__c(
                        Deal_Desk_Case__c = ddCase.Id,
                        sbaa__Opportunity__c = objOpportunity.Id,
                        sbaa__Status__c = 'Requested',
                        sbaa__Approver__c = listApprover[0].Id,
                        sbaa__AssignedTo__c = listUser[0].Id,
                        sbaa__RecordField__c = 'Deal_Desk_Case__c',
                        sbaa__ApprovalStep__c = 1,
                        sbaa__DelegatedApprover__c = listApprover[5].Id,
                        Previous_status__c = 'TestStatus'
                    ) // Approval with Approver User and Delegated Approver Group
                    };
                        system.debug('listddApproval'+listddApproval);
        insert listddApproval;
        
        DdcLwcController.DdcWrapper ddcWrap = new DdcLwcController.DdcWrapper();
        ddcWrap.myId = 'testId102030';
        ddcWrap.message = 'This is test message';
        ddcWrap.ObjectName = 'Deal_Desk_Case__c';
        ddcWrap.status = 'On Hold';
        ddcWrap.userComments = '';
        
        
       
    }
    
    @isTest
    static void testValidateMethods(){
         List<sbaa__approval__c> listddApproval=[Select Id from sbaa__approval__c];
         Deal_Desk_Case__c ddCase=[Select Id from Deal_Desk_Case__c Limit 1];
        List<User> listUser= [Select Id from User Where firstname like 'testClassUser%'];
        DdcLwcController.ApprovalWrapper appWrap = new DdcLwcController.ApprovalWrapper();
        appWrap.amount = 100051.50;
        appWrap.approvalComments = 'This is test commments for Approval';
        Test.startTest();
        String testvalidateData = DdcLwcController.validateData(listddApproval[0].id);
        String validateDataTest = DdcLwcController.validateDataForApproval(listddApproval[0].id, listUser[0].id);
        String testvalidateData1 = DdcLwcController.validateData(ddcase.id);
        String testapproveCase = DdcLwcController.approveCase(listUser[0].Id, listddApproval[0].id, ddCase.Id, JSON.serialize(appWrap) );
        String testData = DdcLwcController.updateCase(ddCase.id, 'testComment');
        Test.stopTest();
        System.assert(ddcase.id!=null);
        
    }
    @isTest
    static void testDMLMethods(){
         Deal_Desk_Case__c ddCase=[Select Id from Deal_Desk_Case__c Limit 1];
         List<sbaa__approval__c> listddApproval=[Select Id from sbaa__approval__c where sbaa__status__c='Requested' and Deal_Desk_Case__c=:ddCase.Id];
        List<User> listUser= [Select Id from User Where firstname like 'testClassUser%'];
        ddCase.Request_Status__c='On Hold';
        update ddCase;
        Test.startTest();
        String testData = DdcLwcController.updateCase(ddCase.id, 'testComment');
         DdcLwcController.testPasser();

        Test.stopTest();
        System.assert(ddcase.id!=null);
        
    }
}