force-app/main/default/objects/Deal_Desk_Case__c/Deal_Desk_Case__c.object-meta.xml
<CustomObject>
    <description>SOX object - Custom Object</description>
    <label>Deal Desk Case</label>
    <nameField>
        <displayFormat>DDC-{000000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Desk Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Desk_Case__c/fields/Amount_Conditional__c.field-meta.xml
<CustomField>
    <fullName>Amount_Conditional__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Desk_Case__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>In Queue</fullName>
                <isActive>false</isActive>
                <label>In Queue</label>
            </value>
            <value>
                <fullName>Requested</fullName>
                <isActive>false</isActive>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Revoked</fullName>
                <isActive>false</isActive>
                <label>Revoked</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Desk_Case__c/fields/Business_Justification__c.field-meta.xml
<CustomField>
    <fullName>Business_Justification__c</fullName>
    <label>What Do You Need Help With?</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Deal_Desk_Case__c/fields/Deal_Desk_Team__c.field-meta.xml
<CustomField>
    <fullName>Deal_Desk_Team__c</fullName>
    <inlineHelpText>Select Deal Structuring if you need help with discounting, quote approvals, structuring or pricing.

Select Deal Operations for help with system errors, quoting bugs or enablement.</inlineHelpText>
    <label>Deal Desk Team</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deal Structuring</fullName>
            </value>
            <value>
                <fullName>Deal Operations</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Desk_Case__c/fields/ETM_Area__c.field-meta.xml
<CustomField>
    <fullName>ETM_Area__c</fullName>
    <label>ETM (Area)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Desk_Case__c/fields/ETM_Region__c.field-meta.xml
<CustomField>
    <fullName>ETM_Region__c</fullName>
    <label>ETM (Region)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Desk_Case__c/fields/ETM_Theatre__c.field-meta.xml
<CustomField>
    <fullName>ETM_Theatre__c</fullName>
    <label>ETM (Theatre)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Desk_Case__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Desk Cases</relationshipLabel>
    <relationshipName>Deal_Desk_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Desk_Case__c/fields/Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Request_Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Closed - Completed</fullName>
            </value>
            <value>
                <fullName>Closed - Incomplete</fullName>
            </value>
            <value>
                <fullName>Conditionally Approved</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Modification Requested</fullName>
                <isActive>false</isActive>
                <label>Modification Requested</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Desk_Case__c/fields/Request_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Sub_Type__c</fullName>
    <label>Request Sub-Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1 Year: FED/SLED</fullName>
            </value>
            <value>
                <fullName>Add-On Node</fullName>
            </value>
            <value>
                <fullName>Approval Issues</fullName>
            </value>
            <value>
                <fullName>ASPEN</fullName>
            </value>
            <value>
                <fullName>Below Minimum Amount (Deal or Product)</fullName>
            </value>
            <value>
                <fullName>Below Minimum Term</fullName>
            </value>
            <value>
                <fullName>Best Practices Enablement</fullName>
            </value>
            <value>
                <fullName>Cohesity Take Out</fullName>
            </value>
            <value>
                <fullName>Complete Quoting</fullName>
            </value>
            <value>
                <fullName>CPQ Bug</fullName>
            </value>
            <value>
                <fullName>CSAT</fullName>
            </value>
            <value>
                <fullName>Custom Deal Structure</fullName>
            </value>
            <value>
                <fullName>Custom Legal Verbiage</fullName>
            </value>
            <value>
                <fullName>Deal Ops Exception</fullName>
            </value>
            <value>
                <fullName>Delayed Start Date</fullName>
            </value>
            <value>
                <fullName>Discount Beyond Hard Floor</fullName>
            </value>
            <value>
                <fullName>Downgrade Request</fullName>
            </value>
            <value>
                <fullName>E1000</fullName>
            </value>
            <value>
                <fullName>E1000’s Request</fullName>
            </value>
            <value>
                <fullName>Entitlement Transfer</fullName>
            </value>
            <value>
                <fullName>Error Message</fullName>
            </value>
            <value>
                <fullName>Expiration Date Change</fullName>
            </value>
            <value>
                <fullName>Expiration Date Update</fullName>
            </value>
            <value>
                <fullName>Extended Payment Terms</fullName>
            </value>
            <value>
                <fullName>Financial Stability Letter</fullName>
            </value>
            <value>
                <fullName>Flip quote</fullName>
            </value>
            <value>
                <fullName>HW Only Quoting</fullName>
            </value>
            <value>
                <fullName>License Transfer</fullName>
            </value>
            <value>
                <fullName>Limited Availability</fullName>
            </value>
            <value>
                <fullName>M365 Beachhead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Desk_Case__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Deal_Desk_Team__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deal Ops Exception</fullName>
            </value>
            <value>
                <fullName>General Inquiry</fullName>
            </value>
            <value>
                <fullName>Legal Language</fullName>
            </value>
            <value>
                <fullName>Minimum or Maximum Discount, Floor, or Term Exceptions</fullName>
            </value>
            <value>
                <fullName>Non-Standard Payments</fullName>
            </value>
            <value>
                <fullName>Non-Standard Programs / Deal Structures</fullName>
            </value>
            <value>
                <fullName>Quoting Bug</fullName>
            </value>
            <value>
                <fullName>Renewal Quote</fullName>
            </value>
            <value>
                <fullName>Exception Quoting</fullName>
                <isActive>false</isActive>
                <label>Exception Quoting</label>
            </value>
            <value>
                <fullName>GTM Program Exceptions</fullName>
                <isActive>false</isActive>
                <label>GTM Program Exceptions</label>
            </value>
            <value>
                <fullName>Product Usage Exceptions</fullName>
                <isActive>false</isActive>
                <label>Product Usage Exceptions</label>
            </value>
            <value>
                <fullName>Term, Floor, Deal Size Threshold</fullName>
                <isActive>false</isActive>
                <label>Term, Floor, Deal Size Threshold</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DDcApprovalControllerTest.cls
@isTest
private class DDcApprovalControllerTest {
    
    static testMethod void testApprovals(){
   Test.startTest();
   
   PageReference pageRef = Page.PreviewApproval;
   Test.setCurrentPage(pageRef);
   
   Account objAccount = new Account();
        Contact objContact = new Contact();
        
        objAccount.Name = 'Test Account 26-05';
        objAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Partner/Distributor').getRecordTypeId();
        insert objAccount;
        
        objContact.Account = objAccount;
        objContact.LastName = 'Test Contact 22-05';
        insert objContact; 
        Opportunity objOpportunity = new Opportunity();
        objOpportunity.StageName = '1 Discovery';
        objOpportunity.Initial_Contacts_Name__c = objContact.Id;
        objOpportunity.Distributor_Lookup__c = objAccount.Id;
        objOpportunity.closeDate = System.Today() + 16;
        objOpportunity.Name = 'Test Opp 31-05';
        objOpportunity.Opportunity_Sub_Type__c = 'Regular';
        objOpportunity.Partner_Lookup__c = objAccount.Id;
        
        insert objOpportunity;
        
        Deal_Desk_Case__c ddCase = new Deal_Desk_Case__c();
        ddCase.Deal_Desk_Team__c = 'Deal Structuring';
        ddCase.ApprovalStatus__c = 'Approved';
        ddCase.Amount_Conditional__c = 100;
        ddCase.Request_Type__c = 'General Inquiry';
        ddCase.Request_Sub_Type__c = 'Below Minimum Term';
        ddCase.Request_Status__c = 'Draft';
        ddCase.Business_Justification__c = 'minimum characters';
        ddCase.ETM_Theatre__c = 'EMEA';
        ddCase.Opportunity__c = objOpportunity.Id;
        ddCase.ETM_Area__c = 'MAJORS';
        ddCase.ETM_Region__c = 'ENT-SOUTHEAST-N';
        insert ddCase; 
   
   ApexPages.StandardController sc = new ApexPages.StandardController(ddCase);
   
   
   DDcApprovalController ddCaseAC = new DDcApprovalController(sc);
   SBAA__Approval__c[] app = ddCaseAC.approvals; 
   Boolean b = ddCaseAC.isReadyForApproval;   
    Test.stopTest();

        System.assert(ddcase.id!=null);
    
 }
}