force-app/main/default/objects/Chassis__c/Chassis__c.object-meta.xml
<CustomObject>
    <label>Chassis</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chassis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Entitlement_Use__c/Entitlement_Use__c.object-meta.xml
<CustomObject>
    <description>&quot;SOX object - The end consumer of an entitlement. The end user could be a contact or a cluster or both.
Primarirly used by manaufacturing team.&quot;</description>
    <label>Entitlement Use</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entitlement Uses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Entitlement_Use__c/fields/entitlement__c.field-meta.xml
<CustomField>
    <fullName>entitlement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Entitlement ID</description>
    <label>Entitlement</label>
    <referenceTo>Entitlement</referenceTo>
    <relationshipLabel>Entitlement Uses</relationshipLabel>
    <relationshipName>Entitlement_Uses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entitlement_Use__c/fields/node__c.field-meta.xml
<CustomField>
    <fullName>node__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Node</label>
    <referenceTo>Node__c</referenceTo>
    <relationshipLabel>Entitlement Uses</relationshipLabel>
    <relationshipName>Entitlement_Uses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entitlement_Use__c/fields/serial_number__c.field-meta.xml
<CustomField>
    <fullName>serial_number__c</fullName>
    <label>Serial Number</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Node__c/Node__c.object-meta.xml
<CustomObject>
    <label>Node</label>
    <nameField>
        <label>Node Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Node__c/fields/asset__c.field-meta.xml
<CustomField>
    <fullName>asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Nodes</relationshipLabel>
    <relationshipName>Nodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Node__c/fields/chassis__c.field-meta.xml
<CustomField>
    <fullName>chassis__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chassis</label>
    <referenceTo>Chassis__c</referenceTo>
    <relationshipLabel>Nodes</relationshipLabel>
    <relationshipName>Nodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EntitlementsWithEntitlemntUseCont_Test.cls
@isTest(SeeAllData=true)
public class EntitlementsWithEntitlemntUseCont_Test {
    //for EntitlementsWithEntitlemntUseController
      static testmethod void test_method_one() {
       
        Entitlement_Use__c entuse = [select Id,serial_number__c,entitlement__r.Order_Service_Item__r.Product_Name__c, entitlement__r.StartDate, entitlement__r.EndDate, node__r.asset__r.Name,node__r.serial_number__c, node__r.chassis__r.serial_number__c from Entitlement_Use__c where entitlement__r.Account.name='TOTVS S.A.' LIMIT 1];
        
        List<Entitlement_Use__c> entuseList = new List<Entitlement_Use__c>();
        entuseList.add(entuse);
        
        Test.startTest();
        Test.setCurrentPage(Page.EntitlementsWithNodeAndAsset);
        ApexPages.StandardSetController stdSetController = new ApexPages.StandardSetController(entuseList);
        stdSetController.setSelected(entuseList);
        EntitlementsWithEntitlemntUseController cont = new EntitlementsWithEntitlemntUseController();
        List<Entitlement_Use__c> entitlementsReturned = cont.getEntitlements();
       // System.assertEquals(1, entitlementsReturned.size());
        System.assertEquals(false, cont.hasNext);
        System.assertEquals(false, cont.hasPrevious);
        cont.next();
        cont.previous();

       
        Test.stopTest();
    }
}