force-app/main/default/objects/Community_Feed__c/Community_Feed__c.object-meta.xml
<CustomObject>
    <label>Community Feed</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Community Feed Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Feeds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Community_Feed__c/fields/Comment_Owner_Email__c.field-meta.xml
<CustomField>
    <fullName>Comment_Owner_Email__c</fullName>
    <label>Comment Owner Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Community_Feed__c/fields/Community_Feed_Parent__c.field-meta.xml
<CustomField>
    <fullName>Community_Feed_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Community Feed Parent</label>
    <referenceTo>Community_Feed__c</referenceTo>
    <relationshipLabel>Community Feeds</relationshipLabel>
    <relationshipName>Community_Feeds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Community_Feed__c/fields/FeedCommentId__c.field-meta.xml
<CustomField>
    <fullName>FeedCommentId__c</fullName>
    <label>FeedCommentId</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Feed__c/fields/FeedItemId__c.field-meta.xml
<CustomField>
    <fullName>FeedItemId__c</fullName>
    <label>FeedItemId</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Feed__c/fields/InsertedById__c.field-meta.xml
<CustomField>
    <fullName>InsertedById__c</fullName>
    <label>InsertedById</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Feed__c/fields/Parent_Comment_Title__c.field-meta.xml
<CustomField>
    <fullName>Parent_Comment_Title__c</fullName>
    <label>Parent Comment Title</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Community_Feed__c/fields/Parentfeed__c.field-meta.xml
<CustomField>
    <fullName>Parentfeed__c</fullName>
    <label>Parentfeed</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Feed__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <label>ParentId</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Feed__c/fields/Post_Title__c.field-meta.xml
<CustomField>
    <fullName>Post_Title__c</fullName>
    <label>Post Title</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Community_Feed__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Customer_Subscription__c/Customer_Subscription__c.object-meta.xml
<CustomObject>
    <label>Customer Subscription</label>
    <nameField>
        <displayFormat>CS-{00000000}</displayFormat>
        <label>Customer Subscriptions#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Subscription__c/fields/Community_Feed__c.field-meta.xml
<CustomField>
    <fullName>Community_Feed__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Community Feed</label>
    <referenceTo>Community_Feed__c</referenceTo>
    <relationshipLabel>Customer Subscriptions</relationshipLabel>
    <relationshipName>Customer_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Subscription__c/fields/KB_ID__c.field-meta.xml
<CustomField>
    <fullName>KB_ID__c</fullName>
    <externalId>true</externalId>
    <label>KB ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Subscription__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Customer_Subscription__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Customer_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CommentsFromRbkSupportHelper.cls
public  without sharing  class CommentsFromRbkSupportHelper {
    
    public static void afterInsert(List<FeedComment>feedCommentList,Map<id,FeedComment>feedCommentMap){
        Map<Id,List<FeedComment>> feedItemIdVsListofComments = new   Map<Id,List<FeedComment>> ();
        Map<Id,Customer_Subscription__c> userIdAndCustomerSubscription = new   Map<Id,Customer_Subscription__c> (); 
        Set<Id>feedItemId= new Set<Id>();
        Set<Id> userIds = new Set<Id>();
        Set<Id>threadParentId= new Set<Id>();
        Set<Id>recordOwnerId= new Set<Id>();
        List<Community_Feed__c> communityFeedRecords1= new List<Community_Feed__c>();
        List<Community_Feed__c> communityFeedRecords2= new List<Community_Feed__c>();
        
        for(FeedComment fc :feedCommentList){
            
            feedItemId.add(fc.FeedItemId);
            userIds.add(fc.CreatedById);
            if(fc.ThreadParentId!=null)
                threadParentId.add(fc.ThreadParentId);    
        }
        
        for(Customer_Subscription__c cs : [SELECT Id, KB_ID__c, User__c FROM Customer_Subscription__c WHERE KB_ID__c IN : feedItemId AND User__c IN : userIds]){
            userIdAndCustomerSubscription.put(cs.User__c,cs);
        }
        
        Map<id,Community_Feed__c> mapofFeedCommetIdVsCommunityFeed= new Map<id,Community_Feed__c>();
        for(Community_Feed__c cf1 :[SELECT Id, CreatedById, CreatedBy.Email, Title__c, FeedCommentId__c,
                                    FeedItemId__c, InsertedById__c, ParentId__c, CreatedBy.IsActive
                                    FROM Community_Feed__c 
                                    WHERE FeedCommentId__c IN :ThreadParentId]){  
            mapofFeedCommetIdVsCommunityFeed.put(cf1.FeedCommentId__c, cf1);
        }
        system.debug('mapofFeedCommetIdVsCommunityFeed@@'+mapofFeedCommetIdVsCommunityFeed);
        
        Map<Id,FeedItem> idVsFeedItemMap = new Map<Id,FeedItem>([Select Id,Title from FeedItem where Id IN:feedItemId]);
        
        for(FeedComment fc :feedCommentList){
            if(!userIdAndCustomerSubscription.containsKey(fc.CreatedById)){
                SubscribePostController.addBookMark('0DB1W00000001vMWAQ', fc.FeedItemId, true);
            }
            Community_Feed__c cf= new Community_Feed__c();
            cf.FeedItemId__c= fc.FeedItemId;
            cf.FeedCommentId__c=fc.Id;
            cf.Post_Title__c=idVsFeedItemMap.get(fc.FeedItemId).Title;
            cf.InsertedById__c=fc.CreatedById;
            cf.Title__c= fc.CommentBody;
            cf.ParentId__c=fc.ThreadParentId;
            if(mapofFeedCommetIdVsCommunityFeed.containsKey(fc.ThreadParentId)){
                cf.Community_Feed_Parent__c=mapofFeedCommetIdVsCommunityFeed.get(fc.ThreadParentId).Id;
                cf.Parentfeed__c=mapofFeedCommetIdVsCommunityFeed.get(fc.ThreadParentId).Id;
                cf.Parent_Comment_Title__c=mapofFeedCommetIdVsCommunityFeed.get(fc.ThreadParentId).Title__c;
                if(mapofFeedCommetIdVsCommunityFeed.get(fc.ThreadParentId).CreatedBy.IsActive)
                    cf.Comment_Owner_Email__c=mapofFeedCommetIdVsCommunityFeed.get(fc.ThreadParentId).CreatedBy.Email;
                
            }
            
            cf.ParentId__c=fc.ThreadParentId;
            threadParentId.add(fc.ThreadParentId);
            communityFeedRecords1.add(cf); 
        }            
        if(!communityFeedRecords1.isEmpty()){
            
            insert communityFeedRecords1;
            system.debug('communityFeedRecords'+communityFeedRecords1);
        }
        
    } 
    
    public static void beforeDelete(List<FeedComment> oldFeedCommentList){
        List<PermissionSetAssignment> psaList = [SELECT PermissionSetId FROM PermissionSetAssignment WHERE AssigneeId =: userInfo.getUserId() AND (PermissionSet.Name = 'Moderate_Community_for_Customer_Community_Login_License_Users' OR PermissionSet.Name = 'Moderate_Community_for_Customer_Community_License_Users')];
        for(FeedComment fc : oldFeedCommentList){
            if((UserInfo.getUserId() == fc.CreatedById && fc.ThreadChildrenCount == 0) || !psaList.isEmpty()){
                
            }
            else{
                fc.addError('Only user with moderator abilities have permission to do this.');
            }
        }
    }
}