force-app/main/default/objects/WL_Domain__c/WL_Domain__c.object-meta.xml
<CustomObject>
    <label>Allowed Support Portal Email Domain</label>
    <nameField>
        <label>Domain Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Allowed Support Portal Email Domains</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WL_Domain__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Whitelisted_Domains</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DomainTriggerHelper.cls
public class DomainTriggerHelper {
    public static void checkDomain(List<WL_Domain__c> domains,Map<Id,WL_Domain__c> oldMap){
        Set<Id> accounts = new Set<Id>();
        for(WL_Domain__c dom:domains){
            accounts.add(dom.Account__c);
        }
        Map<Id,List<String>> domainMap = new Map<Id,List<String>>();
        for(WL_Domain__c dom:[Select Name, Account__c from WL_Domain__c where Account__c IN:accounts]){
            if(!domainMap.containsKey(dom.Account__c)){
                domainMap.put(dom.Account__c,new List<String>());
            }
            domainMap.get(dom.Account__c).add(dom.Name.toLowerCase());
        }
        if(!domainMap.isEmpty()){
            for(WL_Domain__c dom:domains){
                if((domainMap?.containsKey(dom.Account__c) && trigger.isInsert) || dom.Name != oldMap.get(dom.Id).Name){
                    if(domainMap.get(dom.Account__c).contains(dom.Name.toLowerCase())){
                        dom.addError('Domain Already Exist');
                    }
                }
            }
        }
    }
}