force-app/main/default/objects/Countries__c/Countries__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Countries</label>
</CustomObject>

force-app/main/default/objects/Deal_Registration__c/Deal_Registration__c.object-meta.xml
<CustomObject>
    <description>SOX object - Object used for Deal Registrations by Partners</description>
    <label>Deal Registration</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Deal Registration #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Registration__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deal Registrations (Distributor)</relationshipLabel>
    <relationshipName>Deal_Registrations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Partner_Rep_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Partner_Rep_Email_Address__c</fullName>
    <label>Partner Rep Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/States__c/States__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting for States</description>
    <label>States</label>
</CustomObject>

force-app/main/default/classes/DealRegExtensionTest.cls
/**
*  Name : DealRegExtensionTest
*  Description : Test class for DealRegExtension
*  Revision History : 
*  Version    Author Name      Last Modified Date      Comment
*    1.0     Yogesh Sharma        5/13/2016            Created.
*/
@isTest
private class DealRegExtensionTest {
    @testSetup static void methodName() {
      User u=TestDataFactory.getUser();
      u.LastName = 'TestUser101';
      insert u;
    }
    //method to insert lead with all the values and assigned to the campaign
    static testMethod void positiveScenario1() {
        Account acc=TestDataFactory.getAccount();
        insert acc;

       //System.runAs(u){
        Deal_Registration__c deal=TestDataFactory.getDealRegistration();
        deal.Partner_Rep_Email_Address__c='RK@rubrik.com';
        insert deal;
         
         Account accNew=TestDataFactory.getAccount();
         accNew.Distributor__c=acc.id;
         accNew.Type='Distributor';
         insert accNew;
 
         Contact con=TestDataFactory.getContact(accNew);
         con.email='RK@rubrik.com';
         insert con;
            Deal_Registration__c newDeal=[Select Partner_Rep_Email_Address__c from Deal_Registration__c where id=:deal.id];
            Contact c=[select email from contact where id=:con.id];
            Test.startTest();  
            //usr.AccountId=accNew.id;
            
            
            
            States__c objStates = TestDataFactory.insertStates();
            insert objStates;
            
            Countries__c objCountries = TestDataFactory.insertCountries();
            insert objCountries;
                 
            PageReference ObjDealReg = Page.DealReg;
            Test.setCurrentPage(ObjDealReg);
            ObjDealReg.getParameters().put('id',deal.id);
      ApexPages.StandardController sc = new ApexPages.standardController(deal);
            DealRegExtension objHandler = new DealRegExtension(sc);
            objHandler.fetchPartnerAccount();
                 objHandler.makeStateMandatory();
                 objHandler.makeStateNotMandatory();
                 objHandler.updateStateSelection();
                 objHandler.isItRequired();
                 objHandler.save();
                 objHandler.fetchPartnerAccount();
         
        //}
    }
     static testMethod void negativeScenario1() {

        User ur=[Select userrole.Name from User where lastname='TestUser101'];
             System.runAs(ur){
            Account acc=new Account();
            acc.Name='Test';
            insert acc;
            Account accNew=new Account();
            accNew.Name=acc.Name;
            accNew.Distributor__c=acc.id;
            accNew.Type='MSP';
            insert accNew;
            Contact con=TestDataFactory.getContact(accNew);
            con.email='RK@rubrik.com';
            insert con;
        
            Test.startTest();  
            
            Deal_Registration__c deal=new Deal_Registration__c();
            deal.Partner_Rep_Email_Address__c='RK@rubrik.com';
            insert deal;
            
            States__c objStates = TestDataFactory.insertStates();
            insert objStates;
            
            Countries__c objCountries = TestDataFactory.insertCountries();
            insert objCountries;
                 
            PageReference ObjDealReg = Page.DealReg;
            Test.setCurrentPage(ObjDealReg);
            ObjDealReg.getParameters().put('id',deal.id);
      ApexPages.StandardController sc = new ApexPages.standardController(deal);
            DealRegExtension objHandler = new DealRegExtension(sc);
            objHandler.fetchPartnerAccount();
                 objHandler.makeStateMandatory();
                 objHandler.makeStateNotMandatory();
                 objHandler.updateStateSelection();
                 objHandler.isItRequired();
                 objHandler.save();
                 LeadShare share = objHandler.shares;
        } 
     }
}