force-app/main/default/objects/Customer_Subscription__c/Customer_Subscription__c.object-meta.xml
<CustomObject>
    <label>Customer Subscription</label>
    <nameField>
        <displayFormat>CS-{00000000}</displayFormat>
        <label>Customer Subscriptions#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Subscription__c/fields/Category_Label__c.field-meta.xml
<CustomField>
    <fullName>Category_Label__c</fullName>
    <label>Category Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Subscription__c/fields/Category_Name__c.field-meta.xml
<CustomField>
    <fullName>Category_Name__c</fullName>
    <label>Category Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Subscription__c/fields/KB_ID__c.field-meta.xml
<CustomField>
    <fullName>KB_ID__c</fullName>
    <externalId>true</externalId>
    <label>KB ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Subscription__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Category</fullName>
            </value>
            <value>
                <fullName>Article</fullName>
            </value>
            <value>
                <fullName>FeedItem</fullName>
            </value>
            <value>
                <fullName>Forum Category</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Subscription__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Customer_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/How_To__kav/How_To__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <page>ArticleNewView</page>
            <template>Page</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <page>ArticleNewView</page>
            <template>Page</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <page>ArticleNewView</page>
            <template>Page</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge Centered Support (KCS)</label>
    <pluralLabel>Knowledge Base</pluralLabel>
</CustomObject>

force-app/main/default/classes/LtngKnowledgeCategoryHomeTest.cls
@isTest
public class LtngKnowledgeCategoryHomeTest{
    public static testMethod void getSubscription(){
        Customer_Subscription__c newCS = new Customer_Subscription__c();
        newCs.User__c = UserInfo.getUserId();
        newCs.Category_Label__c = 'Test';
        newCs.Type__c = 'Category';
        newCs.KB_ID__c = 'test';
        newCs.Category_Name__c = 'test';
        insert newCs;
        
        Customer_Subscription__c newCS1 = new Customer_Subscription__c();
        newCs1.User__c = UserInfo.getUserId();
        newCs1.Category_Label__c = 'Test';
        newCs1.Type__c = 'Article';
        newCs1.KB_ID__c = 'test';
        newCs1.Category_Name__c = 'test';
        insert newCs1;
        
        how_to__kav article = new how_to__kav();
        article.UrlName = 'testunique';
        article.title = 'test';
        insert article;
        
        how_to__kav articleToPublish = [select id,KnowledgeArticleId from how_to__kav where Id =: article.Id];
        
        KbManagement.PublishingService.publishArticle(articleToPublish .KnowledgeArticleId, true);
        
        //DescribeDataCategoryGroupResult[] results = Schema.describeDataCategoryGroups(new String[] { 'Article__kav'});
        How_To__DataCategorySelection dataCat = new How_To__DataCategorySelection();
        
        datacat.DataCategoryName = 'API';
        datacat.DataCategoryGroupName='Article';
        datacat.parentid = articleToPublish.id;
        insert dataCat;
        
        
        
        LtngKnowledgeCategoryHome.getSubscription();
        List<LtngKnowledgeCategoryHome.SubscribedCustomer> newlist = new List<LtngKnowledgeCategoryHome.SubscribedCustomer>();
        LtngKnowledgeCategoryHome.SubscribedCustomer wrapperCls = new LtngKnowledgeCategoryHome.SubscribedCustomer();
        wrapperCls.api = 'test';
        wrapperCls.isSubscribed = true;
        wrapperCls.categoryName = 'API';
        
        LtngKnowledgeCategoryHome.SubscribedCustomer wrapperCls1 = new LtngKnowledgeCategoryHome.SubscribedCustomer();
        wrapperCls1.api = 'test';
        wrapperCls1.isSubscribed = false;
        wrapperCls1.categoryName = 'API';
        
        newlist.add(wrapperCls);
        
        LtngKnowledgeCategoryHome.saveSubscription(newlist);
        LtngKnowledgeCategoryHome.createKbSubscription();    
        
        
        
    }    
}