force-app/main/default/objects/Escalation__c/Escalation__c.object-meta.xml
<CustomObject>
    <label>Escalation</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>Escalation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Escalations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lessons_Learned__c/Lessons_Learned__c.object-meta.xml
<CustomObject>
    <label>Lessons Learned</label>
    <nameField>
        <displayFormat>LL-{00000000}</displayFormat>
        <label>Lessons Learned Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lessons Learneds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lessons_Learned__c/fields/Escalation__c.field-meta.xml
<CustomField>
    <fullName>Escalation__c</fullName>
    <label>Escalation</label>
    <referenceTo>Escalation__c</referenceTo>
    <relationshipLabel>Lessons Learned</relationshipLabel>
    <relationshipName>Lessons_Learneds</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Note__c/Note__c.object-meta.xml
<CustomObject>
    <description>Enable Escalation Management Team (EMT) Reporting within Salesforce Lightning:
CS21-1378 by Aidan : Change the View/Edit option to custom object/rich text for each update, so the text being entered would have features to modify text with Bold, colour, font etc.</description>
    <label>Note</label>
    <nameField>
        <label>Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Note__c/fields/Escalation__c.field-meta.xml
<CustomField>
    <fullName>Escalation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Escalation</label>
    <referenceTo>Escalation__c</referenceTo>
    <relationshipLabel>Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/isDraft__c.field-meta.xml
<CustomField>
    <fullName>isDraft__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isDraft</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/Lessons_Learned__c.field-meta.xml
<CustomField>
    <fullName>Lessons_Learned__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lessons Learned</label>
    <referenceTo>Lessons_Learned__c</referenceTo>
    <relationshipLabel>Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/Section_Type__c.field-meta.xml
<CustomField>
    <fullName>Section_Type__c</fullName>
    <label>Section Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ransomware_Next_Steps</fullName>
                <label>Ransomware Next Steps</label>
            </value>
            <value>
                <fullName>Escalation_Issue_Summary</fullName>
                <label>Escalation Issue Summary</label>
            </value>
            <value>
                <fullName>LL_Background_Timeline</fullName>
                <label>LL Background &amp; Timeline</label>
            </value>
            <value>
                <fullName>LL_Area_of_Improvement</fullName>
                <label>LL Area of Improvement</label>
            </value>
            <value>
                <fullName>Escalation_RRT_Questions_Feedback</fullName>
                <label>Escalation RRT Questions &amp; Feedback</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/customDataTableController.cls
/*
* @Author           :   Vijay Kumar K R
* @CreatedDate      :   
* @lwc              :   customDataTable.lwc
* @TestClass        :   customDataTableControllerTest.cls
* -------------------------- @History ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
* Story Number       Modified By              Date                          Description
* CS21-1378         Vijay Kumar K R        Nov 29 2022    Enable Escalation Management Team (EMT) Reporting within Salesforce Lightning
* ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
*/
public with sharing class customDataTableController {
    
    @AuraEnabled(cacheable=true)
    public static WrapperClass getFieldsInfo(String objectName, String fieldSetName, Id parentRecordId, String filterStr) {
        System.debug('getFieldsInfo: objectName: '+objectName+' fieldSetName: '+fieldSetName+' parentRecordId: '+parentRecordId+' filter: '+filterStr);
        try {
            
            Schema.SObjectType objectType = null;
            if (String.isNotBlank(objectName)) {
                objectType = Schema.getGlobalDescribe().get(objectName);
            }
            
            Schema.DescribeSObjectResult objectDescribe = objectType.getDescribe();
            Map<String, Schema.FieldSet> fieldSetMap = objectDescribe.fieldSets.getMap();
            Schema.FieldSet fieldSet = fieldSetMap.get(fieldSetName);
            List<Schema.FieldSetMember> fieldSetMembers = fieldSet.getFields();

            Map<String, String> typeInfoByDevName = new Map<String, String>();
            for(FieldDefinition objFldDef : [SELECT DeveloperName, ExtraTypeInfo 
                                                FROM FieldDefinition 
                                                WHERE EntityDefinitionId = 'Note__c']){
                typeInfoByDevName.put(objFldDef.DeveloperName, objFldDef.ExtraTypeInfo);
            }
            
            String fldApiStr = '';

            List<FieldDetail> fldInfo = new List<FieldDetail>();
            for (Schema.FieldSetMember fsm : fieldSetMembers) {

                // Initial fld info
                String fldApiName = String.valueOf(fsm.getSObjectField());
                String fldLabelName = String.valueOf(fsm.getLabel());
                String fldType = String.valueOf(fsm.getType());

                // Reference Fields
                if(fldType == 'REFERENCE'){
                    // Custom fields
                    if(fldApiName.contains('__c')){
                        fldApiName = fldApiName.split('__c')[0]+'__r.Name';
                        fldLabelName = String.valueOf(fsm.getSObjectField()).split('__c')[0].replace('_', ' ');
                    }
                    // Standard fields
                    else{
                        fldApiName = fldApiName.split('Id')[0]+'.Name';
                        fldLabelName = String.valueOf(fsm.getSObjectField()).split('Id')[0];
                    }
                }
                // distinguish between RichText / LongText Area fields
                else if(fldType == 'TEXTAREA'){
                        fldType = typeInfoByDevName.get(fldApiName.split('__c')[0]);   
                }
                if(fldLabelName == 'CreatedBy'){
                    fldLabelName = 'Created By';
                }
                // fields Concatination for Query String
                fldApiStr += fldApiName+' ';
                // Requeired type
                Boolean isReq = fsm.getRequired() || fsm.getDBRequired();
                // Standard fields
                Boolean isFldUpdateable = objectType.getDescribe().fields.getMap().get(String.valueOf(fsm.getSObjectField())).getDescribe().isUpdateable();
                // Final field Info from Wrapper
                fldInfo.add(new FieldDetail(fldLabelName, fldType, String.valueOf(fsm.getSObjectField()), isReq, isFldUpdateable));
            }
            
            List<sObject> sObjList = prepareQuery(fldApiStr, objectName, parentRecordId, filterStr);
            return new WrapperClass(fldInfo, sObjList);} catch(Exception e) {throw new AuraHandledException('getFields expection: '+e.getMessage());
        }
    }

    /**
     * Method: prepareQuery 
     * Description: return list of records based on filter condition 
     * params: 
     * return: WrapperClass
     **/
    @AuraEnabled(cacheable=true)
    public static List<sObject> prepareQuery(String fldApiStr, String objectName, Id parentRecordId, String sectionFilter){
        try{
            String[] values = fldApiStr.split(' ');
            String parentObjFilter = '';
            
            if(parentRecordId.getSObjectType().getDescribe().getName() == 'Escalation__c'){
                parentObjFilter = ' Escalation__c = \''+String.escapeSingleQuotes(parentRecordId)+'\'';
            }else{
                parentObjFilter = ' Lessons_Learned__c = \''+String.escapeSingleQuotes(parentRecordId)+'\'';
            }
            
            String query = 'SELECT Id, isDraft__c, '+String.escapeSingleQuotes(String.join( values, ' , ' ))+' FROM '+String.escapeSingleQuotes(objectName);
            query += ' WHERE '+ parentObjFilter +' AND Section_Type__c = \''+String.escapeSingleQuotes(sectionFilter)+'\' ORDER BY CreatedDate DESC ';
            
            System.debug('query: '+query);
            return Database.query(query);} catch (Exception e) {throw new AuraHandledException(e.getMessage());
        }
    }

    /**
     * Method:      saveNotes 
     * Description: UPDATE notes edited
     * params:      notesStrData
     * return:      void
     **/
    @AuraEnabled
    public static List<Note__c> saveNotes(String notesStrData){
        System.debug('notesStrData:: '+notesStrData);
        try{
            List<Note__c> noteList = (List<Note__c>) JSON.deserialize(notesStrData, List<Note__c>.class);
            UPDATE noteList;
            return noteList;} catch (Exception e) {throw new AuraHandledException(e.getMessage());
        }
    }
    
    public class FieldDetail{
        @AuraEnabled
        public String fldLabel {get; set;}
        @AuraEnabled
        public String fldType {get; set;}
        @AuraEnabled
        public String fldApi {get; set;}
        @AuraEnabled
        public Boolean isFldReq {get; set;}
        @AuraEnabled
        public Boolean isFldUpdateable {get; set;}
        public FieldDetail(String fldLabel, String fldType, String fldApi, Boolean isFldReq, Boolean isFldUpdateable) {
            this.fldLabel = fldLabel;
            this.fldType = fldType;
            this.fldApi = fldApi;
            this.isFldReq = isFldReq;
            this.isFldUpdateable = isFldUpdateable;
        }
    }

    public class WrapperClass{
        @AuraEnabled
        public List<FieldDetail> FieldDetail {get; set;}
        @AuraEnabled
        public List<sObject> sObjectRecords {get; set;}
        public WrapperClass(List<FieldDetail> FieldDetail, List<sObject> sObjectRecords) {
            this.FieldDetail = FieldDetail;
            this.sObjectRecords = sObjectRecords;
        }
    }
}